### ISSUE TITLE
Support for HEIF

### ISSUE THREAD

**Issue by pythonicrubyist** [python-pillow/Pillow#2806] opened 2017-10-18 21:02 UTC
Do you have any plans to support HEIF image format, recently introduced by apple?

**Comment by wiredfool** [comment] 2017-10-19 07:58
I would welcome support, but I'm not aware of any appropriately licensed HEIF or HEVC libraries to do encoding/decoding.

**Comment by CounterPillow** [comment] 2017-10-20 12:27
The [reference HEVC encoder/decoder](https://hevc.hhi.fraunhofer.de/) is licensed as BSD 3-clause (but obviously extremely slow and tuned for PSNR), [the openHEVC decoder](https://github.com/OpenHEVC/openHEVC) is licensed as LGPL2.1.

Patent licenses are the bigger issues; the current patent licensing situation with 3 competing pools means that it'd be practically impossible for any FOSS project to produce binaries including a HEVC decoder which don't violate some patents.

So even if someone were to do the work to implement it, you wouldn't find it in most Pillow builds, because nobody wants to get harassed by the patent trolls.

**Comment by wiredfool** [comment] 2017-10-20 13:03
The HEIF container decoder is also not a free license: https://github.com/nokiatech/heif/blob/master/LICENSE.TXT .

**Comment by CounterPillow** [comment] 2017-10-20 13:21
There's an initial HEIF support patch for FFmpeg floating around [on their mailing list](https://ffmpeg.org/pipermail/ffmpeg-devel/2017-August/215003.html), but as the post itself says, it's early work and the whole format is batshit insane. The container is based off of MP4 for a start.

I don't think it'll be possible to support HEIF in Pillow in a sane manner based on the container and codec complexity alone, and even if someone were to make a demuxer+decoder in one library with a license Pillow could use, you wouldn't be able to build a product on it for around 30 more years, assuming the patents remain unlicenseable for anyone without big money lawyers.

**Comment by wiredfool** [comment] 2017-10-20 20:51
I'm definitely -1 on batshit insane. 

I think that the only way it could work is if we shipped support that was dynamically linked and based off of OS libraries, e.g. CoreImage on OSX. But it's not clear that would work, and it would only be the one platform at this point. 

I'm going to close this, if the world comes around to the point that it's reasonable, we can look at it.

**Closed by wiredfool** 2017-10-20 20:51 UTC
Labels: Enhancement

**Comment by rspeed** [comment] 2018-03-07 01:05
What about [libheif](https://github.com/strukturag/libheif)? It takes care of the packaging while using [libde265](http://www.libde265.org) for reading and [x265](http://x265.org/) for writing. All three libraries are LGPL.

My understanding is that there would be no patent issues whatsoever for Pillow. The HEIF container itself has a blanket patent waiver, and the HEVC licensing authority [doesn't require a license for software that isn't bundled with devices](http://epdf.hevcadvance.com/pdf/embed?hash=5607711a2dea3290b57fbcc93d13383c#1).

As far as I can tell, there's nothing blocking this other than the current instability of libheif's API.

**Comment by farindk** [comment] 2018-04-20 11:59
libheif encoder API is stable since version 1.1.0. It will appear in Debian testing in a few days:
https://packages.qa.debian.org/libh/libheif.html

I have not much experience with python, but if you need any assistance, feel free to contact me (I'm the libheif author).

**Comment by CounterPillow** [comment] 2018-04-21 10:52
@rspeed HEVC Advance is only one of three competing HEVC licensing authorities.

**Comment by CounterPillow** [comment] 2018-04-22 01:43
Yes, or just hope none of them feel like trying to enforce their patents against you. Though I don't think patent issues should prevent HEIF support from being added to Pillow. It's up to the companies or individuals building commercials products using Pillow to ensure their product doesn't infringe on any patents; I was simply pointing out that Linux distros like RedHat or OpenSuSE likely will want to ship Pillow without HEIF support.

**Comment by hugovk** [comment] 2019-01-28 22:54
@ncalligaro Unfortunately no, see above: https://github.com/python-pillow/Pillow/issues/2806#issuecomment-338200112.

**Comment by Cykooz** [comment] 2019-10-03 21:19
If someone else is interested in the ability to decode HEIF-files using Pillow (or without it), then I have released a little wrapper over the [libheif](https://github.com/strukturag/libheif) library - [cykooz.heif](https://pypi.org/project/cykooz.heif/).

**Comment by oebilgen** [comment] 2019-10-25 16:04
Sorry, why are you not using libheif?

**Comment by radarhere** [comment] 2019-10-26 03:57
@oebilgen See https://github.com/python-pillow/Pillow/issues/2806#issuecomment-338200112

**Comment by Cykooz** [comment] 2019-10-26 19:43
May be I wrong, but [this license](https://github.com/nokiatech/heif/blob/master/LICENSE.TXT) only about Nokia's software, not about HEIF container format as is:

> Nokia Technologies Ltd (“Nokia”) hereby **grants to you a ... license**,
under its copyrights and Licensed Patents **only to, use, run, modify** (in a way that still complies
with the Specification), **and copy the Software** within the Licensed Field.

[libheif](https://github.com/strukturag/libheif) is not based on Nokia`s code and don't uses Nokia's library. This is an independent implementation of decoder/encoder of HEIF images under [GPLv3 license](https://github.com/strukturag/libheif/blob/master/COPYING). This library already presents in standard repositories of [Debian](https://packages.debian.org/buster/libheif1), [Ubuntu](https://packages.ubuntu.com/bionic/video/libheif1) and other Linux distros.

**Comment by radarhere** [comment] 2019-10-26 20:19
@Cykooz I feel like this has already been mentioned - https://github.com/python-pillow/Pillow/issues/2806#issuecomment-370985911

**Comment by rspeed** [comment] 2019-10-29 03:04
@radarhere I'm not sure what you're referring to. Nothing I said in that comment disagrees with the point @Cykooz was making.

**Comment by instantlinux** [comment] 2020-02-07 21:19
This issue, I think, very definitely needs revisiting in 2020. A large percentage of all image/video files in the world are now generated, managed and stored natively in heic/heif format. The python community needs a tool for coping with this reality.

**Comment by simonw** [comment] 2020-04-12 00:45
If anyone needs a workaround for this, I managed to open a HEIC file using the [pyheif](https://github.com/david-poirier-csn/pyheif) library and convert it to a Pillow Image like this:

```python
from PIL import Image
import pyheif

heif_file = pyheif.read_heif("IMG_7424.HEIC")
image = Image.frombytes(mode=heif_file.mode, size=heif_file.size, data=heif_file.data)
image.save("IMG_7424.jpg", "JPEG")
```

**Comment by bagipriyank** [comment] 2020-05-04 23:13
is this something that PIL might support in the future?

**Comment by qarthandgi** [comment] 2020-06-07 21:54
I'm here to reiterate my support for HEIF/HEIC files in mid-2020. We've seen a wave of usage with this file format, and the de-facto Python image processing library not being able to handle it is becoming an issue.

**Comment by crawsome** [comment] 2020-07-02 17:24
Thank you for all your work so far, PIL team. Bump for the PIL to support HEIC/HEIF formats. I was trying to automate conversion the other day and was a little shocked to see it wasn't supported. 

Supporting reasons HEIC should be a priority:

- I'm running Windows Education version 10 build 2004 and I see there is still has no native support yet. 
- For many end users, the format is not trival to work with
- It is becoming more prominent as Apple takes more market share
- Users need relief from low-quality software. They are currently driven by search engines to potentially-dangerous closed-source programs for working with HEIC/HEIF. 

Thank you :)

**Comment by hugovk** [comment] 2020-07-02 18:35
I can't really comment on licensing, but Pillow uses a plugin for each image format, and you can use a third-party plugin with Pillow, without needing changes to Pillow itself. Here's the guide:

* https://pillow.readthedocs.io/en/stable/handbook/writing-your-own-file-decoder.html

Someone could already write a plugin. And then if the licensing was subsequently deemed not a blocker, it would be fairly easy to integrate it into Pillow.

**Comment by Ruin0x11** [comment] 2021-05-07 21:30
There is now a Pillow plugin for HEIF available, `pyheif-pillow-opener`.

https://pypi.org/project/pyheif-pillow-opener/

**Comment by mara004** [comment] 2021-07-15 12:53
This issue, I think, needs revisiting in 2021 ;)
As far as I can see, including libheif as dependency should be safe, as even Debian [have added it](https://packages.debian.org/buster/libheif1) to their main repository, and they have a legal team that checks every package very carefully.

**Comment by Yuchen-Wang-SH** [comment] 2021-09-11 02:20
> There is now a Pillow plugin for HEIF available, `pyheif-pillow-opener`.
> 
> https://pypi.org/project/pyheif-pillow-opener/

Finally I probably get this working. If you use this `pyheif-pillow-opener`, you should install `pyheif`, which depends on `libheif`. See `pyheif`'s page for how to install that to your OS. And, if you are using Linux OS or container, you probably want to pay attention to something called `libde265`, or `pyheif` still installs successfully but won't work with HEIC/HEIF. For a discussion on this, see strukturag/libheif#90.

I can confirm it works.

**Comment by mara004** [comment] 2021-10-08 12:03
I just tried using pyheif_pillow_opener, but I don't get it to work.

```python3
>>> from PIL import Image
>>> from pyheif_pillow_opener import register_heif_opener
>>> register_heif_opener()
>>> Image.open(".../heif.heic")
...
PIL.UnidentifiedImageError: cannot identify image file
```

I'm using a Ubuntu 20.04 derivative, pyheif 0.5.1, libheif1 1.11.0, and libde265-0 1.0.8.

**Comment by homm** [comment] 2021-12-09 11:02
I see there are plenty of alternatives and forks. Nevertheless, I want to present my own solution.

First of all, this is not just a fork with some fixes, I've found people who can be responsible for [pyheif development](https://github.com/carsales/pyheif). There are already three versions released after reincarnation. So changes more fundamental, like lazy loading or better pypy memory management.

So solution consist of pyheif itself, which have binary wheel for popular platforms and pure-python Pillow plugin:

### [heif-image-plugin](https://github.com/uploadcare/heif-image-plugin/)

**Comment by Simon566** [comment] 2022-02-09 13:26
this heif-image-plugin somehow crashes:

Collecting albums, done.
  Sorting albums  [####################################]  100%
   Sorting media  [####################################]  100%
Collecting files  [####################################]  100%
Processing files  [------------------------------------]  0/2
Traceback (most recent call last):
  File "/home/simon/python_virt_sigal/env/bin/sigal", line 8, in <module>
    sys.exit(main())
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/__init__.py", line 157, in build
    gal.build(force=force)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/gallery.py", line 756, in build
    for status in self.pool.imap_unordered(worker, media_list):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle 'module' object

**Comment by homm** [comment] 2022-02-09 16:53
@Simon566 I noticed than the Issues page was disabled for https://github.com/uploadcare/heif-image-plugin. Fixed it. Please fill the report there if you think this is heif-image-plugin problem.

**Comment by bigcat88** [comment] 2022-02-10 11:13
@Simon566 can you please check if the bug is reproducible with [pillow-heif](https://pypi.org/project/pillow-heif/) ?
If yes, then give me some info(OS(win,mac,unix), cpu and test file) - i will be glad to fix it if so.

**Comment by aapris** [comment] 2022-04-17 12:35
> I now tried https://github.com/bigcat88/pillow_heif/ which works well

This works for me too, and it was easy to install. I could't get cykooz.heif compiled at all on Mac OS.

**Comment by Simon566** [comment] 2022-04-18 10:34
Hi,

im running it on Debian 11 in a python virtual environment. im using sigal (static image gallery generator) which uses pillow.

I updated to pillow_heif and still it isnt working. How is this heif plugin correctly registered with pillow ?

Traceback (most recent call last):
  File "/home/simon/python_virt_sigal/env/bin/sigal", line 8, in <module>
    sys.exit(main())
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/__init__.py", line 174, in build
    gal.build(force=force)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/gallery.py", line 852, in build
    for status in self.pool.imap_unordered(worker, media_list):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle 'module' object


im registering this in sigal.conf like:

from PIL import Image, ImageSequence
from pillow_heif import register_heif_opener

register_heif_opener()


here are my packages:
blinker==1.4
cffi==1.15.0
click==8.1.2
importlib-metadata==4.11.3
Jinja2==3.1.1
Markdown==3.3.6
MarkupSafe==2.1.1
natsort==8.1.0
piexif==1.1.3
pilkit==2.0
Pillow==9.1.0
pillow-heif==0.2.1
pip==22.0.4
pkg_resources==0.0.0
pycparser==2.21
pyheif==0.7.0
setuptools==62.1.0
sigal==2.3
zipp==3.8.0



regards,
Simon

**Comment by Simon566** [comment] 2022-04-18 10:50
working with the testcode on console nevertheless works ...:

from PIL import Image
import pillow_heif

if pillow_heif.is_supported('input.heic'):
    heif_file = pillow_heif.open_heif('input.heic')
    for img in heif_file:  # you still can use it without iteration, like before.
        img.scale(1024, 768) # `libheif` does not provide much operations, that can be done on image, so just scaling it.
    heif_file.add_thumbnails([768, 512, 256]) # add three new thumbnail boxes.
    # default quality is probably ~77 in x265, set it a bit lower and specify `save mask`.
    heif_file.save('output.heic', quality=70, save_all=False) #save_all is True by default.
    exit(0)



so it looks like a issue with sigal or the way i register the plugin ( i trigger this in the sigal conf file )

**Comment by hugovk** [comment] 2022-04-18 11:19
@Simon566 Please report problems with sigal to https://github.com/saimn/sigal and with pillow-heif to https://github.com/bigcat88/pillow_heif.

**Comment by BubbleFish-FightClub** [comment] 2022-05-13 10:16
It took me super long to find this thread >_<' I have a good 100+ images that fall under this issue, all of the images have a ".jpg" extension which made finding this even more difficult.

The current error that is provided for these images is here:
https://github.com/python-pillow/Pillow/blob/c4325c805e5909f0bf7201ce1f259bc34a1a49e0/src/PIL/Image.py#L3094-L3096

Should we at least update the code to check `Image.format == "HEIF"` to give a better error message or at least link to this issue for other to find a solution?

**Comment by mara004** [comment] 2022-05-13 10:27
> Should we at least update the code to check `Image.format == "HEIF"` to give a better error message or at least link to this issue for other to find a solution?

I think as long as there is no decoder, Pillow has no way of recognising that the image is HEIF.

**Comment by BubbleFish-FightClub** [comment] 2022-05-13 10:30
@mara004 good point. My mistake, I found the Image.format working after having installed the plugin.

**Comment by aapris** [comment] 2022-05-14 07:03
> I think as long as there is no decoder, Pillow has no way of recognising that your image is HEIF.

I've only .HEIC files generated by iPhone, but all of them contain bytes
`0000000   \0  \0  \0       f   t   y   p   h   e   i   c  \0  \0  \0  \0`
in the header. So reading bytes [4:12] of the file may give some kind of a hint if the file is HEIF or not.

I don’t know if such research is Pillow’s job or not.

```
>>> with open("~/Downloads/IMG_1234.HEIC", "rb") as f:
...   x = f.read()
... 
>>> x[4:12]
b'ftypheic'
```

More details: https://github.com/strukturag/libheif/issues/83

**Comment by mara004** [comment] 2022-05-14 15:24
Analysing the file header for a HEIF signature might be possible. However, I don't think there's much point in adding this to Pillow. Unsupported means unsupported after all, and you don't need Pillow to determine the file type. A file manager (or the Unix command `file`) may be used instead.

**Comment by aapris** [comment] 2022-05-14 18:20
This is true. I use [python-magic](https://pypi.org/project/python-magic/) to identify file mime type. It has been very useful.

**Comment by bigcat88** [comment] 2022-05-15 00:41
> > I think as long as there is no decoder, Pillow has no way of recognising that your image is HEIF.
> 
> I've only .HEIC files generated by iPhone, but all of them contain bytes `0000000 \0 \0 \0 f t y p h e i c \0 \0 \0 \0` in the header. So reading bytes [4:12] of the file may give some kind of a hint if the file is HEIF or not.
> 
> I don’t know if such research is Pillow’s job or not.
> 
> ```
> >>> with open("~/Downloads/IMG_1234.HEIC", "rb") as f:
> ...   x = f.read()
> ... 
> >>> x[4:12]
> b'ftypheic'
> ```
> 
> More details: [strukturag/libheif#83](https://github.com/strukturag/libheif/issues/83)

_Pillow decodes files in two stages:_

_It loops over the available image plugins in the loaded order, and calls the plugin’s **_accept** function with the first 16 bytes of the file. If the_ _**_accept** function returns true, the plugin’s_ **_open** method is called to set up the image metadata and image tiles._

[pillow-image-plugin](https://pillow.readthedocs.io/en/latest/handbook/writing-your-own-image-plugin.html#writing-your-own-image-plugin)

Presence of _b'ftypheic'_ is not a guarantee that images inside file are in x265(HEIF) encoding.

**Comment by lupsin** [comment] 2022-11-21 12:28
> > I now tried https://github.com/bigcat88/pillow_heif/ which works well
> 
> This works for me too, and it was easy to install. I could't get cykooz.heif compiled at all on Mac OS.

Maybe someone will post this information in the documents, because it also took me about two days to find this topic and understand which of the HEIF plugins work for Pillow and support imageencoding.
Everyone on stackoverflow mentions `pyheif`, but it looks like it's poorly maintained and a working `pillow-heif` is down there somewhere.
And anyone looking for it needs to test every plugin, not work.
