### ISSUE TITLE
some specific image can be opened by browser,but cannot opened by pillow@4.2.1

### ISSUE THREAD

**Issue by gwl002** [python-pillow/Pillow#2642] opened 2017-07-24 15:18 UTC
### What did you do?
I am using python3,I installed the pillow@4.2.1.It works fine at the beginning.But someday,when i look in my logs,i finded it deal with some images badly.Here is some of my code.
I have tested that all my images can be opened by a chrome browser.
```
from PIL import Image
from io import BytesIO
import requests
stream = requests.get(img_url)
img = Image.open(BytesIO(stream.content))
print(img.size)
```
### What did you expect to happen?
Image can open all image files.
### What actually happened?
some file raise this Error  "cannot not identify image file <BytesIO object at ...>"

### What versions of Pillow and Python are you using?
pillow:4.2.1
python:3.5

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
code goes here
```
![Uploading 002.jpeg…]()

**Comment by cprogrammer1994** [comment] 2017-07-24 15:25
can you paste the image?

**Comment by gwl002** [comment] 2017-07-24 15:37
![002](https://user-images.githubusercontent.com/18588945/28531320-1c5f6146-70c9-11e7-834c-ebdaddddd1ce.jpeg)

**Comment by gwl002** [comment] 2017-07-24 15:41
@cprogrammer1994 
![002](https://user-images.githubusercontent.com/18588945/28531470-85e0855a-70c9-11e7-9bba-107a664e6635.jpeg)

**Comment by cprogrammer1994** [comment] 2017-07-24 15:45
![image](https://user-images.githubusercontent.com/11232402/28531660-29c52182-70a0-11e7-884f-ce5b633e3d18.png)

**Comment by cprogrammer1994** [comment] 2017-07-24 15:48
You cannot open this image with Photoshop. It is likely the image is not valid.

**Comment by gwl002** [comment] 2017-07-25 01:03
@cprogrammer1994 But the browser can open it correctly.Now I solved it by change the pillow version to 3.1.0.

**Comment by hugovk** [comment] 2017-07-25 06:14
git bisect says 07a96209597c5e8dfe785c757d7051ce67a980fb is the first bad commit:

```
commit 07a96209597c5e8dfe785c757d7051ce67a980fb
Author: Hugo
Date:   Tue Mar 14 11:49:10 2017 +0200

    If DPI isn't in JPEG header, fetch from EXIF

:040000 040000 391c8f192170883a508880f4b39be3eb3aecb29b 3aa7b78dd462a731025d6f9f7688eda92e4cdcbf M	PIL
bisect run success
```

Looks like it's falling over getting the EXIF in `x_resolution = self._getexif()[0x011A]`, and that bit should be made more robust.

**Comment by hugovk** [comment] 2017-07-25 06:20
With Tests/images/exif_gps.jpg, `self.info['exif']` is:
```
ExifMM*
���(��1PIL�����
��i��%nMakeXXX-XXX�����(#�3�����)�
=�
���2E�3	e����������2099:09:29 10:10:10����LensMake��������1999:99:99 99:99:99
```
And `self._getexif()` is:
```
{42035: u'LensMake', 258: (24, 24, 24), 36867: u'2099:09:29 10:10:10', 37380: (2147483647, -2147483648), 34853: {0: '\x00\x00\x00\x01', 2: (4294967295, 1), 5: '\x01', 30: 65535, 29: u'1999:99:99 99:99:99'}, 296: 65535, 34665: 185, 41994: 65535, 514: 4294967295, 271: u'Make', 272: u'XXX-XXX', 305: u'PIL', 42034: ((1, 1), (1, 1), (1, 1), (1, 1)), 34867: 4294967295, 34856: '\xaa\xaa\xaa\xaa\xaa\xaa', 282: (4294967295, 1), 50715: ((1, 1), (1, 1), (1, 1)), 33434: (4294967295, 1)}
```

With this issue's image, `self.info['exif']` is just:
```
Exif
```
And `self._getexif()` raises a SyntaxError: `not a TIFF file (header '' not valid)` (from https://github.com/python-pillow/Pillow/blob/1f19c023e1b285d5a43f0658b0cbc61b0af0de45/PIL/TiffImagePlugin.py#L435).

A try/except should do it.

**Comment by gwl002** [comment] 2017-07-25 06:29
@hugovk why treat it as a tiffimage?

**Comment by wiredfool** [comment] 2017-07-25 07:25
See #2632.

**Comment by wiredfool** [comment] 2017-07-25 07:26
@gwl002 EXIF data is formatted as a TIFF file.

**Comment by hugovk** [comment] 2017-07-25 08:02
Confirmed #2632 also fixes this, and merged it.

```python
>>> from PIL import Image
>>> im = Image.open("2642.jpg")
>>> im
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x230 at 0x104517690>
>>> im.size
(800, 230)
```

**Closed by hugovk** 2017-07-25 08:02 UTC

**Comment by gwl002** [comment] 2017-07-25 10:26
@hugovk Thanks a lot.
