### ISSUE TITLE
AttributeError: 'ImagingDecoder' object has no attribute 'pulls_fd'

### ISSUE THREAD

**Issue by kagb** [python-pillow/Pillow#2046] opened 2016-07-29 06:41 UTC
Got errors as title while cropping img.

``` python
    box = (x1, x2, y1, y2)
    imx = im.crop(box)
```

![image](https://cloud.githubusercontent.com/assets/20009087/17239922/61adf294-559a-11e6-9a45-33297988438f.png)

It seems that decoder has no pulls_fd key.

**Comment by hugovk** [comment] 2016-07-29 07:23
I can't reproduce it on Windows 7 with Pillow 3.2.0 or Pillow 3.3.0 and Python 2.7.11.

```
M:\bin>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> box = (1,1,20,20)
>>> im = Image.open("robot.png")
>>> imx = im.crop(box)
>>> imx.show()
>>>
```

What versions of Python and Pillow are you using? What OS? Can you attach an image that causes this? What values do you have for x1, x2, y1 and y2? Please include a more detailed example snippet. Thank you.

**Comment by wiredfool** [comment] 2016-07-29 07:37
That's from the merge to have the C code pull from the python file descriptor to fix Jpeg2k hangs. It was merged just before 3.3.0.

**Comment by kagb** [comment] 2016-07-29 07:39
Thanks for attention.

It raised on Ubuntu with Pillow 3.3.0 and Python 2.7.6.
We have a cropping image feature on web service and errors occurs sometimes.

**Comment by wiredfool** [comment] 2016-07-29 07:43
Do you know what file format is being cropped when the error occurs?  Or have a sample image?

**Comment by kagb** [comment] 2016-07-29 07:45
PNG
and no sample image for now

**Comment by kagb** [comment] 2016-07-29 08:02
There is the image data from the request data:

"'data'":"'\\x89PNG\\r\\n\\x1a\\n\\x00\\x00\\x00\\rIHDR\\x00\\x00\\x01\\xfc\\x00\\x00\\x01\\xfc\\x08\\x06\\x00\\x00\\x004R\\x1d\\x13\\x00\\x00\\x00\\x04gAMA\\x00\\x00\\xb1\\x8f\\x0b\\xfca\\x05\\x00\\x00\\x00 cHRM\\x00\\x00z&\\x00\\x00\\x80\\x84\\x00\\x00\\xfa\\x00\\x00\\x00\\x80\\xe8\\x00\\x00u0\\x00\\x00\\xea`\\x00\\x00:\\x98\\x00\\x00\\x17p\\x9c\\xbaQ<\\x00\\x00\\x01YiTXtXML:com.adobe.xmp\\x00\\x00\\x00\\x00\\x00<x:xmpmeta xmlns:x=\"adobe:ns:meta/\" x:xmptk=\"XMP Core 5.4.0\">\\n   <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\\n      <rdf:Description rdf:about=\"\"\\n    ..."

**Comment by wiredfool** [comment] 2016-07-29 08:02
Can you check to see if the error occurs on a simpler call:

```
im = Image.open('testimg.png')
im.load()
```

**Comment by kagb** [comment] 2016-07-29 08:08
@wiredfool  no any error

**Comment by wiredfool** [comment] 2016-07-29 08:08
That's not a complete image.

**Comment by kagb** [comment] 2016-07-29 08:18
I copied the image data from stack trace and it may not show completely.

As the image below, we can see  the size of image and other states.
![image](https://cloud.githubusercontent.com/assets/20009087/17242035/a162229a-55a7-11e6-9c53-6c1854fe8f30.png)

**Comment by wiredfool** [comment] 2016-08-01 07:13
Did you find the bug?

**Comment by wiredfool** [comment] 2016-08-06 20:52
Since we can't reproduce this with the PNGs that we have in the test cases, we're going to need some sort of reproducable test case to narrow down what's going on.

**Closed** 2017-04-19 09:29 UTC
Labels: Needs Test Case

**Comment by MikotoUrabe** [comment] 2018-12-29 22:10
I'm having the same issue with imread since I upgrated Matplotlib and Scikit-image

**Comment by radarhere** [comment] 2018-12-30 10:07
@MikotoUrabe are you able to provide a sample image, a sample script to produce the error, and a traceback of the error?
