### ISSUE TITLE
Pillow 3.4 breaks Image.thumbnail

### ISSUE THREAD

**Issue by jribbens** [python-pillow/Pillow#2161] opened 2016-10-09 20:40 UTC
### What did you do?
```python
    img = Image.open("test.png")
    img.thumbnail((256, 256))
    img.save("output.png")
```
### What did you expect to happen?
Create a thumbnail.

### What actually happened?
It creates a thumbnail with random transparent lines all over it.

### What versions of Pillow and Python are you using?
Python 3.5 and Pillow 3.4.1. With Pillow 3.3.3 it works perfectly.

![test](https://cloud.githubusercontent.com/assets/350846/19223477/e07b3dfa-8e68-11e6-99e9-07cd12586cb4.png)

![output](https://cloud.githubusercontent.com/assets/350846/19223484/eca989ba-8e68-11e6-8078-7e1404647ea3.png)

**Comment by hugovk** [comment] 2016-10-10 06:48
Reproducible with Pillow 3.4.1 / Python 2.7.12 / macOS Sierra:
![output](https://cloud.githubusercontent.com/assets/1324225/19228430/cf7880ac-8ecd-11e6-83a1-bbec5ad565a8.png)

and Pillow 3.4.0:
![output](https://cloud.githubusercontent.com/assets/1324225/19228503/9649a620-8ece-11e6-952f-ffbeced3335f.png)


Pillow 3.3.3 is fine:
![output](https://cloud.githubusercontent.com/assets/1324225/19228473/449c663c-8ece-11e6-9d65-460f3365ff6c.png)

**Comment by wiredfool** [comment] 2016-10-10 08:23
using this test script:

```
#!/usr/bin/env python
from PIL import Image
img = Image.open('/home/erics/test/thumb.png')
img.thumbnail((256,256))
if img.split()[3].histogram()[0] != 0:
    raise ValueError("Shouldn't be black in alpha histogram")
```

git bisect is giving me this:

```
  File "../test/thumb.py", line 6, in <module>
    raise ValueError("Shouldn't be black in alpha histogram")
ValueError: Shouldn't be black in alpha histogram
7d3db1f02a9e8ac61861b14d21f6d1ab288edaef is the first bad commit
commit 7d3db1f02a9e8ac61861b14d21f6d1ab288edaef
Author: homm <homm86@gmail.com>
Date:   Sat Jul 2 18:24:08 2016 +0300

    truncate zero coefficients

:040000 040000 8360f4acddbcb96de08de6522a59b83453d9ee55 70ef66fa03b804a29dc1ac10ba6587f577865908 M	libImaging
bisect run success
```

**Comment by hugovk** [comment] 2016-10-10 08:33
-> PR https://github.com/python-pillow/Pillow/pull/2008, ping @homm

**Comment by homm** [comment] 2016-10-10 15:45
Yes, this is my fault. Surprisingly, tests never fell due to this bug :/

**Comment by hugovk** [comment] 2016-10-17 10:30
Fixed by PR https://github.com/python-pillow/Pillow/pull/2162.

@jribbens Would you like to retest (from 3.4.x or master branch) to confirm before release?

**Closed by hugovk** 2016-10-17 10:30 UTC
Labels: Bug

**Comment by jribbens** [comment] 2016-10-17 16:44
@hugovk Yes I can confirm that both master and 3.4.x both appear fixed to me.
