### ISSUE TITLE
PIL 7.2.0: failed to convert RGBA image to Numpy array / OpenCV

### ISSUE THREAD

**Issue by anxuae** [python-pillow/Pillow#5438] opened 2021-04-25 10:04 UTC
I noticed a change since Pillow 7.2.0 when I try to convert a PIL RGBA image into an OpenCV image without alpha channel.
Since version 7.2.0, my PIL image is rendered as an opaque square when I convert it.
To illustrate my issue, here is a simple script:

```python
import PIL
import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont

text = "1"
alpha = 255
size = (50, 50)
font = ImageFont.truetype('Arial', 40)

image = Image.new('RGBA', size)
draw = ImageDraw.Draw(image)

txt_width, txt_height = draw.textsize(text, font=font)
position = ((size[0] - txt_width) // 2, (size[1] - txt_height) // 2 - size[1] // 10)
draw.text(position, text, (255, 255, 255, alpha), font=font)

overlay = cv2.cvtColor(np.array(image), cv2.COLOR_RGBA2RGB)
cv2.imwrite(PIL.__version__ + '.jpg', np.array(image))
```

Here the generated image using Pillow 7.1.2 and lower:
![7 1 2](https://user-images.githubusercontent.com/25277953/115989334-1df69280-a5be-11eb-8a4e-b93efef73b88.jpg)

Here the generated image using Pillow 7.2.0 and upper:
![8 2 0](https://user-images.githubusercontent.com/25277953/115989326-1931de80-a5be-11eb-9240-d89731ffd88b.jpg)

### OS, Python and Pillow versions

* OS: Mac OSX
* Python: 3.7.7
* Pillow: 8.2.0
* Numpy: 1.18.2
* OpenCV: 4.2.0.32

**Comment by radarhere** [comment] 2021-04-25 12:25
Hi. I would say this is a duplicate of #5431 - both are issues about drawing text on images revealing boxes once their transparency is converted away.

Testing, PR #5434 would also fix this.

**Comment by radarhere** [comment] 2021-04-26 01:49
Closing as a duplicate.

**Closed by radarhere** 2021-04-26 01:49 UTC
Labels: Duplicate
