### ISSUE TITLE
Support saving uncompressed ICO

### ISSUE THREAD

**Issue by pdknsk** [python-pillow/Pillow#2512] opened 2017-05-09 19:34 UTC
Currently _Pillow_ basically writes multiple _PNGs_ into an _ICO_ container, which is not supported by some applications that can read _ICO_. I'm not familiar with the _ICO_ format, but I think `biCompression` [here](https://msdn.microsoft.com/en-us/library/vs/alm/dd183376(v=vs.85).aspx) references the possible sub-formats.

**Comment by aclark4life** [comment] 2017-06-21 12:53
❓ Is this a feature request?

**Comment by aclark4life** [comment] 2017-06-21 12:55
Duplicate of #2513?

**Comment by pdknsk** [comment] 2017-07-20 06:59
It's a different issue.

**Comment by JamesTheAwesomeDude** [comment] 2021-05-24 00:21
> Duplicate of #2513?

@pdknsk  That issue was about sub-images; this issue is not a duplicate. This is a feature-request (which I share) for non-compressed ICO files; could it be re-opened?

-----

The following is [hard-coded](https://github.com/python-pillow/Pillow/blob/8.0.0/src/PIL/IcoImagePlugin.py#L175-L183):

> When saving, PNG compression is used. Support for this was only added in
> Windows Vista.

And, unfortunately, this is triggering https://github.com/mate-desktop/eom/issues/310  
(I'm not saying that that software isn't at fault, just that *this* issue is triggering *that* one)

**Comment by radarhere** [comment] 2021-05-24 07:47
So from https://docs.microsoft.com/en-us/previous-versions//dd183376(v=vs.85)?redirectedfrom=MSDN, you're after "BI_RGB", "An uncompressed format", yes? Looking at https://en.wikipedia.org/wiki/ICO_(file_format), I'm guessing this would be BMP, instead of PNG. Does that sound right?

**Comment by radarhere** [comment] 2021-05-26 20:28
I've concluded that the BITMAPINFOHEADER structure isn't used, so BI_RGB is irrelevant.

I've created to add BMP format, through ``im.save("out.ico", bitmap_format="bmp")``. Let us know if you have any thoughts.

**Closed** 2021-06-06 15:12 UTC
Labels: Enhancement
