### ISSUE TITLE
Saving PDF when mode is '1' saves as a pdf 1000's of inches wide, 1px tall.  Same image as greyscale or color has no such problem

### ISSUE THREAD

**Issue by aseelye** [python-pillow/Pillow#3829] opened 2019-05-06 19:31 UTC
### What did you do?
Created an image with mode='1', color=1.  Altered appropriately, then image.save('filename.pdf'), leads to a large file size (2.1mb when greyscale is 0.9mb) that has it's dimensions all out of whack.

### What did you expect to happen?
Expected a 1-bit pdf of the appropriate size.

### What actually happened?
Large file size (2.1mb when greyscale is 0.9mb) that has it's dimensions all out of whack

### What are your OS, Python and Pillow versions?

* OS: MacOS 10.14.  Confirmed on AWS Linux running Python 3.6 as well.
* Python: 3.73
* Pillow: 6.0.0

**Comment by radarhere** [comment] 2019-05-06 20:54
This looks like a duplicate of #3267, which was resolved by #3827. If testing with Pillow master does not fix the problem for you, then please provide a code example to demonstrate the issue.

**Closed** 2019-05-11 21:31 UTC
Labels: Awaiting OP Action, Duplicate

**Comment by radarhere** [comment] 2019-05-12 12:00
The file size issue is covered by #1775
