### ISSUE TITLE
Release 5.0.0 Issue: 2018-01-01

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#2832] opened 2017-11-05 15:06 UTC
Release issue placeholder for the ~4.4.0~ 5.0.0 Release.

**Comment by wiredfool** [comment] 2017-12-20 09:40
if we're going to merge the PyTest PR, this is going to turn into a major (5.0) release, due to pytest's lack of support for EOL python 3.3.  There are other potential breaking/major changes that might be worth merging.

* #2257, the pillow scripts rename/install issue. 
* #2583, Decompression bomb warnings -> error
* #2339, Reworking the exception types that we throw.

**Comment by homm** [comment] 2017-12-26 19:25
As part of the major release, I also would like to see #2198, because MRO could change call order.

**Comment by wiredfool** [comment] 2017-12-27 11:17
I dislike #2198, especially WRT python2 required syntax, but also in terms of the MRO at runtime vs our build/test time.

**Comment by wiredfool** [comment] 2017-12-29 21:59
I don't think I'm going to get to #2339 -- There's a lot of subsequently changed imports that are merge errors just to get to the point where it can merge, and then there are the reviews for if we're doing it correctly.

**Comment by cgohlke** [comment] 2017-12-31 08:07
How about discontinuing `bdist_egg` and `bdist_wininst` binaries for Windows?

**Comment by wiredfool** [comment] 2018-01-01 14:13
I'm OK with that, it'll need to be added to the release notes. Basically that means that they need pip of a reasonable recent version?

**Comment by wiredfool** [comment] 2018-01-01 15:18
I've pushed the version bump, but have not tagged yet. I'm waiting on travis to get to the wheel builds, but it's being really slow about that.

**Comment by wiredfool** [comment] 2018-01-01 15:42
Looks like we're getting a max of 2 concurrent builds right now, for comparison, appveyor finished before travis, which basically never happens.

**Comment by hugovk** [comment] 2018-01-01 17:23
Travis is now green. 

https://travis-ci.org/python-pillow/pillow-wheels/builds/323791158

**Comment by wiredfool** [comment] 2018-01-01 18:26
Tagged 5.0.0

**Comment by cgohlke** [comment] 2018-01-01 20:19
[Windows binaries](https://www.lfd.uci.edu/~gohlke/download/Pillow-5.0.0-win-dist.zip) are ready.

**Comment by wiredfool** [comment] 2018-01-01 21:09
Thanks @cgohlke

**Comment by wiredfool** [comment] 2018-01-01 21:27
And we're uploaded and released

**Comment by radarhere** [comment] 2018-01-04 02:06
Maybe this is just caching, but it looks to me like the 'Make sure the default version for Read the Docs is the latest release version' step in the RELEASING checklist hasn't been done?

![screen shot 2018-01-04 at 1 05 26 pm](https://user-images.githubusercontent.com/3112309/34547563-1578ec1e-f150-11e7-8473-521baa5424d0.png)

**Comment by hugovk** [comment] 2018-01-04 06:19
Thanks, I've put 5.0.0 as active and default, and 4.3.x and 3.4.x as inactive. 

http://pillow.readthedocs.io/ ->
http://pillow.readthedocs.io/en/5.0.0/

**Comment by homm** [comment] 2018-01-07 14:27
Close this?

**Closed** 2018-01-07 14:37 UTC
Labels: Release

**Comment by aclark4life** [comment] 2018-01-20 01:32
@hugovk I'm switching back to "latest" on RTD to get rid of the Gratipay badge … probably fine to leave at current release otherwise.

**Comment by radarhere** [comment] 2018-01-20 01:34
@aclark4life there has been mention of a potential [5.0.1](https://github.com/python-pillow/Pillow/issues/2950#issuecomment-356904467), so if there was movement on that, you could include the removal of the Gratipay badge in that.

**Comment by aclark4life** [comment] 2018-01-20 01:37
@radarhere Well, the issue is what do we configure RTD to do by default. I can see preferences for either… so if someone wants to switch from latest back to 5.0.1 after 5.0.1 is out, that's probably fine.

**Comment by wiredfool** [comment] 2018-01-20 09:02
Just cherry pick the docs change onto the 5.x branch and push it. When we do a 5.0.1 release for the install issue, it'll roll up with the delivered docs.

**Comment by aclark4life** [comment] 2018-01-20 11:22
Done (hopefully correctly)

<img width="1028" alt="screenshot 2018-01-20 06 21 12" src="https://user-images.githubusercontent.com/72164/35182854-3793a576-fdaa-11e7-8042-625a732ccb24.png">

**Comment by ThiefMaster** [comment] 2018-03-12 08:34
Are there any backwards-incompatible changes? There is a long changelog, but in its current state it is kind of useless since it's mixing everything together in what appears to be chronological order. And as nice as e.g. using pytest is, when I'm just using a library I couldn't care less about something like this - what I do care about is whether I need to adapt some of my code or (manually) test every single place where Pillow is being used in my application.
