### ISSUE TITLE
resize() loses alpha channel information

### ISSUE THREAD

**Issue by jleclanche** [python-pillow/Pillow#2096] opened 2016-08-31 04:54 UTC
Test program:

```py
from PIL import Image
texture = Image.open("test.png")
texture.save("orig.jpg")
thumb = texture.resize((256, 256))
thumb.save("256x.jpg")
```

Input image:
![Input NEW1_012.png](https://cloud.githubusercontent.com/assets/235410/18116380/00540964-6f50-11e6-85fd-e9b1ea845853.png)

Output:
![Output 256x](https://cloud.githubusercontent.com/assets/235410/18116328/a24365d6-6f4f-11e6-8fce-906d013a586c.png)

Expected output:
![Expected output 256x](https://cloud.githubusercontent.com/assets/235410/18116323/97681fda-6f4f-11e6-86ee-b81a08f262f5.png)

`orig.jpg` is correct.

**Comment by jleclanche** [comment] 2016-08-31 05:29
Doing `convert("RGB")` before resizing works around the issue.

**Comment by wiredfool** [comment] 2016-08-31 08:06
It's probably the save to jpeg, see #2010

**Comment by homm** [comment] 2016-08-31 14:57
Duplicate of #1345

**Closed by homm** 2016-08-31 14:57 UTC
