### ISSUE TITLE
Undefined Behavior: using numpy.array() to convert instances of PIL.TiffImagePlugin.TiffImageFile to ndarrays after opening TIFF with Image.open()

### ISSUE THREAD

**Issue by pigfat** [python-pillow/Pillow#4281] opened 2019-12-20 19:18 UTC
Since I spent multiple days trying to address this issue in my project and cannot find any documented information on why this could be occurring on either StackExchange or the Pillow Issues board, I'm posting it here for some help.

**What did you do?**

Attempted to import a .tif image using Image.open() and then convert the Image to an array.
![image](https://user-images.githubusercontent.com/13093052/71283489-5d5c0180-232e-11ea-8ca0-f16868e924e2.png)

**What did you expect to happen?**

Successful conversion of the pillow image to a numpy ndarray.
As documented per #3301

**What actually happened?**

Both numpy.array() and numpy.asarray() returned an instance of Pil.TiffImagePlugin.TiffImageFile instead of a numpy ndarray when called once. Calling numpy.asarray() or numpy.array() more than once on the instance of Pil.TiffImagePlugin.TiffImageFile causes the numpy.asarray() or numpy.array() to return a numpy ndarray even if no assignment of the returned value from the first call occurs. it's as if the call to numpy.array() or numpy.asarray() is mutating the Pil.TiffImagePlugin.TiffImageFile instance.

I ran the following tests to show the oddity of the behavior, each time I got the console print message "tempfile.tif: Cannot read TIFF header." This error message was not part of my code base and was not raise with an exception. The image I'm using is a scanned .tiff image in grayscale sent through Microsoft outlook.

**Case 1:** 

**Code:**
![Code#1](https://user-images.githubusercontent.com/13093052/71284400-a3b26000-2330-11ea-8aee-bca14449eadb.PNG)
**Result:**
![Result#1](https://user-images.githubusercontent.com/13093052/71284415-ab720480-2330-11ea-8652-4b4a32c2213f.PNG)

**Case 2:**

**Code:**
![Code#2](https://user-images.githubusercontent.com/13093052/71284477-d0ff0e00-2330-11ea-8e96-afa532b059a7.PNG)

**Result:**
![Result#2](https://user-images.githubusercontent.com/13093052/71284486-d65c5880-2330-11ea-8f02-e0e3bf29bcd1.PNG)

**Case 3 :**

**Code:**
![Code#3](https://user-images.githubusercontent.com/13093052/71284495-dc523980-2330-11ea-9f24-2187a15d7ecf.PNG)

**Result:**
![Result#3](https://user-images.githubusercontent.com/13093052/71284504-e1af8400-2330-11ea-905f-7d131c7c5092.PNG)

**Case 4:**

**Code:**
![Code#4](https://user-images.githubusercontent.com/13093052/71284524-ee33dc80-2330-11ea-9377-b041c38d7ce5.PNG)

**Result:**
![Result#4](https://user-images.githubusercontent.com/13093052/71284538-f429bd80-2330-11ea-9456-4986096230d9.PNG)

**Case 5:**

**Code:**
![Code#5](https://user-images.githubusercontent.com/13093052/71284558-00157f80-2331-11ea-900c-f61455214a21.PNG)

**Result:**
![Result#5](https://user-images.githubusercontent.com/13093052/71284564-03107000-2331-11ea-8638-275b1456044a.PNG)

Unfortunately, I'm unable to post the image I'm analyzing as it contains confidential information from my employer. However, since the behavior of the library itself is the really strange thing I'm hoping that should be enough to start looking into why this strange behavior is occurring.

However, here is some file information for the file that I can provide:
![image](https://user-images.githubusercontent.com/13093052/71285027-2ee02580-2332-11ea-91e2-34923867c182.png)

**What versions of Pillow and Python are you using?**
![image](https://user-images.githubusercontent.com/13093052/71285228-add55e00-2332-11ea-8941-f7e524e78da1.png)
![image](https://user-images.githubusercontent.com/13093052/71285199-99916100-2332-11ea-8c97-75a447fd3c6b.png)
![image](https://user-images.githubusercontent.com/13093052/71285176-8d0d0880-2332-11ea-97ed-013b22a576bb.png)

**Comment by radarhere** [comment] 2019-12-20 19:36
You mention #3301. In that issue, users are instructed to use `asarray`. You are just using `array`.

**Comment by pigfat** [comment] 2019-12-20 19:47
I also evaluated with asarray instead of array and confirmed the issue is still present. See Case #4 in "What actually happened?" above.

**Comment by radarhere** [comment] 2019-12-20 19:56
If it helps, the error isn't technically coming from our code either - it is coming from libtiff, at either https://gitlab.com/libtiff/libtiff/blob/master/libtiff/tif_open.c#L291 or https://gitlab.com/libtiff/libtiff/blob/master/libtiff/tif_open.c#L415

**Comment by radarhere** [comment] 2019-12-20 20:50
Regarding your comment about the returned values, I actually can't reproduce this with Pillow 5.3. The following script just gives me five `True` values.

```python
from PIL import Image
import numpy as np

im = Image.open("Tests/images/hopper.tif")
nd = np.array(im)
a = str(nd)
b = str(np.array(im))
print(a == b)

im = Image.open("Tests/images/hopper.tif")
np.array(im)
nd = np.array(im)
a = str(nd)
b = str(np.array(im))
print(a == b)

im = Image.open("Tests/images/hopper.tif")
nd1 = np.array(im)
nd2 = np.array(im)
a = str(nd2)
b = str(np.array(nd1))
print(a == b)

im = Image.open("Tests/images/hopper.tif")
nd = np.asarray(im)
a = str(nd)
b = str(np.asarray(im))
print(a == b)

im = Image.open("Tests/images/hopper.tif")
np.asarray(im)
nd = np.asarray(im)
a = str(nd)
b = str(np.asarray(im))
print(a == b)
```

**Comment by pigfat** [comment] 2019-12-20 21:06
That's definitely helpful!

 Another strange addition to this issue:
**Code:**
![image](https://user-images.githubusercontent.com/13093052/71291479-ccdaec80-2340-11ea-852f-863667d6980d.png)
**Result:**
![image](https://user-images.githubusercontent.com/13093052/71291640-34913780-2341-11ea-9846-73ad93e8f3d4.png)

![image](https://user-images.githubusercontent.com/13093052/71291678-4246bd00-2341-11ea-9780-5e52bd7415e7.png)

I added the above code and started to run my main script again, which iterates through all files in the drive location. It appears that at the numpy.array(img) the console is now waiting for keyboard input to continue. At the bottom of the result you can see that I'm on numpy.array(img), but execution doesn't continue until I press a key. I wonder if something in libtiff is holding up execution?

regarding your last post, can you post your test image? I would like to run your test code on my system and then post back the results.

**Comment by radarhere** [comment] 2019-12-20 21:08
https://github.com/python-pillow/Pillow/raw/master/Tests/images/hopper.tif

**Comment by pigfat** [comment] 2019-12-20 21:20
Just ran the following and got your result:

**Code:**
![image](https://user-images.githubusercontent.com/13093052/71293678-285aa980-2344-11ea-8a53-5ac692931f5e.png)

**Result:**
![image](https://user-images.githubusercontent.com/13093052/71293711-41fbf100-2344-11ea-86e1-8cad177cba69.png)

An interesting thing I noticed is that I did not get the internal libtif error this time around. I'll see if I can replicate the process for creating the image I'm analyzing without any confidential materials present.

**Comment by pigfat** [comment] 2019-12-20 21:22
Also, rerunning your tests with the image I'm analyzing currently gives me the following result:
![image](https://user-images.githubusercontent.com/13093052/71293928-f39b2200-2344-11ea-9a82-57233fac4706.png)

**Comment by pigfat** [comment] 2019-12-20 21:51
Here is an example of an image that's causing the issue to appear:
[error_causing_image.zip](https://github.com/python-pillow/Pillow/files/3990420/error_causing_image.zip)

**Comment by radarhere** [comment] 2019-12-20 22:14
Thanks, but I'm still not seeing a problem.

Here's another thought - the description of needing to hit Enter, the sqlalchemy lines being printed out, and the .filePath that suggests that you're using Twisted (but maybe not) - all of this sounds like interference from other libraries. It would be ideal if you could put together a script that could be run by itself, from start to finish, that shows the problem.

**Comment by pigfat** [comment] 2019-12-20 22:50
I just did a quick check of both pip list and conda list and I don't believe I have twisted installed. The .filePath comes from one of my internal classes I use to hold file metadata and the filepath itself is a pathlib object. 

I pulled out your test script and modified it to run on it's own with the image in the same directory. Hopefully this is what you were after, if not just let me know and I'll see what I can do. 

It still seems to wait for key input and fails the tests on my end. I've attached the code I'm running as well as the image. I'll go ahead and reinstall both packages for numpy and pillow just to see if that resolves it.

**Code:**
![image](https://user-images.githubusercontent.com/13093052/71296610-39a8b380-234e-11ea-88b4-7fea8d181a63.png)

**Result:**
![image](https://user-images.githubusercontent.com/13093052/71296678-6f4d9c80-234e-11ea-9918-4a7e27808be9.png)

Here is a copy of the files executed:
[Test Code.zip](https://github.com/python-pillow/Pillow/files/3990538/Test.Code.zip)

**Comment by pigfat** [comment] 2019-12-20 23:23
I reinstalled both numpy and pillow and no change.

**Comment by radarhere** [comment] 2019-12-20 23:51
Thanks for your efforts, but I still can't reproduce. I've also tried on our CI jobs, and found no success there either.

**Comment by pigfat** [comment] 2019-12-21 00:06
Thanks radarhere, I really appreciate all the help on this. I'm going to try a clean conda environment with only the required dependencies next and see if that works. I'll let you know how it goes.

**Comment by kmilos** [comment] 2019-12-26 10:45
Could this be related to #4237, does it work when downgrading libtiff to 4.0.10?

**Comment by pigfat** [comment] 2020-01-02 15:21
Alright, I just did a conda install --force on libtiff to downgrade my version of libtiff and only libtiff to 4.0.10 and reran the test in the attached test code above. 

My previous conda version of libtiff:
![image](https://user-images.githubusercontent.com/13093052/71673136-ebc87e00-2d45-11ea-919f-100d0ca94969.png)

My current conda version of libtiff:
![image](https://user-images.githubusercontent.com/13093052/71673073-c0de2a00-2d45-11ea-9cb6-0688262e8824.png)

After installing libtiff 4.0.10, I rerun the attached test code and test image again and got the following output:
![image](https://user-images.githubusercontent.com/13093052/71673105-d5babd80-2d45-11ea-8098-68d05aa6e0ab.png)

To confirm I can turn the issue on and off with a version change of libtiff, I then did a conda install --force for libtiff 4.1.0 and again the got the following after running the test code on the test image:
![image](https://user-images.githubusercontent.com/13093052/71673302-6e513d80-2d46-11ea-9579-9cbcc24941f1.png)

So downgrading to libtiff 4.0.10 resolves the issue and upgrading to libtiff 4.1.0 causes the issue to appear again.

Regarding: "Do you maybe have a more descriptive failure on im.load() beforehand?":
unfortunately no, the print statement "tempfile.tif: Cannot read TIFF header" is the only description I get when failure occurs. There's no stack trace that allows me to trace the issue further.

**Comment by pigfat** [comment] 2020-01-02 15:53
I should also add that my development environment is Windows.

**Comment by pigfat** [comment] 2020-01-02 16:15
I just created a clean test environment in conda with only the require dependencies to run test.py in Test Code.zip attached above.

Here is the complete conda environment package version list:
![image](https://user-images.githubusercontent.com/13093052/71677229-4a92f500-2d50-11ea-87d2-80e7d94cb557.png)

**This environment is using libtiff 4.1.0**

Running test.py on this environment outputs the following:
![image](https://user-images.githubusercontent.com/13093052/71677264-70b89500-2d50-11ea-8fec-59b3a5a669b6.png)

After performing the above test, I then installed libtiff 4.0.10 and the results are below.

Here is the new complete conda environment package version list:
![image](https://user-images.githubusercontent.com/13093052/71677431-d278ff00-2d50-11ea-9838-301228305d7a.png)

**This environment is using libtiff 4.0.10**

Running test.py on this new environment outputs the following:
![image](https://user-images.githubusercontent.com/13093052/71677489-f6d4db80-2d50-11ea-9e96-6902dc47c315.png)

Hopefully this helps with reproducing the issue.

**Comment by pigfat** [comment] 2020-01-02 19:57
Doing some experimentation, it appears that libtiff's behavior changed between 4.1.0 and 4.0.10 with regard to how they are handling jpeg compressed tif images.

I did an experimented where I looked at the hopper.tif image ( uncompressed tif ), my test tif image (jpeg compressed tif), a decompression of my test image using gimp (uncompressed tif), and a straight import into gimp and export as a jpeg compressed tif of my test tif image ( jpeg compressed tif). This is using the cleanTestEnvironment shown above. The results show that in libtiff 4.1.0 versus libtiff 4.0.10 the behavior surrounding jpeg compressed tif images has changed and this appears to be directly related the issue that's occurring here.

libtiff 4.0.10:
![image](https://user-images.githubusercontent.com/13093052/71689197-6b1e7780-2d6f-11ea-9d93-d65d180acfdb.png)

libtiff 4.1.0:
![image](https://user-images.githubusercontent.com/13093052/71689230-812c3800-2d6f-11ea-9678-49d2610d1a66.png)

Attached is the code and images for this analysis:
[Test Code.zip](https://github.com/python-pillow/Pillow/files/4017122/Test.Code.zip)

**Comment by radarhere** [comment] 2021-04-02 08:33
#4237 should be fixed in Pillow 8.2.0. If you upgrade, is this resolved?

**Comment by radarhere** [comment] 2021-04-06 08:23
@pigfat ?

**Comment by radarhere** [comment] 2021-04-17 04:21
Closing. This isn't reproducible, and a potential fix has been merged. This can be re-opened if there are any further comments.

Also, if anyone experiences a similar problem with numpy, #5379 should help by showing the hidden error.

**Closed by radarhere** 2021-04-17 04:21 UTC
Labels: Awaiting OP Action, NumPy, TIFF
