### ISSUE TITLE
Keyerror 'RGB' when create a new image

### ISSUE THREAD

**Issue by rickyi22** [python-pillow/Pillow#2682] opened 2017-08-15 03:00 UTC
I was creating a bunch of new image file by using 
```
from PIL import Image
img = Image.new("RGB",size,(255,255,255))
draw = ImageDraw.Draw(img)
```
but somehow there is a keyerror shows 'RGB'. and after looked it up in stackoverflow, it seems has something to do with my computer? but most of the time i could do it okay , but i am not sure which situation would cause that?

**Comment by radarhere** [comment] 2017-08-15 09:23
Would you be able to include the full error message that you receive?

**Comment by rickyi22** [comment] 2017-08-15 09:28
Is it beacause i was using multiprocessing.dummy.pool ? that each thread is creating new images .
the error message was plain "Keyerror : 'RGB'" then nothing else. and now it worked like nothing happened, really confused me :(

**Comment by rickyi22** [comment] 2017-08-22 02:18
ran into this problem once again :(  and this time i get the error message
`
Traceback (most recent call last):
  File "genweekreport.py", line 27, in <module>
    results = pool.map(genpages,ll)
              │        │        └ [(u'3048', u'43741447', (3, 6), (77, 83), (4, 5), 57, u'743', 9, u'78898', u'240', [(u'43453024', 7045), (u'44191299', 7020), (u...
              │        └ <function genpages at 0x0000000003536BA8>
              └ <multiprocessing.pool.ThreadPool object at 0x00000000035641D0>
  File "G:\n4662\rickyi1\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
           │              │     │         └ None
           │              │     └ [(u'3048', u'43741447', (3, 6), (77, 83), (4, 5), 57, u'743', 9, u'78898', u'240', [(u'43453024', 7045), (u'44191299', 7020), (u...
           │              └ <function genpages at 0x0000000003536BA8>
           └ <multiprocessing.pool.ThreadPool object at 0x00000000035641D0>
  File "G:\n4662\rickyi1\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
          └ <multiprocessing.pool.MapResult object at 0x00000000035D8B38>
KeyError: 'RGB'
`
as you can see , i was using multiprocessing threadpool creating lots of pictures, and dont get why this error happened,here is my code from genpages:
`
# this is the gen pic code in function genpages
img = Image.new("RGB",bpicconfig['size'],(255,255,255))

# and this is the run.py
from multiprocessing.dummy import Pool as ThreadPool
pool = ThreadPool(20)
l = main()
results = pool.map(genpages,l)
pool.close()
pool.join()
`
hope to get an answer here :)

**Comment by wiredfool** [comment] 2017-08-23 10:08
That doesn't really give us a backtrace into genpages, which is what is really necessary. 

Try catching the error in genpages, and adding `import inspect; print inspect.trace()` to the except clause to give a better backtrace.

**Comment by radarhere** [comment] 2017-08-23 10:17
```
from multiprocessing.dummy import Pool as ThreadPool

def genpages(size):
	x = {}
	x['test']

pool = ThreadPool(20)
results = pool.map(genpages, [1])
```

gives

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    results = pool.map(genpages, [1])
  File "lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: 'test'
```

So @wiredfool is suggesting

```
import inspect
from multiprocessing.dummy import Pool as ThreadPool

def genpages(size):
	try:
		x = {}
		x['test']
	except:
		print inspect.trace()

pool = ThreadPool(20)
results = pool.map(genpages, [1])
```

which gives

```
[(<frame object at 0x109f663e0>, 'test.py', 7, 'genpages', ["\t\tx['test']\n"], 0)]
```

I might suggest

```
import traceback
from multiprocessing.dummy import Pool as ThreadPool

def genpages(size):
	try:
		x = {}
		x['test']
	except:
		print traceback.format_exc()

pool = ThreadPool(20)
results = pool.map(genpages, [1])
```

which gives
```
Traceback (most recent call last):
  File "test.py", line 7, in genpages
    x['test']
KeyError: 'test'```

Hopefully, that will provide sufficient information to diagnose the problem.

**Comment by rickyi22** [comment] 2017-08-23 12:14
Much appreciated ! it could help a lot, i'll try to work this out :) thx~

**Comment by rickyi22** [comment] 2017-08-28 11:14
Here my error occurs once again , and this time i recorded the error

**Comment by rickyi22** [comment] 2017-08-28 11:17
Here my error occurs once again, and this time i recorded the traceback, 
`
Traceback (most recent call last):
  File "G:\n4662\script\personalspace\project\scripts\gentiaomu_1.py", line 115, in genpages
    draw.multiline_text(gpicconfig[num]['word'][ind],u'鏄电О锛?s\n瑙掕壊锛?s'%(name,racedic[race]),font=font1,fill='R
ed')
  File "G:\n4662\rickyi1\lib\site-packages\PIL\ImageDraw.py", line 284, in multiline_text
    self.text((left, top), line, fill, font, anchor)
  File "G:\n4662\rickyi1\lib\site-packages\PIL\ImageDraw.py", line 248, in text
    ink, fill = self._getink(fill)
  File "G:\n4662\rickyi1\lib\site-packages\PIL\ImageDraw.py", line 122, in _getink
    ink = ImageColor.getcolor(ink, self.mode)
  File "G:\n4662\rickyi1\lib\site-packages\PIL\ImageColor.py", line 118, in getcolor
    if Image.getmodebase(mode) == "L":
  File "G:\n4662\rickyi1\lib\site-packages\PIL\Image.py", line 296, in getmodebase
    return ImageMode.getmode(mode).basemode
  File "G:\n4662\rickyi1\lib\site-packages\PIL\ImageMode.py", line 52, in getmode
    return _modes[mode]
KeyError: 'RGB'
`
Finally i got it's not the error when i create new Image, but why this occurs when i'm trying to add text in a pic :(

**Comment by wiredfool** [comment] 2017-08-28 13:28
The error is coming from ImageMode, which is looking up the basemode for the image to return the correct value for 'Red' for the fill for the text.

It looks like either the mode cache was never filled, filled incorrectly, or corrupted. All of which are pretty strange issues.

Can you reproduce this at will, or is it something that only happens under load?  (also, what's your platform?  Looks like windows, but what versions are you using of windows/python/pillow?)

**Comment by rickyi22** [comment] 2017-08-29 04:05
Thanks a lot. Yeah i'm using windows 7 and my python version is 2.7.11 plus a 1.1.7 version PIL. 

No, it's not only happens under load, i am creating lots of pictures, most of them were created without problem, but somehow it would ran into this error and stop running, that's why it confused me :(

Is it has something to do with my PIL verison ? i am not sure, hope to hear you again~ thanks

**Comment by wiredfool** [comment] 2017-08-31 08:00
Can you check Image.PILLOW_VERSION?  Multiline_text wasn't implemented in PIL.

**Comment by aclark4life** [comment] 2018-04-01 12:49
@rickyi22 Can you check Image.PILLOW_VERSION? Multiline_text wasn't implemented in PIL. Thanks

**Comment by radarhere** [comment] 2018-09-02 05:48
If it helps, the way to check Image.PILLOW_VERSION is
```
>>> from PIL import Image
>>> Image.PILLOW_VERSION
'5.2.0'
```

**Comment by hugovk** [comment] 2018-09-02 05:54
Closing as no reply in about a year, we can re-open if necessary.

**Closed by hugovk** 2018-09-02 05:54 UTC
Labels: Bug
