### ISSUE TITLE
Having issues with exif data

### ISSUE THREAD

**Issue by Atticus837** [python-pillow/Pillow#3779] opened 2019-04-08 05:38 UTC
Python: 3.7.0
Pillow: 5.2.0

Wrote a simple program to square up images from an input folder, that has worked for months without a hitch. Today I tried to run the program and got these errors. unfortunately due to the nature of the images I'm unable to determine which picture caused the issue.

Code for squaring up images:

```python
import os
from PIL import Image

def make_square(im, min_size=256, fill_color=(255, 255, 255)):
    x, y = im.size
    size = max(min_size, x, y)
    new_im = Image.new('RGB', (size, size), fill_color)
    new_im.paste(im, ((size - x) // 2, (size - y) // 2))
    return new_im

for file in os.listdir("Input"):
    if file.endswith('.db'):
        os.remove(file)
    else:
        print(os.path.join("Input", file))
        test_image = Image.open(os.path.join("Input", file))
        new_image = make_square(test_image)
        new_image.save(os.path.join("Output", file))
```

Output:

```
Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 747
    " Skipping tag %s" % (size, len(data), tag))
UserWarning: Possibly corrupt EXIF data.  Expecting to read 35651584 bytes but only got 0. Skipping tag 0

Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 747
    " Skipping tag %s" % (size, len(data), tag))
UserWarning: Possibly corrupt EXIF data.  Expecting to read 18481152 bytes but only got 0. Skipping tag 0

Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 747
    " Skipping tag %s" % (size, len(data), tag))
UserWarning: Possibly corrupt EXIF data.  Expecting to read 19988480 bytes but only got 0. Skipping tag 0

Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 747
    " Skipping tag %s" % (size, len(data), tag))
UserWarning: Possibly corrupt EXIF data.  Expecting to read 17956864 bytes but only got 0. Skipping tag 0

Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 747
    " Skipping tag %s" % (size, len(data), tag))
UserWarning: Possibly corrupt EXIF data.  Expecting to read 33619968 bytes but only got 0. Skipping tag 0

Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 764
    warnings.warn(str(msg))
UserWarning: Corrupt EXIF data.  Expecting to read 12 bytes but only got 10. 
Input\100002.jpg

Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 747
    " Skipping tag %s" % (size, len(data), tag))
UserWarning: Possibly corrupt EXIF data.  Expecting to read 4292411360 bytes but only got 0. Skipping tag 0

Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 747
    " Skipping tag %s" % (size, len(data), tag))
UserWarning: Possibly corrupt EXIF data.  Expecting to read 16842824 bytes but only got 0. Skipping tag 18758

Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 747
    " Skipping tag %s" % (size, len(data), tag))
UserWarning: Possibly corrupt EXIF data.  Expecting to read 8783102816 bytes but only got 0. Skipping tag 65534

Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 747
    " Skipping tag %s" % (size, len(data), tag))
UserWarning: Possibly corrupt EXIF data.  Expecting to read 33686018 bytes but only got 0. Skipping tag 2817

Warning (from warnings module):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 747
    " Skipping tag %s" % (size, len(data), tag))
UserWarning: Possibly corrupt EXIF data.  Expecting to read 1142179972 bytes but only got 0. Skipping tag 515
Traceback (most recent call last):
  File "Z:\Squarify\Squarify.py", line 16, in <module>
    test_image = Image.open(os.path.join("Input", file))
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", line 2609, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", line 2599, in _open_core
    im = factory(fp, filename)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\JpegImagePlugin.py", line 780, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\ImageFile.py", line 102, in __init__
    self._open()
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\JpegImagePlugin.py", line 339, in _open
    handler(self, i)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\JpegImagePlugin.py", line 124, in APP
    exif = self._getexif()
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\JpegImagePlugin.py", line 432, in _getexif
    return _getexif(self)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\JpegImagePlugin.py", line 467, in _getexif
    info.load(file)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\TiffImagePlugin.py", line 738, in load
    fp.seek(offset)
OverflowError: Python int too large to convert to C ssize_t
```

**Comment by radarhere** [comment] 2019-04-08 06:04
I don't know what you mean when you say that you're unable to determine which picture caused the image. 'Input\100002.jpg' is printed, so it looks like at least that causes the issue. Are you able to upload the file here?

**Comment by radarhere** [comment] 2019-04-28 01:46
I'm closing this, since without images, we can't reproduce the problem. Feel free to comment and this can be re-opened.

**Closed by radarhere** 2019-04-28 01:46 UTC
Labels: Awaiting OP Action
