### ISSUE TITLE
PermissionError when attempting to use importlib.resources on Windows to load a custom font with ImageFont

### ISSUE THREAD

**Issue by geajack** [python-pillow/Pillow#6324] opened 2022-05-23 09:48 UTC
### Behavior

My code calls `ImageFont.truetype` to load a font. Because I want to make sure that font is present on the system, I commited it to my repo. When I want to make my package pip installable, I decided to package my font file using [`importlib.resources`](https://docs.python.org/3/library/importlib.html#module-importlib.resources). But now, when I pip install the package on Windows and try and run the code, I get a `PermissionError` when `importlib` attempts to clean up the temporary file - probably because Windows thinks a process is still using it:

```
Traceback (most recent call last):
  File "c:\users\me\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\me\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\Code\PIL Resource Bug\pyenv\lib\site-packages\font_demo-0.0.0-py3.9.egg\font_demo\__main__.py", line 9, in <module>
  File "c:\users\me\appdata\local\programs\python\python39\lib\contextlib.py", line 124, in __exit__
    next(self.gen)
eader
  File "c:\users\me\appdata\local\programs\python\python39\lib\contextlib.py", line 124, in __exit__
    next(self.gen)
  File "c:\users\me\appdata\local\programs\python\python39\lib\importlib\_common.py", line 40, in _tempfile      
    os.remove(raw_path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\me\\AppData\\Local\\Temp\\tmpd01q49pxOpenSans-Regular.ttf'
```

I don't get this with other kinds of resource files, so it seems Pillow is not releasing the file correctly. I have not tested this on other operating systems, but I suspect this is a Windows-only bug.

### Reproduction

1. Clone the [repo](https://github.com/geajack/pillow-resource-bug) I made to illustrate this.
2. Navigate to the root of the repo and optionally create an enter a virtual environment.
3. Install Pillow (`pip install pillow`).
4. Try running the code directly with `python -m font_demo`. You should see an image that says "Hello, world!".
5. Now run `python -m setup.py install` to install the package.
6. Enter a different directory and try running `python -m font_demo` again.
7. You get a`PermissionError` and the program halts without displaying the image.

### What are your OS, Python and Pillow versions?

* OS: Windows 10 (64 bit)
* Python: 3.9
* Pillow: 9.1.1

**Comment by radarhere** [comment] 2022-05-23 10:01
Hi. If you'll permit me to ask a quick question, just to rule out the easy solution, does the problem persist if you don't use Pillow?

```python
import importlib.resources

if __name__ == "__main__":
    with importlib.resources.path("font_demo", "OpenSans-Regular.ttf") as path:
        pass
```

**Comment by geajack** [comment] 2022-05-23 10:29
No, that works fine. However, this does cause an error:

```python
with importlib.resources.path("font_demo", "OpenSans-Regular.ttf") as path:
        font = ImageFont.truetype(str(path), 30)
```

So it seems my minimal example is not so minimal - you don't even need to use the font.

**Comment by nulano** [comment] 2022-05-23 11:04
When using a truetype font, the font file itself is opened using the FreeType library. Looking at the code, it should be properly closed when the font object is deallocated, so adding a `del font` into the `with` block should solve this on CPython (but likely not PyPy which does not use reference counting).

If you need to remove the file before the font is deallocated, you should be able to load the font using a file-like object, perhaps like this:

```python
with importlib.resources.path("font_demo", "OpenSans-Regular.ttf") as path:
    with open(path, "rb") as f:
        font = ImageFont.truetype(f, 30)
```

**Comment by radarhere** [comment] 2022-05-23 11:07
Thanks @nulano. So this is similar to https://github.com/python-pillow/Pillow/issues/3730#issuecomment-480491568

**Comment by geajack** [comment] 2022-05-23 11:17
Yeah, managing the file opening/closing myself seems like the best option. Thanks.

**Comment by radarhere** [comment] 2022-05-23 12:26
@geajack are you happy for this issue to be closed?

**Comment by nulano** [comment] 2022-05-23 15:08
The issue is that your code keeps a reference to the font (keeping the file open via FreeType) while trying to delete the file.

It is unclear whether FreeType keeping the file open while in use is an (upstream) issue or not.

From the comment linked by @radarhere:

> From my understanding, it is FreeType that is actually keeping the file pointer open [...]. We call FT_Done_Face when we are done with the font, but that's not applicable here, since the fonts [...] might still be used.

> So I don't see any reasonable action to take to improve this. We could stop using FreeType, but that's extreme. We could load the [file] into memory, like you're doing with BytesIO, but there's no advantage over that being run externally by you. Feel free to add any more information or disagree with my thoughts.

**Comment by geajack** [comment] 2022-05-23 21:27
I see. Maybe this is just a documentation issue? It's pretty non-obvious behavior after all - how often do you usually have to think about exactly when the garbage collector runs while programming in Python? Perhaps a note in the docs that the file will remain locked as long as the font object exists, and so if you need to do anything else with the file while the Python process is still running you should use the file-like object overload.

**Comment by radarhere** [comment] 2022-08-06 12:54
I've created PR #6485 to add a note to the documentation, resolving this.

**Closed** 2022-08-07 16:14 UTC
Labels: Windows, Fonts
