### ISSUE TITLE
ImageGrab range error when capturing multi-screen shots and the  parameter 'left' is negative

### ISSUE THREAD

**Issue by burning-star-x** [python-pillow/Pillow#8120] opened 2024-06-09 08:57 UTC
The issue with multi-monitor screenshot capturing is that when the secondary monitor is positioned to the left of the primary monitor,
 and in ImageGrab.grab(bbox=(left, top, width, height)), left is set to a negative value like -100,
 the screenshot will incorrectly include an additional area of 100 pixels (or other lengths) from the right side.
 Printing the width of the screenshot will indeed show that it is larger than expected by 100 pixels (or other values).
To fix the mistake on the right side, you have to manually subtract 100 from the right value, which is a bit of a hacky solution.

```python
from functools import partial

import cv2
import numpy as np
from PIL import ImageGrab

ImageGrab.grab = partial(ImageGrab.grab, all_screens=True)

left, top, right, bottom=(-100,0,1920,1080)
width = right - left
height = bottom - top
print(f"left:{left},top:{top},right:{right},bottom:{bottom}")
print(f"width:{width},height:{height}")

screenshot = ImageGrab.grab(bbox=(left, top, width, height))

width_of_screenshot = screenshot.size[0]
height_of_screenshot = screenshot.size[1]

print(f"screenshot_w: {width_of_screenshot}")
print(f"screenshot_h: {height_of_screenshot}")

screenshot_np = np.array(screenshot)
screenshot_opencv = cv2.cvtColor(screenshot_np, cv2.COLOR_RGB2BGR)
cv2.imshow('screenshot_opencv', screenshot_opencv)

#fix
left, top, right, bottom=(-100,0,1920,1080)
right=right+left #fix
width = right - left
height = bottom - top

screenshot = ImageGrab.grab(bbox=(left, top, width, height))

width_of_screenshot = screenshot.size[0]
height_of_screenshot = screenshot.size[1]

print(f"screenshot_w: {width_of_screenshot}")
print(f"screenshot_h: {height_of_screenshot}")

screenshot_np = np.array(screenshot)
screenshot_opencv = cv2.cvtColor(screenshot_np, cv2.COLOR_RGB2BGR)
cv2.imshow('screenshot_opencv_fix', screenshot_opencv)

cv2.waitKey(0)
cv2.destroyAllWindows()
```

**Comment by hugovk** [comment] 2024-06-09 09:21
Duplicate of https://github.com/python-pillow/Pillow/issues/8120.

**Closed by hugovk** 2024-06-09 09:21 UTC
