### ISSUE TITLE
IOError: broken data stream when reading image file loading a progressive jpg

### ISSUE THREAD

**Issue by fabiomignini** [python-pillow/Pillow#1767] opened 2016-03-14 15:12 UTC
Using Pillow [https://github.com/python-pillow/Pillow/commit/0f05eb287a223ce106848cd048cfcb45e9faa565](url) linked to libjpeg 8d, when I try to load a progressive jpeg on windows 7 (32 bit) I get the following error:

```
C:\python27\lib\site-packages\PIL\Image.py:2210:
DecompressionBombWarning: Image size (225000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack. DecompressionBombWarning)
Traceback (most recent call last):
  File "test.py", line 4, in <module>
   i.load()
  File "C:\python27\lib\site-packages\PIL\ImageFile.py", line 250, in load
    raise_ioerror(e)
  File "C:\python27\lib\site-packages\PIL\ImageFile.py", line 59, in raise_ioerror
    raise IOError(message + " when reading image file")
IOError: broken data stream when reading image file
```

Under osx 10.9.5 this problem isn't there.
Furthermore, saving the same image on a no-progressive mode there isn't the problem even under windows.

I also tried to use a different version of libjpeg (6b and 9b) and to use the precompiled version of Pillow 3.1.1 with the same results.

Any ideas?

**Comment by wiredfool** [comment] 2016-03-14 16:23
Is that really supposed to be a 15000x15000 pixel jpeg?

**Comment by fabiomignini** [comment] 2016-03-14 16:31
It is a 20000 × 11250 pixel jpeg, and it is correct.

**Comment by wiredfool** [comment] 2016-03-15 19:03
Can you post the file so we can take a look at it?

**Comment by fabiomignini** [comment] 2016-03-15 19:17
Thank you for your support, I put the image in google drive because it is very big (49MB) [https://drive.google.com/file/d/0B3yBB0C0yHBjZWtyQkhzOVY2aUE/view]

Just for your information, Gimp opens the image without any problem.

**Comment by mightym** [comment] 2016-03-31 23:29
I encountered a similar issue today. Not sure if this is related. I have on Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-57-generic x86_64) a django 1.9.4 site using wagtail 1.4.1 running. 
I get an error `IOError: broken data stream when reading image file` on images that are saved as progressive independent of the dimension. 

I have 3 instances with 512mb, 1GB and 2GB running. The first 2 always fail with that error. The 2gb machine doesn't. 

```Out of memory: Kill process 1627 (python) score 810 or sacrifice child
Killed process 1627 (python) total-vm:1438352kB, anon-rss:848648kB, file-rss:0kB```

Django's runserver just gets killed. When trying to open the image.

Anyway I wonder if this is really a Pillow issue because testing this on all 3 instances worked:

```from PIL import Image
im = Image.open("test.jpg")
im.thumbnail((128,128))```

**Comment by radarhere** [comment] 2019-04-07 23:25
Note that as of #2583, this is image is large enough that it triggers a `DecompressionBombError`.

**Comment by radarhere** [comment] 2019-04-08 00:40
@fabiomignini is this now fixed with the latest version of Pillow? I wonder if this is the same problem as #2717. If so, then this could work by simply allowing truncated images to load -

```python
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
im = Image.open('test.jpg')
im.load()
```

**Comment by radarhere** [comment] 2020-05-28 22:25
Also, Windows 7 has now ended support.

**Comment by hugovk** [comment] 2020-05-29 05:18
Let's also close this due to no reply in a year. We can re-open if it's reproducible with newer/supported versions.

**Closed by hugovk** 2020-05-29 05:18 UTC
Labels: Memory, Windows
