### ISSUE TITLE
Cannot get Pillow TIFF support using Python Docker image

### ISSUE THREAD

**Issue by flowl** [python-pillow/Pillow#3905] opened 2019-06-15 13:53 UTC
Using Dockerfile:
```
FROM python:3.6.8-slim-jessie

ENV PYTHONUNBUFFERED 1

RUN mkdir /app/
WORKDIR /app/

RUN apt-get update && apt-get install -y \
        python-dev python-pip python-setuptools \
        libffi-dev libxml2-dev libxslt1-dev \
        libtiff-dev libjpeg-dev zlib1g-dev libfreetype6-dev \
        liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk

COPY requirements.txt /app/

RUN pip install -r requirements.txt
```

I expect it to install `Pillow` with tiff support but the errors are:

    decoder tiff_lzw not available
    --
    /usr/local/lib/python3.6/site-packages/PIL/Image.py in _getdecoder, line 457

Note: I have no `PIL` installed, only Pillow:

```
Step 8/8 : RUN pip uninstall PIL
 ---> Running in 0151c3985f82
WARNING: Skipping PIL as it is not installed.
```

requirements:
```
Django>=2.0,<3.0
Pillow>=5.0
requests>1.0
fpdf>=1.7.2
openpyxl>=2.6
pandas>=0.24.2
```

**Comment by radarhere** [comment] 2019-06-15 13:59
This may be a duplicate of #3195, in which case it should have been fixed by #3227 in Pillow 5.3.0. Are you able to update Pillow and try again? If that does not work, could you provide a copy of the image you are trying to load?

**Comment by flowl** [comment] 2019-06-15 14:35
Wow, searching an hour for a solution and all I had to do was change `Pillow>=5.0` to `Pillow>=5.3` in requirements.txt.

I think the buggy 5.0 version should be blocked somehow in pip. Why does it not automatically install the most current version or the least version with bugfix applied.. I mean, concerning this, pip behaves different from all other installers (composer, npm, aptitude). Sigh. Not your issue, thanks for helping!

**Comment by hugovk** [comment] 2019-06-15 19:12
Use `pip install --upgrade etc` to get the latest.

**Closed by hugovk** 2019-06-15 19:12 UTC
Labels: TIFF
