### ISSUE TITLE
Setting dpi option while saving an image is not working

### ISSUE THREAD

**Issue by shubhamsharma1609** [python-pillow/Pillow#4873] opened 2020-08-18 07:53 UTC
I am using pillow version 7.0.0 on Windows. While trying to save an image in jpeg format ( with original dpi 650),I am passing dpi=(300,300) as a parameter to save function as I want dpi of resultant image to be 300 .The resultant image(jpeg) is having 96 dpi even after changing the dpi parameter to any value.

**Comment by hugovk** [comment] 2020-08-18 07:55
Please include a self-contained, copy-pastable example that generates the issue if possible. Be concise with code posted.

Guidelines on how to provide a good bug report:

* https://stackoverflow.com/help/mcve

Bug reports which follow these guidelines are easier to diagnose, and are often handled much more quickly.

**Comment by mattiik** [comment] 2020-08-19 08:27
I noticed a similar problem which I posted here: [https://stackoverflow.com/questions/62690745/how-do-i-create-properly-a-new-image-in-python-using-pillow-with-desired-size-an](url)

**Comment by radarhere** [comment] 2020-08-19 09:29
Using the commented code from the end of your StackOverflow post - `img.save("image.png", dpi = (300,300))`, I get
![image](https://user-images.githubusercontent.com/3112309/90616107-589a7500-e250-11ea-9b29-7fdabc076e2e.png)
which has DPI of 300, as shown by Preview.
![Screen Shot 2020-08-19 at 7 15 05 pm](https://user-images.githubusercontent.com/3112309/90616138-64863700-e250-11ea-8831-e3f8d32d79c9.png)
Is that part working for you?

You mention wanting your output image to be 7.5 x 5.5 cm.

cm = dots / dots per inch * cm per inch

Rearranging,

dots per inch = dots / cm * cm per inch

'cm per inch' is [2.54](https://www.google.com/search?q=cm+per+inch). So
```python
from PIL import Image
w, h = 100, 100
im = Image.new("RGB", (w, h))
x_dpi = w / 7.5 * 2.54
y_dpi = h / 5.5 * 2.54
im.save("out.png", dpi=(x_dpi, y_dpi))
```
gives me this image

which if I open up in GIMP, is the correct size.

![Screen Shot 2020-08-19 at 7 26 22 pm](https://user-images.githubusercontent.com/3112309/90617381-f773a100-e251-11ea-8ba2-9a4ee12c0036.png)

Does that answer your questions?

**Comment by mattiik** [comment] 2020-08-19 10:49
@radarhere "Is that part working for you?" Yes, I get a similar result. But why are the edges blurry, especially when magnified? You might see that at the triangle which is constructed using `draw.polygon(((5, 20), (50, 34), (50, 6)), fill=0)`, a simple fill between three points. I would expect a straight line between the points and thought this might result from resolution. But no matter what I try the edges remain unclear. Do you have a suggestions for that?

"Does that answer your questions?" Oh thanks, that makes things clear...

**Comment by radarhere** [comment] 2020-08-19 12:57
So from my understanding, DPI will only affect your resolution when printing. When dealing with an image on your screen, a pixel is just a pixel, and DPI has no effect.

I suspect that the reason you feel like it is blurry is because Pillow is only drawing black pixels. It is not drawing translucent pixels at the edges of the triangle.

For comparsion, if I take the triangle drawn by Pillow, and then using GIMP, fill a rectangle and use the Free Select Tool to copy and paste a section to become a second triangle. I'm guessing that you will deem the second triangle to be less blurry.

![out](https://user-images.githubusercontent.com/3112309/90637315-2ea47b00-e26f-11ea-8e73-4744d7d6e2b8.png)

**Comment by mattiik** [comment] 2020-08-21 06:26
I tried now several approaches including saving at different dpi, creating first a larger image and the resizing (downsizing) it to the desired size. However, common to all attempts is that the printouts look the same, staggered (triangles) or blurry text.

**Comment by radarhere** [comment] 2020-08-21 08:07
Ok, so to be clear - are you saying that the images look fine on your screen, and your only problem is that the quality when they are printed?

**Comment by mattiik** [comment] 2020-08-24 07:53
@hugovk  I tried that already - no success.

**Comment by radarhere** [comment] 2020-08-27 11:42
From my [earlier comment](https://github.com/python-pillow/Pillow/issues/4873#issuecomment-676311475), I'm trying to pin down exactly why you feel the Pillow output image is blurry on your screen, and what a non-blurry version would look like.

As far as your printouts go, in my experience, I would recommend vector images if possible. I realise that's not something that Pillow offers, but I think that's the quickest solution.

**Comment by radarhere** [comment] 2020-11-01 09:50
Closing - I don't think there's enough information here to solve the problem. The report is that the image is 'blurry' on a monitor, but without a more specific description of the problem (or even really an image from the user).
If the image does not appear satisfactorily on the screen, then it's not going to appear satisfactorily when printed out either.

**Closed by radarhere** 2020-11-01 09:50 UTC

**Comment by yasirroni** [comment] 2022-03-01 09:55
I use a print screen images for test. Got 96 DPI, around 500 pixel in H and W.

If I don't care with pixel in H and W, how can I increase it to 300?

I'm using:

```
import PIL
from PIL import Image

img = Image.open("repository.png")
img.save("repository2.png", dpi=(300, 300))

img2 = Image.open("repository2.png")
```

Resulting img2 have same pixel with img. Open in paint, both remain have 96 DPI.

Pillow version 9.0.1

**Comment by radarhere** [comment] 2022-03-01 10:15
Just to be clear - increasing the DPI setting does not change the pixels in the image. On your screen, a pixel is a pixel, and DPI only starts to change things when you are printing.

When I run your code over one of our test images, hopper.png, it works.

If I open the original image and the created images in macOS Preview, the DPI has changed correctly.

I don't have Paint, so I can't test out what it says about the DPI.

**Comment by yasirroni** [comment] 2022-03-01 12:02
Thanks for the response.

Yes, I know that DPI only affects on print. But, can you help me answer this question?

Imagine I have an image of 1000 pixel with 50 DPI. 
Open that in photo viewer with 100% zoom. If PIL edit it into 100 DPI, retaining 1000 pixel, opening on photo viewer with 100% zoom, the dimensions on inch / cm will be changed right? Dimension when using printer with 100% size also results in different inch / cm right?

_
Regarding the sample image, I will try to test it and report here. Is the problem is windows, PIL,or simply paints.

**Comment by yasirroni** [comment] 2022-03-01 12:04
Extra note:

save with DPI params is working with PIL grab (screenshot from PIL on windows). Checked with paints. I just don't understand why it doesn't work on image coming from read method

**Comment by radarhere** [comment] 2022-03-01 12:14
> Imagine I have an image of 1000 pixel with 50 DPI. Open that in photo viewer with 100% zoom. If PIL edit it into 100 DPI, retaining 1000 pixel, opening on photo viewer with 100% zoom, the dimensions on inch / cm will be changed right?

I don't expect the image to take up more space on your monitor. I would expect that the image viewer reports that the image has different dimensions in inches or centimetres. For example, here is the original hopper.png at 96 DPI, and hopper2.png that I saved with Pillow at 300 DPI, in GIMP. One is 3cm, one is 1cm.

<img width="494" alt="Screen Shot 2022-03-01 at 11 10 21 pm" src="https://user-images.githubusercontent.com/3112309/156167072-8274230e-03a8-4044-a9f7-500a16e3d3d3.png">
<img width="494" alt="Screen Shot 2022-03-01 at 11 10 32 pm" src="https://user-images.githubusercontent.com/3112309/156167064-f482368f-1fcc-4090-874d-e1e9dfb8f114.png">

> Dimension when using printer with 100% size also results in different inch / cm right?

Yes, the image should come out at a different size when you print.

**Comment by yasirroni** [comment] 2022-03-01 13:46
> I don't expect the image to take up more space on your monitor. I would expect that the image viewer reports that the image has different dimensions in inches or centimetres.

Glad I'm in the correct path. Thank you.

I'll report back if I got time to debug the problem on windows/paint

**Comment by yasirroni** [comment] 2022-03-01 14:06
![image](https://user-images.githubusercontent.com/48709672/156183127-ddeb7e70-0177-489d-a130-686deee70cfe.png)

The left image using windows screenshot, DPI is 96. `Image.open` and save `dpi=(150, 150)` did not change info in paint.

```python
from PIL import Image

img = Image.open("ss.png")
img.save("ss2.png", dpi=(150, 150))
```

The right one screenshot using windows `ImageGrab.grab()`. Test using various value, the DPI change accordingly *and change dimension in cm too.
```python
from PIL import ImageGrab
import time
import tqdm

for i in tqdm.tqdm(range(100)):
    time.sleep(0.001)
im = ImageGrab.grab()

im.save("imgrab.png", dpi=(600, 600))
```

For pixel, both have the same pixel as my screen.

**Comment by nulano** [comment] 2022-03-01 14:10
The left screenshot says "ss.png" in the titlebar, but your code is saving "ss2.png". Did you open the original image instead of the modified image by accident?

**Comment by yasirroni** [comment] 2022-03-01 14:15
> The left screenshot says "ss.png" in the titlebar, but your code is saving "ss2.png". Did you open the original image instead of the modified image by accident?

Nope, i just edited the piece of code to show different name to avoid confusion.

**Comment by yasirroni** [comment] 2022-03-01 14:16
![image](https://user-images.githubusercontent.com/48709672/156185024-66870c26-efcd-4e86-89ea-aa3ce75746b9.png)

Same image, edited with GIMP, and paint know can recognise 600 DPI.

So, the problem is in PIL that can't modify DPI on `Image.read()`

**Comment by yasirroni** [comment] 2022-03-01 14:19
Suddenly it is working now

```python
import PIL
from PIL import Image

img = Image.open("ss.png")
img.save("ss_resize_dpi_PIL.png", dpi=(150, 150))
```

![image](https://user-images.githubusercontent.com/48709672/156185916-a5b24249-bb4a-47aa-bae4-443150f26b5b.png)

**Comment by yasirroni** [comment] 2022-03-01 14:21
Probably the one of the main problem is replacing an opened file. I'm able to resize properly after closing all files.

But let me confirm with different image. Wait a minute.

**Comment by yasirroni** [comment] 2022-03-01 14:25
Okay, I have found the real culprit. That is image produced by lightshot can't be edited by PIL, but bare screenshot is able.

**Comment by yasirroni** [comment] 2022-03-01 14:30
Image from snipping tools also have this behavior

```
import PIL
from PIL import Image

img = Image.open("Capture.PNG")
img.save("Capture2.PNG", dpi=(600, 600))
```

**Comment by yasirroni** [comment] 2022-03-01 14:34
> Original snippingtools ![Capture](https://user-images.githubusercontent.com/48709672/156187707-dedca38b-aa97-4f90-992b-163fc757e112.PNG)
> 
> PIL image save (have same DPI) ![Capture2](https://user-images.githubusercontent.com/48709672/156187809-596d2da6-afef-44e6-b7fa-bb014f87e58a.PNG)
> 
> What cause this bug?

I've tested by downloading that image from github, apply PIL, can't change DPI (based on paint DPI).

**Comment by radarhere** [comment] 2022-03-01 20:42
If I download your transformed image, macOS Preview reports that it has a DPI of 600, as you intended.
If I open the image up in https://www.metadata2go.com/, I see that it has different "Pixels Per Unit" to your original image.

So Pillow is making a change - it's just that Paint is ignoring it for some reason.

Could you attach a copy of an image saved by Pillow, that Paint doesn't read the correct DPI for, and then a copy of that same image later modified by GIMP, that Paint does read the correct DPI for, so that we can try and spot the difference?

**Comment by yasirroni** [comment] 2022-03-01 23:07
> Original snippingtools ![Capture](https://user-images.githubusercontent.com/48709672/156187707-dedca38b-aa97-4f90-992b-163fc757e112.PNG)
> 
> PIL image save (have same DPI) ![Capture2](https://user-images.githubusercontent.com/48709672/156187809-596d2da6-afef-44e6-b7fa-bb014f87e58a.PNG)
> 
> What cause this bug?

Original image is the first image. Screenshot image that PIL try to convert DPI but ignored by Paint is the second image.

I will post the third image, that is modified DPI by gimp. Wait...

**Comment by yasirroni** [comment] 2022-03-01 23:23
GIMP *FAILED* (method used: open, edit, export)

![Capture_gimp600](https://user-images.githubusercontent.com/48709672/156265575-3a9ab5b1-d3a9-40f3-bacc-62cf124b83b8.PNG)

GIMP *SUCCESS* (method used: open, edit, save a copy in xcf format, close, open saved xcf format, export)

![Capture_gimp600_3](https://user-images.githubusercontent.com/48709672/156265664-d1480fdd-a665-43c3-b326-7fa714d840ba.png)

_
Woow, I should report this finding to GIMP too.

**Comment by yasirroni** [comment] 2022-03-01 23:41
> > PIL image save (have same DPI) ![Capture2](https://user-images.githubusercontent.com/48709672/156187809-596d2da6-afef-44e6-b7fa-bb014f87e58a.PNG)

Further finding, GIMP can recognize PIL modification that it has 600 DPI. Sadly, paint is not. So, the main problem is Paint.
_
But, GIMP capable to edit that can be recognized by Paint, but PIL can't (I don't know how yet). One way that GIMP capable is to by saving in xcf format first.

**Comment by radarhere** [comment] 2022-03-02 02:44
Thanks. One difference that I can see - the successful image has an IHDR chunk with ColorType 2 (RGB), whereas the other two are 6 (RGBA). I know that's not DPI directly, but maybe Paint is re-rendering the image if it doesn't like the type.

So I ran this code,
```python
from PIL import Image

img = Image.open("original.png")
img.convert("RGB").save("rgb.png", dpi=(600, 600))
```
and created this image. Does Paint successfully show the DPI from this image?

![rgb](https://user-images.githubusercontent.com/3112309/156284669-10242212-8243-4cf7-a14a-776ec23c6830.png)

**Comment by yasirroni** [comment] 2022-03-02 02:48
Works like a charm~

![image](https://user-images.githubusercontent.com/48709672/156285287-fd179f3a-3dca-4ff1-8a2d-e43bca175dc7.png)

**Comment by Pjumpod** [comment] 2024-08-15 13:09
I found the same problem. it depend on pictures. example this one, it is 72dpi and I cannot save it with DPI 300.
![Original_500px_72dpi](https://github.com/user-attachments/assets/4b11e076-f426-4ab4-bb92-bdb261dd3285)
![image](https://github.com/user-attachments/assets/77635317-d044-4517-add9-07571257663d)

I already try this solution but the dpi still not change.

> from PIL import Image
> 
> img = Image.open("original.png")
> img.convert("RGB").save("rgb.png", dpi=(600, 600))

**Comment by radarhere** [comment] 2024-08-15 21:09
What program are you using to check the results?

If I run the code from your post over that image, I get the following in macOS Preview.
![final](https://github.com/user-attachments/assets/7c03de65-ed66-4071-9b99-7e299cddb366)

**Comment by Pjumpod** [comment] 2024-08-16 03:29
> What program are you using to check the results?
> 
> If I run the code from your post over that image, I get the following in macOS Preview. ![final](https://private-user-images.githubusercontent.com/3112309/358395981-7c03de65-ed66-4071-9b99-7e299cddb366.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzkyMjMsIm5iZiI6MTcyMzc3ODkyMywicGF0aCI6Ii8zMTEyMzA5LzM1ODM5NTk4MS03YzAzZGU2NS1lZDY2LTQwNzEtOWI5OS03ZTI5OWNkZGIzNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDMyODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkwMDQzN2Q3YjQwMjliN2RlMjEwZmEyNDE3ZGY1YWQyMWE3ZDZiZTE5ZmZkMDk2NzEzNzhlMzZkOTgwM2RkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cVy8B2aXsn1v5vFEVAAHpMjmnEYTXKssLtH5yqqhV30)

I use the picture properties in Windows. (Right click on the picture and select properties.)

**Comment by radarhere** [comment] 2024-08-16 04:40
What version of Pillow are you using? Could you upload a copy of rgb.png?

**Comment by Pjumpod** [comment] 2024-08-16 11:49
good point, my pillow version is 10.1.0
Today I found that the issue solved when I upgrade to latest version
