### ISSUE TITLE
Unable to import Image in MacOSX 10.12 with Pillow 9.1.0

### ISSUE THREAD

**Issue by exhumea** [python-pillow/Pillow#6217] opened 2022-04-15 18:46 UTC
### What did you do?

Simply tried to `from PIL import Image` on my MacOSX 10.12 machine.

### What did you expect to happen?

Import works.
Note that `Pillow 9.0.1` works fine.

### What actually happened?

Low-level import error
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ci/miniconda3/envs/test_pil/lib/python3.9/site-packages/PIL/Image.py", line 132, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/ci/miniconda3/envs/test_pil/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/ci/miniconda3/envs/test_pil/lib/python3.9/site-packages/PIL/.dylibs/libtiff.5.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/ci/miniconda3/envs/test_pil/lib/python3.9/site-packages/PIL/.dylibs/libtiff.5.dylib

### What are your OS, Python and Pillow versions?

* OS: MacOSX 10.12.6
* Python: 3.9.12
* Pillow: 9.1.0

```python
import PIL # Works
PIL.__version__ # '9.1.0'
from PIL import Image
"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ci/miniconda3/envs/test_pil/lib/python3.9/site-packages/PIL/Image.py", line 132, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/ci/miniconda3/envs/test_pil/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/ci/miniconda3/envs/test_pil/lib/python3.9/site-packages/PIL/.dylibs/libtiff.5.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/ci/miniconda3/envs/test_pil/lib/python3.9/site-packages/PIL/.dylibs/libtiff.5.dylib
"""
```

### Full stacktrace (screenshot) :
<img width="1109" alt="Capture d’écran 2022-04-15 à 20 37 41" src="https://user-images.githubusercontent.com/31568095/163608899-c6dfccfb-cec0-4a74-b7d1-33ef671b613f.png">

**Comment by nulano** [comment] 2022-04-15 19:18
Duplicate of #6179?

**Comment by radarhere** [comment] 2022-04-15 21:18
I agree this is a duplicate.

Hi. Yes, we made a mistake with the Pillow 9.1.0 wheels. It should fixed for future Pillow releases. For the moment, if you go to https://github.com/python-pillow/Pillow/issues/6179#issuecomment-1092412377, you can download a wheel for Python 3.9 that should work for you.

**Comment by exhumea** [comment] 2022-04-15 22:41
Hi, indeed, thank you! (Sorry for the duplicate, I did not search among closed issues that's why I did not spot it)

**Closed** 2022-04-15 22:42 UTC
Labels: Duplicate, Installation, macOS
