### ISSUE TITLE
TIFF image cannot be identified

### ISSUE THREAD

**Issue by dorphalsig** [python-pillow/Pillow#7007] opened 2023-03-12 12:45 UTC
Hi all,

When I try to open a specific TIFF image I get an error message saying the image could not be identified. This only happens with this one image, I thought at first it was corrupt, but photoshop, imagemagick and photo viewer can read it no prob. I even tried to save a copy from photoshop to see if there was something weird going on but I still get the same error.

Attached is the file (in zip, because I can't upload TIFFs).
[9895240_PID_HB2_SU.zip](https://github.com/python-pillow/Pillow/files/10950834/9895240_PID_HB2_SU.zip)

**Comment by Yay295** [comment] 2023-03-12 13:41
It looks like that image has five channels, with one `ExtraSamples`, so that might be why Pillow can't load it; it's not in Pillow's list of supported TIFF formats: https://github.com/python-pillow/Pillow/blob/5b3d39c116d012a1a533b7a59360b2451addc36a/src/PIL/TiffImagePlugin.py#L140-L258

![capture_2023-03-12_08 32 37_00](https://user-images.githubusercontent.com/8922038/224548413-d7cb6a38-dfc1-4561-91c2-93a0f09bfe9e.png)
![capture_2023-03-12_08 41 02_01](https://user-images.githubusercontent.com/8922038/224548478-10e7864e-231c-4d3b-8e37-a896fa7884e6.png)

**Comment by radarhere** [comment] 2023-03-13 07:32
The format key for your image is `(b'II', 5, (1,), 1, (8, 8, 8, 8, 8), (1,))`, which has previously been reported in https://github.com/python-pillow/Pillow/issues/3989#issuecomment-585747707

So this is a duplicate of that issue.

**Closed** 2023-03-14 07:19 UTC
Labels: Duplicate, TIFF
