### ISSUE TITLE
Errors upgrading to 3.0.0, IndexError: index out of range and struct.error: unpack requires a bytes object of length 2

### ISSUE THREAD

**Issue by troygrosfield** [python-pillow/Pillow#1474] opened 2015-10-05 17:41 UTC
I'm seeing two separate issues pop up when upgrading pillow from 2.9.0 to 3.0.0.  I don't see the errors when running the test suite in 2.9.0:

```
Traceback (most recent call last):
  File "/py34/lib/python3.4/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/py34/lib/python3.4/site-packages/PIL/JpegImagePlugin.py", line 308, in _open
    i = i8(s)
  File "/py34/lib/python3.4/site-packages/PIL/_binary.py", line 24, in i8
    return c if c.__class__ is int else c[0]
IndexError: index out of range
```

```
Traceback (most recent call last):
  File "/py34/lib/python3.4/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/py34/lib/python3.4/site-packages/PIL/PngImagePlugin.py", line 514, in _open
    self.png.crc(cid, s)
  File "/py34/lib/python3.4/site-packages/PIL/PngImagePlugin.py", line 142, in crc
    crc2 = i16(self.fp.read(2)), i16(self.fp.read(2))
  File "/py34/lib/python3.4/site-packages/PIL/_binary.py", line 53, in i16be
    return unpack(">H", c[o:o+2])[0]
struct.error: unpack requires a bytes object of length 2
```

FWIW, I'm running the tests using **django 1.8.5**, **python 3.4.3**.  I'm still working to build the case on how exactly to recreate either issue.

**Comment by troygrosfield** [comment] 2015-10-05 17:53
He's how to recreate the second error from above:

```
>>> from django.core.files.images import ImageFile
>>> path = '/path/to/images/test-placeholder.png'
>>> image = ImageFile(open(path, 'rb'))
>>> image.height
%s
Traceback (most recent call last):
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/PngImagePlugin.py", line 514, in _open
    self.png.crc(cid, s)
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/PngImagePlugin.py", line 142, in crc
    crc2 = i16(self.fp.read(2)), i16(self.fp.read(2))
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/_binary.py", line 53, in i16be
    return unpack(">H", c[o:o+2])[0]
struct.error: unpack requires a bytes object of length 2
%s
Traceback (most recent call last):
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/PngImagePlugin.py", line 514, in _open
    self.png.crc(cid, s)
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/PngImagePlugin.py", line 142, in crc
    crc2 = i16(self.fp.read(2)), i16(self.fp.read(2))
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/_binary.py", line 53, in i16be
    return unpack(">H", c[o:o+2])[0]
struct.error: unpack requires a bytes object of length 2
```
I've also attached the image used for the test case.

![test-placeholder](https://cloud.githubusercontent.com/assets/1551551/10288677/a5311cc2-6b57-11e5-8313-a4b8dafb3e00.png)

**Comment by hugovk** [comment] 2015-10-05 20:09
Not reproducible on Travis CI with pypy or 2.7.

Reproducible with pypy3, 3.2, 3.3, 3.4 and 3.5, but it's just printing those errors out, and not failing; an added last line `assert(im.height == 22)` passes fine. 

(Python 2.6 has another error.)

https://travis-ci.org/hugovk/test/builds/83763299

Can you reproduce just using Pillow and not Django?

**Comment by troygrosfield** [comment] 2015-10-05 21:19
As it relates to the first issue, here's the output from the first issue error...

**To reproduce the error output:**
```
from PIL import ImageFile as PillowImageFile
import zlib

def get_image_dimensions(file_or_path, close=False):
    p = PillowImageFile.Parser()
    
    if hasattr(file_or_path, 'read'):
        file = file_or_path
        file_pos = file.tell()
        file.seek(0)
    else:
        file = open(file_or_path, 'rb')
        close = True
    try:
        # Most of the time Pillow only needs a small chunk to parse the image
        # and get the dimensions, but with some TIFF files Pillow needs to
        # parse the whole file.
        chunk_size = 1024
        while 1:
            data = file.read(chunk_size)
            if not data:
                break
            try:
                p.feed(data)
            except zlib.error as e:
                # ignore zlib complaining on truncated stream, just feed more
                # data to parser (ticket #19457).
                if e.args[0].startswith("Error -5"):
                    pass
                else:
                    raise
            if p.image:
                return p.image.size
            chunk_size *= 2
        return None
    finally:
        if close:
            file.close()
        else:
            file.seek(file_pos)

get_image_dimensions('/path/to/images/test-image-640x360.jpg')
```
**Output**
```
Traceback (most recent call last):
  File "/py34/lib/python3.4/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/py34/lib/python3.4/site-packages/PIL/JpegImagePlugin.py", line 308, in _open
    i = i8(s)
  File "/py34/lib/python3.4/site-packages/PIL/_binary.py", line 24, in i8
    return c if c.__class__ is int else c[0]
IndexError: index out of range
%s
Traceback (most recent call last):
  File "/py34/lib/python3.4/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/py34/lib/python3.4/site-packages/PIL/JpegImagePlugin.py", line 308, in _open
    i = i8(s)
  File "/py34/lib/python3.4/site-packages/PIL/_binary.py", line 24, in i8
    return c if c.__class__ is int else c[0]
IndexError: index out of range
%s
Traceback (most recent call last):
  File "/py34/lib/python3.4/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/py34/lib/python3.4/site-packages/PIL/JpegImagePlugin.py", line 308, in _open
    i = i8(s)
  File "/py34/lib/python3.4/site-packages/PIL/_binary.py", line 24, in i8
    return c if c.__class__ is int else c[0]
IndexError: index out of range
%s
Traceback (most recent call last):
  File "/py34/lib/python3.4/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/py34/lib/python3.4/site-packages/PIL/JpegImagePlugin.py", line 308, in _open
    i = i8(s)
  File "/py34/lib/python3.4/site-packages/PIL/_binary.py", line 24, in i8
    return c if c.__class__ is int else c[0]
IndexError: index out of range
%s
Traceback (most recent call last):
  File "/py34/lib/python3.4/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/py34/lib/python3.4/site-packages/PIL/JpegImagePlugin.py", line 308, in _open
    i = i8(s)
  File "/py34/lib/python3.4/site-packages/PIL/_binary.py", line 24, in i8
    return c if c.__class__ is int else c[0]
IndexError: index out of range
Out[2]: (640, 360)
```

As you mentioned, it prints the error, but also returns the correct output.  As I look back at the test runs, all the tests I mention pass using pillow 3.0.  However, I was assuming there were errors because the two errors originally listed litter the test run output (while still passing).

The attached file used for the test:

![test-image-640x360](https://cloud.githubusercontent.com/assets/1551551/10293914/672f7fdc-6b74-11e5-953d-5aa9dd844ec5.jpg)

**Comment by troygrosfield** [comment] 2015-10-05 21:24
If I use the same snippet in the previous comment (```get_image_dimensions(...)```) you'll see the error output:

```
>>> get_image_dimensions('/path/to/images/test-placeholder.png')
%s
Traceback (most recent call last):
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/PngImagePlugin.py", line 514, in _open
    self.png.crc(cid, s)
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/PngImagePlugin.py", line 142, in crc
    crc2 = i16(self.fp.read(2)), i16(self.fp.read(2))
  File "/Users/troy/.virtualenvs/py34/lib/python3.4/site-packages/PIL/_binary.py", line 53, in i16be
    return unpack(">H", c[o:o+2])[0]
struct.error: unpack requires a bytes object of length 2
Out[3]: (23, 22)
```

**Comment by wiredfool** [comment] 2015-10-06 10:57
So I think what's happening here is that there's a combination of things. (of course)

- First, there's the change to the _binary methods to use pack and unpack. These pick up mistreads that would have previously gone unreported, e.g., when there's not enough data for a long, the old version would happily give a best guess from the data it had. It looks like this might have predated 2.9.0, but I'm not 100% sure on that. 
- Second, while most of the decoders can take incremental bits of data, the metadata readers really aren't setup that way. So when it's feeding 1k at a time to the parser, it's expecting to read and seek through that metadata to read the individual chunks. 

I think what's happening is that the metadata is large enough that one of the chunks that it's trying to read is at least partially over the end of what's been fed to the decoder, in this case, it's reading a couple fo bytes for the crc.

**Comment by hugovk** [comment] 2015-10-06 12:03
>  It looks like this might have predated 2.9.0, but I'm not 100% sure on that.

Yep, the _binary changes were on 1st March, so have been there since 2.8.0.
https://github.com/python-pillow/Pillow/commit/aeb1e61aa753beacf442763f0df23af8fb9c781c

But the errors aren't shown with 2.9.0 (released 1st July):
https://travis-ci.org/hugovk/test/jobs/83870499

**Comment by wiredfool** [comment] 2015-10-06 12:10
Well, I can't replicate on 2.7. Running the above:
```
No handlers could be found for logger "PIL.ImageFile"
(640, 360)
```
3.4 is giving the above traces.

It's looking like this is fallout from the debugging traces versus logging that was done right after 2.9.0. Setting logger.setLevel(logging.CRITICAL) suppresses the 'errors'.

**Comment by hugovk** [comment] 2015-10-06 13:01
Yes, only Python 3.x are printing all those errors. I also get the same one-liner for 2.7.

---

The catch to log `struct.error` exceptions was added in this 31st July commit:
https://github.com/python-pillow/Pillow/commit/b8b3cdc146cdc588b7da1f94ba5ab3a196508659#diff-6b6c4410a4159082c840f529897c991aR105

Which results in `logger.exception("%s")` being newly called in this case.

From PR https://github.com/python-pillow/Pillow/pull/1366:

> This fixes regression from #1121 (version 2.8.1).
Starting from #1121 all functions in _binary.py start raising struct.error instead of IndexError. This leads to two side effects with truncated PNG images: wrong exception type when LOAD_TRUNCATED_IMAGES = False and truncated files are not loaded when LOAD_TRUNCATED_IMAGES = True.

**Comment by shredding** [comment] 2015-10-09 08:11
I have the same error, disappears after reverting to pillow 2.9.0. Please note that the current django 1.8.x does yet have merged this fix:

https://github.com/django/django/blob/8047e3666b0b50bb04e6f16c2a4fb21ddfd5713f/django/core/files/images.py#L75 

(I don't know if this is related).

**Comment by wiredfool** [comment] 2015-10-09 12:29
It looks like Hugo's found the place where the logging is triggered. 

This does not appear to be a bug, in that once enough of the image is fed into the parser, there will be a successful interpretation of the image. When there isn't enough data in the buffer, the `Image.open` (which ends up calling ImageFile.open) call in `ImageFile.Parser.feed` dies with some error, which is entirely expected and handled in `feed`. Because it's logged as an error in `open`, it's now showing up as an error. 

The change to django  shouldn't affect this, as the error is never propagated out Pillow. 

I think the best case is either to delete the logging of the exception, or ratchet it's importance down to DEBUG at the most. Or revert the debug flag vs logging commit completely, but that's likely to ruffle some feathers.

**Comment by thijstriemstra** [comment] 2015-10-14 16:05
Also see `No handlers could be found for logger "PIL.ImageFile"` in my unit tests after upgrading to 3.0.0. Didn't break anything in my project though.

**Comment by soar** [comment] 2015-10-28 10:05
I can confirm this issue

**Comment by codecresta** [comment] 2015-11-02 13:41
I tried downgrading to version 2.9, but I still get this error.  Is there an easy way to suppress this error from being logged?  If so how?

**Comment by comandrei** [comment] 2015-11-09 12:33
I can also confirm the issue.

**Comment by daviddyball** [comment] 2015-12-03 15:12
I don't want to simply +1 this, but I can reproduce this issue using Ubuntu `14.04`, Python `2.7.3`, Django `1.8.4` and Pillow `3.0.0` and I get the following stack-trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 100, in __init__
              self._open()
  File "/usr/local/lib/python2.7/dist-packages/PIL/JpegImagePlugin.py", line 308, in _open
              i = i8(s)
  File "/usr/local/lib/python2.7/dist-packages/PIL/_binary.py", line 18, in i8
          return ord(c)
TypeErrorord() expected a character, but string of length 0 found
```

Reverting to 2.9.0 for the time being has resolved the immediate issue.

**Comment by stepmr** [comment] 2015-12-13 18:01
I can confirm this issue too

**Comment by wiredfool** [comment] 2015-12-29 23:03
This should be fixed in master.

**Closed by wiredfool** 2015-12-29 23:03 UTC

**Comment by codecresta** [comment] 2016-01-03 00:02
Which version will this be fixed in?

**Comment by radarhere** [comment] 2016-01-03 00:16
3.1, which should be released within the next few days.
