### ISSUE TITLE
Tamil font is rendered in a wrong manner in matplotlib

### ISSUE THREAD

**Issue by GitPavan123** [python-pillow/Pillow#8481] opened 2024-10-17 21:14 UTC
I have been working on with a project in matplotlib.
I'm trying to display tamil texts in a pie chart.
I did downloaded and specified the appropriate font paths (In my case Brahmini, Noto sans tamil, Tiro, etc...)
Everything does render the tamil font but it is completely in a wrong manner.
Figure(1) is the actual rendering.
Figure(2) is the required rendering.
 
### CODING ###
```python
import matplotlib.pyplot as plt
from matplotlib.font_manager import FontProperties

font_path = r"Fonts\Tamil Font.TTF" //Replace with a tamil font path

tamil_font = FontProperties(fname=font_path) 

sizes = [25, 35, 20, 20]  
labels = ['எனக்கு ', 'மின்விசிறி', 'கலை', 'வாழைப்பழம்']  
colors = ['#ff9999','#66b3ff','#99ff99','#ffcc99']

fig, ax = plt.subplots()
wedges, texts, autotexts = ax.pie(sizes, colors=colors, autopct='%1.1f%%', startangle=90)

ax.axis('equal')

for i, autotext in enumerate(autotexts):
    autotext.set_text(labels[i])  
    autotext.set_color("black")  
    autotext.set_fontsize(12)  
    autotext.set_fontproperties(tamil_font)  

for text in texts:
    text.set_fontproperties(tamil_font)

plt.show()
```
![Screenshot 2024-10-18 024111](https://github.com/user-attachments/assets/3046709d-0680-45d7-9f24-fdfa3f6d7c8d)
![image](https://github.com/user-attachments/assets/91967259-99f3-4668-af87-d9dbbba75472)

**Comment by radarhere** [comment] 2024-10-17 21:22
Hi. Do you have raqm installed?
```pycon
>>> from PIL import features
>>> features.check("raqm")
True
```

**Comment by GitPavan123** [comment] 2024-10-18 01:52
No what is it's used for?

**Comment by radarhere** [comment] 2024-10-18 02:16
Complex text rendering. It is "[recommended for all non-English text](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html)". See https://github.com/python-pillow/Pillow/issues/6018#issuecomment-1030893495 for an instance where using Raqm has solved Tamil rendering in the past.

How did you install Pillow?

If you're a Windows user, I suggest looking at https://pillow.readthedocs.io/en/stable/installation/building-from-source.html
> On Windows this requires compiling FriBiDi and installing fribidi.dll into a directory listed in the [Dynamic-link library search order (Microsoft Learn)](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-unpackaged-apps) (fribidi-0.dll or libfribidi-0.dll are also detected).

**Comment by GitPavan123** [comment] 2024-10-18 13:21
I installed pillow in my conda environment using the  command "pip install pillow".
But even though i upgrade my pillow version still it returns false for the checking the existence of raqm.

**Comment by radarhere** [comment] 2024-10-18 14:10
What operating system are you using?

Could you uninstall Pillow, and then run `pip install -v Pillow` and show us the output?

**Comment by GitPavan123** [comment] 2024-10-18 17:40
Iam using windows os

**Comment by radarhere** [comment] 2024-10-18 22:10
Have you attempted placing fribidi in the correct location? Here is fribidi.dll from our recent Pillow 11.0.0 release for various architectures - [fribidi.zip](https://github.com/user-attachments/files/17441205/fribidi.zip)

https://pillow.readthedocs.io/en/stable/installation/building-from-source.html
> On Windows this requires compiling FriBiDi and installing fribidi.dll into a directory listed in the [Dynamic-link library search order (Microsoft Learn)](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-unpackaged-apps) (fribidi-0.dll or libfribidi-0.dll are also detected).

**Comment by GitPavan123** [comment] 2024-10-19 17:58
Can you please help me with all the necessary steps involved in setting up fribidi, pillow, matplotlib, raqm since iam not at all familiar with these text rendering engines

**Comment by GitPavan123** [comment] 2024-10-19 18:46
I have installed raqm and now i get true for the following code,
>>> from PIL import features
>>> features.check("raqm")

Now how do i enable or activate raqm to render text in matplotlib pie chart?

**Comment by radarhere** [comment] 2024-10-19 20:32
Hmm. I would have expected the correct output once you had done that.

If matplotlib is still not working as you expect, does the following Pillow-only code work?
```python
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype(r"Fonts\Tamil Font.TTF", 25)

im = Image.new("RGB", (250, 250))
draw = ImageDraw.Draw(im)

for i, text in enumerate(['எனக்கு ', 'மின்விசிறி', 'கலை', 'வாழைப்பழம்']):
    draw.text((20, 20+i*50), text, font=font, fill="white")
im.show()
```

**Comment by GitPavan123** [comment] 2024-10-20 02:52
The provided code does give the correct output but in matplotlib it is not outputting correctly

**Comment by radarhere** [comment] 2024-10-20 05:50
Ok, so we are agreed that Pillow by itself is behaving correctly.

Can I ask - what led you to the conclusion that incorrect matplotlib output was caused by Pillow? Searching through the matplotlib main, I see no calls to `truetype()` or `FreeTypeFont`.

https://github.com/matplotlib/matplotlib/issues/5941#issuecomment-176474866 says
> Matplotlib uses its own basic text layout algorithm, rather than something like Pango, which can handle internationalized text. This is the main purpose of MEP14

MEP14 is https://matplotlib.org/devdocs/devel/MEP/MEP14.html

https://github.com/matplotlib/matplotlib/issues/23082 indicates that using https://github.com/matplotlib/mplcairo might be the solution.

**Comment by GitPavan123** [comment] 2024-10-20 06:06
Can you please tell me indepth about setting up mpl cairo backend to overcome the issue

**Comment by radarhere** [comment] 2024-10-20 11:05
Could you
1. `pip install mplcairo`
2. Add the following to the beginning of your Python script?
```python
import matplotlib
matplotlib.use("module://mplcairo.tk")

# Once your code is working, this can be removed.
# It is just to force an error to be raised if raqm cannot be found
import mplcairo
mplcairo.set_options(raqm=True)
```

Then try to run your script again. If an error is displayed, please let us know what it is.

**Comment by GitPavan123** [comment] 2024-10-20 11:31
import matplotlib.pyplot as plt
from matplotlib.font_manager import FontProperties
import matplotlib.pyplot as plt
import mplcairo
import matplotlib

matplotlib.use("module://mplcairo.tk")

mplcairo.set_options(raqm=True)

font_path = r"Fonts\Tamil Font.TTF"

tamil_font = FontProperties(fname=font_path)

plt.title('எனக்கு', fontproperties=tamil_font)

plt.show()




with this code i get the following error,

(.venv) C:\Users\pavan\StudioProjects\UK_Client>python temp.py
Traceback (most recent call last):
  File "C:\Users\pavan\StudioProjects\UK_Client\temp.py", line 10, in <module>
    mplcairo.set_options(raqm=True)
OSError: [WinError 126] The specified module could not be found

mplcairo is installed successfully and so fribidi and raqm as well

**Comment by radarhere** [comment] 2024-10-21 19:33
mplcairo README says
> the directory containing libraqm.dll and libfribidi-0.dll need to be added to the [DLL search path](https://docs.python.org/3/library/os.html#os.add_dll_directory)

This is really a question for https://github.com/matplotlib/mplcairo. They will have the proper expertise to help you out.

**Comment by nulano** [comment] 2024-10-21 21:58
> libraqm.dll and libfribidi-0.dll

~~I'd wager a guess that these are the libs that cgohlke was providing for Pillow before #5062 was merged.~~ Actually, looking at the readme, it specifically links to the page that used to host cgohlke's Pillow builds.

But yes, this is a question for mplcairo, not Pillow, especially since we no longer use or build `libraqm.dll`.

**Closed** 2024-10-22 06:59 UTC
Labels: Windows, Third Party Framework, Font Rendering
