### ISSUE TITLE
Stroke color for font

### ISSUE THREAD

**Issue by controversial** [python-pillow/Pillow#1907] opened 2016-05-12 00:44 UTC
Is there a way in `ImageDraw` or `ImageFont` to draw text with a border color? If not, there probably should be. [It can be faked](http://stackoverflow.com/a/8050556/4414003) but it'd be nice if this functionality was built-in.

**Comment by radarhere** [comment] 2016-06-17 10:33
The only solutions that I'm aware of are the workaround already suggested, or finding a font file that has a shadow built in.

**Comment by HinTak** [comment] 2017-05-08 19:24
https://github.com/rougier/freetype-py have 4 examples on this.

**Comment by radarhere** [comment] 2019-03-19 01:15
Closing as a duplicate of #2209. I know this issue was first, but that one has more detail.

**Closed by radarhere** 2019-03-19 01:15 UTC
Labels: Enhancement

**Comment by radarhere** [comment] 2019-07-19 09:10
I've created PR #3978 to resolve this.
