### ISSUE TITLE
When opening an invalid image with 2.8.0, an unpack error is generated instead of IOError.

### ISSUE THREAD

**Issue by danielsamuels** [python-pillow/Pillow#1163] opened 2015-04-01 21:00 UTC
Bare-bones example available here (using Django as a base): https://github.com/danielsamuels/pillow-test

If you attempt to perform `Image.open(f)` on an invalid image, the following error is generated:

```
Traceback (most recent call last):
  File "/pillow-test/testing/tests.py", line 12, in test_invalid_file
    Image.open(test_file)
  File "/pillow-test/.venv/lib/python2.7/site-packages/PIL/Image.py", line 2279, in open
    if not accept or accept(prefix):
  File "/pillow-test/.venv/lib/python2.7/site-packages/PIL/FliImagePlugin.py", line 33, in _accept
    return i16(prefix[4:6]) in [0xAF11, 0xAF12]
  File "/pillow-test/.venv/lib/python2.7/site-packages/PIL/_binary.py", line 39, in i16le
    return unpack("<H", c[o:o+2])[0]
error: unpack requires a string argument of length 2
```

**Comment by aclark4life** [comment] 2015-04-01 21:02
Thanks, what was the previous behavior?

**Comment by danielsamuels** [comment] 2015-04-01 21:03
Running the same code under 2.7.0 I receive the following error:

```
Traceback (most recent call last):
  File "/pillow-test/testing/tests.py", line 12, in test_invalid_file
    Image.open(test_file)
  File "/pillow-test/.venv/lib/python2.7/site-packages/PIL/Image.py", line 2274, in open
    % (filename if filename else fp))
IOError: cannot identify image file <SimpleUploadedFile: invalid.jpeg (image/jpeg)>
```

**Comment by aclark4life** [comment] 2015-04-01 21:09
OK so we've broken invalid image handling. I'll try to get a 2.8.1 out ASAP, sorry about that.

**Comment by aclark4life** [comment] 2015-04-01 22:53
@mfitzp Any chance this is due to your new feature? I will take a look shortly but I thought maybe you'd know immediately. Thanks

**Comment by wiredfool** [comment] 2015-04-01 22:56
I think there was a style update that hit the FliImagePlugin.

**Comment by aclark4life** [comment] 2015-04-01 23:17
@wiredfool I'm going to guess that changes to Image.py caused opening invalid files to end up in FliImagePlugin somehow… when the open should never make it that far. Here's the  entire _accept method that fails:

```
def _accept(prefix):
    return i16(prefix[4:6]) in [0xAF11, 0xAF12]

```

I can't imagine that code has changed much. Though being more careful there would be nice too.

**Comment by aclark4life** [comment] 2015-04-02 01:17
OK I'm stumped. I don't see anything obviously wrong anywhere. :8ball:

**Comment by wiredfool** [comment] 2015-04-02 02:00
This sounds like a job for BICYCLE REPAIR MAN!!!!!


no sorry, wrong superhero. `git bisect` should do it.

**Comment by wiredfool** [comment] 2015-04-02 02:06
Is there a bad image that hits this in the repo?  I didn't  see `invalid.jpeg` anywhere.

**Comment by hugovk** [comment] 2015-04-02 04:28
FliImagePlugin.py hasn't changed in 7 months, so has been the same since 2.6.0.

"invalid.jpeg" is just a dummy filename given in the test program: https://github.com/danielsamuels/pillow-test

The image is created by Django's `SimpleUploadedFile` with data = "data", which is clearly invalid.

**Comment by hugovk** [comment] 2015-04-02 04:45
Is it a stockbroker? Is it a quantity surveyor? Is it a church warden? No! It's BICYCLE REPAIR MAN!!!

Or rather, I can reproduce and `git bisect` gives:

```
aeb1e61aa753beacf442763f0df23af8fb9c781c is the first bad commit
commit aeb1e61aa753beacf442763f0df23af8fb9c781c
Author: amoibos <amoibos@gmail.com>
Date:   Sun Jan 11 23:29:47 2015 +0100

    let python do the endian stuff

:040000 040000 8d82aeb52d849ed636fcdae05ff7afe7357b573c aeeecd81b2181efca2e735eb6bb2625b9d123aa6 M	PIL
```

**Comment by wiredfool** [comment] 2015-04-02 04:53
Ok, minimal test without Django:

```
#!/usr/bin/env python

from PIL import Image
import io
import sys

b = io.BytesIO('a'*1024)

try:
    img = Image.open(b)
except IOError:
    print "success"
    sys.exit(0)

sys.exit(1)
```

Returns success, but with shorter arbitrary strings, it fails in a different location. 
4: 
```
Traceback (most recent call last):
  File "../invalid/test.py", line 10, in <module>
    img = Image.open(b)
  File "build/bdist.linux-x86_64/egg/PIL/Image.py", line 2279, in open
  File "build/bdist.linux-x86_64/egg/PIL/DcxImagePlugin.py", line 36, in _accept
  File "build/bdist.linux-x86_64/egg/PIL/_binary.py", line 49, in i32le
```

5:
```
  File "../invalid/test.py", line 10, in <module>
    img = Image.open(b)
  File "build/bdist.linux-x86_64/egg/PIL/Image.py", line 2279, in open
  File "build/bdist.linux-x86_64/egg/PIL/FliImagePlugin.py", line 33, in _accept
  File "build/bdist.linux-x86_64/egg/PIL/_binary.py", line 39, in i16le
struct.error: unpack requires a string argument of length 2
```

2.7.0 successfully dies with the IOerror.

**Comment by hugovk** [comment] 2015-04-02 04:56
Reverting the changes to PIL/_binary.py from https://github.com/python-pillow/Pillow/pull/1121 fixes the problem. I've left the test case from that PR.

I've made a PR: https://github.com/python-pillow/Pillow/pull/1164

Assuming that's ok to release, two things to do (can be post-release):

1. Create a test case for an invalid JPEG without Django
2. Fix https://github.com/python-pillow/Pillow/pull/1121, if desired

**Comment by hugovk** [comment] 2015-04-02 04:58
The minimal test without Django passes on my machine with PIL/_binary.py reverted.

**Comment by wiredfool** [comment] 2015-04-02 04:59
So, the underlying issue is that we're (safely, in pythonland) reading off the end of a buffer, and trying to convert it. But now, we're getting a different exception than we used to, or previously we were simply truncating what we got. 

I'm not entirely clear that the old behavior was correct, and we may be better served by catching/rethrowing an io error.

**Comment by wiredfool** [comment] 2015-04-02 05:04
What about this:
```
diff --git a/PIL/Image.py b/PIL/Image.py
index 58944f8..3a104c1 100644
--- a/PIL/Image.py
+++ b/PIL/Image.py
@@ -110,6 +110,7 @@ from PIL._util import deferred_error
 import os
 import sys
 import io
+import struct
 
 # type stuff
 import collections
@@ -2281,7 +2282,7 @@ def open(fp, mode="r"):
                     im = factory(fp, filename)
                     _decompression_bomb_check(im.size)
                     return im
-            except (SyntaxError, IndexError, TypeError):
+            except (SyntaxError, IndexError, TypeError, struct.error):
                 # import traceback
                 # traceback.print_exc()
                 pass
```

**Comment by hugovk** [comment] 2015-04-02 05:08
Catching `struct.error ` fails the right way:

```
ERROR: test_invalid_file (testing.tests.PillowTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/pillow-test/testing/tests.py", line 12, in test_invalid_file
    Image.open(test_file)
  File "/Users/hugo/github/Pillow/PIL/Image.py", line 2291, in open
    % (filename if filename else fp))
IOError: cannot identify image file <SimpleUploadedFile: invalid.jpeg (image/jpeg)>
```

**Comment by wiredfool** [comment] 2015-04-02 05:09
Yep. We'll probably need one at line 2270 as well, post `preinit()` and pre `init()`.

**Comment by hugovk** [comment] 2015-04-02 05:42
PR for that: https://github.com/python-pillow/Pillow/pull/1165

**Comment by aclark4life** [comment] 2015-04-02 11:28
@danielsamuels Any preference on the fix for this?  #1165 or #1164 . Also @homm and @wiredfool weigh in and majority rules. @hugo and are +1 for #1165 . I'm assuming #1165 is the winner, but I want to make extra-sure before releasing 2.8.1. Thanks all

**Comment by danielsamuels** [comment] 2015-04-02 11:37
No preference for me, I don't know your codebase well enough to be able to make a judgement. For me, any fix which resolves the issue is fine.

**Comment by aclark4life** [comment] 2015-04-02 11:40
@danielsamuels We don't know our code base that well either, apparently :wink: but it's 20 years old now, so I don't feel too bad. Anyway, 2.8.1 should be out today-ish.

**Comment by homm** [comment] 2015-04-02 14:46
+1 for #1165

**Comment by aclark4life** [comment] 2015-04-02 15:09
Thanks all, 2.8.1 source is up: https://pypi.python.org/pypi/Pillow/2.8.1

**Comment by danielsamuels** [comment] 2015-04-02 15:50
I can confirm that our test suite is now passing under 2.8.1. Thanks all! :+1:

**Comment by aclark4life** [comment] 2015-04-02 16:11
Great, thanks for the report @danielsamuels

**Comment by tukhfatov** [comment] 2015-05-05 21:17
Still got this problem under 2.8.1 version. How to solve? 

     File "/var/www/***/lib/python2.7/site-packages/sorl/thumbnail/engines/pil_engine.py", line 71, in  _orientation
       exif = image._getexif()
     File "/var/www/***/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 390, in _getexi f
       return _getexif(self)
     File "/var/www/***/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 419, in _getexif
   info.load(file)
     File "/var/www/***/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 430, in load 
       tag, typ = i16(ifd), i16(ifd, 2)
     File "/var/www/***/lib/python2.7/site-packages/PIL/_binary.py", line 39, in i16le    
    return unpack("<H", c[o:o+2])[0]
    error: unpack requires a string argument of length 2

**Comment by vdboor** [comment] 2015-05-26 12:09
Some for me. I'm getting a similar error with Pillow 2.8.1, with JPEG images. Perhaps struct.error is not handled in some cases?

```
  File "/Users/diederik/Sites/virtualenvs/....nl26/lib/python2.6/site-packages/sorl/thumbnail/engines/pil_engine.py", line 71, in _orientation
    exif = image._getexif()
  File "/Users/diederik/Sites/virtualenvs/....nl26/lib/python2.6/site-packages/PIL/JpegImagePlugin.py", line 390, in _getexif
    return _getexif(self)
  File "/Users/diederik/Sites/virtualenvs/....nl26/lib/python2.6/site-packages/PIL/JpegImagePlugin.py", line 419, in _getexif
    info.load(file)
  File "/Users/diederik/Sites/virtualenvs/....nl26/lib/python2.6/site-packages/PIL/TiffImagePlugin.py", line 430, in load
    tag, typ = i16(ifd), i16(ifd, 2)
  File "/Users/diederik/Sites/virtualenvs/....nl26/lib/python2.6/site-packages/PIL/_binary.py", line 39, in i16le
error: unpack requires a string argument of length 2
```

Pillow 2.7.0 can handle the same image just fine:

```
PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 2284257280 bytes but only got 0. Skipping tag 0
```

**Comment by hugovk** [comment] 2015-05-26 12:36
Sounds like another regression caused by https://github.com/python-pillow/Pillow/commit/aeb1e61aa753beacf442763f0df23af8fb9c781c in 2.8.0 that needs handling.

In the meantime, you can `pip install pillow==2.7.0` to use the old version.

**Comment by aclark4life** [comment] 2015-05-26 12:39
Someone patch and I'll release 2.8.2

**Comment by radarhere** [comment] 2015-06-05 04:34
The image in Issue 518 (I'm deliberately not linking, since the issues aren't actually related) -

https://camo.githubusercontent.com/c1c9d345ca82c833ce2ee6e3e954fc97f1ba70ef/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333038383737332f323038363939322f33383039313233612d386536332d313165332d383338362d6564353435343532626132372e6a7067

has bad EXIF data. With it, the following code produces the bug -

    from PIL import Image
    x = Image.open('incrediblylongname.jpeg')
    x._getexif()`

I've created a PR of my attempt to fix it.

**Comment by radarhere** [comment] 2015-06-05 10:53
@tukhfatov or @vdboor, do you have a test image that could be redistributed under the Pillow licence?

**Comment by radarhere** [comment] 2015-06-08 01:33
Thanks @tukhfatov and @vdboor for reporting. I've managed to create a suitable test image.

2.8.2 has now been released, so this issue should be fixed.

**Comment by hugovk** [comment] 2015-06-08 06:01
Thanks @radarhere!

**Closed by hugovk** 2015-06-08 06:01 UTC
