### ISSUE TITLE
"unknown file extension" error whenever I try to save an image on Windows 10

### ISSUE THREAD

**Issue by MahmoudThePeltist** [python-pillow/Pillow#3381] opened 2018-09-28 22:29 UTC
### What did you do?
Attempt to save an image using the Image module, the screenshot is of a specific window that was captured using win32gui.

### What did you expect to happen?
the image to be saved as test.png

### What actually happened?
`ValueError: unknown file extension: .png`
I tried changing the extension to .jpg or .gif and it still failed
I tried replacing `im.save("image.png")` with `im.save("image.png", format='PNG')` but it failed with 
`KeyError: 'PNG'`

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 2.7.10
* Pillow:  5.2.0

```python
import win32gui
import win32ui
from ctypes import windll
from PIL import Image

hwnd = win32gui.FindWindow(None, 'bin')

# Change the line below depending on whether you want the whole window
# or just the client area. 
#left, top, right, bot = win32gui.GetClientRect(hwnd)
left, top, right, bot = win32gui.GetWindowRect(hwnd)
w = right - left
h = bot - top

hwndDC = win32gui.GetWindowDC(hwnd)
mfcDC  = win32ui.CreateDCFromHandle(hwndDC)
saveDC = mfcDC.CreateCompatibleDC()

saveBitMap = win32ui.CreateBitmap()
saveBitMap.CreateCompatibleBitmap(mfcDC, w, h)

saveDC.SelectObject(saveBitMap)

# Change the line below depending on whether you want the whole window
# or just the client area. 
#result = windll.user32.PrintWindow(hwnd, saveDC.GetSafeHdc(), 1)
result = windll.user32.PrintWindow(hwnd, saveDC.GetSafeHdc(), 0)
print result

bmpinfo = saveBitMap.GetInfo()
bmpstr = saveBitMap.GetBitmapBits(True)

im = Image.frombuffer(
    'RGB',
    (bmpinfo['bmWidth'], bmpinfo['bmHeight']),
    bmpstr, 'raw', 'BGRX', 0, 1)

win32gui.DeleteObject(saveBitMap.GetHandle())
saveDC.DeleteDC()
mfcDC.DeleteDC()
win32gui.ReleaseDC(hwnd, hwndDC)

if result == 1:
    #PrintWindow Succeeded
    im.save("test.png")
```

**Comment by radarhere** [comment] 2018-09-29 00:29
Could you provide the values of `bmpinfo['bmWidth']`, `bmpinfo['bmHeight']` and `bmpstr`? Just saving them from that point in your script. That would allow us to replicate the save operation.

**Comment by MahmoudThePeltist** [comment] 2018-10-01 17:16
The program freezes when i try to print those values.

**Comment by MahmoudThePeltist** [comment] 2018-10-01 17:21
adding 
```
print bmpinfo['bmWidth']
print bmpinfo['bmHeight']
print bmpstr
```
at line 36 results in the program freezing for a few minutes before printing the following:
```
1
1382
744
```
followed by a massive amount of ASCII question marks and space.

**Comment by radarhere** [comment] 2018-10-02 10:18
Okay, so the width is 1382, and the height is 744.

Could you run
```
with open('bmpstr.txt', 'w') as f:
    f.write(bmpstr)
```

And then upload the resulting bmpstr.txt file here?

**Comment by hugovk** [comment] 2018-10-02 10:38
I cannot reproduce with:

* OS: Windows 7
* Python: 2.7.11
* Pillow: 5.3.0

First got this, because I don't have a window titled `bin`:
```
Traceback (most recent call last):
  File "3381.py", line 11, in <module>
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', 'Invalid window handle.')
```

But it worked when changing line 6 to this, and opening https://www.google.com/ in Chrome:
```python
hwnd = win32gui.FindWindow("Chrome_WidgetWin_1", "Google - Google Chrome")
```
Output:
```
1
```
![test](https://user-images.githubusercontent.com/1324225/46343995-5329e680-c648-11e8-89a5-01f7a27f300f.png)

**Comment by radarhere** [comment] 2018-10-25 10:13
@MahmoudThePeltist any thoughts on the fact that @hugovk was able to run your script without errors? Or are you able to upload the image output as per my last comment?

**Comment by hugovk** [comment] 2018-10-25 10:30
One difference is I used Windows 7, not 10.

**Comment by radarhere** [comment] 2019-09-30 11:38
Be aware that Pillow is committed to https://python3statement.org/, and so will be dropping support for Python 2 at the beginning of 2020.

**Comment by hugovk** [comment] 2019-11-20 14:09
Closing due to lack of response, but we can reopen it if it's reproducible with Python 3.

**Closed by hugovk** 2019-11-20 14:09 UTC
Labels: Windows

**Comment by radarhere** [comment] 2020-11-08 01:52
#5034 is possibly related

**Comment by radarhere** [comment] 2020-11-08 20:01
#5034 concluded that their problem was due to missing zlib. So that may also be the case here.
