### ISSUE TITLE
Problem with Keras/Pillow and Tiffs with padding

### ISSUE THREAD

**Issue by Jodahr** [python-pillow/Pillow#3174] opened 2018-06-11 10:05 UTC
### Issue

I use load_image from Keras/PIl/Pillow to open a certain [Tiff File](https://www.dropbox.com/s/0lw6i0yc9xmctrn/SOE4630.tif?dl=0).

### Expected Result

Opening the file without an exception

### Actual Result
I got an exception:
I get the following error:

------ERROR--------

ValueErrorTraceback (most recent call last)
in ()
----> 1 load_img('/opt/hdp/share/data/wertermittlung/newData/Ausbau/train/ausbau/GT12113.tif')

/opt/hdp/anaconda2/lib/python2.7/site-packages/keras/preprocessing/image.py in load_img(path, grayscale, target_size, interpolation)
351 else:
352 if img.mode != 'RGB':
--> 353 img = img.convert('RGB')
354 if target_size is not None:
355 width_height_tuple = (target_size[1], target_size[0])

/opt/hdp/anaconda2/lib/python2.7/site-packages/PIL/Image.pyc in convert(self, mode, matrix, dither, palette, colors)
855 return self.copy()
856
--> 857 self.load()
858
859 if matrix:

/opt/hdp/anaconda2/lib/python2.7/site-packages/PIL/TiffImagePlugin.pyc in load(self)
1009 if self.use_load_libtiff:
1010 return self._load_libtiff()
-> 1011 return super(TiffImageFile, self).load()
1012
1013 def load_end(self):

/opt/hdp/anaconda2/lib/python2.7/site-packages/PIL/ImageFile.pyc in load(self)
202 args, self.decoderconfig)
203 seek(offset)
--> 204 decoder.setimage(self.im, extents)
205 if decoder.pulls_fd:
206 decoder.setfd(self.fp)

ValueError: tile cannot extend outside image
----- ERROR -----

### Tried with both: python 2.7 and 3.6

When I try to load it with the command:
`from keras.preprocessing.image import load_img`

`load_img(path_to_tiff)`

I get the error message above. I already opened an issue in Keras but I guess the problem is actually PIL.
Maybe anyone can help me?

Here is a link to the Keras issue:

[Keras Issue](https://github.com/keras-team/keras/issues/10268)

Cheers,

Marcel

**Comment by cgohlke** [comment] 2018-06-12 19:43
Duplicate of #3044

**Closed** 2018-06-12 20:37 UTC
Labels: Duplicate
