### ISSUE TITLE
How to edit TIFF image in place without changing meta information

### ISSUE THREAD

**Issue by YubinXie** [python-pillow/Pillow#3692] opened 2019-03-06 03:28 UTC
Hi, I have multiple pages TIFF image and I need to apply to pre-process on each page. How can I do it with PIL while keeping all the meta information;

Current reading method like ` ImageSequence.Iterator(img)` only takes out the page, but do not modify the original TIFF in place.

Would appreciate it if anyone has any suggestion on this question.

**Comment by radarhere** [comment] 2019-03-12 02:04
When you say 'all the meta information', is there a specific piece of meta data that you are interested in keeping, or do you really want all the meta data?

**Comment by YubinXie** [comment] 2019-03-12 02:12
In other word, I hope to keep everything the same in that image but edit one image array in the multiple page TIFF. 

I need to share my edited image to a server where they extract meta information to classify the image (the image is from that server too); I am not entirely sure what kind of meta info they need. So I hope to keep everything the same.

**Comment by radarhere** [comment] 2019-03-12 02:42
I would try this and see how it goes.

```python
from PIL import Image
path = 'Tests/images/multipage.tiff'

im = Image.open(path)
im.save(path, save_all=True, tiffinfo=im.tag)
```

**Comment by radarhere** [comment] 2019-03-12 03:02
I would try this and see how it goes.

```python
from PIL import Image, ImageSequence
path = 'Tests/images/g4-multi.tiff'

im = Image.open(path)
frames = []
for i, frame in enumerate(ImageSequence.Iterator(im)):
	frame = frame.copy()
	
	# Perform an operation, for example, rotate the second frame
	if i == 1:
		frame = frame.rotate(5)
	
	frames.append(frame)
frames[0].save(path, tiffinfo=im.tag, save_all=True, append_images=frames[1:])
```

**Comment by radarhere** [comment] 2019-03-20 07:25
@YubinXie was that helpful, or not quite what you are after?

**Comment by YubinXie** [comment] 2019-03-21 19:53
Thanks for reminding and sorry for the late reply!

For one of my data set, I use the same codes you provided and it returns error:, which seems to be related to tag. It works fine if I delete the tag option.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-49-d4d20cc58335> in <module>
     16 
     17         frames.append(frame)
---> 18 frames[0].save(path.replace('tif','new.tif'), tiffinfo=im.tag, save_all=True, append_images=frames[1:])

~/miniconda3/lib/python3.6/site-packages/PIL/Image.py in save(self, fp, format, **params)
   1992 
   1993         try:
-> 1994             save_handler(self, fp, filename)
   1995         finally:
   1996             # do what we can to clean up

~/miniconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py in _save_all(im, fp, filename)
   1840                     ims.seek(idx)
   1841                     ims.load()
-> 1842                     _save(ims, tf, filename)
   1843                     tf.newFrame()
   1844     finally:

~/miniconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py in _save(im, fp, filename)
   1551 
   1552         a = (rawmode, compression, _fp, filename, atts)
-> 1553         e = Image._getencoder(im.mode, 'libtiff', a, im.encoderconfig)
   1554         e.setimage(im.im, (0, 0)+im.size)
   1555         while True:

~/miniconda3/lib/python3.6/site-packages/PIL/Image.py in _getencoder(mode, encoder_name, args, extra)
    475         # get encoder
    476         encoder = getattr(core, encoder_name + "_encoder")
--> 477         return encoder(mode, *args + extra)
    478     except AttributeError:
    479         raise IOError("encoder %s not available" % encoder_name)

RuntimeError: Error setting from dictionary
```

**Comment by YubinXie** [comment] 2019-03-21 19:54
For the other data set, where I construct the multiple tiff from n-d array, it gives different error"

When I save it as '**tif**':
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-51-e1073355e36e> in <module>
     10 
     11         frames.append(frame)
---> 12 frames[0].save(path.replace('tif','new.tif'), tiffinfo=im.tag, save_all=True, append_images=frames[1:])

~/miniconda3/lib/python3.6/site-packages/PIL/Image.py in save(self, fp, format, **params)
   1992 
   1993         try:
-> 1994             save_handler(self, fp, filename)
   1995         finally:
   1996             # do what we can to clean up

~/miniconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py in _save_all(im, fp, filename)
   1840                     ims.seek(idx)
   1841                     ims.load()
-> 1842                     _save(ims, tf, filename)
   1843                     tf.newFrame()
   1844     finally:

~/miniconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py in _save(im, fp, filename)
   1561                 break
   1562         if s < 0:
-> 1563             raise IOError("encoder error %d when writing image file" % s)
   1564 
   1565     else:

OSError: encoder error -9 when writing image file
```


when it is **tiff**:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-52-781c23254b8a> in <module>
     10 
     11         frames.append(frame)
---> 12 frames[0].save(path.replace('tif','new.tiff'), tiffinfo=im.tag, save_all=True, append_images=frames[1:])

~/miniconda3/lib/python3.6/site-packages/PIL/Image.py in save(self, fp, format, **params)
   1970         if not format:
   1971             if ext not in EXTENSION:
-> 1972                 init()
   1973             try:
   1974                 format = EXTENSION[ext]

~/miniconda3/lib/python3.6/site-packages/PIL/Image.py in init()
    426         try:
    427             logger.debug("Importing %s", plugin)
--> 428             __import__("PIL.%s" % plugin, globals(), locals(), [])
    429         except ImportError as e:
    430             logger.debug("Image: failed to import %s: %s", plugin, e)

~/miniconda3/lib/python3.6/site-packages/PIL/WebPImagePlugin.py in <module>
    346 if SUPPORTED:
    347     Image.register_save(WebPImageFile.format, _save)
--> 348     if _webp.HAVE_WEBPANIM:
    349         Image.register_save_all(WebPImageFile.format, _save_all)
    350     Image.register_extension(WebPImageFile.format, ".webp")

AttributeError: module 'PIL._webp' has no attribute 'HAVE_WEBPANIM'

**Comment by radarhere** [comment] 2019-03-23 21:03
Are you able to provide the images that are generating these errors? What version of Pillow and what operating system are you using?

**Comment by YubinXie** [comment] 2019-03-25 17:23
PIL version 5.4.1, Mac OS 10.13.5

I zipped the tiff image. Thanks!
[sample_image.tiff.zip](https://github.com/python-pillow/Pillow/files/3004653/sample_image.tiff.zip)

**Comment by radarhere** [comment] 2019-03-25 20:48
Thanks for that, but the tiff inside the zip is a file with zero bytes.

**Comment by YubinXie** [comment] 2019-03-25 21:28
Sorry, I just update the linked file above. This time it should work!

**Comment by radarhere** [comment] 2019-08-21 12:01
Investigating, the problem is that the XPosition tag is negative. https://sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html says that the value is unsigned, and even if I change the tag type in Pillow to a signed rational, the error is still present. So my guess is that the file is not well formed.

You could work around this by removing the problem tag -

```python
from PIL import Image, ImageSequence
path = 'sample.tiff'

im = Image.open(path)
frames = []
for i, frame in enumerate(ImageSequence.Iterator(im)):
	frame = frame.copy()
	
	# Perform an operation, for example, rotate the second frame
	if i == 1:
		frame = frame.rotate(5)
	
	frames.append(frame)
del im.tag[286]
frames[0].save(path, tiffinfo=im.tag, save_all=True, append_images=frames[1:])
```

**Comment by radarhere** [comment] 2019-09-18 10:21
Closing. Let us know if you have any further thoughts or questions.

**Closed by radarhere** 2019-09-18 10:21 UTC
Labels: TIFF

**Comment by rashmitadudhat** [comment] 2020-05-20 15:03
> Investigating, the problem is that the XPosition tag is negative. https://sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html says that the value is unsigned, and even if I change the tag type in Pillow to a signed rational, the error is still present. So my guess is that the file is not well formed.
> 
> You could work around this by removing the problem tag -
> 
> ```python
> from PIL import Image, ImageSequence
> path = 'sample.tiff'
> 
> im = Image.open(path)
> frames = []
> for i, frame in enumerate(ImageSequence.Iterator(im)):
> 	frame = frame.copy()
> 	
> 	# Perform an operation, for example, rotate the second frame
> 	if i == 1:
> 		frame = frame.rotate(5)
> 	
> 	frames.append(frame)
> del im.tag[286]
> frames[0].save(path, tiffinfo=im.tag, save_all=True, append_images=frames[1:])
> ```

you can try with I == 0 in for loop
