### ISSUE TITLE
Failed to add border to images using ImageOps.expand

### ISSUE THREAD

**Issue by matthewmok** [python-pillow/Pillow#1948] opened 2016-06-13 23:25 UTC
Hi,

I was trying to add border to images from the original kodak dataset and the same image but compressed with pngnq. For the original image, the code successfully added a border to it, but it failed to add the border to the image that is compressed by pngnq. Here is the code that I use:
```python
def pad_image(image):
    new_image = image.split('.png')[0] + '_withbordered.png'
    img = Image.open(image)
    img_with_border = ImageOps.expand(img, border = 4, fill='black')
    img_with_border.save(new_image)
    return new_image
```
When I input the image compressed by pngnq into the function, the following error pops up:
```python
  File "pyqt_learning.py", line 69, in pad_image
    img_with_border = ImageOps.expand(img, border = 4, fill='black')
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/PIL/ImageOps.py", line 239, in expand
    out = Image.new(image.mode, (width, height), _color(fill, image.mode))
  File "/Users/xxx/anaconda/lib/python2.7/site-packages/PIL/Image.py", line 2036, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: function takes exactly 1 argument (3 given)
```
I am using Python 2.7.11 :: Anaconda 2.4.1 (x86_64).

The images for reproducing the error:
successful image:
![image](https://cloud.githubusercontent.com/assets/10650116/16026421/5eb3ac36-3183-11e6-938c-2ca11c7805d2.png)
failed image:
![image](https://cloud.githubusercontent.com/assets/10650116/16026425/67f9118c-3183-11e6-9801-3389cb364a14.png)

Thanks!

**Comment by hugovk** [comment] 2016-06-14 07:29
It's working for me (Windows 7, Python 2.7.11, Pillow 3.2.0).

```python
from PIL import Image, ImageOps

def pad_image(image):
    new_image = image.split('.png')[0] + '_withbordered.png'
    img = Image.open(image)
    img_with_border = ImageOps.expand(img, border = 4, fill='black')
    img_with_border.save(new_image)
    return new_image

pad_image("1.png")
pad_image("2.png")
```

Produces these images:

1_withbordered.png
![1_withbordered](https://cloud.githubusercontent.com/assets/1324225/16034467/b199085a-321a-11e6-85c5-41a89d5fb181.png)

2_withbordered.png
![2_withbordered](https://cloud.githubusercontent.com/assets/1324225/16034472/b780c03c-321a-11e6-8481-05f4cc131c8c.png)

Which Pillow version are you using? (e.g. `pip freeze | grep Pillow`)

**Comment by wiredfool** [comment] 2016-06-14 07:45
I bet there's something going on with the Palette, probably that in the second image it's trying to add a border for a color that doesn't exist in the palette and failing. It's passing a tuple of (0,0,0) in instead of the index of black.

**Comment by matthewmok** [comment] 2016-06-14 18:12
Thanks for the input!
@hugovk I am using Pillow 3.2.0 too... but I am using it on a mac if there would make a difference..
@wiredfool I am suspecting the Palette too but I am not sure how to get around with it.

I am currently using another code that I found on Stackoverflow which works in my case but I would love to know the problem of using expand...

The working code is adapted from 
http://stackoverflow.com/a/11143078/5844182
```
import Image

old_im = Image.open('someimage.jpg')
old_size = old_im.size

new_size = (800, 800)
new_im = Image.new("RGB", new_size)   ## luckily, this is already black!
new_im.paste(old_im, ((new_size[0]-old_size[0])/2,
                      (new_size[1]-old_size[1])/2))

new_im.show()
# new_im.save('someimage.jpg')
```

**Comment by hugovk** [comment] 2016-06-14 20:20
It's also working for me on OS X (Python 2.7.11, Pillow 3.2.0), producing binary-identical output files. I didn't use Anaconda for with Windows or Mac.

**Comment by matthewmok** [comment] 2016-06-14 21:06
@hugovk I tried that again on my Mac with your code and it produced the same error on the second image...

**Comment by hugovk** [comment] 2016-06-15 05:06
I installed pngnq (`brew install pngnq`) and ran it on the first image (`pngnq 1.png`) and can now reproduce it:

```python
$ python test.py
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    pad_image("1-nq8.png")
  File "test.py", line 6, in pad_image
    img_with_border = ImageOps.expand(img, border = 4, fill='black')
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageOps.py", line 239, in expand
    out = Image.new(image.mode, (width, height), _color(fill, image.mode))
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2036, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: function takes exactly 1 argument (3 given)
```

Here's 1-nq8.png, the output of pngnq:

![1-nq8](https://cloud.githubusercontent.com/assets/1324225/16068606/dcdd95ac-32cf-11e6-9d38-5c61e56a3984.png)

**Comment by hugovk** [comment] 2016-06-15 05:30
Adding `print(mode, size, color)` just before the exception in Image.py gives:
```
RGBA (776, 520) (0, 0, 0, 255)
P (776, 520) (0, 0, 0)
```

And the exception is caused by calling `core.fill(mode, size, color)`.

---

The test code works if the "P"-mode image is converted to "RGBA":
```python
    ...
    img = Image.open(image)
    if img.mode == "P":
        img = img.convert("RGBA")
    img_with_border = ImageOps.expand(img, border = 4, fill='black')
    ...
```

**Comment by hugovk** [comment] 2016-06-15 05:56
The test code can be boiled down to:
```python
out = Image.new("RGBA", (776, 520), (0, 0, 0, 255))
out = Image.new("P", (776, 520), (0, 0, 0))
```
Or even:
```python
out = Image.new("RGBA", (776, 520), "black")
out = Image.new("P", (776, 520), "black")
```

This is a duplicate of https://github.com/python-pillow/Pillow/issues/1808. If I downgrade to Pillow 3.1.0 the code runs smoothly but the output image is monochrome, consistent with #108.

**Closed by hugovk** 2016-06-15 05:56 UTC
