### ISSUE TITLE
Array interface for 1-bit images seems wrong.

### ISSUE THREAD

**Issue by LimEJET** [python-pillow/Pillow#1228] opened 2015-05-11 22:41 UTC
Python 3.4.2 Windows 64 bit
NumPy 1.9.2
pillow  2.8.1

Converting a pillow image to 1-bit format and attempting to create a numpy array of it results in a lot of junk data. The numpy guys don't actually support bit-arrays, but the array interface seems to push one out anyway.

I've tested this with a small image and a large image.

Small image (3x3):
![test](https://cloud.githubusercontent.com/assets/4407285/7554999/853ef4c2-f73d-11e4-9747-2e9c79190344.png)

Pillow represents it like this:
```python
>>> i = Image.open("test.png")
>>> for k in i.convert("1").getdata(): print(k)
0
255
0
255
0
255
0
255
0
```
while the resulting numpy array varies in how it looks:
```python
>>> p = np.array(i.convert("1"))
>>> p
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]], dtype=bool)
>>> i = Image.open("test.png")
>>> p = np.array(i.convert("1"))
>>> p
array([[ True,  True,  True],
       [False, False, False],
       [False, False,  True]], dtype=bool)
```

I tried this out on a bigger image (represented below), and I saw some interesting patterns in the output.

The code I tested with:
```python
i = Image.open("a.png")
i.show()
p = numpy.array(i.convert("1")) #becomes array of booleans
j = Image.fromarray(numpy.uint8(p)*255)
j.show()
```
Input image:
![2015-05-10_17-50-18](https://cloud.githubusercontent.com/assets/4407285/7554994/1031077e-f73d-11e4-9923-f07bf9117c4e.png)

Output image:
![2015-05-10_17-48-37](https://cloud.githubusercontent.com/assets/4407285/7554995/121907da-f73d-11e4-8e1f-f574fba57567.png)

Notice the row of miniaturized versions of the input along the top.

**Comment by wiredfool** [comment] 2015-05-12 16:24
Known issue, see #350. 

I've got this workaround in my code:
```
	@classmethod
	def to_nimage(self, img):
		""" PIL -> numpy array for scipy work"""
		nimg = numpy.asarray(img.convert("L"))
		nimg.setflags(True) # writable
		return nimg

	@classmethod
	def to_pimage(self, nimg):
		""" numpy array -> PIL Image """
		return Image.fromarray(numpy.uint8(nimg), mode='L').convert('1')
```

**Comment by aclark4life** [comment] 2015-06-28 19:32
Duplicate of #350

**Closed by aclark4life** 2015-06-28 19:32 UTC
