### ISSUE TITLE
UserWarning: Possibly corrupt EXIF data

### ISSUE THREAD

**Issue by isalirezag** [python-pillow/Pillow#3352] opened 2018-09-14 01:48 UTC
This warning is kinda annoying and we dont know why it happens.

```
/home/alireza/anaconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:747: UserWarning: Possibly corrupt EXIF data.  Expecting to read 395876289 bytes but only got 0. Skipping tag 34464
  " Skipping tag %s" % (size, len(data), tag))
I am using 
```

when i downgrade the pillow to version 4.0.0 it disappears 

more people face it and mentioned it here:
[1 
](https://github.com/python-pillow/Pillow/issues/518)
[2
](https://github.com/python-pillow/Pillow/issues/520)
[3](https://github.com/uber/horovod/issues/333)

**Comment by hugovk** [comment] 2018-09-14 03:53
Please give more info:

### What did you do?

### What did you expect to happen?

### What actually happened?

### What versions of Pillow and Python are you using?

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
code goes here
```

**Comment by isalirezag** [comment] 2018-09-14 13:15
trying to finetune imagenet
i expected no warning to happen
the warning that i mentioned above happened
the latested version of pillow i used

I cannot share my code

**Comment by isalirezag** [comment] 2018-09-14 15:40
this is part of the code that im using
https://github.com/pytorch/examples/blob/master/imagenet/main.py

**Comment by radarhere** [comment] 2018-09-16 07:07
Correct me if I'm wrong, but you're running that script over an ImageNet folder, that hasn't been linked to here? So we still don't actually have access to the images that are giving you the warning?

**Comment by isalirezag** [comment] 2018-09-17 15:35
yeah the size is super large so that is why i cannot provide it here

**Comment by radarhere** [comment] 2018-09-17 20:37
I understand if you cannot upload it to Github, but can you link to it?

**Comment by isalirezag** [comment] 2018-09-17 21:06
hmmm I mean I downloaded the imagenet dataset and run the code in https://github.com/pytorch/examples/tree/master/imagenet

**Comment by hugovk** [comment] 2018-09-26 10:50
It's not feasible to expect us to download a 300 GB dataset of images and install and run a machine learning library over the whole thing to find a problem image, and then further identify how PyTorch is calling Pillow.

Please at least identify the problem image and and narrow down the code needed to run it, ideally calling Pillow directly without any third-party libraries.

In the meantime, closing this as a duplicate of the three issues you linked to.

**Closed by hugovk** 2018-09-26 10:50 UTC

**Comment by HatScripts** [comment] 2018-09-30 16:39
@isalirezag If you simply wish for these warnings to stop spamming your console, you can just filter them, e.g.
```py
warnings.filterwarnings("ignore", "(Possibly )?corrupt EXIF data", UserWarning)

with Image.open("problematic_image.jpg") as image:
    # do something with image
```
