### ISSUE TITLE
AttributeError: 'PngStream' object has no attribute 'chunk_tIME'

### ISSUE THREAD

**Issue by SnichOne** [python-pillow/Pillow#3723] opened 2019-03-16 13:35 UTC
Pillow raises an exception while loading .png image: `AttributeError: 'PngStream' object has no attribute 'chunk_tIME'`.

* OS: Ubuntu 18.04.2 LTS
* Python: 3.6.7
* Pillow: 5.4.1

```python
from PIL import Image

im = Image.open('image.png')
im.load()
```

```
Traceback (most recent call last):
  File "code.py", line 4, in <module>
    im.load()
  File ".../python3.6/site-packages/PIL/ImageFile.py", line 252, in load
    self.load_end()
  File ".../python3.6/site-packages/PIL/PngImagePlugin.py", line 680, in load_end
    self.png.call(cid, pos, length)
  File ".../python3.6/site-packages/PIL/PngImagePlugin.py", line 140, in call
    return getattr(self, "chunk_" + cid.decode('ascii'))(pos, length)
AttributeError: 'PngStream' object has no attribute 'chunk_tIME'
```
Example file: [image.png](https://raw.githubusercontent.com/SnichOne/Pillow/cb677680270e7e6ab01ad0bd812556fd6e0ef760/image.png).

**Comment by radarhere** [comment] 2019-03-16 20:47
This is a duplicate of #3557. The fix will be part of Pillow 6.0, due out on April 1.

**Closed by radarhere** 2019-03-16 20:47 UTC
Labels: Duplicate
