### ISSUE TITLE
font.getsize fail with empty strings

### ISSUE THREAD

**Issue by iurisilvio** [python-pillow/Pillow#2614] opened 2017-07-06 18:19 UTC
### What did you do?

```python
from PIL import ImageFont

font = ImageFont.truetype(
    '/usr/share/fonts/truetype/msttcorefonts/arial.ttf', 30)
font.getsize('', direction=None, features=None)
```

### What did you expect to happen?

Not break. :)

### What actually happened?

```python
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    print font.getsize('', None, None)
  File "local/lib/python2.7/site-packages/PIL/ImageFont.py", line 156, in getsize
    size, offset = self.font.getsize(text, direction, features)
SystemError: error return without exception set
```

### What versions of Pillow and Python are you using?

It works with 3.4.2 and breaks with 4.2.0. I didn't tried other versions yet.

**Comment by ksze** [comment] 2017-07-07 15:12
I bumped into this issue as well. I was trying to draw some multiline Chinese text on a blank image. The text string ends with a "\n", so the last line after splitting was empty.

Although the error message is slightly different, I'm pretty sure the problem is identical at its core:
```
$ python chinese_ticket.py
Traceback (most recent call last):
  File "chinese_ticket.py", line 23, in <module>
    draw.text((10, 10), text_to_render, font=ttf, fill=0, spacing=5)
  File "/home/regsys/berryconda3/envs/registration/lib/python3.6/site-packages/PIL/ImageDraw.py", line 209, in text
    *args, **kwargs)
  File "/home/regsys/berryconda3/envs/registration/lib/python3.6/site-packages/PIL/ImageDraw.py", line 233, in multiline_text
    line_width, line_height = self.textsize(line, font)
  File "/home/regsys/berryconda3/envs/registration/lib/python3.6/site-packages/PIL/ImageDraw.py", line 260, in textsize
    return font.getsize(text, direction, features)
  File "/home/regsys/berryconda3/envs/registration/lib/python3.6/site-packages/PIL/ImageFont.py", line 156, in getsize
    size, offset = self.font.getsize(text, direction, features)
SystemError: <built-in method getsize of Font object at 0x7685f278> returned NULL without setting an error
```

As soon as I removed the trailing "\n", the error went away.

Environment:
Raspberry Pi 3
Raspbian (Jessie)
Python 3.6.1. from Berryconda
Pillow 4.2.1

**Comment by ryanmrubin** [comment] 2017-07-07 15:24
I have confirmed the same. It works in Pillow 4.1.1 and breaks in 4.2.0. This is also a problem as font.getsize is used in `ImageDraw.Draw.multiline_text`, if one of the lines is an emptystring (e.g. between other blocks of text).

**Comment by iurisilvio** [comment] 2017-07-07 16:33
I confirm the issue is with `Pillow>=4.2.0`. Tested 4.1.1 too and it worked fine.

**Comment by wiredfool** [comment] 2017-07-07 16:42
Do you have the RAQM feature installed?

```
from PiL import features
print (features.check('raqm'))
```

**Comment by ryanmrubin** [comment] 2017-07-07 16:44
In my case, no.

**Comment by ksze** [comment] 2017-07-08 06:46
I don't have RAQM either.

**Comment by iurisilvio** [comment] 2017-07-10 13:07
It is not installed here.

**Comment by ryanmrubin** [comment] 2017-10-02 14:53
This has been closed for a couple months, but it has not been released yet. Any chance of a release in the near future?

**Comment by wiredfool** [comment] 2017-10-02 14:55
It's in the release that was tagged 30 minutes ago.  Binaries should be up soonish.

**Comment by ryanmrubin** [comment] 2017-10-02 14:56
Hey, amazing. Thanks!!

**Comment by NotSoSuper** [comment] 2017-10-03 20:34
This still seems to be broken in the latest release? Just tested with a build from GitHub too.

**Comment by shawnblakesley** [comment] 2017-10-03 23:20
I'm seeing the same issue that @NotSoSuper described in #2783, and I'd also like to point out that it fails for strings that end in newlines like `"test\n"`

**Comment by hugovk** [comment] 2017-10-04 05:54
I can't reproduce it with latest Pillow 4.3.0 in Python 2.7.13 and Python 3.6.0 on macOS Sierra:

```
[hugo:/tmp] % pip install pillow
Collecting pillow
  Downloading Pillow-4.3.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.5MB)
    100% |████████████████████████████████| 3.6MB 293kB/s
Requirement already satisfied: olefile in /usr/local/lib/python2.7/site-packages (from pillow)
Installing collected packages: pillow
Successfully installed pillow-4.3.0
```
```
[hugo:/tmp] % python
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import ImageFont
>>> font = ImageFont.truetype("arial.ttf", 30)
>>> font.getsize('', direction=None, features=None)
(0, 0)
>>> font.getsize('test\n', direction=None, features=None)
(76, 33)
>>> font.getsize('\n', direction=None, features=None)
(18, 33)
>>> font.getsize('')
(0, 0)
>>> font.getsize('test\n')
(76, 33)
>>> font.getsize('\n')
(18, 33)
>>>
```
```
[hugo:/tmp] 1 % pip3 install pillow
Collecting pillow
  Downloading Pillow-4.3.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.5MB)
    100% |████████████████████████████████| 3.6MB 290kB/s
Requirement already satisfied: olefile in /usr/local/lib/python3.6/site-packages (from pillow)
Installing collected packages: pillow
Successfully installed pillow-4.3.0
```
```
[hugo:/tmp] 4s % python3
Python 3.6.0 (default, Mar  4 2017, 12:32:34)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import ImageFont
>>> font = ImageFont.truetype("arial.ttf", 30)
>>> font.getsize('', direction=None, features=None)
(0, 0)
>>> font.getsize('test\n', direction=None, features=None)
(76, 33)
>>> font.getsize('\n', direction=None, features=None)
(18, 33)
>>> font.getsize('')
(0, 0)
>>> font.getsize('test\n')
(76, 33)
>>> font.getsize('\n')
(18, 33)
>>>
```

What's different between my setup and yours?


I _did_ see this with the old Pillow 4.2.1 and Python 3.6.0:

```
>>> font.getsize('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/PIL/ImageFont.py", line 156, in getsize
    size, offset = self.font.getsize(text, direction, features)
SystemError: <built-in method getsize of Font object at 0x101ec7738> returned NULL without setting an error
```

**Comment by hugovk** [comment] 2017-10-04 06:09
I _can_ reproduce it with the code in #2783, which is from `ImageDraw.Draw.textsize` not `ImageFont.getsize`. Let's continue that issue over there. I'll close this again, we can re-open this one if the problem can be reproduced with `ImageFont.getsize`.

**Closed by hugovk** 2017-10-04 06:09 UTC
Labels: Bug, Regression
