### ISSUE TITLE
rotate not adjusting size attribute appropriately when BICUBIC and BILINEAR are used for resample filter

### ISSUE THREAD

**Issue by spencera1** [python-pillow/Pillow#1369] opened 2015-08-03 21:38 UTC
Using Pillow 2.9.0 and Python 3.4.3.

im = Image.new('RGB', (100,200))
im
&lt;PIL.Image.Image image mode=RGB size=100x200 at 0x7F3745C1DDA0&gt;

im.rotate(90)
&lt;PIL.Image.Image image mode=RGB size=200x100 at 0x7F3745C1D710&gt;

That's good. Explicity setting NEAREST is fine too:
im.rotate(90, resample=Image.NEAREST)
&lt;PIL.Image.Image image mode=RGB size=200x100 at 0x7F3745C1F8D0&gt;

But, using BICUBIC or BILINEAR results in incorrect sizes showing:
im.rotate(90, resample=Image.BICUBIC)
&lt;PIL.Image.Image image mode=RGB size=100x200 at 0x7F3745C1D9B0&gt;
im.rotate(90, resample=Image.BILINEAR)
&lt;PIL.Image.Image image mode=RGB size=100x200 at 0x7F3745C1FF60&gt;

Is the behavior with NEAREST actually supposed to be like that of BICUBIC/BILINEAR in this regard without expand? It seems like the rotate docs suggest that on http://pillow.readthedocs.org/reference/Image.html, but since NEAREST is the default filter, it seems really misleading.

**Comment by radarhere** [comment] 2015-08-05 14:26
Thanks for finding this! The problem is actually - if certain filters are used, for 90 or 270 degree rotation operations, a faster algorithm is used. However, these faster algorithms ignore the expand option.

So I've created a PR that only uses those fast operations if the expand flag is in use, or if the image is square.

**Comment by spencera1** [comment] 2015-08-05 20:03
Thanks! I'm glad I could help in some small way.

So, if I'm understanding correctly, in the future, these changes will only be relevant when the NEAREST filter is being used? Also, will the pillow.readthedocs.org documentation be updated? Or, is that a completely separate project? Sorry, I'm not familiar with how all these things work/are coordinated.

**Comment by radarhere** [comment] 2015-08-06 10:02
pillow.readthedocs.org works live from the master branch of Pillow. The way that you have interpreted the docs is correct, and my PR is about fixing the bug that you're found.

So, the code has been -

    if not nearest filter and not a special image type
    	…
    else if angle is 90 or 270)
    	use fast rotate function that forgets that expand might not be on
    else
    	…

My PR changes it to -

    if not nearest filter and not a special image type
    	…
    else if (angle is 90 or 270) and (expand or image is square)
    	use fast rotate function that forgets that expand might not be on
    else
    	…

I'm not quite sure what a special image pixel type is, but I know it's not uint8, int32 or float32.

So, while the code is clearer than this convoluted sentence, the Pillow operations that will notice a change are - non-square images being rotated 90 or 270 with the expand flag off that aren't both (using a filter other than nearest && of the type uint8, int32 or float32).

**Comment by radarhere** [comment] 2015-08-06 10:04
If the PR is just merged as is into the master branch, then the change will be present in Pillow 3.0, due to be released on October 1. Or if you like, you can download a development branch with the change and install it locally.

**Comment by spencera1** [comment] 2015-08-07 02:59
Thank you for the clarifications.

I was digging around in libImaging and _imaging.c, and it looked like IMAGING_TYPE_SPECIAL is supposed to be a sort of catch-all image type for the experimental image modes (libImaging/Storage.c) to indicate that further checking of image properties, like mode or pixelsize, is needed to handle the image properly. I suppose they check for it in_rotate because they don't have cases/support for the special type in the non-NEAREST cases of getfilter in libImaging/Geometry.c.

**Closed** 2015-08-09 08:26 UTC
Labels: Bug
