### ISSUE TITLE
OSError when opening a font file whose name is not in English

### ISSUE THREAD

**Issue by jdhao** [python-pillow/Pillow#3480] opened 2018-11-28 03:07 UTC
# Issue description
When I tried to open a font using `ImageFont.truetype()` method (the font file name is in Chinese):

```python
from PIL import ImageFont
font = ImageFont.truetype("方正黄草简体.ttf")
```

I encountered an error: 
```
> D:\Anaconda\lib\site-packages\PIL\ImageFont.py in truetype(font, size, index, encoding, layout_engine)
>     278
>     279     try:
> --> 280         return FreeTypeFont(font, size, index, encoding, layout_engine)
>     281     except IOError:
>     282         ttf_filename = os.path.basename(font)
> 
> D:\Anaconda\lib\site-packages\PIL\ImageFont.py in __init__(self, font, size, index, encoding, layout_engine)
>     143         if isPath(font):
>     144             self.font = core.getfont(font, size, index, encoding,
> --> 145                                      layout_engine=layout_engine)
>     146         else:
>     147             self.font_bytes = font.read()
> 
> OSError: cannot open resource
```
When I change the font name to English name, for example, `fzhcjt.tff`, I can open the same font file without any error. 

### What are your OS, Python and Pillow versions?

* OS: Windows 10 Pro 1803
* Python: 3.6.5
* Pillow: 5.3.0

I have also tested on my CentOS machine and this issue does not exist.

**Comment by hugovk** [comment] 2018-11-28 08:32
I get something different (Pillow 5.3.0,  macOS High Sierra) for both Chinese and English characters:

```
Python 3.7.1 (default, Nov  6 2018, 18:45:35)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import ImageFont
>>> font = ImageFont("方正黄草简体.ttf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
>>> font = ImageFont("arial.ttf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```

Instead, use `ImageFont.truetype(font_path, font_size)`:
```python
>>> ImageFont.truetype("arial.ttf", 15)
<PIL.ImageFont.FreeTypeFont object at 0x1096e5f60>
>>> ImageFont.truetype("方正黄草简体.ttf", 15)
<PIL.ImageFont.FreeTypeFont object at 0x1096ea080>
>>>
>>> font = ImageFont.truetype("方正黄草简体.ttf", 15)
>>>
>>> from PIL import Image, ImageDraw
>>> im = Image.new("RGB", (200, 100), "white")
>>> draw = ImageDraw.Draw(im)
>>> draw.text((10, 10), "abc", font=font, fill="black")
>>> im.show()
```
Produces:

![image](https://user-images.githubusercontent.com/1324225/49138725-9b881c80-f2f8-11e8-8aad-d4f74bab3372.png)

See https://pillow.readthedocs.io/en/5.3.x/reference/ImageFont.html

Do you get the same OSError with `ImageFont.truetype(font_path, font_size)`?

**Comment by jdhao** [comment] 2018-11-28 09:09
@hugovk , sorry, I have paste the wrong code. The code to produce has been corrected.

**Comment by radarhere** [comment] 2018-11-28 11:54
This looks like a duplicate of #3145

**Closed** 2018-11-28 12:18 UTC
Labels: Duplicate
