### ISSUE TITLE
Pillow 3.0 raises errors on open when using tempfile.TemporaryFile

### ISSUE THREAD

**Issue by kmike** [python-pillow/Pillow#1460] opened 2015-10-02 19:31 UTC
Here is a Travis job which starts to fail because of Pillow update: https://travis-ci.org/scrapy/scrapy/jobs/83354354. Sorry, I haven't checked what happens and why, so this bug report is very vague. Maybe someone with more detailed knowledge can spot an issue immediately. If not, I'll take a deeper look later.

This line fails: https://github.com/scrapy/scrapy/blob/fe15f93e533be36e81e0385691fe5571c88b0b31/tests/test_pipeline_images.py#L81. This is `_create_image` function: https://github.com/scrapy/scrapy/blob/fe15f93e533be36e81e0385691fe5571c88b0b31/tests/test_pipeline_images.py#L208.

There are also some errors printed to stdout in this job; they can be a different Pillow issue.

**Comment by wiredfool** [comment] 2015-10-02 19:38
How are you installing pillow?

**Comment by kmike** [comment] 2015-10-02 19:41
It is in tox.ini deps; we're running tox on Travis. I believe Travis uses Ubuntu 12.04 and tox just runs 'pip install'.

**Comment by hugovk** [comment] 2015-10-02 19:44
Yes, Travis is Ubuntu 12.04. If you pin Pillow to 2.9.0, what do you get?

**Comment by kmike** [comment] 2015-10-02 19:50
Just tried it on OS X locally: Scrapy testing suite fails with Pillow 3.0, but passes if I pin Pillow to 2.9.0. So with Pillow 2.9.0 there are no exceptions. I haven't seen these errors in stdout before.

The command to get a test failure is `tox -r -e py27 tests/test_pipeline_images.py` executed from https://github.com/scrapy/scrapy checkout.

**Comment by wiredfool** [comment] 2015-10-02 19:51
I wonder if Travis has libjpeg-dev and libz-dev packages installed.

**Comment by wiredfool** [comment] 2015-10-02 19:53
So, on OS X it should be installing a binary wheel, so that shouldn't have the jpeg or zlib build issue.

**Comment by kmike** [comment] 2015-10-02 19:54
These packages should be installed: Travis tests used to work before the upgrade, they started to fail when Pilow 3.0 was released. Or are there new dependencies in Pillow 3.0?

**Comment by kmike** [comment] 2015-10-02 19:55
right, and it also fails in OS X, so this is not OS-specific.

**Comment by hugovk** [comment] 2015-10-02 19:56
Pillow 3.0.0 now requires libjpeg and zlib, before they were optional: https://github.com/python-pillow/Pillow/issues/1412

**Comment by wiredfool** [comment] 2015-10-02 19:57
They were formerly optional, but commonly used and if not used, indicative of installing pillow without a working tool chain.  Now they are required unless disabled.

**Comment by kmike** [comment] 2015-10-02 19:57
But it should fail during installation, not at runtime, right? Travis shows that Pillow==3.0.0 is installed.

**Comment by wiredfool** [comment] 2015-10-02 20:01
Yes..  It should fail on install. So, then not that problem.  Also ruled out by the OS X failure.

What image is failing in this test?   It's looking like it's just not getting recognized, and it's falling through to the we can't identify this image error.

Could be bad exif info borking a jpeg, could be an mpo change. That's what I remember touching in JpegImagePlugin this time through.

**Comment by kmike** [comment] 2015-10-02 20:09
I think stdout log errors are not related to the test failure, they are different.

Ok, a short example to reproduce the issue. This was previously supported, but not now:

Image is just that:
```python
from PIL import Image
from tempfile import TemporaryFile

buf = TemporaryFile()
im = Image.new('RGB', (100, 100), (0, 127, 255))
im.save(buf, 'JPEG')

buf.seek(0)
im = Image.open(buf)
```

I'm not sure why is the code written this way though.

**Comment by kmike** [comment] 2015-10-02 20:12
Previously we used BytesIO instead of TemporaryFile, but as I recall BytesIO buffers were not supported by Pillow.

**Comment by wiredfool** [comment] 2015-10-02 20:12
So, I just ran this:
```
from helper import PillowTestCase
from PIL import Image

class test_scrapy(PillowTestCase):
    def _create_image(self, format, *a, **kw):
        buf = open(self.tempfile('temp.jpg'), 'w+b')
        Image.new(*a, **kw).save(buf, format)
        buf.seek(0)
        return Image.open(buf)

    def test_create_image(self):
        SIZE = (100, 100)
        # straigh forward case: RGB and JPEG
        COLOUR = (0, 127, 255)
        im = self._create_image('JPEG', 'RGB', SIZE, COLOUR)

        self.assert_image_equal(Image.new('RGB', (100,100), COLOUR), im)

``` 

and it passes.

**Comment by kmike** [comment] 2015-10-02 20:16
Do you use Python 2 or Python 3? My example with TemporaryFile fails in Python 2.7 but passes in Python 3.3.

**Comment by wiredfool** [comment] 2015-10-02 20:17
BytesIO are fine. They're all over our test cases. 

This was 2.7

**Comment by kmike** [comment] 2015-10-02 20:19
hm, the difference between open(self.tempfile(...), 'w+b') and TemporaryFile is that TemporaryFile uses os.fdopen

**Comment by hugovk** [comment] 2015-10-02 20:23
Here's two builds of scrapy. The only change is Python 2.7 fails with Pillow 3.0.0 but passes with Pillow 2.9.0. (Python 3.3 passes for both.)

Pillow 3.0.0: https://travis-ci.org/hugovk/scrapy/builds/83371654
Pillow 2.9.0: https://travis-ci.org/hugovk/scrapy/builds/83373252

**Comment by wiredfool** [comment] 2015-10-02 20:24
```
from helper import PillowTestCase
from PIL import Image
import tempfile

class test_scrapy(PillowTestCase):
    def _create_image(self, format, *a, **kw):
        buf = open(self.tempfile('temp.jpg'), 'w+b')
        Image.new(*a, **kw).save(buf, format)
        buf.seek(0)
        return Image.open(buf)

    def _create_image_tempfile(self, format, *a, **kw):
        buf = tempfile.TemporaryFile()
        Image.new(*a, **kw).save(buf, format)
        buf.seek(0)
        return Image.open(buf)    

    def test_create_image(self):
        SIZE = (100, 100)
        # straigh forward case: RGB and JPEG
        COLOUR = (0, 127, 255)
        im = self._create_image('JPEG', 'RGB', SIZE, COLOUR)
        self.assert_image_equal(Image.new('RGB', (100,100), COLOUR), im)

        im = self._create_image_tempfile('JPEG', 'RGB', SIZE, COLOUR)
        self.assert_image_equal(Image.new('RGB', (100,100), COLOUR), im)

```

I'm failing at the call to _create_image_tempfile.   It's not scrapy, It appears to be file handling somewhere. I'm wondering if we're not getting a flush happening somewhere.

**Comment by kmike** [comment] 2015-10-02 20:25
> BytesIO are fine. They're all over our test cases. 

Yeah, right, but they were not fine in PIL or Pillow < 2.0, and this is what Ubuntu Precise users get by apt-get. Scrapy tries to support system packages from Ubuntu Precise, so we had to avoid using BytesIO. Test failure: https://travis-ci.org/scrapy/scrapy/jobs/29975641 and a comment: https://github.com/scrapy/scrapy/pull/803#issuecomment-49028433

**Comment by wiredfool** [comment] 2015-10-02 20:43
Right. Old distro versions. 

I'm going to bisect this one while running on battery.

**Comment by kmike** [comment] 2015-10-02 20:45
Thanks!

**Comment by hugovk** [comment] 2015-10-02 20:49
Also [bisecting](https://robots.thoughtbot.com/git-bisect):

```
$ git bisect start
$ git bisect good 80672b6
$ git bisect bad 0177cce
$ cat doit.sh
python setup.py develop build_ext --disable-zlib && python Tests/1460.py
$ git bisect run ./doit.sh
```

I get:
```
457d39832d4f433a59c78598849eef3d073cf7e5 is the first bad commit
commit 457d39832d4f433a59c78598849eef3d073cf7e5
Author: radarhere
Date:   Wed Aug 5 20:54:33 2015 +1000

    Added support for pathlib Path objects to open and save

:040000 040000 77908caa2a5443c957478713e8b97dce3834cb87 ed58750db298c338e3475385c1928f2de1a7bc66 M	PIL
```

**Comment by wiredfool** [comment] 2015-10-02 20:54
Yep, that's the one I got. 

Also, Georgia fell apart in the last 10 minutes against NZ.

**Comment by hugovk** [comment] 2015-10-02 21:03
One thing that's happening is this `if ... elif` used to be an `if ... else`, and neither of the `if` or `elif` match anything so `filename == ""`.

https://github.com/radarhere/Pillow/commit/457d39832d4f433a59c78598849eef3d073cf7e5#diff-3fef5f960d5bd8bdfb9c6fadcf96af22R2283

**Comment by hugovk** [comment] 2015-10-02 21:05
Further, adding this:
```
    elif hasattr(fp, "name") and isPath(fp.name):
        filename = fp.name
```
passes the test. 

This snippet then matches the `if ... elif ... elif` by line 1659.

**Comment by wiredfool** [comment] 2015-10-02 21:13
Looking at the first part of the diff:
```
index 861599b..87d77ef 100644
--- a/PIL/Image.py
+++ b/PIL/Image.py
@@ -1653,13 +1653,15 @@ class Image(object):
            may have been created, and may contain partial data.
         """
 
+        filename = ""
         if isPath(fp):
             filename = fp
-        else:
-            if hasattr(fp, "name") and isPath(fp.name):
-                filename = fp.name
-            else:
-                filename = ""
+        elif sys.version_info >= (3, 4):
+            from pathlib import Path
+            if isinstance(fp, Path):
+                filename = str(fp.resolve())
+        elif hasattr(fp, "name") and isPath(fp.name):
+            filename = fp.name
```

Filename is the original fp, '', or fp.name. The new version adds the possibility of fp.resolve(). 

The next part:
```
 
-        if isPath(fp):
-            fp = builtins.open(fp, "wb")
+        if filename:
+            fp = builtins.open(filename, "wb")
             close = 1
```
Looks suspect to me, because now we're opening the filename, and not the file pointer. I think that the file pointer should always point to something, but it might not be named. 

e.g.:
```
(vpy27)erics-air:Pillow erics$ python 
Python 2.7.10 (default, Jul 13 2015, 12:18:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tempfile import TemporaryFile
>>> f = TemporaryFile()
>>> f
<open file '<fdopen>', mode 'w+b' at 0x109feb9c0>
>>> hasattr(f, 'name')
True
>>> f.name
'<fdopen>'
>>> 
```

So, in this case, we have a valid fp, but the name is not openable. And for the TemporaryFile, we'd never be able to reopen it from anything other than the file pointer, because it's been deleted.

**Comment by wiredfool** [comment] 2015-10-02 21:35
Basically, I'm thinking that when the fp has a name attribute, the filename should only be passed into the save for metadata purposes and that name should never be used to reopen the file pointer.

**Comment by pawl** [comment] 2015-10-03 05:15
Here's an example of the issue in a flask application: https://gist.github.com/pawl/ee7c76bb066b7d1cbe5d

2.9.0 is able to open the file, but 3.0.0 gives this error: ```IOError: cannot identify image file <FileStorage: u'copyleft.tiff' ('image/tiff')>```

**Comment by pawl** [comment] 2015-10-03 05:52
It might be better to start a separate issue and close this one?

The title needs to be something like "Pillow 3.0 issues with opening temporary files". This issue starts too vague and it's starting to get too long.

**Comment by wiredfool** [comment] 2015-10-03 06:46
I've edited the title, context is good so I'd prefer to have it here.

**Comment by pawl** [comment] 2015-10-03 06:55
Here's an even shorter example that reproduces the issue:
```
from tempfile import TemporaryFile
from PIL import Image

with open('copyleft.tiff', 'rb') as fp:
    my_file_contents = fp.read()

with TemporaryFile() as temp:
    temp.write(my_file_contents)
    temp.seek(0)  # go back to the beginning
    image = Image.open(temp)
```

The weirdest part is that it only happens with TIFF file that was working with 2.9.0: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/tests/data/copyleft.tiff?raw=true

**Comment by wiredfool** [comment] 2015-10-03 07:16
Give this branch a shot to see if it fixes things: https://github.com/wiredfool/Pillow/tree/pathlib_temporaryfile

**Comment by pawl** [comment] 2015-10-03 18:50
@wiredfool that fixes @kmike's example in: https://github.com/python-pillow/Pillow/issues/1460#issuecomment-145142825

I think my issue was a separate one with TIFF files, sorry for the confusion.

**Closed** 2015-10-05 08:42 UTC
Labels: Bug
