### ISSUE TITLE
Pillow cannot open specific JPEG2000 files

### ISSUE THREAD

**Issue by MerlijnWajer** [python-pillow/Pillow#5629] opened 2021-07-22 17:28 UTC
### What did you do?

Calling `Image.open` on a specific JPEG2000 file (other JPEG2000 files open just fine)

### What did you expect to happen?

The image would be successfully opened

### What actually happened?

Pillow raised:

```
PIL.UnidentifiedImageError: cannot identify image file '/tmp/CAT10923792_0107.jp2'
```

Other JPEG2000 images open just fine, though. (Other) OpenJPEG users can load the problematic image just fine (e.g. `opj_decompress`, `convert`, or `mupdf`)

### What are your OS, Python and Pillow versions?

* OS: Linux
* Python: 3.7.10
* Pillow: 8.3.1

```python
from PIL import Image
img = Image.open('CAT10923792_0107.jp2')
```

Image can be found here: https://archive.org/~merlijn/pillow-jp2/CAT10923792_0107.jp2

**Comment by radarhere** [comment] 2021-07-22 22:15
Taking a look, this file has a `meth` value of 2, signifying a Restricted ICC profile - making this a duplicate of #3556.

**Closed** 2021-07-23 00:23 UTC
Labels: Duplicate, JPEG
