### ISSUE TITLE
Hide "TIFFSetField: tempfile.tif: Unknown pseudo-tag 65538." messages

### ISSUE THREAD

**Issue by marlemion** [python-pillow/Pillow#3487] opened 2018-12-06 16:26 UTC
I get due to

https://github.com/python-pillow/Pillow/issues/3413

the error above. I tried everything with the logger module, but I do not seem to be able to remove this message. However, it completely destroys unnecessarily my output. Is there a simple fix to get away with this annoying message?

**Comment by hugovk** [comment] 2018-12-06 16:38
### What did you do?

### What did you expect to happen?

### What actually happened?

### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
code goes here
```

**Comment by radarhere** [comment] 2018-12-07 07:52
If your issue is truly the same as #3413, then that was addressed in #3417. So 5.4.0 will fix this, or you could build from master before that. Or are you looking for an immediate solution that doesn't improve building from source?

**Comment by marlemion** [comment] 2018-12-07 12:43
It is truly the same and I would like to know how to get rid of the message. It seems neither to be controlled by stderr nor by the logging module.

**Comment by kkopachev** [comment] 2018-12-07 22:16
It should be output directly to stderr of the process.

```
root@dc1fa6dc47ed:/# python -c "from PIL import Image; Image.open('copyleft.tiff').load()"
TIFFSetField: tempfile.tif: Unknown pseudo-tag 65538.
root@dc1fa6dc47ed:/# python -c "from PIL import Image; Image.open('copyleft.tiff').load()" 2> /dev/null
root@dc1fa6dc47ed:/# 
```

So you might try to redirect it somewhere.

**Comment by marlemion** [comment] 2018-12-10 10:10
Why does this not work?

```
import os
import sys
f = open(os.devnull, 'w')
sys.stdout = f
```

**Comment by radarhere** [comment] 2018-12-15 04:30
@kkopachev suggested redirecting stderr, while your code addresses stdout. However, it still does not work with stderr, and I would guess suggest that's because the message is not coming from Python, but from libtiff.

**Closed as completed** 2019-01-01 20:21 UTC
Labels: TIFF
