### ISSUE TITLE
Another PNG bug with 5.4+

### ISSUE THREAD

**Issue by Traktormaster** [python-pillow/Pillow#3607] opened 2019-01-25 13:41 UTC
I have a PNG image file that I wanted to open. It's fine with Pillow 5.3 but not with 5.4 or 5.4.1.
I thought #3535 was going to fix this as well but it did not. Here's the exception:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/.local/share/virtualenvs/proj/lib/python3.7/site-packages/PIL/ImageFile.py", line 252, in load
    self.load_end()
  File "/home/user/.local/share/virtualenvs/proj/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 680, in load_end
    self.png.call(cid, pos, length)
  File "/home/user/.local/share/virtualenvs/proj/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 140, in call
    return getattr(self, "chunk_" + cid.decode('ascii'))(pos, length)
AttributeError: 'PngStream' object has no attribute 'chunk_exIf'
```

* OS: Arch Linux
* Python: 3.7.2
* Pillow: 5.4.1

```
from PIL import Image
im = Image.open('breaking_pillow_png_exif.png')
im.load()  # raises AttributeError with 5.4+
```
![breaking_pillow_png_exif](https://user-images.githubusercontent.com/9530287/51749198-05316680-20af-11e9-9fba-d582f331243b.png)

**Comment by radarhere** [comment] 2019-01-25 20:03
Hi. This is actually a duplicate of #3557, and so it can also be resolved by #3558

**Closed** 2019-01-27 09:50 UTC
Labels: Duplicate
