### ISSUE TITLE
3.2.0 clipboard image corrupted when saved to png

### ISSUE THREAD

**Issue by techtonik** [python-pillow/Pillow#1811] opened 2016-04-06 10:41 UTC
This is a continuation after #1810 is fixed.

### What did you do?
1 open mspaint
2 alt+prtscr
3 run the code
```python
import sys
from PIL import ImageFile
from PIL import ImageGrab

# #1810 workaround
ImageFile.LOAD_TRUNCATED_IMAGES = True

im = ImageGrab.grabclipboard()
if im is None:
  sys.exit('Error: No image data in clipboard')
im.save('save.bmp', 'BMP')
im.save('save.png', 'PNG')
```

### What did you expect to happen?
BMP and PNG to be the same.

### What actually happened?
BMP:
![image](https://cloud.githubusercontent.com/assets/515889/14313895/f33bf0f0-fbfc-11e5-972b-4a410500e2c8.png)

PNG:
![save](https://cloud.githubusercontent.com/assets/515889/14313916/12478d10-fbfd-11e5-96a4-f417dc454d84.png)

### What versions of Pillow and Python are you using?

Pillow 3.2.0, Python 2.7, Vista 32.

**Comment by radarhere** [comment] 2016-04-06 13:56
If you open the BMP with Pillow, and try to save it as a PNG, is the result the same as the original PNG? Quite possibly the answer is no, it's just that if the answer were yes, then sharing the BMP here would mean that testers on any platform could reproduce the issue.

**Comment by wiredfool** [comment] 2016-04-06 14:09
I think that this and #1810 are both the same as #1293, since there is an error in the interpretation of the BMP header in the DIB in memory. 

The best debugging for it is going to be to get dumps of the raw data from the imageGrab function, as noted here: https://github.com/python-pillow/Pillow/issues/1293#issuecomment-206338667

**Comment by hugovk** [comment] 2016-04-06 17:01
PR #1813 is merged, so this should be fixed too.

**Comment by wiredfool** [comment] 2016-04-06 17:31
Please check the fix, there may be other stuff hiding in there

**Comment by techtonik** [comment] 2016-04-06 22:39
Are there any Windows builds that could be installed?

**Comment by techtonik** [comment] 2016-04-07 04:42
@wiredfool is it possible to release 3.2.1 with those fixes?

**Comment by techtonik** [comment] 2016-04-07 09:26
Saved .bmp looks fine, but .png now has a different transparency problem: 

![save](https://cloud.githubusercontent.com/assets/515889/14346609/a931df50-fcbb-11e5-8070-c5b9f570344c.png)

**Comment by wiredfool** [comment] 2016-04-07 18:49
Can you dump the raw bytes from within the ImageGrab.grabclipboard()?  As well as what you're seeing from the BMP and the PNG?

**Comment by techtonik** [comment] 2016-04-07 23:57
Attach contains all three files [1811alphabugs.zip](https://github.com/python-pillow/Pillow/files/209411/1811alphabugs.zip)

**Comment by wiredfool** [comment] 2016-04-09 14:06
It looks like the data that's in the alpha channel is not an alpha or transparency mask, it's likely some sort of active area mask, or highlighting, or something. In this case, it's coming up like this:

![alpha](https://cloud.githubusercontent.com/assets/19792/14404028/a8456ad0-fe64-11e5-8618-027f7a513445.png)

**Comment by techtonik** [comment] 2016-04-16 06:46
This is how inactive window looks like:

![image](https://cloud.githubusercontent.com/assets/515889/14579576/b87a1a42-03b7-11e6-9098-8f78fcfac8f3.png)

So that mask are probably RGB pixels that are applied with addition or some other algorithm.

Another things that it is not clear why BMP is saved ok.

**Comment by wiredfool** [comment] 2016-04-19 19:45
The reason that the BMP is ok is that it's loaded into pillow as `RGB`, so the funky mask is ignored. So, the BMP is probably broken, and the png is as well.

**Comment by wiredfool** [comment] 2016-05-05 16:21
Fix merged in #1847

**Closed by wiredfool** 2016-05-05 16:21 UTC
Labels: Windows

**Comment by techtonik** [comment] 2016-05-05 19:55
Need https://github.com/python-pillow/Pillow/pull/1815 to be merged to be able to test this.

**Comment by techtonik** [comment] 2016-05-05 20:05
[This](https://github.com/pypa/pip/issues/492#issuecomment-55263723) hints that egg can be converted to wheel:

    wget https://ci.appveyor.com/api/buildjobs/2lt1ejrowq9eyw5x/artifacts/Pillow-3.3.0.dev0-py2.7-win32.egg
    pip install wheel
    python -m wheel convert Pillow-3.3.0.dev0-py2.7-win32.egg 
    pip install Pillow-3.3.0.dev0-cp27-none-win32.whl -U

That works fine. Thanks.
