### ISSUE TITLE
[9.0.0 Regression] Pillow claims GIF frame to be mode RGB instead of P

### ISSUE THREAD

**Issue by doko42** [python-pillow/Pillow#5966] opened 2022-01-17 10:50 UTC
Forwarding from https://bugs.debian.org/1003661

img2pdf's autopkg tests fail with pillow 9.0.0, as seen at
https://tracker.debian.org/pkg/img2pdf

=========================== short test summary info ============================
FAILED src/img2pdf_test.py::test_general[animation.gif-internal] - AssertionE...
FAILED src/img2pdf_test.py::test_general[animation.gif-pikepdf] - AssertionEr...
ERROR src/img2pdf_test.py::test_gif_animation[internal] - TypeError: object i...
ERROR src/img2pdf_test.py::test_gif_animation[pikepdf] - TypeError: object is...

The img2pdf autopkgtest has found a regression in Pillow. Minimal reproducer
with the attached gif:

python3 -c 'from PIL import Image;img=Image.open("animation.gif");img.seek(1);print(img.mode)'

With 9.0.0 this will output "RGB" even though frame 1 is a palette based image.
With Pillow 8.4.0 above one-liner will correctly print "P".

tracked this down to this commit: b383a175be70da0df33babea3d480efd9768e937

**Comment by doko42** [comment] 2022-01-17 10:51
[https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1003661;filename=animation.gif;msg=8](url)

**Comment by radarhere** [comment] 2022-01-17 21:16
Hi. This is not a bug, but a deliberate and necessary change.

https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#convert-subsequent-gif-frames-to-rgb-or-rgba
> Since each frame of a GIF can have up to 256 colors, after the first frame it is possible for there to be too many colors to fit in a P mode image. To allow for this, seeking to any subsequent GIF frame will now convert the image to RGB or RGBA, depending on whether or not the first frame had transparency.

**Comment by josch** [comment] 2022-01-18 07:54
Hi, I'm the author of img2pdf and version 9.0.0 breaks the tests due to the new handling of GIF images.

If this change is here to stay, what can software do that wants to really figure out whether frame X of an image is P or RGB?

**Comment by radarhere** [comment] 2022-01-18 07:59
The first frame will be P (and, technically, it could also be L, but that's not new behaviour).
Any frame that you seek to after the first frame will be RGB or RGBA.

If you would like to know what the mode of an image is, you can just get the `mode` attribute. That will update when you seek to the new frame.
```pycon
>>> from PIL import Image
>>> im = Image.open("Tests/images/iss634.gif")
>>> im.tell()
0
>>> im.mode
'P'
>>> im.seek(1)
>>> im.tell()
1
>>> im.mode
'RGB'
```

**Comment by radarhere** [comment] 2022-01-18 08:08
> what can software do that wants to really figure out whether frame X of an image is P or RGB?

Perhaps I've misunderstood. If you're asking whether the GIF frame was RGB or not before Pillow got to it, I can answer that simply - the frame is never RGB in the GIF file itself. Each GIF frame in the file can only support up to 256 colors.

**Comment by josch** [comment] 2022-01-18 08:53
Yes, but I can I obtain the original image data somehow or is that information lost now?

**Comment by wiredfool** [comment] 2022-01-18 09:09
If you seek to the nth frame of a GIF, the file stores an extents, dispose setting, possibly a palette, and the image data for that frame.  If you display just that data, it will show a paletted image that encodes the changes from the previous frame. (modulo what the dispose setting is). However, to regenerate what should be shown to the user, that needs to be composited onto the previous frame.  Each frame may have a different palette, extents, and dispose setting, so that once you get the second frame, you may be dealing with as many as 512 colors. This is no longer representable in our palette image format.

There is no general way to get to the nth frame of a GIF without rendering each previous frame and composing the results, and since each frame may have an arbitrary palette, the logical end point is that once you get to the possibility of a second palette, the image needs to be RGB(A).

**Comment by wiredfool** [comment] 2022-01-18 09:14
For reference, this is an explainer with a demo: https://notes.tweakblogs.net/blog/8712/high-color-gif-images.html

**Comment by josch** [comment] 2022-01-18 09:36
Okay, then I guess the simple answer is just that there is currently no way to get the second frame of the GIF *without* it being composited onto the first frame?

**Comment by radarhere** [comment] 2022-01-18 09:46
```python
from PIL import Image, GifImagePlugin
GifImagePlugin.GifImageFile.load_end = lambda self: None
im = Image.open("/Users/andrewmurray/Dropbox/docs/pillow/Pillow/Tests/images/iss634.gif")
print("Frame:", im.tell(), "palette index at (0, 0):", im.getpixel((0, 0)), "mode:", im.mode)
im.seek(1)
print("Frame:", im.tell(), "palette index at (0, 0):", im.getpixel((0, 0)), "mode:", im.mode)
```
does what you're asking, giving
```
Frame: 0 palette index at (0, 0): 60 mode: P
Frame: 1 palette index at (0, 0): 255 mode: P
```

**Comment by josch** [comment] 2022-01-18 09:51
That's awesome, thank you!

Since this behaviour is intended. I'll adjust img2pdf accordingly and I guess you can close this issue. Thank you for taking the time and answering all my questions so quickly. :)

**Closed** 2022-01-18 09:51 UTC
Labels: GIF
