### ISSUE TITLE
Unable to draw a unicode character with combination characters

### ISSUE THREAD

**Issue by danny0838** [python-pillow/Pillow#4691] opened 2020-06-14 00:11 UTC
### What did you do?
Draw a char with combination characters `a\u0308\u0325` using [HanaMin](http://fonts.jp/hanazono/). (See code below)

### What did you expect to happen?
The output should be ![圖片](https://user-images.githubusercontent.com/531417/84581688-88736980-ae16-11ea-964b-3b5f28062991.png).

### What actually happened?
The output is ![image](https://user-images.githubusercontent.com/531417/84581671-611c9c80-ae16-11ea-9942-1e6d48eb62b2.png).

### What are your OS, Python and Pillow versions?

* OS: Windows 7 SP1
* Python: 3.8.1
* Pillow: 7.1.2

```python
from PIL import Image, ImageDraw, ImageFont

text = "a\u0308\u0325"
font = "HanaMinA.ttf"

img = Image.new('RGBA', (240, 80))
draw = ImageDraw.Draw(img)
fnt = ImageFont.truetype(font, 80)
dx, dy = fnt.getoffset(text)
draw.text((-dx, -dy), text, font=fnt, fill="#000")
img.save("image.png")
```

**Comment by nulano** [comment] 2020-06-14 00:14
Duplicate of https://github.com/python-pillow/Pillow/issues/4690#issuecomment-643697897.

**Comment by radarhere** [comment] 2020-06-14 00:34
It is similar enough that it might be more helpful to discuss the problems in the one issue, yes. Closing as a duplicate.

**Closed by radarhere** 2020-06-14 00:34 UTC
Labels: Duplicate
