### ISSUE TITLE
Using OSError as a general error in the parsing process is unituitive

### ISSUE THREAD

**Issue by vanschelven** [python-pillow/Pillow#7489] opened 2023-10-23 10:12 UTC
### What did you do?

I was handling a truncated (corrupted) image.

### What did you expect to happen?

I was expecting an error to be raised that pointed at the corrupted image as the source of the problem.

### What actually happened?

An `OSError` was raised. In my particular case the message was "broken data stream when reading image file", but I believe there may be many such exceptions with different messages.

The Python Manual has the following to say about this:

> This exception is raised when a system function returns a system-related error, including I/O failures such as “file not found” or “disk full” (not for illegal argument types or other incidental errors).

And this is the direction I was looking in even before reading the manual. This may be more so the case because of the reference to a "broken data stream". In particular, I was suspecting a broken network connection to S3. It took me longer than needed to figure out I needed to turn my attention to the image itself.

Another problem is: this makes it hard to distinguish between _actual_ `OSErrors` (such as full disks, broken network connections to S3 and such) and problems with images when catching exceptions.  

### What are your OS, Python and Pillow versions?

this applies across the board, I believe

* Pillow: 10.0.1

### What solution do you suggest?

Hard to say... perhaps clarification of the documentation? I have to admit that the docs do mention the fact that `OSErrors` may be raised during parsing but still "OS" is such a strong pointer in the wrong direction that it's hard to go right here when debugging.

I do understand that backwards compatibility is a thing, so perhaps a new subclass of `OSError` such as `NotActuallyOSError` could be created?

**Comment by radarhere** [comment] 2023-10-23 10:55
This seems the same as #7425. Do you mind if this is closed as a duplicate of that?

That was closed, and instead mentioned in an open issue, #1643, that is similarly about switching to custom errors.

**Comment by vanschelven** [comment] 2023-10-23 11:01
The issues you mention are indeed raising similar concerns. Feel free to merge this one into #1643 too.

**Closed** 2023-10-23 11:02 UTC
Labels: Duplicate
