### ISSUE TITLE
Problem with EXIF in some files

### ISSUE THREAD

**Issue by mpyatishev** [python-pillow/Pillow#518] opened 2014-02-05 12:48 UTC
I've got a strange problem with some files with EXIF in them. Here is a traceback and the file in attachment.

```
Internal Server Error: /place/content/upload/
Traceback (most recent call last):
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/var/www/tourism/www/tourism/core/mixins.py", line 13, in dispatch
    return super(LoginRequredMixin, self).dispatch(*args, **kwargs)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 205, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 171, in post
    return self.form_valid(form)
  File "/var/www/tourism/www/tourism/apps/place/views.py", line 368, in form_valid
    self.object.save()
  File "/var/www/tourism/www/tourism/apps/place/models.py", line 409, in save
    super(Photo, self).save(*args, **kwargs)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/tourism/www/tourism/apps/place/models.py", line 108, in do_post_save
    instance.rename_files()
  File "/var/www/tourism/www/tourism/apps/place/models.py", line 101, in rename_files
    self.save(update_fields=update_fields)
  File "/var/www/tourism/www/tourism/apps/place/models.py", line 415, in save
    crop='center'
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/sorl/thumbnail/shortcuts.py", line 8, in get_thumbnail
    return default.backend.get_thumbnail(file_, geometry_string, **options)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/sorl/thumbnail/base.py", line 61, in get_thumbnail
    thumbnail)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/sorl/thumbnail/base.py", line 86, in _create_thumbnail
    image = default.engine.create(source_image, geometry, options)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/sorl/thumbnail/engines/base.py", line 15, in create
    image = self.orientation(image, geometry, options)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/sorl/thumbnail/engines/base.py", line 26, in orientation
    return self._orientation(image)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/sorl/thumbnail/engines/pil_engine.py", line 29, in _orientation
    exif = image._getexif()
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 362, in _getexif
    return _getexif(self)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 386, in _getexif
    info.load(file)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 421, in load
    tag, typ = i16(ifd), i16(ifd, 2)
  File "/var/www/tourism/env/local/lib/python2.7/site-packages/PIL/_binary.py", line 29, in i16le
    return i8(c[o]) | (i8(c[o+1])<<8)
IndexError: string index out of range
```

![admiral](https://f.cloud.github.com/assets/3088773/2086992/3809123a-8e63-11e3-8386-ed545452ba27.jpg)

**Comment by radarhere** [comment] 2015-06-08 10:48
I think that the latest problem in Issue #1163 may have actually been the same problem as this, just with the new Python _binary methods, as PR #1256 means that the image is this issue is now dealt with gracefully, rather than generating an error.

I would say that this issue can be closed, since #520 seems to have taken over the task of creating a better way of handling EXIF data.

**Comment by hongquan** [comment] 2015-07-31 04:04
This file

![run_run_shaw_creative_media_center_hk](https://cloud.githubusercontent.com/assets/314607/9000581/2774cdd8-377c-11e5-9105-5e86a9ae9572.jpg)

failed with `SyntaxError` in `._getexif()`.

ImageMagick read it successfully.

**Comment by radarhere** [comment] 2016-01-22 03:04
I can't replicate that problem, either with current Pillow or 2.9.x, which would have been the version when you posted this image. Can you provide any information about your platform/version of Pillow/version of Python?

**Comment by sciunto** [comment] 2017-10-18 09:42
I attach a jpeg file for which reading the metadata fails with `_getexif()` (Object with a None type is returned) while imagemagick and exiftool successfully read the metadata.

The best workaround I found so far is to install exiftool (written in perl) and use for instance https://github.com/smarnach/pyexiftool to make system calls.

I attach the image for a testing purpose. I checked that the uploaded image still fails.

![image_marne](https://user-images.githubusercontent.com/335370/31711422-538a40ba-b3f8-11e7-9911-b690178b9d24.JPG)

Could someone fix the tag of this issue to indicate that jpg files are also impacted?

**Comment by wiredfool** [comment] 2017-10-19 08:16
@sciunto There's no exif info in that file.

**Comment by sciunto** [comment] 2017-10-19 15:45
```
exiftool /tmp/31711422-538a40ba-b3f8-11e7-9911-b690178b9d24.JPG 
ExifTool Version Number         : 10.55
File Name                       : 31711422-538a40ba-b3f8-11e7-9911-b690178b9d24.JPG
Directory                       : /tmp
File Size                       : 30 kB
File Modification Date/Time     : 2017:10:19 17:45:13+02:00
File Access Date/Time           : 2017:10:19 17:45:13+02:00
File Inode Change Date/Time     : 2017:10:19 17:45:17+02:00
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : inches
X Resolution                    : 96
Y Resolution                    : 96
Image Width                     : 1280
Image Height                    : 960
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 1280x960
Megapixels                      : 1.2

```

**Comment by wiredfool** [comment] 2017-10-19 16:18
That's the basic JFIF info, not EXIF info:
```
>>> from PIL import Image
>>> im = Image.open('bad_exif.jpg')
>>> im.info
{'jfif_version': (1, 1), 'jfif': 257, 'jfif_unit': 1, 'jfif_density': (96, 96), 'dpi': (96, 96)}
```
Looking at the segments in the jpeg, there are the following segments:
```
0xffd8 SOI Start of image
0xffe0 APP0 Application segment 0
0xffdb DQT Define quantization table
0xffdb DQT Define quantization table
0xffc0 SOF0 Baseline DCT
0xffc4 DHT Define Huffman table
0xffc4 DHT Define Huffman table
0xffc4 DHT Define Huffman table
0xffc4 DHT Define Huffman table
0xffda SOS Start of scan
```

There's no `APP1 Application segment 0` which would be the EXIF segment.

**Comment by hugovk** [comment] 2017-10-19 16:20
exiftool can read more than just EXIF metadata (see  [here](https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/JPEG.html) for examples).

That image:

![image](https://user-images.githubusercontent.com/1324225/31781934-41659ce4-b502-11e7-991c-fc59951be79e.png)

This [image](https://github.com/python-pillow/Pillow/blob/master/Tests/images/exif_gps.jpg):

![image](https://user-images.githubusercontent.com/1324225/31781983-68304ac2-b502-11e7-8c09-5adb8a3c47f2.png)

**Comment by sciunto** [comment] 2017-10-20 10:05
Thanks for shedding light on this. I was tricked by exiftool on what exif actually is. :)

**Comment by jdhao** [comment] 2017-10-28 16:32
If you do not care about exif info and do not want to get the warning message, you can use [piexif](https://pypi.python.org/pypi/piexif) to the remove the exif info.

**Comment by peymanrah** [comment] 2018-06-11 04:51
This sounds like a compatibility issue between pillow, numpy, etc
I solved the issue by downgrading to Pillow version 4 by below command on anaconda

conda install pillow=4.0.0

My python version is 3.5. This would solve the issue.

**Comment by HatScripts** [comment] 2018-09-30 04:53
If you simply wish for these warnings to stop spamming your console, you can just filter them, e.g.
```py
warnings.filterwarnings("ignore", "(Possibly )?corrupt EXIF data", UserWarning)

with Image.open("problematic_image.jpg") as image:
    # do something with image
```

**Comment by hugovk** [comment] 2018-09-30 05:39
> I think that the latest problem in Issue #1163 may have actually been the same problem as this, just with the new Python _binary methods, as PR #1256 means that the bug in this issue is now dealt with gracefully, rather than generating an error.
>
> I would say that this issue can be closed, since #520 seems to have taken over the task of creating a better way of handling EXIF data.

Closing.

**Closed by hugovk** 2018-09-30 05:39 UTC
Labels: Bug, Exif, NumPy, TIFF

**Comment by Light--** [comment] 2019-06-11 10:10
still dont know how to repair the exif corrupt image file problem....

**Comment by radarhere** [comment] 2019-06-11 10:11
@Light-- would you be able to open a new issue with specific details of your situation?

**Comment by scottw-finao** [comment] 2019-08-19 18:38
Is there a defined fix for this yet? I think a script we just outsourced is encountering this on some customer images with exif TIFF info in a jpeg.

**Comment by radarhere** [comment] 2019-08-19 20:54
@scottw-finao would you be able to open a new issue with specific details of your situation?

**Comment by scottw-finao** [comment] 2019-08-19 21:11
@radarhere I'm not a big python guy. We're still trying to reproduce it locally and this is the only semi-related thread I could find on exif in jpeg files. We're trying to generate thumbnails on AWS lambda and when I run the code locally, it works fine in python 3.6. The AWS appears to be using python 3.7. That's the only difference I've detected thus far. But the problem is, the cloud logs aren't giving me anything useful by way of errors or exceptions. It's just making it to the Image.thumb() call and the script fails from a timeout.
Examining the file compared to ones that worked, and the only difference is that the failing files have embedded exif(TIFF) info in them. Still exploring and trying to reproduce it locally. I'll most more if I find it and it turns out to be related. We are looking into the versioning mentioned by @peymenrah above
