### ISSUE TITLE
JPEG binary data changed after 5.3.0 on Windows (not on Linux)

### ISSUE THREAD

**Issue by claweyenuk** [python-pillow/Pillow#4686] opened 2020-06-12 18:02 UTC
### What did you do?
Output a JPEG (converted from a PNG)

### What did you expect to happen?
I upgraded from Pillow 5.2.0 to 7.1.2 on Windows and Linux. I expected the binary JPEG data to remain the same. It did for Linux, but on Windows, the binary JPEG data changed (visually, the images look the same, but the RGB values have changed slightly too).

I did a little digging, and starting with build 5.3.0, on Windows, Pillow outputs data that is different from Linux, and different from previous releases.

### What actually happened?
See above.

### What are your OS, Python and Pillow versions?

* OS: Windows 10 & Ubuntu 18.04
* Python: 3.6.8 Windows, 3.6.9 Linux
* Pillow: 7.1.2 (all Pillow versions installed using pip)

Code:

```python
    import PIL
    from PIL import Image
    import numpy as np
    from scipy import misc as spm

    # image_data = Image.open(input_path)
    # np.save("npyout_{}.npy".format(PIL.__version__), image_data)
    # img = Image.fromarray(image_data)
    img = Image.open(input_path)
    out_path = "out_{}.jpg".format(PIL.__version__)
    img.save(out_path, format='JPEG', quality=95)
```

**Comment by wiredfool** [comment] 2020-06-12 18:23
JPEG is a lossy image format, so the exact encoded or decoded pixel values can vary, depending on compression settings, the exact version of the underlying jpeg library, and other settings. It is meant to gradually throw away data that is unlikely to be noticed in photographic type images. 

If you require exact pixel perfect images, you need an image format that doesn't use lossy compression, such as PNG or TIFF (with a lossless compression method).

**Comment by nulano** [comment] 2020-06-12 18:33
Checking `Image.core.jpeglib_version`, I get "9.0" for Pillow 5.2.0, but "6.2" for Pillow 5.3.0. If I had to guess, starting with 5.3.0, Pillow was built with libjpeg-turbo (which claims to be "6.2" by default) instead of libjpeg.

There is no easy way to check for sure, as `Image.core.HAVE_LIBJPEGTURBO" was only added in later versions of Pillow, but Pillow 6.0.0 also claims to use libjpeg 6.2, with HAVE_LIBJPEGTURBO=True.

libjpeg-turbo is likely preferred because it claims to be faster with marginal encoding differences. The library used on Linux (if building from source) depends on the system version of libjpeg.

**Comment by claweyenuk** [comment] 2020-06-13 00:14
Thanks you @nulano for the insight. I went and checked several versions and got libjpeg and the libjpeg turbo flag (if available). The data is below.

It appears as though libjpeg version is what causes the change.

OS does not directly cause a change, however, the Pillow package for a given OS may use different versions of libjpeg and that could cause differences. For libjpeg 6.2 I was able to get with and without turbo, and that does not change the hash of the output image.

I will leave this open, but feel free to close this ticket. I am not sure if this difference in binary output matters.

Thanks!

| libjpeg | libjpeg-turbo | Pillow | Output Hash | Source                          |
|---------|---------------|--------|-------------|---------------------------------|
| 6.2     | unknown       | 4.1.1  | 94e         | pip (Windows)                   |
| 6.2     | unknown       | 5.3.0  | 94e         | pip (Windows)                   |
| 6.2     | w/ turbo      | 5.4.1  | 94e         | pip (Windows)                   |
| 6.2     | w/ turbo      | 6.0.0  | 94e         | pip (Windows)                   |
| 6.2     | w/o turbo     | 7.1.2  | 94e         | git source (Linux)              |
| 8       | w/ turbo      | 6.2.2  | 94e         | pip (Windows)                   |
| 8       | w/ turbo      | 7.1.2  | 94e         | pip (Windows)                   |
| 8       | w/ turbo      | 7.1.2  | 94e         | git source (Linux)              |
| 9       | unknown       | 4.1.1  | aac         | pip (Windows)                   |
| 9       | unknown       | 5.2.0  | aac         | pip (Windows)                   |
| 9       | unknown       | 5.2.0  | aac         | pip (Linux)                     |
| 9       | unknown       | 5.3.0  | aac         | pip (Linux)                     |
| 9       | w/o turbo     | 5.4.1  | aac         | pip (Linux)                     |
| 9       | w/o turbo     | 6.0.0  | aac         | pip (Linux)                     |
| 9       | w/o turbo     | 7.1.2  | aac         | pip (Linux), git source (Linux) |

**Comment by nulano** [comment] 2020-06-13 01:29
> For libjpeg 6.2 I was able to get with and without turbo, and that does not change the hash of the output image.

Oh right, libjpeg-turbo was based on libjpeg 6.2.

From https://libjpeg-turbo.org/:

>libjpeg-turbo was originally based on libjpeg/SIMD, an MMX-accelerated derivative of libjpeg v6b developed by Miyasaka Masaru

**Comment by radarhere** [comment] 2020-06-13 09:51
I'm actually going to close this as a duplicate of #3833

**Closed** 2020-06-13 09:51 UTC
Labels: Duplicate, JPEG
