### ISSUE TITLE
PIL.ImageOps.exif_transpose() fails on some PNGs

### ISSUE THREAD

**Issue by doublex** [python-pillow/Pillow#5509] opened 2021-05-24 20:06 UTC
Testcase (extension should be .py):
[testcase.txt](https://github.com/python-pillow/Pillow/files/6534717/testcase.txt)

Pillow 8.1 works, 8.2 fails

Traceback:
```
  File "/home/max/.local/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 940, in load_end
    self.png.call(cid, pos, length)
  File "/home/max/.local/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 187, in call
    return getattr(self, "chunk_" + cid.decode("ascii"))(pos, length)
AttributeError: 'PngStream' object has no attribute 'chunk_'
```

**Comment by radarhere** [comment] 2021-05-24 22:53
Just to clarify, the issue doesn't relate to `exif_transpose()`. It's our generic `load()` method. Testing, the error started after https://github.com/python-pillow/Pillow/pull/5377/commits/22e9bee4ef225c0edbb9323f94c26cee0c623497. So this may not be a bug as much as a security measure.

You probably know, but if you don't enable `LOAD_TRUNCATED_IMAGES`, then the error doesn't appear.

**Comment by radarhere** [comment] 2021-05-25 02:59
Actually, I've found that this would be fixed by #5493, making this a duplicate of #5491.

**Closed by radarhere** 2021-05-25 02:59 UTC

**Comment by radarhere** [comment] 2021-06-06 11:17
#5493 has been merged, so this should be fixed in the next version of Pillow. due out on July 1.

**Comment by doublex** [comment] 2021-06-06 11:39
@radarhere 
Thank you so much for `pillow`!
