### ISSUE TITLE
Animated gifs saving with `save_all` outputs broken animation

### ISSUE THREAD

**Issue by Sapphire64** [python-pillow/Pillow#1355] opened 2015-07-24 09:38 UTC
Hi everyone,

### Description

It looks like animated gifs saving is broken in **Pillow**. I wrote failing test here:
https://github.com/Sapphire64/Pillow/commit/4aec16d6d88a71209bb480330b6171c220613fa9

```python
def test_headers_saving_for_animated_gifs(self):  # FAILING test
    important_headers = ['background', 'version', 'transparency', 'duration', 'loop']
    # Multiframe image
    im = Image.open("Tests/images/dispose_bgnd.gif")

    out = self.tempfile('temp.gif')
    im.save(out, save_all=True)
    reread = Image.open(out)

    for header in important_headers:
        self.assertEqual(
            im.info[header],
            reread.info[header]
        )
```

It fails because:
```
(Pdb) im.info
{'duration': 1000, 'version': 'GIF89a', 'extension': ('NETSCAPE2.0', 41), 'background': 0, 'loop': 0}
(Pdb) reread.info
{'version': 'GIF87a', 'background': 0}
```
As far as I know `GIF87a` does not support animations (?), transparency and loop header. And we are getting corrupted GIF as an output with no looping and weird colours, and duration of the frames is wrong.

### Original animated gif

![Original Image](http://i.imgur.com/t6XVOc9.gif)

### Pillow's save_all output

To see how bad it is just look on the output of our test which saying that GIF's `save_all` works fine:

![Output](http://i.imgur.com/HQxo7CT.gif)
*If you don't see any animation please reload a page, because it has only one loop which takes ~1 second. Or you can [open direct link](https://camo.githubusercontent.com/4d4d5b2b6255e26aa864d198a061f764754d1e0f/687474703a2f2f692e696d6775722e636f6d2f4851786f3743542e676966) and refresh the page.*

### My investigation

We need to fix `GifImagePlugin.py` first to not hardwire `GIF87a` header, second - to write all meta about that animation. Maybe it can be related to the fact that in `save_all` we are not calling `_get_local_header` function which does something with that important headers. Also note that our function which should support duration is actually ignoring it:
```
# To specify duration, add the time in milliseconds to getdata(),
# e.g. getdata(im_frame, duration=1000)   # <<< this won't work
```
I've tried to work on fix but got no luck yet, so would like to get some help from the community.

#### Further reading
https://bitbucket.org/bench/images2gif.py/src/a618bd8fc352f278a3b0c777cb6427ec39236f0a/images2gif.py?at=master - it looks like somebody already solved this problem using PIL

**Comment by Sapphire64** [comment] 2015-08-19 09:52
It would be nice to receive at least some feedback and have labels assigned :)

**Comment by radarhere** [comment] 2015-08-19 09:54
Hi. I'm aware of the bug, just hoping to find some time to get around to it. Certainly I'd want it to be a part of the next release, so I'll add the relevant label and milestone. Thanks for your contribution of creating the issue!

**Comment by radarhere** [comment] 2015-08-19 12:38
I'll note that in your test, part of what you check is `version` and `transparency`
- The original image doesn't have a `transparency` key in it's info dictionary, and so your test will always produce a `KeyError` on that
- You'll see at https://github.com/python-pillow/Pillow/blob/master/PIL/GifImagePlugin.py#L537 that the version for GifImagePlugin outputs is fixed at `GIF87a`. To suggest that Pillow should also save images as `GIF89a` sounds like a feature request to me, not a bug.

**Comment by radarhere** [comment] 2015-08-19 13:57
`background` was already working. I've created a PR to fix `duration` and `loop`. So have a look at that and let us know if your problem is resolved.

**Comment by Sapphire64** [comment] 2015-08-19 15:30
@radarhere Thanks for reply! Maybe some stuff changed in last 26 days since I reported this, before that I was getting simple set of headers and duration was never part of them, even after `duration=1000` applied (you can see my env vars after tests' code). There was some code which was dropping/not setting it, don't remember much already :)

I've read here: http://docstore.mik.ua/orelly/web2/wdesign/ch19_01.htm that GIF89a is the only valid header if you want to have transparency and animations, that's why we may want to set this value in header (I believe it's only constant value thing and no major difference exists).

**Comment by radarhere** [comment] 2015-08-20 10:50
I've looked into this, and you're absolutely right about GIF89a being the required header. Thanks! Looks like this has been wrong since 2002. I've created a PR to fix it.

**Comment by radarhere** [comment] 2015-08-25 09:35
Would you be able to try out the latest PR and see if you think that solves the issue?

**Comment by Sapphire64** [comment] 2015-08-26 08:37
@radarhere sorry for very late reply, I think I'll be able to test animations saving later today. Before that our PIL-based image service was not able to handle animated GIFs (we do resizing etc.) so I'll make very simple test with using `save_all` and updating to latest Pillow.

**Comment by radarhere** [comment] 2015-08-26 09:15
No problem, these issues are often solved over much longer timescales than a day. Maybe you meant this, but just a note that you'll have to use the branch I created for #1384, as none of the changes have been merged yet.

**Comment by Sapphire64** [comment] 2015-08-26 14:21
@radarhere ok, it looks much better now (thank you!) BUT still output can be weird (also note line on bottom which appeared on output)

Original file
![http://media.giphy.com/media/LPBYImbgzsKpG/giphy.gif](http://media.giphy.com/media/LPBYImbgzsKpG/giphy.gif)

Result
![http://i.imgur.com/VjBrPlq.gif](http://i.imgur.com/VjBrPlq.gif)

In our project we use thumbnail function which also may drop frames (I'll need to check). I'm going to look into tests to make tests fail because of corrupted output as shown above.

**Comment by Sapphire64** [comment] 2015-08-26 14:44
@radarhere it's me again, I wrote failing test for image not looking as expected:
https://github.com/Sapphire64/Pillow/commit/177121233b432a371532b377f7db982ac5347012
Should we continue in this thread or should we create new bug?

**Comment by radarhere** [comment] 2015-08-26 14:54
It's up to you whether to create a new issue or not - on the one hand, you're no longer talking about a problem with `save_all` - this is now just a problem with the images contained within the animations. On the other hand, this is still related to what you discussed in your original post.

**Comment by Sapphire64** [comment] 2015-08-26 15:07
I think I will create new issue with details and examples so we will start looking into why frames are broken. The animation itself seems to be fixed now.

**Comment by radarhere** [comment] 2015-09-20 13:28
Just a note to say that #1384 has been merged, so the animation related issues in this should now be resolved.

**Closed** 2015-09-24 20:57 UTC
Labels: Bug
