### ISSUE TITLE
ImageGrab.grabclipboard() can't recognize image (png 32bit) in clipboard 

### ISSUE THREAD

**Issue by vanleo2001** [python-pillow/Pillow#3211] opened 2018-06-28 09:49 UTC
Now I write some code with Pillow. I found  ImageGrab.grabclipboard() can't work if the  image content  in clipboard is png 32bit.
My OS: win7 x64
Pillow: 5.1.0 
Python: 3.6.5

My code is 
```python
import os
import sys
import win32clipboard
import win32con
from PIL import ImageGrab
from PIL import ImageFile
from PIL import Image

if win32clipboard.IsClipboardFormatAvailable(win32clipboard.CF_BITMAP):
    im = ImageGrab.grabclipboard()
    im.save('000.png', 'PNG')
    print('bitmap saved')
```

1.  I open this 32bit png 
![32bitpng](https://user-images.githubusercontent.com/12027772/42026965-167f2652-7afb-11e8-80c2-e6eecb4abe2c.png), copy it into clipboard. Run pythod code above. Error will show
```
Traceback (most recent call last):
  File "cl.py", line 13, in <module>
    im.save('000.png', 'PNG')
AttributeError: 'NoneType' object has no attribute 'save'
```
2. I try 24bit png
![24bitpng](https://user-images.githubusercontent.com/12027772/42027107-7df93516-7afb-11e8-9068-6af4aa28c3f3.png)
 or 8bit png, it works ok.

**Comment by nulano** [comment] 2019-07-05 09:57
I can reproduce this when copying the image with Windows 7 Photo Viewer, but not with Windows 10 Photos. Chrome on Windows 7 also works fine.

Keep in mind, that the clipboard format is determined by the application you copy from, and that Pillow only grabs the `CF_DIB` format, not `CF_BITMAP`.

**Comment by nulano** [comment] 2020-03-27 23:02
Looking into this a bit more, [Windows is supposed to automatically convert `CF_BITMAP` into `CF_DIB`](https://docs.microsoft.com/en-us/windows/win32/dataxchg/clipboard-formats#synthesized-clipboard-formats). Unlike `CF_DIB` (the format supported by Pillow), `CF_BITMAP` doesn't contain the image palette (it is assumed to be in the system palette, but this is not required), which makes it difficult to support. This is why the system is supposed to automatically convert it to `CF_DIB`, but for some reason, this appears to be failing on Windows 7.

Unfortunately, because of the reasons above, I doubt Pillow will provide a workaround for this.

I can only suggest you update your code to check for `CF_DIB` instead of `CF_BITMAP`.

**Comment by hugovk** [comment] 2020-05-04 17:28
Thanks for checking @nulano. Let's close this as there's not much we can do for this, especially as Windows 7 is no longer supported.

**Closed by hugovk** 2020-05-04 17:28 UTC
Labels: Windows
