### ISSUE TITLE
Images with Alpha of 0 have performance issues

### ISSUE THREAD

**Issue by simonschofield** [python-pillow/Pillow#2451] opened 2017-03-18 19:08 UTC
### What did you do?
I am doing multiple (like thousands of) image composites using Image.alpha_composite() onto a large target image with initial colour of (255,255,255,0) i.e. a transparent image.
### What did you expect to happen?
That there would be a steady performance over time
### What actually happened?
 I notice the system slowing down over time. When I changed the initial colour of the target image to (255,255,255, 1) i.e. _almost_ transparent, it ran much faster, and did not slow down. 
The slowing-down was significant; it started at 0.03 secs per composite but slowed to 0.33 secs per composite in about 1000 operations. 
### What versions of Pillow and Python are you using?
Old stuff, admittedly. Pillow 2.4, Python 3.0 32bit

**Comment by wiredfool** [comment] 2017-03-18 20:41
Python 3.0?  I don't think we ever supported any python 3 < 3.2. 

Could you post code that triggers the bug?  I can't reproduce it here with a quick check.

**Comment by simonschofield** [comment] 2017-03-18 22:54
Sorry, it's Python 3.3.3, I'm using. The code is a big system including a TKInter/Photo image real-time display of the compositing happening, so it's not viable to send the code at the moment. After some investigation I think the issue is in the TKInter/Photo image updating. I'll root around a bit more and if I narrow it down will let you know where I think the problem lies.

Best

Simon


________________________________

**Comment by wiredfool** [comment] 2017-03-19 13:36
IIRC, there are some notes in the source for Tk that there are performance issues when modifying a visible image.

**Comment by homm** [comment] 2017-04-02 11:11
We still need a minimal test case with Pillow code (without TKInter) to reproduce the issue.


There [should be significant speedup](https://github.com/python-pillow/Pillow/blob/master/libImaging/AlphaComposite.c#L59) for transparent source pixels (i.e. second argument for `alpha_composite()` function), but there shouldn't be any penalties for opaque or transparent destination pixels.

By the way, have you considered use Pillow-SIMD for this?

```
Pillow 4.1.0.dev0
Composition 2560×1600 RGB image
    Composition         0.03379 s   121.21 Mpx/s

Pillow-SIMD 4.0.0.post0
Composition 2560×1600 RGB image
    Composition         0.00962 s   425.60 Mpx/s
```

**Comment by aclark4life** [comment] 2017-06-21 12:51
Marking as a bug until proven otherwise… ("Pillow is guilty until proven innocent? :smile: Or maybe we need a "Possible bug" label.)

**Comment by wiredfool** [comment] 2017-06-21 12:54
I think this got left as a 'likely tk' bug unless there's code.

**Comment by aclark4life** [comment] 2017-06-21 12:57
So it is

**Closed by aclark4life** 2017-06-21 12:57 UTC
Labels: Bug
