### ISSUE TITLE
Image.show() causes xwayland to crash

### ISSUE THREAD

**Issue by xAspirus** [python-pillow/Pillow#6154] opened 2022-03-24 07:16 UTC
```py
def image_split_into_4(im: Image.Image):
    return (
        im.crop((0          , 0           , im.width//2, im.height//2)), # tl
        im.crop((im.width//2, 0           , im.width   , im.height//2)), # tr
        im.crop((0          , im.height//2, im.width//2, im.height   )), # bl
        im.crop((im.width//2, im.height//2, im.width   , im.height   )), # br
    )

im = Image.open('test.png')
x = image_split_into_4(im)
x[0].show()
x[1].show()
x[2].show()
x[3].show()
```

will cause xwayland server to crash

**Comment by hugovk** [comment] 2022-03-24 07:48
### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

Did it output any error traceback? Please paste it in full.

Does it happen with all images or only certain ones?

**Comment by radarhere** [comment] 2022-03-25 11:05
What viewers are detected by Pillow?
```pycon
>>> from PIL import ImageShow
>>> ImageShow._viewers
[<PIL.ImageShow.MacViewer object at 0x1050706d0>]
```

**Comment by radarhere** [comment] 2022-03-27 04:18
When Pillow "shows" an image on Linux, it is running `xdg-open`, `display`, `gm`, `eog` or `xv` on the command line. If there is a crash after that, it is because of a problem in the Linux software, not within Pillow.

It is possible that the PNG file being saved by Pillow is corrupt in some way, or that we have chosen an obscure method of writing the file that is not fully supported by the Linux software. This could result in Linux being unable to display the image correctly, but it shouldn't result in a crash.

If your problem is easily reproducible, that would be interesting. If it is a common problem, then we should see if there is anything we can do to help from our side. But I think the most likely reason for this situation is that there is a problem in your installation.

**Comment by radarhere** [comment] 2022-04-01 09:57
@xAspirus did you have any more information for us?

**Comment by radarhere** [comment] 2022-04-07 09:42
Closing, unless more information can be provided.

**Closed by radarhere** 2022-04-07 09:42 UTC
Labels: Linux, Awaiting OP Action
