### ISSUE TITLE
The image compress issue

### ISSUE THREAD

**Issue by ReZeroS** [python-pillow/Pillow#2480] opened 2017-04-07 03:55 UTC
### What did you do?

Reverse a gif get it much bigger size on disk

### What did you expect to happen?

Still the original size or only a bit more

### What versions of Pillow and Python are you using?

latest Pillow and 3.6 Python

```python
from PIL import Image, ImageSequence
from PIL import ImagePalette
with Image.open('sd.gif') as im:
    if im.is_animated:
        frames = [f.copy() for f in ImageSequence.Iterator(im)]
        frames.reverse()
        frames[0].save('out.gif', save_all=True, append_images = frames[1:])  
```

**Comment by hugovk** [comment] 2017-04-07 05:49
Duplicate of https://github.com/python-pillow/Pillow/issues/617.

**Closed by hugovk** 2017-04-07 05:49 UTC
