### ISSUE TITLE
Calling im.convert() after accessing im.is_animated on gives an error with specific gifs

### ISSUE THREAD

**Issue by ranetp** [python-pillow/Pillow#6605] opened 2022-09-21 17:39 UTC
### What did you do?
Tried to call im.convert() after accessing im.is_animated on a non-animated gif file.

### What did you expect to happen?
Expected the im.convert() command to execute successfully.
### What actually happened?
im.convert() gave an error `'NoneType' object has no attribute 'convert'`

### What are your OS, Python and Pillow versions?

* OS: Windows 10 (build 19041.388)
* Python: 3.7.6
* Pillow: 9.2.0

```python
im = Image.open('test.gif')
im.is_animated # is_animated was accessed, the next line calling .convert() will now fail
im.convert() # This gives "'NoneType' object has no attribute 'convert'"
```
If you call im.convert() without first calling im.is_animated, it will work fine.
This seemingly doesn't happen with every gif, including probably non animated ones.

I went through every line of the is_animated method in [GifImagePlugin.py](https://github.com/python-pillow/Pillow/blob/main/src/PIL/GifImagePlugin.py) and it seems that the convert() error starts happening when an exception is thrown when calling `self._seek(1, False)` on[ line 134](https://github.com/python-pillow/Pillow/blob/main/src/PIL/GifImagePlugin.py#L134)

test.gif which was used to produce the bug: 
![test](https://user-images.githubusercontent.com/36000241/191572654-9e514be0-57b4-4668-b013-3da65559ab92.gif)

**Comment by radarhere** [comment] 2022-09-22 07:11
Hi. This has actually already been fixed in main by PR #6455 (so this is effectively a duplicate of #6454). It will be part of the next Pillow release, due out in late October.

**Closed** 2022-09-22 08:48 UTC
Labels: Duplicate, GIF
