### ISSUE TITLE
TIFF distorted or squeezed

### ISSUE THREAD

**Issue by maha-01** [python-pillow/Pillow#5581] opened 2021-07-05 15:28 UTC
I wanted to convert multi-page tiff fax documents to pdf. I have used PIL library to do this. But some documents appear to be distorted or squeezed after pdf conversion. I do not know why this happens .
Tiff file properties are: compression= group3
Dpi=(204,98)
Mode=1
Size=(1728,1151) 

My code:
```python
from PIL import Image,ImageSequence
img = Image.open("sample.tiff")
pages=[]
for page in ImageSequence.Iterator(img):
    Pages.append(page.convert("L"))
img.close()
pages[0].save("sample.pdf",save_all= True, append_images = pages[1:])
```
It would good if anyone can help on this to add any additional parameter if required to overcome the issue.

Thanks in advance

**Comment by radarhere** [comment] 2021-07-05 23:27
Would you be able to attach a copy of the TIFF?

**Comment by maha-01** [comment] 2021-07-06 04:49
> Would you be able to attach a copy of the TIFF?

No, sorry I could not attach a copy of it as it is a confidential fax document.
It would be great if could help on it using the details mentioned above or suggest me some other way to convert tiff to pdf for all the documents.

**Comment by radarhere** [comment] 2021-07-06 12:47
What is the mode of the original image? `img.mode`

You're performing various tasks with Pillow here - you're opening a TIFF, you're converting it to L mode, you're saving it as a multipage PDF. It would be good to narrow down which of those operations is not performing correctly. So -

If you just load all of the images and save them to PNG, do they output correctly?
```python
from PIL import Image,ImageSequence
img = Image.open("sample.tiff")
img.save("first.png")
i = 0
for page in ImageSequence.Iterator(img):
    page.save("page"+str(i)+".png")
    i += 1
```

If so, then do they all save correctly after when you convert to L?
```python
from PIL import Image,ImageSequence
img = Image.open("sample.tiff")
i = 0
for page in ImageSequence.Iterator(img):
    page.convert("L").save("pageL"+str(i)+".png")
    i += 1
```

If so, then do they all save correctly as individual PDFs?
```python
from PIL import Image,ImageSequence
img = Image.open("sample.tiff")
i = 0
for page in ImageSequence.Iterator(img):
    page.convert("L").save("pageL"+str(i)+".pdf")
    i += 1
```

**Comment by maha-01** [comment] 2021-07-07 06:22
from PIL import Image,ImageSequence
img = Image.open("sample.tiff")
img.save("first.png")
i = 0
for page in ImageSequence.Iterator(img):
    page.save("page"+str(i)+".png")
    i += 1

I have experimented the above script. The PNG file is not proper and it is not output correctly . It is not the same as tiff looks. The contents are squished and expanded and the file length & width also looks weired compared to tiff. But I checked the PNG properties , the size it is same as tiff i.e, (1728,1151)

The further scripts you have attached also behaves in the way same as above output.

**Comment by radarhere** [comment] 2021-07-07 08:12
Ok, so it sounds like the problem is not writing to a PDF, it's Pillow reading the TIFF image in the first place.

**Comment by maha-01** [comment] 2021-07-07 08:19
``

> Ok, so it sounds like the problem is not writing to a PDF, it's Pillow reading the TIFF image in the first place.


The other tiff documents I have works good after conversion to pdf. Still why some tiff documents behaves like this even that looks good in size, resolution etc.

**Comment by wiredfool** [comment] 2021-07-07 18:12
I'm going to bet that the pdf conversion isn't taking into account the non-square dpi (204,98) and is just copying the tiff in directly with essentially a square dpi for the bounding box.

**Comment by maha-01** [comment] 2021-07-08 04:19
> I'm going to bet that the pdf conversion isn't taking into account the non-square dpi (204,98) and is just copying the tiff in directly with essentially a square dpi for the bounding box

What is the solution for these kinds of documents and what i supposed to do in order to get a good pdf which looks same like tiff looks.

**Comment by radarhere** [comment] 2021-07-09 12:03
If the non-square DPI theory is correct, then maybe this will fix your problem?

```python
from PIL import Image, ImageSequence
img = Image.open("sample.tiff")
pages = []
for page in ImageSequence.Iterator(img):
	page = page.convert("L")
	dpi = page.info["dpi"]
	if isinstance(dpi, tuple) and len(dpi) == 2:
		x, y = dpi
		if x > y:
			page = page.resize((int(page.width * x / y), page.height), Image.ANTIALIAS)
		else:
			page = page.resize((page.width, int(page.height * y / x)), Image.ANTIALIAS)
    pages.append(page)
img.close()
pages[0].append("sample.pdf",save_all= True, append_images = pages[1:])
```

**Comment by radarhere** [comment] 2021-07-14 23:38
@maha-01 were you able to try my code?

**Comment by radarhere** [comment] 2021-07-18 07:39
Closing, as it isn't clear what the problem is. If I create a non-square DPI image on my machine, it works as I expect it would.

This can be re-opened if there is further discussion.

**Closed by radarhere** 2021-07-18 07:39 UTC
Labels: Awaiting OP Action
