### ISSUE TITLE
RLE8 compression support for BMP images

### ISSUE THREAD

**Issue by bbotezatu** [python-pillow/Pillow#3427] opened 2018-10-22 01:52 UTC
### What did you do?
Attempted to open an RLE8-compressed bitmap image.
### What did you expect to happen?
The image to display correctly.
### What actually happened?
An IOError("Unsupported BMP compression (%d)" % file_info['compression']) was thrown.

We try to open the image in our main program:
```def load_image(self, path, canvas):
        try:
            image = Image.open(path)
            ...
```
This calls the BmpImageFile class from BmpImagePlugin.py, which attempts to display the file according to the compression types listed in the dictionary on line 63: 
```
COMPRESSIONS = {
        'RAW': 0,
        'RLE8': 1,
        'RLE4': 2,
        'BITFIELDS': 3,
        'JPEG': 4,
        'PNG': 5
    }
    RAW, RLE8, RLE4, BITFIELDS, JPEG, PNG = 0, 1, 2, 3, 4, 5
```
After reading header data, the program continues; on [line 158](https://github.com/python-pillow/Pillow/blob/master/src/PIL/BmpImagePlugin.py#L158), an if statement checks:
```
if file_info['compression'] == self.BITFIELDS:
```
which evaluates to false. So, the program then jumps to [line 190](https://github.com/python-pillow/Pillow/blob/master/src/PIL/BmpImagePlugin.py#L190), where it checks whether the file's compression type is RAW:
```
elif file_info['compression'] == self.RAW:
```
 which also evaluates to false. This causes the program to jump the code block to [line 193](https://github.com/python-pillow/Pillow/blob/master/src/PIL/BmpImagePlugin.py#L193), where the exception is thrown, and causes our main program to fail.
```
raise IOError("Unsupported BMP compression (%d)" %
```
The code that ultimately throws this exception is found at line 194, in the [BmpImagePlugin source.](https://github.com/python-pillow/Pillow/blob/master/src/PIL/BmpImagePlugin.py)

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.6.3
* Pillow: 5.2.0

[testImages.zip](https://github.com/python-pillow/Pillow/files/2498557/testImages.zip)

**Comment by hugovk** [comment] 2018-10-22 10:38
Closing as a duplicate of #3425, caused by today's GitHub data storage problems:

![image](https://user-images.githubusercontent.com/1324225/47288660-b5e72000-d5ff-11e8-9b18-d34d4d57ec22.png)

**Closed by hugovk** 2018-10-22 10:38 UTC
Labels: Duplicate

**Comment by hugovk** [comment] 2018-10-22 12:51
Closing as a duplicate of #3425, caused by today's GitHub data storage problems:

![image](https://user-images.githubusercontent.com/1324225/47288660-b5e72000-d5ff-11e8-9b18-d34d4d57ec22.png)
