### ISSUE TITLE
Release 5.2.0 not available for Linux Python 3.7

### ISSUE THREAD

**Issue by jcea** [python-pillow/Pillow#3224] opened 2018-07-02 14:00 UTC
Pillow 5.2.0 released Yesterday. I upgraded my Python 2.7 and 3.6 fine, but my Python 3.7 is stuck in Pillow 5.1.0.

There is no wheel for Python 3.7, neither a source code release I can compile myself.

Probably related to issue #3154 and #3074.

UPDATE: There is a source release now. Compiled and installed fine under Ubuntu 16.04.

**Comment by hugovk** [comment] 2018-07-02 15:54
Because Python 3.7 is so new (less than a week old), not all the Linux/Mac wheel building dependencies are quite ready (#3074). We'll add the wheels when possible. 

Good to hear the source release works for you now. Closing this as a duplicate of https://github.com/python-pillow/Pillow/issues/3074.

**Closed by hugovk** 2018-07-02 15:54 UTC
Labels: Linux, Release
