### ISSUE TITLE
Pillow 5.2.0 missing PIL Image 

### ISSUE THREAD

**Issue by kurt-rhee** [python-pillow/Pillow#3439] opened 2018-10-25 15:38 UTC
### What did you do?

Imported pillow 5.2.0 via conda

### What did you expect to happen?

Bokeh graph would show

### What actually happened?

Bokeh shows exception, missing PIL.Image

### What are your OS, Python and Pillow versions?

* OS: Windows 7
* Python: 3.7
* Pillow: 5.2.0

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```
from PIL import Image
```

**Comment by hugovk** [comment] 2018-10-25 15:45
Please can you include the full error traceback message?

This could be a duplicate of https://github.com/python-pillow/Pillow/issues/2945. See https://github.com/python-pillow/Pillow/issues/2945#issuecomment-356905216 for a workaround, or see https://github.com/conda/conda/issues/7626 for a proposed Conda fix you can test.

**Comment by kurt-rhee** [comment] 2018-11-07 23:00
Hello I have attached the full error traceback message as an image.

I am using conda version 4.5.11 so I am not sure if conda/conda#7626 will work for me.  

![image](https://user-images.githubusercontent.com/33131958/48166576-d371e600-e29d-11e8-940f-f33bf29dff63.png)

**Comment by kurt-rhee** [comment] 2018-11-07 23:18
I get the same error message when pillow is installed with pip instead of conda

**Comment by radarhere** [comment] 2018-11-17 00:49
What happens when you try `from PIL import Image`?

**Closed** 2019-02-11 14:53 UTC
