### ISSUE TITLE
The headers or library files could not be found for zlib

### ISSUE THREAD

**Issue by Zs-1010** [python-pillow/Pillow#4967] opened 2020-10-12 11:56 UTC
currently using 3.9 python version, pip 20.0
.....my last resort was to downgrade my python version to 3.8 however, is there a way I will not do this? TIA

Collecting Pillow==7.0.0
  Downloading https://files.pythonhosted.org/packages/39/47/f28067b187dd664d205f75b07dcc6e0e95703e134008a14814827eebcaab/Pillow-7.0.0.tar.gz (38.2MB)
     |████████████████████████████████| 38.2MB 6.4MB/s
Installing collected packages: Pillow
    Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
.....
 running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\PIL
    copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\features.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Image.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TarIO.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_binary.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_util.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_version.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\__init__.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\__main__.py -> build\lib.win-amd64-3.9\PIL
    running egg_info
    writing src\Pillow.egg-info\PKG-INFO
    writing dependency_links to src\Pillow.egg-info\dependency_links.txt
    writing top-level names to src\Pillow.egg-info\top_level.txt
    reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
    running build_ext

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

**Comment by radarhere** [comment] 2020-10-12 12:01
Hi. If you wait a few days, Pillow 8.0.0 is due to be released on October 15, which will include support for Python 3.9.

Otherwise, you could download Pillow‑7.2.0‑cp39‑cp39‑win_amd64.whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow.

Or you if you want to compile from source, https://pillow.readthedocs.io/en/latest/installation.html#building-on-windows is your starting point.

Or are you asking specifically for Pillow 7.0?

**Comment by Zs-1010** [comment] 2020-10-12 12:04
nope, you just answered my question, oh gee thanks a lot!

**Comment by hugovk** [comment] 2020-10-12 12:09
Let's close this as a duplicate of https://github.com/python-pillow/Pillow/issues/4960.

**Closed by hugovk** 2020-10-12 12:09 UTC
Labels: Installation, Windows
