### ISSUE TITLE
Using specified font to draw text would sometimes fail with segfault

### ISSUE THREAD

**Issue by kenziefc** [python-pillow/Pillow#3252] opened 2018-07-14 06:47 UTC
### What did you do?

Adding text with specified font to Pillow created canvas

### What did you expect to happen?

Text with specified font to be added consistently

### What actually happened?

The process fails sometimes, sometimes runs without a problem. When font=<font name> was removed from ImageDraw.Draw.text parameter, the process runs without a problem.

### What versions of Pillow and Python are you using?

Pillow 5.2.0
python 3.6.6

```python

def draw_quest_descriptions(quests_dict, c, filename="desc.png", 
        max_height=0):
    """ Create an image of quest descriptions
    which can be combined with quest dependencies later """

    def indent_helper(quest_task, max_length=50):
        string = quest_task.replace('\n', '')
        indented_string = ""
        for i in range(len(string)):
            indented_string += string[i]
            if i % max_length == 0 and not i == 0:
                indented_string += '\n'

        return indented_string

    quests = []
    for quest_id, quest_deps in quests_dict.items():
        quests.append(quest_id)
        quests.extend(quest_deps)

    quests = sorted(list(set(quests)))
    quests = list(filter(None, quests))

    quest_desc = {}
    total_lines = 0
    for quest in quests:
        c.execute("""SELECT quest_title, quest_task FROM quest
                     WHERE quest_id == (?)""", (quest.upper(),))
        q_title, q_task = c.fetchone()
        q_title_indented = indent_helper(q_title, max_length=50)
        q_task_indented = indent_helper(q_task, max_length=56)
        quest_desc[quest] = q_title_indented, q_task_indented

        total_lines += 3 \
                + q_title_indented.count('\n') \
                + q_task_indented.count('\n')

    # Font size
    font_size = 20
    
    # Spacing between texts
    line_spacing = font_size + 10

    # Calculate total image length
    total_image_length = total_lines * line_spacing

    # Calculate how much width do we need to fit all descriptions
    total_pages = math.ceil(total_image_length / max_height)
    if total_pages <= 1:
        total_pages = 1

    image_page_width = 39 * font_size
    image_width = total_pages * image_page_width

    # Add 200 just in case there are long quest tasks
    image_length = max_height + 200

    img = Image.new("RGB", (image_width, image_length), color="white")
    print("Created canvas {}x{}".format(image_width, image_length))
    font_location = os.path.dirname(os.path.abspath(__file__))
    default_font = ImageFont.truetype(
            font_location + "/SourceHanSansJP-Regular.otf", font_size)
    d = ImageDraw.Draw(img)

    # Color presets
    black = (0, 0, 0)
    red = (231, 76, 60)
    blue = (52, 152, 219)

    # Offsets where the text will be printed
    y_offset = 1
    x_offset = 30
    for quest, desc in quest_desc.items():
        print("Printing {} at {}, {}".format(quest, x_offset, y_offset))
        q_title, q_task = desc

        d.text((x_offset, y_offset), quest, fill=black, font=default_font)
        y_offset += line_spacing

        d.text((x_offset, y_offset), q_title, fill=red, font=default_font)
        y_offset += line_spacing * (1 + q_title.count('\n'))

        d.text((x_offset, y_offset), q_task, fill=blue, font=default_font)
        y_offset += line_spacing * (1 + q_task.count('\n'))

        if y_offset >= max_height:
            y_offset = 1
            x_offset += image_page_width

    img.save(filename)

```

Fail screenshot:
![screenshot](https://user-images.githubusercontent.com/11149264/42721865-1193b7be-8796-11e8-8ba6-168f95ed2bc5.png)

Success screenshot:
![screenshot](https://user-images.githubusercontent.com/11149264/42721879-422ad786-8796-11e8-8b13-d08d76179419.png)

Final result if success (Pillow generated decription texts for the tree graph):
![final-f46](https://user-images.githubusercontent.com/11149264/42721929-e7195056-8796-11e8-8a23-5c83c40063ff.png)

**Comment by radarhere** [comment] 2018-08-09 09:55
Using https://github.com/tkiapril/source-fonts/blob/master/SourceHanSansJP-Regular.otf, and running the following script -

```
from PIL import Image, ImageDraw, ImageFont
for i in range(1000):
	im = Image.new("RGB", (1000, 1000), "#f00")
	default_font = ImageFont.truetype('SourceHanSansJP-Regular.otf', 48)
	d = ImageDraw.Draw(im)
	quest = "Font draw test"
	black = (0, 0, 0)
	y_offset = 1
	x_offset = 30
	d.text((x_offset, y_offset), quest, fill=black, font=default_font)
	im.save('out.png')
```

I am unable to replicate the problem. So closing, due to that and lack of further information.

**Comment by vispeal** [comment] 2018-08-13 09:02
I also get this error use pillow 5.2.0 when using font.
font
bold font
open image
open draw
INFO 2018-08-13 16:53:58,778 radio_transcode:231 end draw count
Segmentation fault

**Comment by radarhere** [comment] 2018-08-13 09:56
I am able to run your script without problems on macOS. What operating system are you using?

My successful run may be due to the different images that I used as input however. Are you able to make your example self-contained by providing 4f9b0c2d7ab03a13de1f813a07cf9313.png and radio_bg.png?

Are you able to reproduce this with fonts other than PingFang.ttc, or is it just that font?

Note to others: PingFang.ttc can be found at https://github.com/ZTfer/weui-sketch/blob/master/font/PingFang.ttc

**Comment by vispeal** [comment] 2018-08-13 10:02
OS:
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core

**Comment by vispeal** [comment] 2018-08-13 10:15
4f9b0c2d7ab03a13de1f813a07cf9313.png is http://radio.klm123.com/share/code/4f9b0c2d7ab03a13de1f813a07cf9313.png
radio_bg.png is http://klm-output-radio.oss-cn-beijing.aliyuncs.com/share/image/test0.png
I encounter this problem with any font.

**Comment by radarhere** [comment] 2018-09-01 10:13
I am still able to run your script without problems on macOS.

How did you install Pillow? Which version of Python are you using?

**Comment by radarhere** [comment] 2018-09-16 05:05
Closing to due lack of response. Feel free to comment again for this to be re-opened.

**Comment by Sanny26** [comment] 2018-12-11 12:12
When I use the following function to render, I get seg fault.

```
def synthesizeImage(rText):
    font_path = 'SakalBharati.ttf'
    rText.encode('utf-8')
    rFontIdx = 0
    font = ImageFont.truetype(font_path, 48)
    w, h = font.getsize(rText)
    if(w>384):
        font = ImageFont.truetype(font_path, 32)
        w, h = font.getsize(rText)
    image = Image.new('L', (384,128), 'white')
    brush = ImageDraw.Draw(image)
    brush.text((0, 0), rText, font=font, fill=0)
    return
```
I don't get the error always and the code works perfectly. Some times I get Segmentation fault (core dumped) error and sometimes I get an OSError followed by Seg fault. (Error screen shot here: https://imgur.com/a/1md496O)

Font file used : https://www.cdac.in/index.aspx?id=dl_sakal_bharati_font
I tried with other fonts as well and the error still occurs.
I'm trying to render Indian languages, so I have installed pillow with libraqm support.
Running the code using python3

I reassign `font` variable with new parameters in the above function. Can't I reassign in this manner?
The error seems to vanish without the if block in the above code.

**Comment by radarhere** [comment] 2018-12-14 13:31
What operating system are you using? Would you be able to provide the text that you are passing into the function?

There shouldn't be an error due to reassigning an existing variable. If it disappears without the `if` block, then I would suspect it is happening for size 48 font but not size 32 font.

**Comment by radarhere** [comment] 2018-12-24 01:52
Also, how did you install Pillow?

**Comment by radarhere** [comment] 2019-01-01 07:05
@Sanny26 I've just realised that your problem sounds identical to #3066. So I'm closing this issue, feel free to contribute to the discussion over there

**Closed by radarhere** 2019-01-01 07:05 UTC

**Comment by dhruvsatyapanthi007** [comment] 2019-04-06 15:25
I am getting issue with segmentation fault when I call font.getsize()

**Comment by radarhere** [comment] 2019-04-06 20:40
@dhruvsatyapanthi007 could you open a new issue, ideally with a self-contained script to demonstrate the problem, and which font, operating system, Python and Pillow version you are using?
