### ISSUE TITLE
ImageDraw.text segfaults when TTF font is resized to certain values

### ISSUE THREAD

**Issue by pigfrown** [python-pillow/Pillow#5092] opened 2020-12-13 19:56 UTC
### What did you do?

Attempting to draw text on an image using TTF font

### What did you expect to happen?

Text will be drawn on image

### What actually happened?

Segfault when font is not resized to particular sizes (see code comments)

### What are your OS, Python and Pillow versions?

* OS: Linux
* Python: Python 3.9.0
* Pillow: Pillow==8.0.1

The font used was DejaVuSans-ExtraLight.ttf (copied into working directory as font.ttf). I tried it with another DejaVu TTF font and the same thing happened.

```python
import os
import tempfile
from PIL import Image, ImageDraw, ImageFont

def segfaults_sometimes(path):
    font_path = os.path.join(os.path.dirname(__file__), "font.ttf")

    #Font size 24 never seems to segfault
    #Font size 25 segfaults pretty much everytime
    #Font size 200 segfaults half the time
    font_size = 25

    font = ImageFont.truetype(font_path, font_size)

    img = Image.open(path)
    draw = ImageDraw.Draw(img)
    text = "this is some text :)"

    draw.text((10, 10), text, (255,0,0), font=font)
    tmppath = tempfile.mktemp(suffix=".jpg")
    img.save(tmppath)
    return tmppath
```

**Comment by nulano** [comment] 2020-12-13 20:23
I can't reproduce on Windows.

Can you please provide your FreeType version and whether you have Raqm installed?
You can get this information by running `python -m PIL` or using the `PIL.features.pilinfo(supported_formats=False)` function.

**Comment by pigfrown** [comment] 2020-12-13 21:57
```python -m PIL
--------------------------------------------------------------------
Pillow 8.0.1
Python 3.9.0 (default, Oct  7 2020, 23:09:01)
       [GCC 10.2.0]
--------------------------------------------------------------------
Python modules loaded from /usr/lib/python3.9/site-packages/PIL
Binary modules loaded from /usr/lib/python3.9/site-packages/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 8.0.1
*** TKINTER support not installed
--- FREETYPE2 support ok, loaded 2.10.4```

**Comment by pigfrown** [comment] 2020-12-13 23:07
I played around a bit more and can only seem to reproduce this when I call ```segfaults_sometimes``` from within ipython. When I run directly from the command line with ```python -c``` it never seems to segfault :shrug:

**Comment by pigfrown** [comment] 2020-12-13 23:17
related ? https://github.com/python-pillow/Pillow/issues/3066

**Comment by nulano** [comment] 2020-12-14 00:03
Yes, this is probably a duplicate of #3066.

**Closed** 2020-12-14 04:16 UTC
