### ISSUE TITLE
Multipage TIFF operations broken

### ISSUE THREAD

**Issue by juhaszp95** [python-pillow/Pillow#5640] opened 2021-07-27 15:30 UTC
**What did you do?**

```python
from PIL import Image, ImageSequence

im = Image.open("image.tif")

for i, page in enumerate(ImageSequence.Iterator(im)):
    page.save("page%d.png" % i)
```

**What did you expect to happen?**

image.tif is a 25-page TIFF file. I expected that this would save the 25 pages separately as png files. Up until Pillow 8.1.2 this works correctly, but beginning with Pillow 8.2.0 (I'm currently using 8.3.1) this seems to just break Python. Not just save, but many other operations (e.g. getpixel) also seem to produce the same issue.

**What actually happened?**
- python.exe crashes without giving any errors

**What are your OS, Python and Pillow versions?**

OS: Windows 10
Python: 3.8.10 (as part of a standard Anaconda installation)
Pillow: 8.3.1 (as part of a standard Anaconda installation)

**Comment by radarhere** [comment] 2021-07-27 22:28
Hi. If I run your code with [one of our test images](https://github.com/python-pillow/Pillow/blob/master/Tests/images/multipage.tiff), it works. Would you be able to upload the image that you're having trouble with?

**Comment by juhaszp95** [comment] 2021-07-27 23:15
Yes - please see below. As GitHub doesn't support adding .tif files directly, I put it in a .zip archive.

[image.zip](https://github.com/python-pillow/Pillow/files/6889194/image.zip)

**Comment by radarhere** [comment] 2021-07-28 01:06
I'm not able to reproduce this locally on my macOS machine. I guess this may be an issue specific to Windows/Anaconda.

**Comment by kmilos** [comment] 2021-07-28 08:08
Are you using libtiff + Pillow from defaults or conda-forge channels?

**Comment by juhaszp95** [comment] 2021-07-28 08:41
Hi, I'm using libtiff + Pillow from the default channel (as that comes with the default Anaconda installation). Libtiff is version 4.2.0, which works fine with Pillow 8.1.2 but not with Pillow >= 8.2.0.

**Comment by kmilos** [comment] 2021-07-28 08:43
Please try creating a test environment using the conda-forge channel and confirm it is working.

**Comment by juhaszp95** [comment] 2021-07-28 09:06
If I switch only libtiff to conda-forge (which upgrades it to 4.3.0 from 4.2.0) it still isn't working. If both Pillow and libtiff are installed from conda-forge, it is working (which seems surprising as pillow is the same version in both repositories). I can't seem to create an environment where only Pillow is from conda-forge but libtiff is from default...

**Comment by kmilos** [comment] 2021-07-28 09:30
> If I switch only libtiff to conda-forge (which upgrades it to 4.3.0 from 4.2.0) it still isn't working.

Yes, because libtiff I/O scheme between default and conda-forge is now identical (Unix I/O) - this wasn't the case some time ago when default libtiff was using Win32 I/O (libtiff <= 4.1.0 or 4.0.10 I think)

> If both Pillow and libtiff are installed from conda-forge, it is working (which seems surprising as pillow is the same version in both repositories)

This is not surprising because each repository might add its own specific patches to the package according to their internal policies (security critical fix, important feature bugfix until next version is released, compatibility fixes w/ other packages in that repository, enabled features, etc.) so they will likely differ in some subtle way even though the version is "the same". This is the case here, [conda-forge disables Pillow's Win32 I/O by a patch to match their own libtiff package](https://github.com/conda-forge/pillow-feedstock/tree/master/recipe), while Anaconda default obviously does not, and the bug is within their repository.

See also https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels

**Comment by juhaszp95** [comment] 2021-07-28 09:37
I see, thanks. I'll try to report it there...

**Comment by kmilos** [comment] 2021-07-28 09:43
> Specifically, what would be needed on their side? To change the recipe for Pillow on the default channel so that it matches the conda-forge channel?

Specifically, to keep libtiff and Pillow in sync wrt to I/O scheme. How they do that is up to them.

**Comment by kmilos** [comment] 2021-07-30 09:05
@juhaszp95 Thanks for passing on the bug report!

**Comment by radarhere** [comment] 2021-08-01 06:28
@juhaszp95 we've established that if you use conda-forge, the latest Pillow works for you. Unless there's anything further, do you mind if we close this and leave the problem as https://github.com/ContinuumIO/anaconda-issues/issues/12546?

**Comment by juhaszp95** [comment] 2021-08-01 10:26
No, not at all, I think that's right. I haven't managed to trigger a reponse from them so far, but at least conda-forge is an interim solution. Thanks for the help!

**Closed** 2021-08-01 10:27 UTC
Labels: TIFF, Windows
