### ISSUE TITLE
Can't load module Image

### ISSUE THREAD

**Issue by johnny7johnson** [python-pillow/Pillow#3452] opened 2018-11-05 11:33 UTC
### What did you do?
I tried to import module Image by callling
`from PIL import Image`

### What did you expect to happen?
Importing the Image module

### What actually happened?
Error message:
`ImportError: DLL load failed: The specified procedure could not be found.`

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.6.6
* Pillow: 5.3.0

I'm using the Anaconda distribution of Python 3.6.6. When trying to import Image the Error rises. Importing other modules from PIL is working fine. 
There is a very similar post on [stackoverflow](https://stackoverflow.com/questions/43264773/pil-dll-load-failed-specified-procedure-could-not-be-found) but downgrading Pillow to different versions didn't work for me.

**Comment by radarhere** [comment] 2018-11-06 07:49
How did you install Pillow?

**Comment by johnny7johnson** [comment] 2018-11-06 09:04
I did it with conda
`conda install pillow`

**Comment by 2005ai** [comment] 2018-11-06 23:44
I have the same issue... Any suggestions would be highly appreciated

**Comment by IvoMerchiers** [comment] 2018-11-07 13:06
I followed the suggestion in #2945 of using pip to reinstall the package:

`conda uninstall pillow`
`pip install pillow`

This seemed to resolve the issue.

**Comment by hugovk** [comment] 2018-11-20 13:14
Closing this as a duplicate of https://github.com/python-pillow/Pillow/issues/2945, looks this a Conda bug: https://github.com/conda/conda/issues/7626.

**Closed by hugovk** 2018-11-20 13:14 UTC
Labels: Windows
