### ISSUE TITLE
`Too many open files` error

### ISSUE THREAD

**Issue by indirectlylit** [python-pillow/Pillow#1237] opened 2015-05-20 22:38 UTC
## Issue

While generating thumbnails of a few hundred large image files, I'm getting a `IOError: [Errno 24] Too many open files`. My understanding is that the [`Image.load`](http://pillow.readthedocs.org/en/latest/reference/Image.html#PIL.Image.Image.load) method should "close the file associated with the image", so it's not clear to me why this happens. That said, this could certainly be user error.

The problem looks similar to [this question on stackoverflow](http://stackoverflow.com/questions/29234413/too-many-open-files-error-when-opening-and-loading-images-in-pillow#).

## System

* OSX 10.9.5
* Python 2.7.9
* Pillow 2.8.1

## Reproducing

```
Python 2.7.9 (default, Feb 10 2015, 03:29:19) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import glob
>>> names = glob.glob('*.JPG')
>>> len(names)
415
>>> thumbs = {}
>>> from PIL import Image
>>> for n in names:
...   thumbs[n] = Image.open(n)
...   thumbs[n].load()
...   thumbs[n].thumbnail((300, 300))
... 
<PixelAccess object at 0x108156110>
<PixelAccess object at 0x108156170>
<PixelAccess object at 0x108156190>
<PixelAccess object at 0x1081561b0>
<PixelAccess object at 0x1081561d0>
<PixelAccess object at 0x1081561f0>
```

*(244 similar lines omitted)*

```
<PixelAccess object at 0x10b7fd110>
<PixelAccess object at 0x10b7fd130>
<PixelAccess object at 0x10b7fd150>
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/d/PythonEnvs/main/lib/python2.7/site-packages/PIL/Image.py", line 2248, in open
IOError: [Errno 24] Too many open files: 'DSC00271.JPG'
```

## Workaround

I was able to work around this issue by creating a copy of the image object, similar to this:

```
for n in names:
    img = Image.open(n)
    thumbs[n] = img.copy()
    img.close()
    thumbs[n].thumbnail((300, 300))
```

**Comment by radarhere** [comment] 2015-05-21 01:33
You may be interested in #1144

**Comment by aclark4life** [comment] 2015-06-28 19:33
Duplicate of #1144

**Closed by aclark4life** 2015-06-28 19:33 UTC

**Comment by webeng** [comment] 2016-01-18 14:43
Workaround works.

**Comment by maxvonhippel** [comment] 2016-12-25 00:45
Workaround working fine for me, with over 3000 frames.
