### ISSUE TITLE
problems on converting a png to jpg where the source png is mode I

### ISSUE THREAD

**Issue by Henner** [python-pillow/Pillow#2597] opened 2017-06-27 15:31 UTC
### What did you do?
im.convert('RGBA') of an png image in I mode
save as JPEG

### What did you expect to happen?
after saving it looks still the same

### What actually happened?
only the borders exist of black shapes exist

### What versions of Pillow and Python are you using?
pillow==4.1.1
python 2.7.9

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
im = Image.open('/tmp/test.png')
new_im = im.convert('RGBA')
new_im.save('/tmp/test.jpg', 'JPEG', quality=100)
```
Source-Image
![test](https://user-images.githubusercontent.com/1674487/27595950-6a2d3bf8-5b5e-11e7-9ef2-5c3fd6cf4c4b.png)
Resulting-Image
![test](https://user-images.githubusercontent.com/1674487/27596028-9e098396-5b5e-11e7-8c84-0ccca79b0440.jpg)

**Comment by wiredfool** [comment] 2017-06-27 16:27
This is a duplicate of #2574, with the possible complication of an alpha channel as well.

**Closed** 2017-08-17 13:59 UTC
