### ISSUE TITLE
"ValueError: unknown raw mode for given image mode" when loading TIFF

### ISSUE THREAD

**Issue by conceptfarm** [python-pillow/Pillow#8636] opened 2024-12-29 01:29 UTC
### What did you do?
I am trying to resize a tiff file with an alpha channel

### What did you expect to happen?
Have a resized image

### What actually happened?
I got a ValueError: unknown raw mode for given image mode error

### What are your OS, Python and Pillow versions?

* OS: Windows 10 21H2
* Python: 3.10.6
* Pillow: 11.1.0

```text
python3 -m PIL.report

--------------------------------------------------------------------
Pillow 11.0.0
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
--------------------------------------------------------------------
Python executable is C:\Python3106\python.exe
System Python files loaded from C:\Python3106
--------------------------------------------------------------------
Python Pillow modules loaded from C:\Python3106\lib\site-packages\PIL
Binary Pillow modules loaded from C:\Python3106\lib\site-packages\PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 11.0.0
--- TKINTER support ok, loaded 8.6
--- FREETYPE2 support ok, loaded 2.13.3
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.4.0
--- JPEG support ok, compiled for libjpeg-turbo 3.0.4
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2
--- ZLIB (PNG/ZIP) support ok, loaded 1.3.1
--- LIBTIFF support ok, loaded 4.6.0
*** RAQM (Bidirectional Text) support not installed
*** LIBIMAGEQUANT (Quantization method) support not installed
*** XCB (X protocol) support not installed
--------------------------------------------------------------------
```

```python
from PIL import Image
file = r'c:\temp\test.tif'
imgObject = Image.open(file)
outImageObject = imgObject.resize((800, 800))
```
Traceback of the error :
```python
Traceback (most recent call last):
  File "c:\Python38\Projects\poliigonBrowser_v2.4\test3.py", line 20, in <module>
    outImageObject = imgObject.resize((800, 800))
  File "C:\Python3106\lib\site-packages\PIL\Image.py", line 2335, in resize
    return self.copy()
  File "C:\Python3106\lib\site-packages\PIL\Image.py", line 1282, in copy
    self.load()
  File "C:\Python3106\lib\site-packages\PIL\TiffImagePlugin.py", line 1277, in load
    return self._load_libtiff()
  File "C:\Python3106\lib\site-packages\PIL\TiffImagePlugin.py", line 1345, in _load_libtiff
    decoder = Image._getdecoder(self.mode, "libtiff", args, self.decoderconfig)
  File "C:\Python3106\lib\site-packages\PIL\Image.py", line 442, in _getdecoder
    return decoder(mode, *args + extra)
ValueError: unknown raw mode for given image mode
```
[Link to the image to reproduce](https://github.com/user-attachments/files/18268159/test.zip)

**Comment by radarhere** [comment] 2024-12-29 06:02
The problem isn't actually to do with resizing. Once Pillow images are opened, data still needs to be read from the file. It is that reading of the data (`self.load()`) that is causing the problem.

I've created https://github.com/python-pillow/Pillow/pull/8637 to resolve this.

**Comment by radarhere** [comment] 2024-12-29 06:06
Also, I don't believe there is an alpha channel. There is a fourth channel, but it is unused. I just want to make sure you're not expecting transparency in the final result.

If my PR is merged, then
```python
from PIL import Image
im = Image.open("test.tif")
im.save("out.png")
```
will give
![out](https://github.com/user-attachments/assets/9a71855b-2da3-4fac-b484-62ddbf0f3752)

**Closed** 2024-12-29 19:35 UTC
Labels: TIFF

**Comment by conceptfarm** [comment] 2024-12-29 23:44
> Also, I don't believe there is an alpha channel. There is a fourth channel, but it is unused. I just want to make sure you're not expecting transparency in the final result.
> 
Not sure about what is exactly considered an alpha channel here, but I consider 4th channel with RGB channels present as alpha in an RGBA supported file formats. The image has a fully white/opaque 4th/alpha channel. The result shown is correct.

**Comment by radarhere** [comment] 2024-12-30 00:06
If you run `tiffinfo test.tif | grep Extra`, you can see `Extra Samples: 1<unspecified>`

https://web.archive.org/web/20240228161252/https://www.awaresystems.be/imaging/tiff/tifftags/extrasamples.html states
> If an extra sample is used to encode information that has little or nothing to do with alpha, ExtraSample=0 (EXTRASAMPLE_UNSPECIFIED) is recommended.
