### ISSUE TITLE
P3 ppm file format support (the non binary version of ppm that is very common)

### ISSUE THREAD

**Issue by wegfawefgawefg** [python-pillow/Pillow#4999] opened 2020-10-20 18:07 UTC
**What did you do?**
try to open the non binary versions of ppm files p1,p2,p3

**What did you expect to happen?**
to load the file

**What actually happened?**
it errors. you cant load p1,p2,p3 with pillow because pillow does not support them.

There are a lot of ppm p3 format files on the internet
Many graphics programming tutorials work with the non binary version.

I have found others complaining about this.
https://stackoverflow.com/questions/4101576/importing-ppm-images-with-python-and-pil-module

Its a dead simple image format and support for loading a text ppm and writing one 
could be added really easily.

i volunteer if anyone is interested.

**Comment by CodeMarbles15** [comment] 2020-10-20 18:10
Hmm, definitely should be added. Easy file format.

**Comment by radarhere** [comment] 2020-10-20 21:34
This looks like a duplicate of #860

**Comment by wegfawefgawefg** [comment] 2020-10-20 23:57
that issue is 6 years old and dead so.

lets make ascii ppm's happen!

**Closed** 2022-06-14 12:24 UTC

**Comment by wegfawefgawefg** [comment] 2022-07-07 12:06
thanks you're a god
