### ISSUE TITLE
Apparently image.convert("L").resize((x, y), Image.NEAREST) changes between version 3.3.1 and 3.3.2?

### ISSUE THREAD

**Issue by fake-name** [python-pillow/Pillow#2321] opened 2016-12-30 05:16 UTC
### What did you do?

```
image = Image.open(io.BytesIO(fCont))
image = image.convert("L").resize((HASH_SIZE, HASH_SIZE), Image.NEAREST)
pixels = numpy.array(image.getdata(), dtype=numpy.float).reshape((HASH_SIZE, HASH_SIZE))

# Calculate the md5 of the resulting image, to verify the libraries are consistent in their resize behaviour.

pxStr = str(list(pixels.flatten()))
fMD5 = hashlib.md5()
fMD5.update(pxStr.encode("utf-8"))
pxHexHash = fMD5.hexdigest()

print("image: {} Hashes: ({} - {}), ({} - {})".format(imName, contHexHash, hashes[0], pxHexHash, hashes[1]))

self.assertEqual(contHexHash, hashes[0])
self.assertEqual(pxHexHash, hashes[1])
```

### What did you expect to happen?

Expect that `image.convert("L").resize((x, y), Image.NEAREST)` would be consistent, at least between minor version numbers

### What actually happened?

The MD5 of the image bytes changes between pillow 3.3.1 and 3.3.2, which makes my units tests fail. All versions after 3.3.1 appear to be different (thank raptor jesus I thought to validate the libraries are consistently loading the images I'm feeding into later processing). I get a bunch of later failures as a result.

### What versions of Pillow and Python are you using?
Python 3.5.2, pillow 3.3.1 and 3.3.2

------

Actual test script is [here](https://github.com/fake-name/IntraArchiveDeduplicator/blob/master/Tests/Test_ImLoad.py). Images for the test script are [here](https://github.com/fake-name/IntraArchiveDeduplicator/tree/master/Tests/testimages), or you can just clone the whole repo.

My assumption is that this sort of thing shouldn't change without a major revision number increment, but apparently not. A minor version number would be odd, but *patch release* breaking previous expectations is just crazy.

**Comment by fake-name** [comment] 2016-12-30 05:27
Additionally, the [changelog for 3.3.2](https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#332-2016-10-03) only mentions 2 changes, both of which are security hardening changes, so I have *no* idea how they caused the basic image functionality to change.

**Comment by radarhere** [comment] 2016-12-30 05:48
You don't define `contHexHash` in your snippet, so I presume that you're talking about `pxHexHash`.

I am unable to replicate this, testing with the test suite image hopper_bw_500.png and `HASH_SIZE` 100.

Would you be able to test the script with that file and that variable? Or provide a sample image and sample `HASH_SIZE` value?

**Comment by fake-name** [comment] 2016-12-30 06:08
@radarhere - They're in the link https://github.com/fake-name/IntraArchiveDeduplicator/blob/master/Tests/Test_ImLoad.py

Note that it only happens for some images, apparently.

**Comment by fake-name** [comment] 2016-12-30 06:19
Test output with 3.3.2:

```
durr@mscrape:/media/Storage/Scripts/Deduper/wat$ python3 -m nose --exe
F
======================================================================
FAIL: test_hashImage1 (Test_ImLoad.TestSequenceFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/Storage/Scripts/Deduper/wat/Test_ImLoad.py", line 76, in test_hashImage1
    imgn, hashtype, hashes[0], hashes[1]
AssertionError: '9e0e86672909bdb35ac06b8730c8512d' != '83aec17425e9d6720bc27efde7d0f2d0'
- 9e0e86672909bdb35ac06b8730c8512d
+ 83aec17425e9d6720bc27efde7d0f2d0
 : Mismatch in lolcat-crocs.jpg of image resize hash - (9e0e86672909bdb35ac06b8730c8512d, 83aec17425e9d6720bc27efde7d0f2d0)
-------------------- >> begin captured stdout << ---------------------
image: Lolcat_this_is_mah_job.png Hashes: (1268e704908cc39299d73d6caafc23a0 - 1268e704908cc39299d73d6caafc23a0), (822c823d4e3bd49a35da06a86cb6231e - 822c823d4e3bd49a35da06a86cb6231e)
image: lolcat-crocs.jpg Hashes: (6d0a977694630ac9d1d33a7f068e10f8 - 6d0a977694630ac9d1d33a7f068e10f8), (9e0e86672909bdb35ac06b8730c8512d - 83aec17425e9d6720bc27efde7d0f2d0 MISMATCH)
image: dangerous-to-go-alone.jpg Hashes: (dcd6097eeac911efed3124374f44085b - dcd6097eeac911efed3124374f44085b), (5217b1c8f8bac745bea087c1c282b9ff - 407bc3580af7a999b340145a997e5bc7 MISMATCH)
image: Lolcat_this_is_mah_job.jpg Hashes: (d9ceeb6b43c2d7d096532eabfa6cf482 - d9ceeb6b43c2d7d096532eabfa6cf482), (822c823d4e3bd49a35da06a86cb6231e - 1798dbdf54498f7b6d2e6adc9f00b423 MISMATCH)
image: Lolcat_this_is_mah_job_small.jpg Hashes: (40d39c436e14282dcda06e8aff367307 - 40d39c436e14282dcda06e8aff367307), (2ddaf55b1ed59e1b8c0dbd53548808eb - a28a0a9253ad1aa2dcbb22309f91721d MISMATCH)
image: lolcat-oregon-trail.jpg Hashes: (7227289a017988b6bdcf61fd4761f6b9 - 7227289a017988b6bdcf61fd4761f6b9), (2bee65c30033043293a809a4f1439d3f - ed69c0db2493e0eba18d378b22335342 MISMATCH)

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
PIL.PngImagePlugin: DEBUG: STREAM b'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM b'pHYs' 41 9
PIL.PngImagePlugin: DEBUG: STREAM b'IDAT' 62 8192
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.176s

FAILED (failures=1)

```

Test output with 3.3.1

```
durr@mscrape:/media/Storage/Scripts/Deduper/wat$ python3 -m nose --exe
.
----------------------------------------------------------------------
Ran 1 test in 0.202s

OK
```

Minimal failing unit test is here: https://github.com/fake-name/IntraArchiveDeduplicator/tree/master/wat

**Comment by fake-name** [comment] 2016-12-30 06:30
I've noticed changes in the behaviour here before, but at the time I assumed it was due to minor optimizations in the bilinear resizing implementation (I was using bilinear, at that time). I switched to `NEAREST`, under the assumption that it *should* never change, updated the output hashes (and the resulting p-hashes later down the test-chain, etc...), and haven't looked at it for a while. 

It only came up now because I'm doing a new install, and tried to just grab the latest version, resulting in failing tests.

**Comment by fake-name** [comment] 2016-12-30 06:36
Whoa, interesting, I resaved the images as .png files, and they're invariant across 3.3.1 -> 3.3.2.

As a sidenote (if you look at the test images), this is a prime example of a new, wonderful development and testing methodology I invented and use. It's called LDD, or lolcat-driven-development.

**Comment by wiredfool** [comment] 2016-12-30 09:45
If it's a difference in JPEG, then it's probably a difference in the libjpeg version that's being linked to. #2316 hit the same issue. 

Specifically, Pillow 3.3.1 had binaries which ship a version of libjpeg. Pillow 3.3.2 was a source only release at the same time as 3.4.0, which when built would use your system libjpeg.

**Comment by fake-name** [comment] 2016-12-30 21:38
FYI:

> TypeError: hexdigest() takes no arguments (1 given)

I extended the tests to include hashing the images before resize, and they also mismatch, so it looks like this is the libjpeg change issue.

Why doesn't the changelog mention the dropping of the vendored images?

**Comment by wiredfool** [comment] 2016-12-30 21:52
Yeah, I copied the wrong line. `md5(im.tobytes()).hexdigest()`

We didn't drop the vendored libjpeg, we just didn't produce the 50 odd binary packages for 3.3.2 because 3.4.0 was simultaneously released including the binaries.  Our policy is to have one visible release on pypi, so they would have been invisible. The 3.3.2 release was important enough to provide clean patches to those who want security only fixes to backport, and they're mainly distros who have their own build systems. (and by mainly distros, I mean debian)

**Comment by fake-name** [comment] 2016-12-30 22:18
I see.

------

Ok, this gets more interesting.

My tests for 3.3.1 -> 3.3.2 differ in the raw image before resizing. However, 3.4.0 the unresized image matches, while the resize image no longer matches. This is also true globally, even for .png files:

```

image:                         lolcat-crocs.jpg Hashes: (JPEG Bytes: 6d0a977694630ac9d1d33a7f068e10f8 - 6d0a977694630ac9d1d33a7f068e10f8), (Original Pixels: 194e61198caf20000c5effdb28455165 - 194e61198caf20000c5effdb28455165), (Resized Pixels: 63d4a41d74397ae8b58b70ec880ea66b - 83aec17425e9d6720bc27efde7d0f2d0 MISMATCH)
image:                dangerous-to-go-alone.jpg Hashes: (JPEG Bytes: dcd6097eeac911efed3124374f44085b - dcd6097eeac911efed3124374f44085b), (Original Pixels: 2e2598def5e8f4aea9300b63c5dc7581 - 2e2598def5e8f4aea9300b63c5dc7581), (Resized Pixels: d958d47e04812e34746b9c36f40e0385 - 407bc3580af7a999b340145a997e5bc7 MISMATCH)
image:               Lolcat_this_is_mah_job.jpg Hashes: (JPEG Bytes: d9ceeb6b43c2d7d096532eabfa6cf482 - d9ceeb6b43c2d7d096532eabfa6cf482), (Original Pixels: 4739fed7a22b8dfaa77f5e4a4382c8ab - 4739fed7a22b8dfaa77f5e4a4382c8ab), (Resized Pixels: f238cfe1c2262cc5fea335dc85c3d8ba - 1798dbdf54498f7b6d2e6adc9f00b423 MISMATCH)
image:         Lolcat_this_is_mah_job_small.jpg Hashes: (JPEG Bytes: 40d39c436e14282dcda06e8aff367307 - 40d39c436e14282dcda06e8aff367307), (Original Pixels: 9a7c7c6b9bd532816a8da12ac8f5c8c6 - 9a7c7c6b9bd532816a8da12ac8f5c8c6), (Resized Pixels: a1a5ca5f755b9a340f52c16a41fddc6d - a28a0a9253ad1aa2dcbb22309f91721d MISMATCH)
image:                  lolcat-oregon-trail.jpg Hashes: (JPEG Bytes: 7227289a017988b6bdcf61fd4761f6b9 - 7227289a017988b6bdcf61fd4761f6b9), (Original Pixels: e8bdd8193c73a2dd132058b2077f2643 - e8bdd8193c73a2dd132058b2077f2643), (Resized Pixels: 013936aadb798634d26a8d3df4a1d90a - ed69c0db2493e0eba18d378b22335342 MISMATCH)
image:               Lolcat_this_is_mah_job.png Hashes: (JPEG Bytes: 1268e704908cc39299d73d6caafc23a0 - 1268e704908cc39299d73d6caafc23a0), (Original Pixels: 8df218eba4cd6d531a308947078b0566 - 8df218eba4cd6d531a308947078b0566), (Resized Pixels: 766744a9d5a4c3ae9a14f5b4218bc3af - 822c823d4e3bd49a35da06a86cb6231e MISMATCH)
image:                         lolcat-crocs.png Hashes: (JPEG Bytes: c699c3b0df40be264d2566970a01af72 - c699c3b0df40be264d2566970a01af72), (Original Pixels: 58934b4a2538a172958ebda0486e8c76 - 58934b4a2538a172958ebda0486e8c76), (Resized Pixels: b6caca3a5870b58e70d07a3c9a5bb852 - 9e0e86672909bdb35ac06b8730c8512d MISMATCH)
image:                dangerous-to-go-alone.png Hashes: (JPEG Bytes: 351d82c14bbf6c94d97112cd27cc5198 - 351d82c14bbf6c94d97112cd27cc5198), (Original Pixels: 45ad38f0c051eb71396877910f8b2e73 - 45ad38f0c051eb71396877910f8b2e73), (Resized Pixels: 629e1e8f3fa36336159d93e2e4a02242 - 5217b1c8f8bac745bea087c1c282b9ff MISMATCH)
image:               Lolcat_this_is_mah_job.png Hashes: (JPEG Bytes: 1268e704908cc39299d73d6caafc23a0 - 1268e704908cc39299d73d6caafc23a0), (Original Pixels: 8df218eba4cd6d531a308947078b0566 - 8df218eba4cd6d531a308947078b0566), (Resized Pixels: 766744a9d5a4c3ae9a14f5b4218bc3af - 822c823d4e3bd49a35da06a86cb6231e MISMATCH)
image:         Lolcat_this_is_mah_job_small.png Hashes: (JPEG Bytes: 1bb81f4262f6d1219f3d71a5f857cdab - 1bb81f4262f6d1219f3d71a5f857cdab), (Original Pixels: e2c3512ca205287ac72591a1ace84c31 - e2c3512ca205287ac72591a1ace84c31), (Resized Pixels: c2dc17efd0d69068a363f92af453eff8 - 2ddaf55b1ed59e1b8c0dbd53548808eb MISMATCH)
image:                  lolcat-oregon-trail.png Hashes: (JPEG Bytes: 4a282959a53d259283f6e977c9be4143 - 4a282959a53d259283f6e977c9be4143), (Original Pixels: ea972dd40220ce031a516dd93b510075 - ea972dd40220ce031a516dd93b510075), (Resized Pixels: 3d22396c57edc70063fa88d61c075ec7 - 2bee65c30033043293a809a4f1439d3f MISMATCH)

```

**Comment by fake-name** [comment] 2016-12-30 22:24
Ok, MOAR testing. It looks like `image = image.convert("L")` changed between 3.3.1 and 3.4.0:

```
======================================================================
FAIL: test_hashImage1 (Test_ImLoad.TestSequenceFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/Storage/Scripts/Deduper/wat/Test_ImLoad.py", line 95, in test_hashImage1
    imgn, hashtype, hashes[0], hashes[1]
AssertionError: '63d4a41d74397ae8b58b70ec880ea66b' != '83aec17425e9d6720bc27efde7d0f2d0'
- 63d4a41d74397ae8b58b70ec880ea66b
+ 83aec17425e9d6720bc27efde7d0f2d0
 : Mismatch in lolcat-crocs.jpg of image resize hash - (63d4a41d74397ae8b58b70ec880ea66b, 83aec17425e9d6720bc27efde7d0f2d0)
-------------------- >> begin captured stdout << ---------------------
image:                         lolcat-crocs.jpg Hashes:
        (JPEG Bytes: 6d0a977694630ac9d1d33a7f068e10f8 - 6d0a977694630ac9d1d33a7f068e10f8),
        (Original Pixels: 194e61198caf20000c5effdb28455165 - 194e61198caf20000c5effdb28455165),
        (Greyscale Pixels: 1a633cbdc867e5832587d401c0b62b9c - 1a633cbdc867e5832587d401c0b62b9c MISMATCH),
        (Resized Pixels: 63d4a41d74397ae8b58b70ec880ea66b - 83aec17425e9d6720bc27efde7d0f2d0 MISMATCH)
image:                dangerous-to-go-alone.jpg Hashes:
        (JPEG Bytes: dcd6097eeac911efed3124374f44085b - dcd6097eeac911efed3124374f44085b),
        (Original Pixels: 2e2598def5e8f4aea9300b63c5dc7581 - 2e2598def5e8f4aea9300b63c5dc7581),
        (Greyscale Pixels: f78a6e4896fd84d30c332ec4778d751b - f78a6e4896fd84d30c332ec4778d751b MISMATCH),
        (Resized Pixels: d958d47e04812e34746b9c36f40e0385 - 407bc3580af7a999b340145a997e5bc7 MISMATCH)
image:               Lolcat_this_is_mah_job.jpg Hashes:
        (JPEG Bytes: d9ceeb6b43c2d7d096532eabfa6cf482 - d9ceeb6b43c2d7d096532eabfa6cf482),
        (Original Pixels: 4739fed7a22b8dfaa77f5e4a4382c8ab - 4739fed7a22b8dfaa77f5e4a4382c8ab),
        (Greyscale Pixels: 57819e9843f5b1001aa5f084cebc5baf - 57819e9843f5b1001aa5f084cebc5baf MISMATCH),
        (Resized Pixels: f238cfe1c2262cc5fea335dc85c3d8ba - 1798dbdf54498f7b6d2e6adc9f00b423 MISMATCH)
image:         Lolcat_this_is_mah_job_small.jpg Hashes:
        (JPEG Bytes: 40d39c436e14282dcda06e8aff367307 - 40d39c436e14282dcda06e8aff367307),
        (Original Pixels: 9a7c7c6b9bd532816a8da12ac8f5c8c6 - 9a7c7c6b9bd532816a8da12ac8f5c8c6),
        (Greyscale Pixels: e7e5aad5ec078fc91e7cc6a95acb0315 - e7e5aad5ec078fc91e7cc6a95acb0315 MISMATCH),
        (Resized Pixels: a1a5ca5f755b9a340f52c16a41fddc6d - a28a0a9253ad1aa2dcbb22309f91721d MISMATCH)
image:                  lolcat-oregon-trail.jpg Hashes:
        (JPEG Bytes: 7227289a017988b6bdcf61fd4761f6b9 - 7227289a017988b6bdcf61fd4761f6b9),
        (Original Pixels: e8bdd8193c73a2dd132058b2077f2643 - e8bdd8193c73a2dd132058b2077f2643),
        (Greyscale Pixels: 107850e42e3c2797204683f608e03f64 - 107850e42e3c2797204683f608e03f64 MISMATCH),
        (Resized Pixels: 013936aadb798634d26a8d3df4a1d90a - ed69c0db2493e0eba18d378b22335342 MISMATCH)
image:               Lolcat_this_is_mah_job.png Hashes:
        (JPEG Bytes: 1268e704908cc39299d73d6caafc23a0 - 1268e704908cc39299d73d6caafc23a0),
        (Original Pixels: 8df218eba4cd6d531a308947078b0566 - 8df218eba4cd6d531a308947078b0566),
        (Greyscale Pixels: 2e793c83d71f9c3a0f21340ecef1cf22 - 2e793c83d71f9c3a0f21340ecef1cf22 MISMATCH),
        (Resized Pixels: 766744a9d5a4c3ae9a14f5b4218bc3af - 822c823d4e3bd49a35da06a86cb6231e MISMATCH)
image:                         lolcat-crocs.png Hashes:
        (JPEG Bytes: c699c3b0df40be264d2566970a01af72 - c699c3b0df40be264d2566970a01af72),
        (Original Pixels: 58934b4a2538a172958ebda0486e8c76 - 58934b4a2538a172958ebda0486e8c76),
        (Greyscale Pixels: 5eb913ed7f9b03ab973c64116ae15856 - 5eb913ed7f9b03ab973c64116ae15856 MISMATCH),
        (Resized Pixels: b6caca3a5870b58e70d07a3c9a5bb852 - 9e0e86672909bdb35ac06b8730c8512d MISMATCH)
image:                dangerous-to-go-alone.png Hashes:
        (JPEG Bytes: 351d82c14bbf6c94d97112cd27cc5198 - 351d82c14bbf6c94d97112cd27cc5198),
        (Original Pixels: 45ad38f0c051eb71396877910f8b2e73 - 45ad38f0c051eb71396877910f8b2e73),
        (Greyscale Pixels: 7351d3509a65f37eb89320bd14bb0ed7 - 7351d3509a65f37eb89320bd14bb0ed7 MISMATCH),
        (Resized Pixels: 629e1e8f3fa36336159d93e2e4a02242 - 5217b1c8f8bac745bea087c1c282b9ff MISMATCH)
image:               Lolcat_this_is_mah_job.png Hashes:
        (JPEG Bytes: 1268e704908cc39299d73d6caafc23a0 - 1268e704908cc39299d73d6caafc23a0),
        (Original Pixels: 8df218eba4cd6d531a308947078b0566 - 8df218eba4cd6d531a308947078b0566),
        (Greyscale Pixels: 2e793c83d71f9c3a0f21340ecef1cf22 - 2e793c83d71f9c3a0f21340ecef1cf22 MISMATCH),
        (Resized Pixels: 766744a9d5a4c3ae9a14f5b4218bc3af - 822c823d4e3bd49a35da06a86cb6231e MISMATCH)
image:         Lolcat_this_is_mah_job_small.png Hashes:
        (JPEG Bytes: 1bb81f4262f6d1219f3d71a5f857cdab - 1bb81f4262f6d1219f3d71a5f857cdab),
        (Original Pixels: e2c3512ca205287ac72591a1ace84c31 - e2c3512ca205287ac72591a1ace84c31),
        (Greyscale Pixels: 3205a7cb4a9002ab05f086769ad88506 - 3205a7cb4a9002ab05f086769ad88506 MISMATCH),
        (Resized Pixels: c2dc17efd0d69068a363f92af453eff8 - 2ddaf55b1ed59e1b8c0dbd53548808eb MISMATCH)
image:                  lolcat-oregon-trail.png Hashes:
        (JPEG Bytes: 4a282959a53d259283f6e977c9be4143 - 4a282959a53d259283f6e977c9be4143),
        (Original Pixels: ea972dd40220ce031a516dd93b510075 - ea972dd40220ce031a516dd93b510075),
        (Greyscale Pixels: f781356fd64a6d30e11bf633dd4ac601 - f781356fd64a6d30e11bf633dd4ac601 MISMATCH),
        (Resized Pixels: 3d22396c57edc70063fa88d61c075ec7 - 2bee65c30033043293a809a4f1439d3f MISMATCH)

```

**Comment by wiredfool** [comment] 2016-12-30 23:39
1) It looks like the changes are still in resize, not in convert. There are significant ongoing changes to the resize/resample code as @homm speeds it up. It's been faster and more precise with each PR. 

2) MD5 is a pretty crummy basis for detecting significant changes to lossy or approximate algorithms. Nearest Neighbor is a fast approximation, worst quality for the hopefully fastest speed. We do regression testing by looking at the image similarity, given an epsilon, are the images close enough?  For places where there's an exact answer, we can use image equality. You've detected a change. How big is it? Is it meaningful? Is it bad?

3) We aren't really doing semantic major versioning. 3.0 followed 2.9. We've got a few deprecations here and there, with plenty of warning.  However, we are bumping to 4.0 this time due to dropping support for python 2.6 and 3.2. 

4) You've got a test case, feel free to git bisect and see where it lands. I'm going to bet it's in one of @homm's PRs. Most of those PRs speed things up by 30+%. Once you find the commit, you'll have a handle on what it will take to undo those changes, and at what cost.

**Comment by fake-name** [comment] 2016-12-30 23:51
At this point, I think I'm going to version-lock to 3.3.1, Really, in this case, the testing was initially written to catch issues before they led to later confusion, rather then be maximally robust for testing pillow itself. My concern when I actually wrote the tests were filesystem corruption, rather then changes in the image processing algorithms.

Basically, these tests are done before later testing of the integrity of a perceptual-hashing system on the resulting images, and were *supposed* to be just a idiot-check type thing (which, I suppose, just shows my inexperience).

**Closed** 2016-12-31 00:05 UTC

**Comment by homm** [comment] 2016-12-31 22:30
Affine transformations (including `Image.resize()` with `NEAREST` filter) were fixed in https://github.com/python-pillow/Pillow/pull/2022. It didn't introduce any speedups, just fixed existed issues

**Comment by fake-name** [comment] 2017-01-01 01:21
Yeah, but I'm seeing a difference in the behavior of even `image.convert("L")` between 3.3.1 and 3.4.0.

**Comment by wiredfool** [comment] 2017-01-01 09:35
None of your latest hashes show a change in the convert stage, they're only different on the resample.

**Comment by fake-name** [comment] 2017-01-02 08:15
Wow, well I'm incredibly dumb. You are correct, and I apparently fail at test-case.
