### ISSUE TITLE
10.0.0 refused to build on Windows with 32-bit Python

### ISSUE THREAD

**Issue by baaziznasser** [python-pillow/Pillow#7251] opened 2023-07-02 20:26 UTC
hello the pillow lib refused to install on windows python 3.11 x32
here is the error

        File "<string>", line 1005, in <module>
      RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
Failed to build pillow
ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects

C:\Users\nacer baaziz><!--

### What are your OS, Python and Pillow versions?

* OS: windows 11
* Python: python 3.11 x32
* Pillow: 10.0.0

**Comment by baaziznasser** [comment] 2023-07-02 20:26
the wheel of python 3.11 x32 is not exist

**Comment by radarhere** [comment] 2023-07-02 21:31
Hi. You will read in the [release notes](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#bit-wheels) that it was a deliberate decision to not provide 32-bit wheels any longer.

https://github.com/python-pillow/Pillow/issues/6941#issuecomment-1604058002
> I suggest we drop all the 32-bit wheels... If there's a lot of demand or very good reason, we can always add something back (e.g. 3.8 on Windows has a slightly larger percentage).

While we are no longer providing 32-bit wheels though, you can still build from source. See https://pillow.readthedocs.io/en/stable/installation.html#building-from-source

**Comment by robgom** [comment] 2023-07-03 07:39
The problem is that when installing pillow, newer version (10.x) with tar.gz is preferred over the older wheel.
And newer version can't be built on 32 bits, so several people could be affected by this.

**Comment by radarhere** [comment] 2023-07-03 08:20
You can select only versions of Pillow with a wheel when installing by using `python3 -m pip install Pillow --only-binary=:all:`

**Comment by robgom** [comment] 2023-07-03 08:30
Thank you, @radarhere , but that might be not scalable. The pillow package is rarely used directly, it is rather an indirect dependency. Other packages can be involved, for which tar.gz would be needed.
Just trying to chime in, providing arguments to consider providing wheels or not announcing 32 bit support in first place.

**Comment by homm** [comment] 2023-07-03 08:36
@robgom You don't need list Pillow directly to use `--only-binary=:all:` option

**Comment by robgom** [comment] 2023-07-03 08:41
@homm yes, I know. My point was that including this option could have bigger implications. That's what it'd have to look like:
```
--only-binary=:all:  # workaround for pillow dependency

matplotlib
yaml
whatever
```
1. Repeated for several dependency/requirements files used for different processes.
2. Expressing implicit dependency version restriction
3. Potentially conflicting with any other package requiring source, not binary

Do those arguments make sense to you?
Again, I can follow your advice, just trying to suggest to solve the issue closer to its roots.

**Comment by radarhere** [comment] 2023-07-03 09:25
> providing arguments to consider providing wheels or not announcing 32 bit support in first place

I don't understand the meaning of 'not announcing 32 bit support in first place'. Perhaps these words aren't quite correct, because this was [announced](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#bit-wheels).

If you just want to say that you're a 32-bit user, and wheels make your life easier, mission accomplished - I don't think we're trying to tell you that dropping 32-bit wheels has zero effect. If a flood of other people also chime in and say that they want 32-bit wheels, then those voices and your voice will make us reconsider this.

> Potentially conflicting with any other package requiring source, not binary

If you're concerned about packages that do not provide wheels, there is also `--prefer-binary` - https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-prefer-binary

In your example, you mention matplotlib. I realise you might say that was just an example, but matplotlib has actually also decided to drop 32-bit wheels moving forward.

https://github.com/matplotlib/matplotlib/issues/25811#issuecomment-1535486764
> On main we no longer build 32 bit wheels and will not publish them in the future.

**Comment by radarhere** [comment] 2023-07-03 09:39
@baaziznasser do you have any further questions?

**Comment by homm** [comment] 2023-07-03 10:28
> somehow indicating in its data that it's not supporting 32 bits (in its metadata).

It’s not the case. Wheels are not provided, which doesn’t mean that you can’t install it at all.

There are could be a dozen of reasons why provided wheels does not suits you. It’s more correct to say that there is always only tiny intersection of factors (OS vendor, OS version, core libraries, platform, bitness) when you can find wheels. And of course Pillow provides a list of this intersections: it's a list of the wheels itself.

**Comment by jamesbraza** [comment] 2023-07-05 20:24
I am hitting this as well.  See here for relevant discussion: https://github.com/pypa/setuptools/issues/3746

**Comment by radarhere** [comment] 2023-07-05 22:49
For a summary of that other issue, the user suggests that setuptools allow packages to require 32-bit support.

That discussion has another offshoot in https://discuss.python.org/t/idea-enforcing-32-bit-vs-64-bit-support-in-setuptools/29040, where so far, a CPython core developer questions why this would be relevant to packages that still support 32-bit, but have merely stopped distributing 32-bit wheels (like we have).

**Comment by xqt** [comment] 2023-07-06 10:55
We have the same issue with Python 3.8 and Python 3.10 on 32-bit system:
https://ci.appveyor.com/project/pywikibot-core/pywikibot/builds/47477816

**Comment by radarhere** [comment] 2023-07-06 11:29
@xqt we are no longer providing 32-but wheels, so your code is trying to install Pillow from source. The error is telling you that you are missing a dependency. See https://pillow.readthedocs.io/en/stable/installation.html#building-from-source for instructions about how to build Pillow from source.

**Comment by xqt** [comment] 2023-07-06 11:48
@radarhere: Pillow is a requirement of the Pywikibot framework and we are running 32/64-bit tests on Appveyor. But CI tests are only one side. What is the solution for bot owners having Python 3.8+ on 32-bit? We could require Pillow < 10.0.0 for a while but this cannot be the way to go.

**Comment by radarhere** [comment] 2023-07-06 12:20
Do you mean that it is not just a matter of you installing Pillow, but also your users? It would be the hope that because 32-bit use is fading, that this only affects [a small portion of users](https://github.com/python-pillow/Pillow/issues/6941#issuecomment-1561081046). If you find otherwise, you can ask your users to can here and encourage us to restore 32-bit wheels.

https://github.com/python-pillow/Pillow/issues/6941#issuecomment-1604058002
> I suggest we drop all the 32-bit wheels... If there's a lot of demand or very good reason, we can always add something back (e.g. 3.8 on Windows has a slightly larger percentage).

**Comment by hugovk** [comment] 2023-07-06 14:31
Using https://github.com/ofek/pypinfo to get downloads numbers for Pywikibot from PyPI over the last week, I only see a single download for 32-bit (armv7l, 0.06%), the other 1,732 are 64-bit (99.94%):


```console
$ pypinfo --days 7 --limit 1000 --percent pywikibot version cpu
Served from cache: False
Data processed: 281.80 MiB
Data billed: 282.00 MiB
Estimated cost: $0.01

| version      | cpu     | percent | download_count |
| ------------ | ------- | ------- | -------------- |
| 8.1.2        | x86_64  |  55.57% |            963 |
| 7.0.0        | x86_64  |  20.31% |            352 |
| 6.1.0        | x86_64  |   8.77% |            152 |
| 6.6.5        | x86_64  |   5.19% |             90 |
| 8.1.2        | AMD64   |   1.90% |             33 |
| 8.2.0        | x86_64  |   1.44% |             25 |
| 6.6.0        | x86_64  |   1.27% |             22 |
| 6.6.3        | x86_64  |   1.15% |             20 |
| 8.0.1        | x86_64  |   0.75% |             13 |
| 7.1.0        | x86_64  |   0.46% |              8 |
| 7.6.0        | x86_64  |   0.46% |              8 |
| 7.7.3        | x86_64  |   0.40% |              7 |
| 6.6.1        | x86_64  |   0.29% |              5 |
| 6.0.1        | x86_64  |   0.29% |              5 |
| 8.1.0        | x86_64  |   0.23% |              4 |
| 8.1.2        | aarch64 |   0.23% |              4 |
| 8.1.2        | arm64   |   0.17% |              3 |
| 8.0.2        | x86_64  |   0.12% |              2 |
| 6.6.5        | AMD64   |   0.12% |              2 |
| 6.4.0        | x86_64  |   0.12% |              2 |
| 7.7.3        | aarch64 |   0.12% |              2 |
| 6.6.5        | arm64   |   0.06% |              1 |
| 3.0.20200609 | x86_64  |   0.06% |              1 |
| 6.5.0        | AMD64   |   0.06% |              1 |
| 8.2.0        | AMD64   |   0.06% |              1 |
| 6.6.1        | AMD64   |   0.06% |              1 |
| 7.7.1        | x86_64  |   0.06% |              1 |
| 8.2.0        | armv7l  |   0.06% |              1 |
| 4.3.0        | AMD64   |   0.06% |              1 |
| 8.0.2        | AMD64   |   0.06% |              1 |
| 5.6.0        | x86_64  |   0.06% |              1 |
| 6.6.3        | AMD64   |   0.06% |              1 |
| Total        |         |         |          1,733 |

```

**Comment by jamesbraza** [comment] 2023-07-06 15:27
> For a summary of that other issue, the user suggests that setuptools allow packages to require 32-bit support.

Just to follow up on this, @radarhere I think you misinterpreted in your summary post, it's wasn't about requiring 32-bit support.  It was about enabling `pip` to automatically discern 32-bit systems' should fall back on `Pillow` version 9, by packages adding metadata on supported platforms.

Anyways, the idea kind of sizzled out 🤷‍♂️, as stating supported platform(s) isn't feasible in practice.  For example, perhaps win32 actually has `zlib`, so source build would've worked.

**Comment by nulano** [comment] 2023-07-06 17:40
> I only see a single download for 32-bit (armv7l, 0.06%)

Worth noting that this is ARM, not x86, so the wheel would not have been compatible anyway.

**Comment by radarhere** [comment] 2023-08-01 23:03
It's now been a month since the release of Pillow 10.0.0.

In the first week, we had some feedback here about the absence of 32-bit wheels here, and [a comment in the release issue](https://github.com/python-pillow/Pillow/issues/7195#issuecomment-1616115771), but no new users have added feedback since.

If there is further feedback, we can reconsider 32-bit wheels, but for the moment, no users here have active questions about how to install Pillow, so I'm closing this.

**Closed by radarhere** 2023-08-01 23:03 UTC
Labels: Installation, Windows
