### ISSUE TITLE
Not able to open tiff-file with Pillow (regression)

### ISSUE THREAD

**Issue by marfri** [python-pillow/Pillow#1526] opened 2015-11-05 11:35 UTC
We encountered a tiff-file that Pillow failed to open in version 3.0.0, in version 2.9.0 it works just fine.

https://drive.google.com/a/greyrook.com/file/d/0Bypf_GpBFGxZU3A1QmsxQlRXVXc/view

on `Image.open(path)`: `IOError: cannot identify image file`

**Comment by acdha** [comment] 2015-11-13 16:41
I've encountered the same problem on OS X and Ubuntu 14.04 LTS.

**Comment by acdha** [comment] 2015-11-13 16:54
It looks like the wheels distributed on PyPI were compiled on a machine without libtiff – if I install from source (`pip install --no-binary=all --no-use-wheel Pillow==3`) it works as expected.

**Comment by wiredfool** [comment] 2015-11-13 18:10
@acdha Which platform is missing tiff in the distributed files?

**Comment by acdha** [comment] 2015-11-13 18:35
@wiredfool OS X and Linux 64-bit

**Comment by wiredfool** [comment] 2015-11-13 19:00
We don't distribute binaries for Linux, so I'm not sure where that comes from.  The OS X wheels are built on Travis, and they pass the libtiff tests: https://travis-ci.org/python-pillow/pillow-wheels/jobs/88293220.

**Comment by acdha** [comment] 2015-11-13 22:53
Hmmm, that's really quite odd – on both platforms, 2.9.0 installs without a
hitch with no special handling but 3.0.0 only works from source, not the
wheel. I'll look into it more on Monday.

Chris

**Comment by wiredfool** [comment] 2015-11-15 15:56
@acdha Your issue appears to be something other than what @marfri is seeing. 

@marfri Your issue is a duplicate of #1466, with a side of #1465 where the fix didn't fix your issue.  So it's wrong in master and 3.0.0 for different reasons.

**Closed** 2015-11-16 08:23 UTC
Labels: Tiff
