### ISSUE TITLE
Can't open CMYK tiff image with spot channels

### ISSUE THREAD

**Issue by genequ** [python-pillow/Pillow#2821] opened 2017-11-01 09:01 UTC
The provided sample file has 5 channels, CMYK + PMS 200 C. When i am trying to open it using 
Image.open(), it reports: IOError: cannot identify image file '/Users/gequ/Desktop/cmyk.tif'
[cmyk.tif.zip](https://github.com/python-pillow/Pillow/files/1433584/cmyk.tif.zip)

Thanks for taking care of this!

**Comment by wiredfool** [comment] 2017-11-01 12:47
We're currently not able to open files with more than 4 channels.

**Comment by homm** [comment] 2017-12-10 15:14
I also have requests for such files from our users and the only solution I see without rewriting most parts of Pillow is on-the-fly conversion to RGBA.

@genequ Will you be satisfied with such solution?

**Comment by wiredfool** [comment] 2017-12-10 15:38
@homm I wonder if we could figure out a way to spilt extra channels out as additional bands in the image structure, so that we'd have our usual optimized set of pixels, and spot channels like this would essentially be extra single band images.

**Comment by homm** [comment] 2017-12-11 11:26
@wiredfool Interesting idea. How we can provide access to additional channels? Via image.info?

**Comment by genequ** [comment] 2017-12-18 08:59
@homm it is common a file with several spot channels in the prepress industry(mostly generated by Adobe's product). I do not know if it is a good idea to convert to RGBA.
@homm that sounds promising

**Comment by homm** [comment] 2018-01-07 14:57
Hi! I've created some fix which allows opening some TIFFs with ExtraSamples. The problem is that that fix also allows opening your sample TIFF while shouldn't. Some more explanation:

TIFF files contain `ExtraSamples` marker which tells how to interpret extra channels. [According to the docs](https://www.awaresystems.be/imaging/tiff/tifftags/extrasamples.html), it could have three values:

```
EXTRASAMPLE_UNSPECIFIED = 0;
EXTRASAMPLE_ASSOCALPHA = 1;
EXTRASAMPLE_UNASSALPHA = 2;
```

The sample file has the following value:

> tag: ExtraSamples (338) - type: short (3) - value: (0,)

This means that additional channel in the file contains some service information. So I suppose that it is legal to open the file and discard that channel if we don't know what to do with it. On the other hand, Macos's Preview and Windows's 7 Photo viewer treats that channel as the alpha channel. But InfanView and Paint.NET don't.

It is more likely that the file should have ExtraSamples (1,).

**Comment by homm** [comment] 2018-01-07 15:13
@genequ Oh, I'm sorry, just noticed that you never claim that this is alpha channel. So, does discarding the extra channel is better than rejecting the entire image for you?

**Comment by genequ** [comment] 2018-01-08 05:04
@homm, thanks a lot for your effect!
Discarding the spot channels does not actually solve my problem since those channels always contain real contents.

**Comment by radarhere** [comment] 2021-02-27 12:56
#2938 was merged. Closing in favour of the tracking issue, #1888

**Closed by radarhere** 2021-02-27 12:56 UTC
Labels: Conversion, Enhancement
