### ISSUE TITLE
TIFF Encoder traces out when trying to save a file

### ISSUE THREAD

**Issue by sparklespdx** [python-pillow/Pillow#4307] opened 2019-12-27 04:22 UTC
### What did you do?
Opened the attached TIFF image with Image.open() and tried to save it to a new file with Image.save(), and got this exception:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: an integer is required (got type bytes)

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-4-77ee9991eb39> in <module>
----> 1 image.save("toorcon-sticker-2.tiff")

~/git/stickermuseum/venv/lib/python3.7/site-packages/PIL/Image.py in save(self, fp, format, **params)
   2082 
   2083         try:
-> 2084             save_handler(self, fp, filename)
   2085         finally:
   2086             # do what we can to clean up

~/git/stickermuseum/venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py in _save(im, fp, filename)
   1645         tags.sort()
   1646         a = (rawmode, compression, _fp, filename, tags, types)
-> 1647         e = Image._getencoder(im.mode, "libtiff", a, im.encoderconfig)
   1648         e.setimage(im.im, (0, 0) + im.size)
   1649         while True:

~/git/stickermuseum/venv/lib/python3.7/site-packages/PIL/Image.py in _getencoder(mode, encoder_name, args, extra)
    475         # get encoder
    476         encoder = getattr(core, encoder_name + "_encoder")
--> 477         return encoder(mode, *args + extra)
    478     except AttributeError:
    479         raise IOError("encoder %s not available" % encoder_name)

SystemError: <built-in function libtiff_encoder> returned a result with an error set

```
### What did you expect to happen?
I expected the image to be written to the file handle.

### What are your OS, Python and Pillow versions?

* OS: Fedora 30
* Python: Python 3.7.5 (also replicated on 3.8.1)
* Pillow: 6.2.1

### PoC Code
```python
from PIL import Image

image = Image.open("toorcon-sticker.tiff")
image.save("toorcon-sticker-2.tiff")
```

**Comment by radarhere** [comment] 2019-12-27 04:24
You refer to 'the attached TIFF image', but I see no attachment?

**Comment by sparklespdx** [comment] 2019-12-27 04:24
Adding the TIFF file in a ZIP since Github won't allow TIFFs as attachments apparently

[toorcon-sticker.zip](https://github.com/python-pillow/Pillow/files/4004189/toorcon-sticker.zip)

**Comment by sparklespdx** [comment] 2019-12-27 04:28
I think I cut off part of the trace when I copy pasted, editing to fix

**Comment by sparklespdx** [comment] 2019-12-27 04:31
My version of libtiff is `libtiff-4.0.10-7.fc30`. I also tested with the `python:latest` Docker image.

**Comment by radarhere** [comment] 2019-12-27 05:13
If you're interested, I find that deleting two TIFF tags allows the image to save -

```python
from PIL import Image

im = Image.open("toorcon-sticker.tiff")
del im.tag_v2[34377]
del im.tag_v2[700]
im.save("toorcon-sticker-2.tiff")
```

**Comment by sparklespdx** [comment] 2019-12-27 05:19
hrrrrmrmrmrm thanks for helping me troubleshoot. I will investigate the file.

**Comment by sparklespdx** [comment] 2019-12-27 05:21
Is this expected behavior for Pillow when there are bad tags?

**Comment by radarhere** [comment] 2019-12-27 05:26
I wouldn't say that the tags are incorrect, I'm just offering a workaround, in case that is helpful.

**Comment by sparklespdx** [comment] 2019-12-27 05:37
Looks like the 700 tag is an XML payload from Photoshop:

```
(b'<?xpacket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>\n<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c145 79.163499, 2018/08/13-16:40:22        ">\n   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n      <rdf:Description rdf:about=""\n            xmlns:xmp="http://ns.adobe.com/xap/1.0/"\n            xmlns:dc="http://purl.org/dc/elements/1.1/"\n            xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"\n            xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"\n            xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#">\n         <xmp:CreatorTool>Adobe Photoshop CC 2019 (Macintosh)</xmp:CreatorTool>\n         <xmp:CreateDate>2019-08-05T02:08:25-07:00</xmp:CreateDate>\n         <xmp:ModifyDate>2019-08-16T23:17:39-07:00</xmp:ModifyDate>\n         <xmp:MetadataDate>2019-08-16T23:17:39-07:00</xmp:MetadataDate>\n         <dc:format>image/tiff</dc:format>\n         <photoshop:ColorMode>3</photoshop:ColorMode>\n         <photoshop:ICCProfile>sRGB IEC61966-2.1</photoshop:ICCProfile>\n         <xmpMM:InstanceID>xmp.iid:0115ca7f-569b-47f8-ac2c-b32105bfbf5d</xmpMM:InstanceID>\n         <xmpMM:DocumentID>adobe:docid:photoshop:11d7dcfc-7714-0845-8b2d-6c3723c6dadf</xmpMM:DocumentID>\n         <xmpMM:OriginalDocumentID>xmp.did:43e4c691-8414-4fe8-806e-3bece7aa8e33</xmpMM:OriginalDocumentID>\n         <xmpMM:History>\n            <rdf:Seq>\n               <rdf:li rdf:parseType="Resource">\n                  <stEvt:action>created</stEvt:action>\n                  <stEvt:instanceID>xmp.iid:43e4c691-8414-4fe8-806e-3bece7aa8e33</stEvt:instanceID>\n                  <stEvt:when>2019-08-05T02:08:25-07:00</stEvt:when>\n                  <stEvt:softwareAgent>Adobe Photoshop CC 2019 (Macintosh)</stEvt:softwareAgent>\n               </rdf:li>\n               <rdf:li rdf:parseType="Resource">\n                  <stEvt:action>saved</stEvt:action>\n                  <stEvt:instanceID>xmp.iid:6a1b186f-6d38-40ca-9b45-6c3556e105cd</stEvt:instanceID>\n                  <stEvt:when>2019-08-16T23:17:39-07:00</stEvt:when>\n                  <stEvt:softwareAgent>Adobe Photoshop CC 2019 (Macintosh)</stEvt:softwareAgent>\n                  <stEvt:changed>/</stEvt:changed>\n               </rdf:li>\n               <rdf:li rdf:parseType="Resource">\n                  <stEvt:action>saved</stEvt:action>\n                  <stEvt:instanceID>xmp.iid:0115ca7f-569b-47f8-ac2c-b32105bfbf5d</stEvt:instanceID>\n                  <stEvt:when>2019-08-16T23:17:39-07:00</stEvt:when>\n                  <stEvt:softwareAgent>Adobe Photoshop CC 2019 (Macintosh)</stEvt:softwareAgent>\n                  <stEvt:changed>/</stEvt:changed>\n               </rdf:li>\n            </rdf:Seq>\n         </xmpMM:History>\n      </rdf:Description>\n   </rdf:RDF>\n</x:xmpmeta>\n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                                                                                                    \n                            \n<?xpacket end="w"?>',)
```

And the value at 34377 is some large chunk of bytes with a couple strings in it. I assume it's some other photoshop metadata or something.

**Comment by sparklespdx** [comment] 2019-12-27 05:39
The workaround is indeed helpful. I don't *think* I need this data but I need to check on a few things.

**Comment by radarhere** [comment] 2019-12-28 02:46
Closing, as I've realised this is a duplicate of the current state of #3677

**Closed by radarhere** 2019-12-28 02:46 UTC
Labels: TIFF
