### ISSUE TITLE
Image.crop changes resolution

### ISSUE THREAD

**Issue by rajeshktym** [python-pillow/Pillow#4221] opened 2019-11-20 22:50 UTC
After crop an TIF Image, it automatically reduce its original resolution. I am trying to crop 1 Bit(mode="1")  high resolution (1270 DPI) image, but after save it change to 70 DPI Image, Is it limitation or Bug?

**Comment by radarhere** [comment] 2019-11-21 07:47
Could you attach the image, and a short segment of code to demonstrate the problem?

**Comment by radarhere** [comment] 2019-12-17 08:38
Here is code using one of the test images, opening and saving a mode 1 TIFF, keeping the resolution.

```python
import os
from PIL import Image
print("Pillow version "+Image.__version__)  # Pillow version 6.2.1

im = Image.open("Tests/images/g4-multi.tiff")
print("im.size "+str(im.size))  # im.size (3307, 4677)
print("im.mode "+im.mode)   # im.mode 1
print("im dpi "+str(im.info["dpi"]))  # im dpi (400, 400)

im = im.crop((0, 0, 500, 500))
im.save("out.tiff", dpi=im.info["dpi"])

reloaded = Image.open("out.tiff")
print("reloaded dpi "+str(reloaded.info["dpi"]))  # reloaded dpi (400, 400)
```

**Comment by radarhere** [comment] 2019-12-28 02:27
If the `dpi` argument is not included, exiftool no longer reports a resolution.

So the behaviour that you're seeing is not a bug, and I wouldn't describe it as a limitation either since your goal can be achieved. This is just the default behaviour of Pillow. If you have strong feelings that this should be changed, let us know, but otherwise, closing, as I think you can have this functionality, just not by default.

**Closed by radarhere** 2019-12-28 02:27 UTC
Labels: TIFF
