### ISSUE TITLE
Japanese font glyph with direction "ttb" is drawn to incorrect position

### ISSUE THREAD

**Issue by masushin** [python-pillow/Pillow#2656] opened 2017-08-06 15:00 UTC
### What did you do?

I tried to draw Japanese font glyph by following test code.

```python
from PIL import Image, ImageDraw, ImageFont

txt = Image.new('RGBA', (200,200), (255,255,255,255))
fnt = ImageFont.truetype("GenEiAntiqueN-Medium.otf", 80)
d = ImageDraw.Draw(txt)
d.text((60,20), "あい", font=fnt, fill=(0,0,0,255), direction="ttb")
txt.show()
```

### What did you expect to happen?
I expected to get the following image.

![ai](https://user-images.githubusercontent.com/18723885/29004138-ee250fee-7afd-11e7-9142-31ba68545270.png)

### What actually happened?

I got the following image.

![ai2](https://user-images.githubusercontent.com/18723885/29004148-0923991e-7afe-11e7-9182-b594afa87903.png)

Glyphs are drawn to deviate to the lower left.

Also, it seems that these glyphs are drawn overlapping.
(It may be better to deal with this after the first problem has been solved..)

The font file using in my code can be got from the following link.
http://okoneya.jp/font/GenEiAntique-3.0.zip

Incidentally, I tried it using other font "ヒラギノ 明朝".
It included in Japanese mac OS. And same problem appear.
So, I think it is not problem with a specific font file.

Please let me know if there are mistake in my code.

### What versions of Pillow and Python are you using?
Python 3.6.0
Pillow 4.2.1

**Comment by wiredfool** [comment] 2017-08-06 16:41
Do you have the raqm feature compiled in?  ( you would have had to build from source, as it's not in the binary builds)

**Comment by masushin** [comment] 2017-08-06 17:28
I installed libraqm using `depends/install_raqm_cmake.sh`.
It seemed that it is compiled from source. So, I think yes.

```
>>> from PIL import features
>>> print ("raqm:",features.check('raqm'))
raqm: True
```

**Comment by masushin** [comment] 2017-10-03 08:18
Similarly, This phenomenon appear in pillow 4.3.0.

**Comment by wiredfool** [comment] 2017-10-04 10:18
It looks like the layout we're getting is straight from what raqm is getting from harfbuzz. It's either a bug in harfbuzz, or raqm is driving it incorrectly for this font/script. 

I've looked at this against harfbuzz 1.01 (default ubuntu 16.04) and the latest 1.5.1.

@khaledhosny Can you take a look at this?

**Comment by khaledhosny** [comment] 2017-10-06 12:22
Raqm only passes the direction to HarfBuzz, the code that does the rendering needs to handle vertical direction specially by using `y_advance` instead of `x_advance`.

**Comment by masushin** [comment] 2017-11-04 15:52
Sorry, I couldn't understand above exactly. Let me confirm about this issue.
Is it mean that cause of this issue is raqm or HarfBuzz, not pillow?
(Is it better that I contact to raqm or HarfBuzz official ?)

**Comment by aclark4life** [comment] 2018-03-17 15:02
@masushin FWIW I read it as potentially something Pillow could do (e.g. "by using y_advance instead of x_advance"), assuming Pillow is "the code that does the rendering".

**Comment by HinTak** [comment] 2018-10-26 00:51
Have a look at the vertical layout example https://github.com/HinTak/harfbuzz-python-demos

**Comment by radarhere** [comment] 2019-05-17 14:13
I wasn't able to reproduce the shift to the left, but I've created PR #3856 to fix the vertical positioning issues.

**Comment by radarhere** [comment] 2019-06-19 10:31
@masushin #3856 has been merged. Are you able to install raqm 0.7, retest this with Pillow master, and let us know if this issue is resolved?

**Comment by masushin** [comment] 2019-06-19 10:41
ok, I'll try it and report a result.

**Comment by masushin** [comment] 2019-06-23 09:48
I got a image as I expected.

![tmpto88ub18](https://user-images.githubusercontent.com/18723885/59974449-4e96cb00-95e7-11e9-8a44-d4a77a55fe48.png)

I think this issue is fixed.
thank you !

**Closed** 2019-06-23 10:44 UTC
Labels: Bug, Font Rendering
