### ISSUE TITLE
RGBA convert to CMYK lost dpi and other info

### ISSUE THREAD

**Issue by zhanglc** [python-pillow/Pillow#1676] opened 2016-01-22 17:41 UTC
```python
im = Image.open('1.jpg')
im.info
{'jfif': 257, 'jfif_unit': 1, 'exif': 'Exif\x00\x00MM\x00_\x00\x00\x00\x08\x00\x0c\x01\x00\x00\x03\x00\x00\x00\x01\x03A\x00\x00\x01\x01\x00\x03\x00\x00\x00\x01\x01\xc1\x00\x00\x01\x02\x00\x03\x00\x00\x00\x03\x00\x00\x00\x9e\x01\x06\x00\x03\x00\x00\x00\x01\x00\x02\x00\x00\x01\x12\x00\x03\x00\x00\x00\x01\x00\x01\x00\x00\x01\x15\x00\x03\x00\x00\x00\x01\x00\x03\x00\x00\x01\x1a\x00\x05\x00\x00\x00\x01\x00\x00\x00\xa4\x01\x1b\x00\x05\x00\x00\x00\x01\x00\x00\x00\xac\x01(\x00\x03\x00\x00\x00\x01\x00\x02\x00\x00\x011\x00\x02\x00\x00\x00\x1d\x00\x00\x00\xb4\x012\x00\x02\x00\x00\x00\x14\x00\x00\x00\xd1\x87i\x00\x04\x00\x00\x00\x01\x00\x00\x00\xe8\x00\x00\x01 \x00\x08\x00\x08\x00\x08\x00\x00\x00\x96\x00\x00\x00\x01\x00\x00\x00\x96\x00\x00\x00\x01Adobe Photoshop CC (Windows)\x002016:01:18 10:25:46\x00\x00\x00\x00\x00\x04\x90\x00\x00\x07\x00\x00\x00\x040221\xa0\x01\x00\x03\x00\x00\x00\x01\xff\xff\x00\x00\xa0\x02\x00\x04\x00\x00\x00\x01\x00\x00\x03A\xa0\x03\x00\x04\x00\x00\x00\x01\x00\x00\x01\xc1\x00\x00\x00\x00\x00\x00\x00\x06\x01\x03\x00\x03\x00\x00\x00\x01\x00\x06\x00\x00\x01\x1a\x00\x05\x00\x00\x00\x01\x00\x00\x01n\x01\x1b\x00\x05\x00\x00\x00\x01\x00\x00\x01v\x01(\x00\x03\x00\x00\x00\x01\x00\x02\x00\x00\x02\x01\x00\x04\x00\x00\x00\x01\x00\x00\x01~\x02\x02\x00\x04\x00\x00\x00\x01\x00\x00\x10H\x00\x00\x00\x00\x00\x00\x00\x96\x00\x00\x00\x01\x00\x00\x00\x96\x00\x00\x00\x01\xff\xd8\xff\xed\x00\x0cAdobe_CM\x00\x02\xff\xee\x00\x0eAdobe\x00d\x80\x00\x00\x00\x01\xff\xdb\x00\x84\x00\x0c\x08\x08\x08\t\x08\x0c\t\t\x0c\x11\x0b\n\x0b\x11\x15\x0f\x0c\x0c\x0f\x15\x18\x13\x13\x15\x13\x13\x18\x11\x0c\x0c\x0c\x0c\x0c\x0c\x11\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x01\r\x0b\x0b\r\x0e\r\x10\x0e\x0e\x10\x14\x0e\x0e\x0e\x14\x14\x0e\x0e\x0e\x0e\x14\x11\x0c\x0c\x0c\x0c\x0c\x11\x11\x0c\x0c\x0c\x0c\x0c\x0c\x11\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\xff\xc0\x00\x11\x08\x00V\x00\xa0\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xdd\x00\x04\x00\n\xff\xc4\x01?\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x01\x02\x04\x05\x06\x07\x08\t\n\x0b\x01\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x10\x00\x01\x04\x01\x03\x02\x04\x02\x05\x07\x06\x08\x05\x03\x0c3\x01\x00\x02\x11\x03\x04!\x121\x05AQa\x13"q\x812\x06\x14\x91\xa1\xb1B#$\x15R\xc1b34r\x82\xd1C\x07%\x92S\xf0\xe1\xf1cs5\x16\xa2\xb2\x83&D\x93TdE\xc2\xa3t6\x17\xd2U\xe2e\xf2\xb3\x84\xc3\xd3u\xe3\xf3F\'\x94\xa4\x85\xb4\x95\xc4\xd4\xe4\xf4\xa5\xb5\xc5\xd5\xe5\xf5Vfv\x86\x96\xa6\xb6\xc6\xd6\xe6\xf67GWgw\x87\x97\xa7\xb7\xc7\xd7\xe7\xf7\x11\x00\x02\x02\x01\x02\x04\x04\x03\x04\x05\x06\x07\x07\x06\x055\x01\x00\x02\x11\x03!1\x12\x04AQaq"\x13\x052\x81\x91\x14\xa1\xb1B#\xc1R\xd1\xf03$b\xe1r\x82\x92CS\x15cs4\xf1%\x06\x16\xa2\xb2\x83\x07&5\xc2\xd2D\x93T\xa3\x17dEU6te\xe2\xf2\xb3\x84\xc3\xd3u\xe3\xf3F\x94\xa4\x85\xb4\x95\xc4\xd4\xe4\xf4\xa5\xb5\xc5\xd5\xe5\xf5Vfv\x86\x96\xa6\xb6\xc6\xd6\xe6\xf6\'7GWgw\x87\x97\xa7\xb7\xc7\xff\xda\x00\x0c\x03\x01\x00\x02\x11\x03\x11\x00?\x00\xe7\x12I\x1f\x03\x14\xe6\xe7ca\x87l96\xb2\x90\xf2\'n\xf3\xb7~\xd9n\xed\xab=\xec\x89\x00\x12v\x02\xca\x04\x96\xf6\x1f\xd5\x9a\xb2\xebu\xd5d\xde\xfa\xbe\xca\xdc\xba\xcb1\x9b$\x17\x9a\r/e\x99m\xfd6\xe6?\xd8\xcb6>\xbf\xf0\xdf\xe0\xd5ln\x93\x82\xfc\x03\x97\x93\x98\xfa\x9d\xf6k2\xc5U\xd2,\x86W\x7f\xd8=\xcf}\xf5n}\x96\xfef\xdf\xfa\xf2<\'\xf6\xb1}\xe7\x16\xbe\xa3\xa1\x11>\x99\xfc\xd2\xdb\xf4\\xa4\x95\x8e\xa1\x89\xf6\x1c\xfc\x8c-\xe2\xdf\xb3\xd8k\xf5\x00\xda\x1d\x1f\x9d\xb2]\xb3\xfa\xbb\x95t\x19A\x04\x026"\xc7\xd5I$\x92\nRJ\xd5}3\xa8[\xe9\xfax\xef>\xb3\\xfa\x89\x86\x875\xa7k\xdd\xef-W:W\xd5n\xb3\xd5\xab\xba\xcc:\xeb#\x1e\xc3M\xa2\xcb\x03H{@s\xdb\x10\xff\x00\xa3\xb9\x11\x12t\x00\xac\x96\q\x04\xcaq\x88\x1b\xd9rR[\xd6}J\xebuY\xe9Z\xecZ\xed\x8d\xdb\x1dx\x07i\xdewj\xcf\xf8+\x7f\xed\xb7\xa8\xbb\xeawVln\xbb\r\xb2$N@\xe2}?\xdc\xff\x00H\xdfO\xfa\xe9\xde\xdc\xff\x00t\xfd\x8c\x7f}\xe5\xbf\xcfC\xfc`\xe1\xa4\xb7O\xd4\xde\xae9\xb7\x0chN\xb9\r\xe1\xb3\xbf\xf3\x7f3k\xb7(\xf5\x1f\xa9\xbdw\xa6\xe1[\x9d\x97]M\xa2\x80\x0b\xcbl\xdc`\x90\xcd\x1b\xb4~\xf2F\x13\x1a\x98\x9f\xb11\xe6\xf9y\x11\x18\xe5\x81$\xd0\x02Cr\xe2$\xaf\xf4\x8e\x9fFu\x99#"\xcbkf5M\xb0\n\x18,\xb1\xee}\x95\xe3WS\x19c\x98\xdfs\xed\xfd\xe5\xb2\xdf\xaa8B\xe6\xd5\x91vn8y{}GSE\x8d\x0e\xae\xbb2_[\x9b\x89\x93\x93o\xa9\xe9Qf\xd6zh\x08\x13\xb2rs\x18\xa0H\x91\xa2<\t\xe9\xc4\xf2\xe9.\xaf#\xea\x87L\xc5\xb5\x8c\xc9\xcc\xcc\xa9\xb6>\xca\x9bi\xc5\x05\xbb\xebw\xa6\xd6\xed\xad\xcf\xb5\xdfi\xff\x00\xb4\x9bj\xfdc\xfe1\t\xbfU1,v\xda\x9f\x9fdz`\xcd8\xf5\xc3\xed\xae\xbc\x96Q\xb7\'_\x97z\xcd\xae\xfa\xfdF#\xed\xcb\xb2\xc1\xce\xe0"\xf8\x8dw1\x90\x8f\xee\xee\xf3_L\xfam\xfe\xb0\xfc\xaa\xe7W\xc0\xa3\x06\xea\x1b\x8fe\x96W}>\xaf\xe9\x98+\xb1\x8e\x16[\x8deOc\x1c\xf6\xfb\x1fB\xa6\xcf\xa6\xdf\xeb\x0f\xca\x9aE\x16x\xc8J<Cb\xff\x00\xff\xd0\xe7\x15\x9e\x9b\x94\xcc.\xa3\x89\x98\xf0\\xcck\xab\xb5\xcd\x11$1\xdb\x9c\x1b\xba\x1b\xb9VIg\xbd\x91\x00\x82\x0e\xc4Q\xfa\xbdn-\xd8\x98\x95\xdb\x8b\x93\xd2\xf2\xb2\x18zp\xe9\xf4:\xc0\xc6X\xe7o\xb3_\xd6\xeck\xad\xae\x8d\xff\x00j\xc7\xb2\xbb\x7fK\xe9z\x08}?\xab\xf5\xce\x9d\x89\x8fE\x98\x8f\xcf\xb2\xd1\xb6\xca\xf2kcX\xdcv\xec\x1fe\xc3 \x7f\x86k\xe8\xba\xcb\xac\xfd\x0f\xab\xe8\xfe\xado\xe9\xb7\xf2\xbb[\x11\x1ax\'\xda\x06\x80s\xcaw\x19\xe9\xa55\xbe\xe9\x13|U.#\xc5+\x12\xf9\x87\xee\xfa\xfd\x1f\xe07:\xb5\xf6\xdf\xd4.u\xb7]\x90\xe6\x1fL?%\xa1\x97\x00\xdf\xf0W\xb5\x93\xfaZ]\xba\xa7_i$\x9aulF"1\x11\x1d\x05)$\x92<i\xca\x0b\x9b\x15g\xe6\xd5\xe9zw9\xa2\x82M`\x1d\x06\xef\xe7\x03\xbfy\xb6~{\x15\xee\x95\xf5\x9f\xac\xf4\x9a\xee\xaf\n\xc6\x06\xdfa\xba\xcd\xf5\x87\x12\xf2\x03\\\xef\xcd\xfa[R\x16\xfd]\x15RM.6\n\x8f\xab\x1e\xa1>\xaf\xb3\x9d\xc5\xb5lw\xe9=\xecz\xd7\xfa\xb5\xff\x002},\xdf\xda\xe6\x92~\xd2\xef\xb2\x9b\xc3\x83\xbd\x08o\xa5\xb7\xf9\x1b\xb7\xff\x00/\xfd"|A\xb1R\x03\xc6\xda\x99\xa7\x0fnFx%1\x7f/\x00\x97\x17\xa9\xa1o\xd7^\xbbq.\xbb\xec\xf68\x8d\xa5\xce\xa0LC\xd9\x1b\xb7n\xfa\x17\xde\xcf\xfa\xf5\xaa?\xf3\xc3\xab\x83"\xbc@@#Lv\xf0\xe9.\x1fK\xf3\xb7.\x8f+\xff\x00\x1b\xcfL}\x8b\xf6\x7f\xa9\xb8n\xf5\xb7\xed\xdb\xf9\xdfG\xf3\xd0H\xfa\x93\xa4;\xa6j\x1d \xb5\xc4\x03/\xf4\xff\x00\xae\xd77\xd2\xf5?\x9bR\xf0\xcf\xfc\xe8\xff\x00\x19\xa7\xee\xf2\xdf\xf8\x83\'\xfe\x13\x17\x07\xfewum\xa5\xbe\x9e&\xd26\x90(\x00A\x06\xb2\x04?\xd9\xecv\xcfb]C\xeb\x87^\xeaXV\xe0\xe5\xdb[\xa8\xb8\x01`ma\xa6\x01\x0f\xd1\xd3\xfc\x95\xd0\xe2\x7f\xcc(\x9c\xf3\xd3f4\x14\x07\xc13\xf4\xbd\xfe\xe6\xfb\x7f1W\xfa\xc1\xff\x000\xbfce~\xc9\xfb7\xdb\xf6\xb7\xd0\xf4\xf7o\x9d\xcd\x9d\xbf\xd9BBto :m\xc4\xbf\x16N\\\xce"<\x94\xe0L\x85H\xe2\x8cxM\xfc\xd6\xe2}Z{kwQ\xb9\xd62\x91N5V\xfa\x96\x87\x16\x03^N=\xad\x0f\xf4Ym\xbe\xf73g\xb2\xb5\xb7\x8a\xfc\x1aE\xd9\x98b\x9aX\xe7[\x9dq.\xcc\xbc\xbb}\x19\x98\xd4\xdb\xe8\xb7\xa7\xe2\\\xce\x9c\xcb2l\xf5\xf2\xd8\xefg\xd0\xf5}U\x99\xf53\xd4\xf5\xfa\xb1\xa9\xc1\x8foN\xb1\xc0\xb9\xa2\xc6\xe8\xe6\xbbk\xeaxslc\xfe\x83\xda\xae\xd3\x86\xf7[\x8c:\x83\x0fO\xa6\xacZ-\xc7}\x8c\x03 \xd1\x8a\xfb3r\xec\xa3"\xaf~5\xedk\xacg\xd8\xf0\xf6ezvb\xd9\xfc\xd5W!\x0b\xa0\xbb\x98\xe192\x02H\xf9n\x8e\xf10\x8f\x17\xea\xff\x00M\xb1\x87P\xcc\xb3\x07\x00\xd0\xea\xf3h`f7\xda\x1ba\xb1\xcc\xf57\xe6f\xe4\xda\xcc\x8d\x8fu?\xd2>\xc3\xf6\x8a\xaf\xe9\xb9\xff\x00\xa1\xfd"=\xb8\x83:\xf1~MU\xde\xfc{+\xccs_}\xac\xb2\xab+\xad\x98\x19L\xcb~?O\xc8\xc7\xb6\xb6\xe5t\\x96\xfd\xa2\xbfJ\xbf\xfbz\x85\x9dfQ\xca\xa7\x0b\xedU\x8c\xbc\xabn\xa3.\xcc\x06\x8a\x81\xb3\xd7>\xab\x9dU_\x9b\xf6\x8a\xff\x00Ig\xd9\xbf\xf6\xa5\xfaef\xae\xa1\x8d\x91\x9fKY\x97fNuls\x0eE\xf3n\x1e3lo\xd9\xec\xb2\x87\xdb\xfa;\xfd\x1bk\xa2\x8f\xb6\xd9\xfd5\x99\xfe\xa5\x9e\xad\x88\x82\x18e\t\x83z\xed/\x97\x8b\xd3\x7f5K\xe6\xf6\xf2\x7f/q\xc5\xfa\xd7U\x95e`\xfa\x8ec\xddn\x1f\xae]^\xed\x9f\xa7\xc8\xca\xc9\x1b=V\xd7g\xf8o\xcfb\xc6g\xd3o\xf5\x87\xe5Z\xff\x00Y\xb1\xec\xc6\xb3\xa6Quo\xa6\xda\xf0\x1a\xdbk\xb3l\xb5\xfe\xb6G\xa8\xd6\xfa_\xa3\xf4w\xff\x00G\xdb\xfe\x03\xd3Y\x0c\xfam\xfe\xb0\xfc\xaa)|\xc5\xd2\xe5\xff\x00\x99\x8e\xb7\xbe\xbf\xe1?\xff\xd1\xe7\x12I;Z\\H\x1a\x90\x0b\x8f\xc1\xa0\xbd\xdf\xf4Z\xb3\x9e\xc9d\x95\xd7\xf4~\xa7Y!\xf4m \xb1\xa6^\xcem\xfek\xf3\xff\x009W\xb7\x1a\xfaZ\xd7Z\xcd\xad|\xed2\x0c\xc1\xda\xee\x0f\xe6\xb9\x1a(\x13\x89\xda@\xf9\x14I$\x92\tRI$\x92\x94\x92I$\xa5\xe5)L\x92J^RL\x92Jv~\xac[\xe8\xdb\x9c\xff\x00Y\xd8\xed\xf4hm\x971\xe6\xb2\xd6;/\x16\xbb\x8f\xac\xc2\xd7W\xfa\'?\xdf\xb9n\xdb\x95\x97[2~\xd7\x1b\x03\xb2\x9bM\x1fm\xba\xf6\xdf\x8e\xdc<\xfb]\xf6\x8a]\x9d\x95\xf9\xf5c~\x91\xbe\x8f\xf2\x17%\x83\xd4s\xbau\x8f\xb7\n\xd1S\xedg\xa7d\xb1\x96\x072C\xf6\x96^\xcb\x19\xf4\x9a\xae3\xebG^\xac\xee\xaf"\xb6\x12\x08\x96\xe3c\x03\x07B4\xc7RF`\x00\r\xb53r\xd9\'9J<\x15/\xde\x94\xe3/\x961\xfd\x18\xbd\x15u?\x0f\xa4S\x85\xd3\xb2p\xc3\x0e\xdfS\x12\xc6\x91nU\xe4\xfb)\xba\xa6\xda\xe6\xba\xcc\xbb?S\xc8\xa7\xed\xb9X\x96\xe2\xfe\xb5\x8f\xfa\xbf\xe8\xd6c\xf2+\xea\x03\x13\t\xd9x\xd7\x9e\x9c\xe7W\x8b\x8eM\xd4\xd9n\xdd\x9d?\x1d\xce\xb2\xdb\xda\xdc+\x9f^/\xdb=:\xfd6c\xfe\x8a\xefO&\xcc\xab\xaaT\xc7\xd6\xef\xac\x804\x0c\xc6\x81\\x16\x01\x8f\x8f\xed-\x1b\x1b\xb7\xf4\x1e\xdd\xac\xf6(\xbb\xeb_\xd6\x17\xce\xfc\xa6;v\xae\x9c|s3\xe3\xfa\x04L\xe3\xe3\xf6\x7f\xe8K#\xcbg\x04\x93\xc0dI\x97\x17\x11\xbe)|\xdc_\xa9I\xf5\xa7!\xb99\x1d>\xd6\x978}\x880\xb9\xf6\x9c\x878\xb2\xfc\x9a\x9dg\xda\x8cz\xfe\xa3\x99\xbfz\xc7g\xd3o\xf5\x87\xe5G\xce\xea9\xbdF\xd6]\x9b`\xb6\xca\xd8_a\x0ce`0\x17=\xac\x0c\xa1\x95\xb3\xe9=\xc8\x0c\xfam\xfe\xb0\xfc\xa9\x926m\xb7\x8a\x06\x18\xc4Mi{\x1e/\xf9\xd2\x7f\xff\xd2\xe7\x12\xdcZ\t\x07i\x83\xa8\xff\x00bI\xc3\\\xed\x1a$\xc105\xe0IY\xcfd\xec3\x18\n\xf7\xdb\x83\x95o\xe9\x1c\xc2\xe7_\xee 0~\x8e\x1a\xf6\xee\xf4\xff\x00\x9d\xfe\xa2\x83\xc6\x1b\x83\x03\xb0\xae\xe6\xb75\x87"C\x9a\x03\x1b{}\xd6\xee\xfd=\x96\xfa\xb5\xedQ\xa2\xaa\xdav\xdf\xd3\xb3-./\r\x97<N\xe6\xed\xa1\x85\x8d\xd9\xfc\xd3\xf7\xbbw\xf8D\xefe\x15C]\xd3r\xeb}\x80\x90K\xec\x05\xcck?I\xed\xdd\xefo\xab\xfat\xe6\xb7^\xbfI\x7f\xeb\xe6v\xe2b\x8d\xdb:m\xcc\xda\xe7\xee\x1e\xbb\\\x03A\xde\xc6\xb7\xf4\x9e\xefg\xb3\xfe\x17\xf3\x13_\x81Q\xbb\xd3\xa3\xa7\xdbY\xb6\xdf\xb3\xd5[\xaek\x8f\xabcZ\xfa\x1b\xfc\xe7\xe6\xee\xfc\xef\xd1{\xd4\x1a\xdcv\x06\xef\xe9\xf9a\xad\xf4\x9e\xedlh\x1b\x86\xc7X\xdf\xd2{~\xd5w\xba\x97\xa1\xd8-f1q\xc6\xcac\xde&\xac\x89\xb2\x01\xa5\xd3}\x83\xf4\x8ek\x9a\xcff\xff\x00\xf4\x1b\x12H\xe2\xb1\xa9\xed\xa9?\xa5\xff\x00U\xfd\x16\xce7Mc\xea\rwL\xba\xdbd\x93cn\r\x05\x9b\x9bW\xb5\x8e\xb1\xff\x00\xcd\xbd\xe8O\xe9\xde\x88\xad\x97a[\xeaV\x1d\xeb\x9fQ\x80\xbfk\xc6\xe75\xad\xb0\xed\xfd\x1b}\x1d\xac\xfd\xfbm\xff\x00\x02\xa3p\xf5\xdc\x1f\x8d\x8d\x97]~\xa3X\xd8/\xb0\xc8n\xebi\x07\xd4\xfav0\xfa\x88Oh\xbb\x1a\xb3\x89\x8f\x95\xea\x87<\xd9x/{\x1e\x01\x11\xa0.\xf4\xdfEn\xd9bI\x1cW\xac\xb7:\xfc\xde\x9f?\xd6\xb6.\xaf\x002\xdb\xc7N\xb5\x944\xb8n\xf5~\x86\xe7\xec\xa7\x97\xbfw\xa7\xe9]_\xfe\n\xacY\xd2\x9bS\xdel\xe96\xb2\xb8t\x03\x90\xdd\xcd&\xbfU\x9az\x9e\xe6U\xb9\x96\xbb\xfe\xdaY#\x1b<\x9d*\xb8\x9d\x01\xd1\xdf\xe18\x0e\xfd\xdf[\xf9_\xce\'4\xf5 \x0c\xb3&\x00\xde\x7f\x9c:\x12\xd6o?\xd6s\xd8\xcf\xed\xa5\xf4I\x81\xd8d\xef\xbc\xa7\xd7o\xf2\x8d\xf7\xe3b\xd5C\xb2\xaf\xe9w2\xb0\xfd\xa4\x8b}\xa0\xba\xad\xccg\xf3\x9b\xfd\xb6~\x9br\xc91\'l\xc7i\xe7\xf8\xa3;\x1f<Huw\x8d\xa4\xb0\x87\x07\xe8c{\x99\xb5\xdf\xf0j\x1fg\xc8\xd4zO\x90\x01#i\xe1\xda\xb7\xfc\xe9@\xf9/\x80\xab\xb9_\xd4\xff\x00\xddJH\xd2Gv\x0es]\xb1\xf8\xd75\xe3B\xd7V\xe0t\x1b\xf8#\xf7=\xe8:\x8d\x0e\x85%\xe0\x83\xb1\xb5\x92I$\x14\xa4\x92I%)I\x9fM\xbf\xd6\x1f\x95EI\x9fM\xbf\xd6\x1f\x95%?\xff\xd3\xe7\x11(\x8fSW\xfaCk\x86\xf8\x9eZ\xefo\xfds\xf9\xb44\xe0\xc1\x06\x01\x8e\xc4H\xf9\xb4\xac\xe7\xb2;:\xf5d\xb0\x00\xe7u\x9bZ\xe6\xba\xa2\xdfd\x91 :\xf7\xfb\xfd\xdf\xa0v\xe63o\xf3\x89\xac\xba\x9b\x8dO\xb7\xab\xbd\xef\xa9\x8e\x0c/\xaav\x979\xdb\xebg\xd2\xfaU\xfe\x91W\xfd\xa5\x8d\x00\x0e\x9b\x8a\x00s\x9d\x10\xe3\xa3\x9c\xd7\xec\x93\xef\xd8\xcd\x9e\x93=\xdf\xcd\xefP\xfbv<i\xd3\xf1\x81\xf1\xfd!\xfd\xef\x17\xed\xfc\xff\x00\xfa\t\xd7\xfc\xb5`\xf6\xce\xfc$}0\xa7\xbe\xd6\xba\xc3`\xea\x8e\xb9\xf8\xf3\xf6w=\xb1;C}\r\x9a\xbf\xfe/\xd2\xff\x00\x04\x8bm\xf5\xbc\x86\xfe\xd9{\xebn\xe6\xfd\x02\xd8m\x9f\xce3n\xdf\xd21\xf0\xcfW\xff\x00F_M\xcd\xa1\xad\xdb\xf6\x1a\x0e\x84\x02\xed\xc4\xea\x1b\xac\xff\x00\'g\xb1J\xae\xa3En\x04\xf4\xfck\x00 \x90\xf0L\xc1\xdf\xb4\xff\x00[\xe8\x7fQ+\xfeZ\xa4\xe344:m\xfc\xd7\xfd\xeav\xdc\xd6]Sk\xea\x8feNt\xd9v\xcf{_\xb3n\xf0\xd1\xb5\xcf\xaf\xfc\x0f\xbd\xff\x00\xcd\xfa\x7f\xf5\xb9V\xfcv\xd5\xed\xea\xefi\x10\xe1P\xac\x01\xb9\xe4\xfa\xedo\xe6\xb7\xff\x00FoT\xea\xcd\xa1\x8cs]\x85E\xb2Ac\x9d\xbbs}\xce\xb2\to\xf3\x9b\xb7z_\xf1H\x87\xa8b\x98\x07\xa6\xe3\x80\x04{K\x81>\xd7W.w\xbb\xf7\xbdO\xf8\xc4\xaf\xf9j\xa3\x03\xd8\xff\x00\xe3>\xa4\xc7 \x8d\xf5\xb7\xaa?c\xdf\xae\x82\x1c+\'\xd1\xb1\xdbG\xfd\x04\xde\xbb\x1a\xc75\xbdM\xee\x1e\x99\x01\xa5\x90f\x1bkk\xf7n\xf6:\xe6\xfd?\xa6\xaa\xd5\x99S\x00k\xf0\xe8\xb4\x00\x07\xb8\x10\xe3\x01\xed\xdc^\xd3\xf4\xdd\xbf\xdf\xff\x00\x16\xc5\x07\xdd[\xafm\xa2\x861\xa0\xb4\xba\x96\x93\xb1\xdb\x7f\x92\xe9\xd9\xbf\xf3\xd2\xb4\x8cz\xec~\xccm\xbb\xb2\x9eXv\xf5\'X\xe0\xe2\xe6\x82\x03N\xe2\x03_\xacn\xdc\xf6\xff\x00\x9f\xb1U\xfbvl\xb4\xfa\xcf\x05\xa3kH0@\x1c7A\xf9\xb0\x8d\xfbB\x8d\xafh\xc1\xa1\xbb\xc4Kd~\x7f\xaa7Hw\xb7o\xe8vW\xe9~\x8d@fR,/8X\xee\x1a\xc3\x08ph\x98\xfd\xd2\xd4\xbe\xa9\x8ckx\x7f\xd0\xff\x00\xb9S\xba\xa7S{\x8b\x9f\x95c\x9c\xe7\x17\x92H\x92\xe26\xef:}=\xbf\x9c\xab\x12\I<\x9f\x01\x1f\x91Y\xfbm0\xf1\xf6\x1cs\xbc\x92\x0c:[-\x0c\xdb\;\xf3\x7f\x9c\xff\x00\x8cUG\x08\x1f5\xd1\x00m\x1e\x1f\xf1\x7f\xeeT\x910$\xf6I"$\x11\xe3\xa2\x0b\xdb\xae\xe8\xddU\xac\xf5\x1d\x8c\xe6\xb3\xd1vPq-\x83K6\xef\xb8{\xbe\x8b}F_\xae\xaa\xe6\xee.\xad\xed\r :X\xe1\x04\xfd\x10\xe9o\xb7r\xbaz\xdeQf\xc0\xc6\x80Z\xd6:]k\x83\xab\x10\x1dC\x9be\xaeo\xa5n\xdf\x7f\xfd\x04W}e\xea\xaex\xb3\xd4sHn\xdd,\xb7X>\xd3\xb8\xd9\xbf\xdb\xefo\xfdq;F\x11,\xddc\x13\xf5\xe1\xff\x00\xbfr\xbe:\x1f\x03\xa2\x93>\x9b\x7f\xac?*\x9eNE\x99Y\x16d\xd9\xfc\xe5\xce\xdc\xedK\xb5\xfe\xbd\x85\xd6;\xfbnPg\xd3o\xf5\x87\xe5A\x97Z\xd7M\x1f\xff\xd4\xe7\x12\jK9\xec\x9e\xc9%\xc6\xa4\x92\x9e\xc9%\xc6\xa4\x92\x9e\xc9%\xc6\xa4\x92\x9e\xc9%\xc6\xa4\x92\x9e\xc9%\xc6\xa4\x92\x9e\xc9%\xc6\xa4\x92\x9e\xc9%\xc6\xa4\x92\x9e\xc9%\xc6\xa4\x92\x9e\xc9I\x9fM\xbf\xd6\x1f\x95qi$\xa7\xff\xd9', 'jfif_version': (1, 1), 'jfif_density': (150, 150), 'dpi': (150, 150)}
```

convert 1.jpg to CMYK
```python
im.convert('CMYK').save('2.jpg',dpi=(150,150))
```

then

```python
im = Image.open('3.jpg')

 im.info

{'adobe': 100, 'adobe_transform': 100}
```

**Comment by radarhere** [comment] 2016-01-23 01:22
I can tell you that when the file is being re-read, it looks like the APP0 (JFIF and DPI) and APP1 (EXIF) markers are missing, and the APP14 (Adobe) marker is being read instead.

`convert Tests/images/hopper.jpg -colorspace CMYK test.jpg` preserves the DPI and JFIF data without a problem, so I can confirm that this is a bug with Pillow.

**Comment by zhanglc** [comment] 2016-01-23 04:51
any idea for temporary fix?

**Comment by radarhere** [comment] 2016-01-23 04:55
If your use case allows it, the ImageMagick command I mentioned above could serve you well. Otherwise, I doubt that there will be a temporary fix before the actual fix.

**Comment by zhanglc** [comment] 2016-01-23 05:07
<code>im.convert('CMYK').info </code>

<code>
{'jfif': 258, 'jfif_unit': 1, 'adobe': 100, 'jfif_version': (1, 2), 'jfif_density': (350, 350), 'dpi': (350, 350), 'adobe_transform': 100}
</code>

but when save ,the info lost ,does it mean that ,the save method has a issue ?

**Comment by radarhere** [comment] 2016-01-23 05:08
Yes, that is my current assessment.

**Comment by wiredfool** [comment] 2016-01-23 11:00
Is the metadata preserved if opening and saving as a plain RGB jpeg?

**Comment by radarhere** [comment] 2016-01-24 01:08
from PIL import Image
	im = Image.open('Tests/images/pil_sample_rgb.jpg')
	im.info.keys()
	>>> dict_keys(['exif', 'adobe', 'dpi', 'jfif', 'adobe_transform', 'icc_profile', 'jfif_unit', 'jfif_version', 'jfif_density'])

	im.save('test.jpg')
	Image.open('test.jpg').info.keys()
	>>> dict_keys(['jfif_density', 'jfif_version', 'jfif', 'jfif_unit'])

	im.save('test.jpg',dpi=im.info['dpi'])
	Image.open('test.jpg').info.keys()
	>>> dict_keys(['dpi', 'jfif_density', 'jfif_version', 'jfif', 'jfif_unit'])

	im.save('test.jpg',exif=im.info['exif'])
	Image.open('test.jpg').info.keys()
	>>> dict_keys(['exif', 'jfif_density', 'jfif_version', 'jfif', 'jfif_unit'])

	im.save('test.jpg',dpi=im.info['dpi'],exif=im.info['exif'])
	Image.open('test.jpg').info.keys()
	>>> dict_keys(['exif', 'dpi', 'jfif', 'jfif_unit', 'jfif_version', 'jfif_density'])

**Comment by wiredfool** [comment] 2016-01-24 21:11
So, it's not CMYK, it's the jpeg encoder.

**Comment by dawncold** [comment] 2017-07-07 06:34
yes, it's jpeg encoder. I added resolution info via `exiftool -xresolution=300 -yresolution=300 xxx.jpg`

**Comment by radarhere** [comment] 2020-05-24 14:02
PR #4639 has a fix to resolve this. If that PR is merged in, then it's just a matter of using the `dpi` and `exif` arguments when saving, and this should be fixed.

```python
from PIL import Image
im = Image.open("in.jpg")
im.save("out.jpg", dpi=im.info['dpi'], exif=im.info['exif'])
```

**Comment by hugovk** [comment] 2020-06-20 12:56
Fixed by https://github.com/python-pillow/Pillow/pull/4639. Nice to squash a 4.5 year old bug!

**Closed by hugovk** 2020-06-20 12:56 UTC
Labels: Bug
