### ISSUE TITLE
UnboundLocalError: local variable 'photoshop' referenced before assignment

### ISSUE THREAD

**Issue by kyamagu** [python-pillow/Pillow#3772] opened 2019-04-05 08:03 UTC
The following line throws an `UnboundLocalError`.
https://github.com/python-pillow/Pillow/blob/d61ab018fe4cfeb1ffe5305f8cb6bc860abb3d2a/src/PIL/JpegImagePlugin.py#L139

Apparently, this if-else condition does not cover all the cases.
https://github.com/python-pillow/Pillow/blob/d61ab018fe4cfeb1ffe5305f8cb6bc860abb3d2a/src/PIL/JpegImagePlugin.py#L108

**Comment by radarhere** [comment] 2019-04-05 08:04
This is a duplicate of #3769

**Closed by radarhere** 2019-04-05 08:04 UTC
Labels: Duplicate

**Comment by radarhere** [comment] 2019-04-05 08:49
I don't suppose that the image that you found this issue with is one that you are able to provide for inclusion in the test suite under Pillow's license?

**Comment by kyamagu** [comment] 2019-04-05 08:58
@radarhere You can include the following small JPG in the test suite. The file is extracted from Adobe PSD file's thumbnail resource.

![example](https://user-images.githubusercontent.com/1190780/55616107-1217b800-57cc-11e9-8b67-91231a66ff9d.jpg)

BTW: I'm the author of [psd-tools](https://github.com/psd-tools/psd-tools). Thanks for maintaining the great tool!

**Comment by radarhere** [comment] 2019-04-05 09:04
@kyamagu thanks, and thanks for the image
