### ISSUE TITLE
Invalid character spacing

### ISSUE THREAD

**Issue by Askaniy** [python-pillow/Pillow#7765] opened 2024-01-30 17:55 UTC
### What did you do?
Switched project development from openSUSE global Python environment to a virtual environment. 

### What did you expect to happen?
No changes in font rendering.

### What actually happened?
Wrong font spacing appears. This results in uneven letter spacing and uneven alignment. Seems quite similar to https://github.com/python-pillow/Pillow/issues/3977 
I checked with different TrueType fonts, the problem persists.
There is confirmation that others in the virtual environment have the same render. And the problem has persisted for more than a year.
No bug on 9.1.1 and earlier ones.
On 9.2, the bug behaves a little different: rounding seems to be changed to the other side, and the effect sometimes disappears.

### What are your OS, Python and Pillow versions?

* OS: Linux, openSUSE Tumbleweed
* Python: the bug tested on versions 3.9−3.11
* Pillow: 
   * [PyPI version](https://pypi.org/project/pillow/): version >=9.2.0
   * [openSUSE version](https://software.opensuse.org/package/python311-Pillow): the bug has never been observed, the version installed now is 10.2.0

```python
from PIL import Image, ImageDraw, ImageFont
from pathlib import Path

noto = 'NotoSans-DisplayCondensed.ttf'

img = Image.new('RGB', (32, 32), (0, 0, 0))
draw = ImageDraw.Draw(img)
font = ImageFont.truetype(noto, 12)

draw.text((16, 16), '00000', fill=(230, 230, 230), font=font, anchor='mm')

img = img.resize((img.width*16, img.height*16), Image.Resampling.NEAREST)
img.save(Path(__file__).parent.resolve()/'test_img.png')
```

Comparison of the bagged and not-bagged test results:
![image](https://github.com/python-pillow/Pillow/assets/44873271/86913619-107a-48f6-ba65-3452bc3e6778)

The impact of this bug on [the project](https://github.com/Askaniy/TrueColorTools) looks like this:
- [no-bug version (9.1.1 and openSUSE's one)](https://github.com/python-pillow/Pillow/assets/44873271/4aaa08fc-8dfa-4e78-8ee0-31ae41f4f655);
- [bugged version (9.2.0)](https://github.com/python-pillow/Pillow/assets/44873271/8a9fa5fb-61e3-429a-8d06-f114315f5a40);
- [bugged version (actual)](https://github.com/python-pillow/Pillow/assets/44873271/7f7ac902-5630-4df2-bebc-85ff83679b98).

**Comment by nulano** [comment] 2024-01-30 18:29
This looks like a duplicate of #4483, partially related to #7747 and #6871 as well.
I expect adding `layout_engine=ImageFont.Layout.BASIC` will produce the results you expect:
```python
font = ImageFont.truetype(noto, 12, layout_engine=ImageFont.Layout.BASIC)
```

To explain a bit: Pillow can use different methods to compute the positions of glyphs used when rendering text. BASIC layout simply converts character values directly to corresponding glyphs and sums their offsets. RAQM layout uses the libraqm library (which supports more advanced text layout and is recommended for all non-English text) to compute glyph mappings and positions. While BASIC layout rounds the current offset to an exact pixel after each glyph, RAQM layout doesn't seem to do this and IIRC libraqm did not support this at all when I tried it in the past. However, I would not call this a bug, just a different approach to the same problem -- making sure glyphs are rendered at exact pixel coordinates to avoid artifacts.

**Comment by Askaniy** [comment] 2024-01-30 18:43
Yes, thanks a lot! The following line reproduces the 9.1.1 behavior.

This is not related to the issue, but can you tell me if there is a solution to the problem of subpixel rendering of shapes such as `rounded_rectangle`?

**Closed** 2024-01-30 18:54 UTC
