### ISSUE TITLE
Pillow not working on Python 3.6.5, macOS 10.10

### ISSUE THREAD

**Issue by justvanrossum** [python-pillow/Pillow#3177] opened 2018-06-12 09:21 UTC
### What did you do?

Install Pillow on macOS 10.10, with pip 9.0.3 and Python 3.6.5

### What did you expect to happen?

A working PIL installation

### What actually happened?

An `ImportError` when I try to import `PIL.Image`

### What versions of Pillow and Python are you using?

```python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> PIL.__version__
'5.1.0'
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/just/code/git/virtualenvironments/pillowtest/lib/python3.6/site-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/just/code/git/virtualenvironments/pillowtest/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Users/just/code/git/virtualenvironments/pillowtest/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/just/code/git/virtualenvironments/pillowtest/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib
>>> 
```

**Comment by hugovk** [comment] 2018-06-12 09:41
This is a duplicate of https://github.com/python-pillow/Pillow/issues/3068, which will be fixed in the next release, likely 5.2.0 which is due out around 2018-07-01.

**Closed by hugovk** 2018-06-12 09:41 UTC
