### ISSUE TITLE
DPI doesn't work for CMYK save

### ISSUE THREAD

**Issue by 007gzs** [python-pillow/Pillow#3970] opened 2019-07-15 11:03 UTC
### What did you do?
save a jpeg image where param dpi
### What did you expect to happen?
the new jpg image dpi same as the dpi param
### What actually happened?
new file doesn't have dpi info
### What are your OS, Python and Pillow versions?

* OS: window7/centos 7
* Python: 2.7.5/3.6.8
* Pillow: 6.1.0

```python
    from PIL import Image
    img = Image.open("test1.jpg")
    print("test1.jpg", img.info.get('dpi'))
    other_img = Image.open("test2.jpg")
    print("test2.jpg", other_img.info.get('dpi'))
    img.paste(other_img.resize((200, 200), Image.LANCZOS), (0, 0))
    img.save("test3.jpg", dpi=(300, 300), quality="keep")
    new_img = Image.open("test3.jpg")
    print("test3.jpg", new_img.info.get('dpi'))
```
[sample_file.zip](https://github.com/python-pillow/Pillow/files/3391932/data.zip)

**Comment by radarhere** [comment] 2019-07-15 11:28
Looks like this is because the image is in CMYK mode -

```python
from PIL import Image
im = Image.new("CMYK", (100, 100))
im.save("out.jpg", dpi=(300, 300))

new_im = Image.open("out.jpg")
print("out.jpg", new_im.info.get('dpi'))  # out.jpg None
```

**Comment by radarhere** [comment] 2019-07-15 11:59
You may or may not be interested in this as an immediate solution - remove the 'quality' argument, convert to RGB, and it works -

```python
from PIL import Image
img = Image.open("test1.jpg")
print("test1.jpg", img.info.get('dpi'))
other_img = Image.open("test2.jpg")
print("test2.jpg", other_img.info.get('dpi'))
img.paste(other_img.resize((200, 200), Image.LANCZOS), (0, 0))
img.convert("RGB").save("test3.jpg", dpi=(300, 300))
new_img = Image.open("test3.jpg")
print("test3.jpg", new_img.info.get('dpi'))
```

**Comment by 007gzs** [comment] 2019-07-15 12:02
but I need to save it in CMYK format for my users to print.

**Comment by radarhere** [comment] 2019-07-15 12:05
Is saving it as TIFF an option?

```python
from PIL import Image
img = Image.open("test1.jpg")
print("test1.jpg", img.info.get('dpi'))
other_img = Image.open("test2.jpg")
print("test2.jpg", other_img.info.get('dpi'))
img.paste(other_img.resize((200, 200), Image.LANCZOS), (0, 0))
img.save("test3.tiff", dpi=(300, 300), quality="keep")
new_img = Image.open("test3.tiff")
print("test3.tiff", new_img.info.get('dpi'))
```

**Comment by radarhere** [comment] 2019-07-15 12:29
Actually, I've realised that this is a duplicate of #1676

**Closed by radarhere** 2019-07-15 12:29 UTC
Labels: Duplicate, JPEG
