### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by Coolgamerguy4793** [python-pillow/Pillow#4416] opened 2020-02-11 20:15 UTC
### What did you do?
Tried to run: from PIL import Image
### What did you expect to happen?
To get access to the Image package contained in PIL
### What actually happened?
I got the error:
```
ImportError: cannot import name '_imaging' from 'PIL'
```
### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.8.1
* Pillow: 7.0.0

```python
from PIL import Image
```

**Comment by radarhere** [comment] 2020-02-14 20:33
How did you install Pillow?

**Comment by Coolgamerguy4793** [comment] 2020-02-14 21:20
> How did you install Pillow?

I installed it from PIL

**Comment by radarhere** [comment] 2020-02-14 21:28
Did you run `pip install Pillow`, or are you saying that you ran `pip install PIL`? If you ran `pip install PIL`, then you should know that PIL does not support Python 3, so that will not ultimately work for you.

I presume you did not try and build Pillow from source.

Could you post the output of the following code?
```python
import PIL
print(PIL)
```

**Comment by radarhere** [comment] 2020-02-20 08:58
Also, be aware of the documented instructions for installing Pillow using pip - https://pillow.readthedocs.io/en/latest/installation.html#windows-installation

```
python -m pip install --upgrade pip
python -m pip install --upgrade Pillow
```

**Comment by radarhere** [comment] 2020-02-26 09:44
Googling, I found suggestions that you might have PIL installed alongside Pillow. Could you try uninstalling Pillow, checking that you can no longer `import PIL`, and then re-installing Pillow?

I presume that you haven't created a script named PIL.py that could be interfering.

**Comment by HTG-YT** [comment] 2020-02-29 06:16
Having the same issue here, however I am pretty sure that they aren't installed side by side, with proof here:
![image](https://user-images.githubusercontent.com/39023054/75602224-13746200-5abb-11ea-9abb-6cfa47b48be0.png)

**Comment by radarhere** [comment] 2020-02-29 06:59
@HTG-YT what operating system are you using? How did you install Pillow?

Could you post the output of the following code?
```python
import PIL
print(PIL)
```

**Comment by HTG-YT** [comment] 2020-02-29 08:02
My operating system is Windows 10 Home.

The output of the code is as below:
![image](https://user-images.githubusercontent.com/39023054/75603802-e3808b00-5ac9-11ea-9638-4dd08406ece8.png)

**Comment by HTG-YT** [comment] 2020-02-29 08:20
and this is the traceback:
```python
Traceback (most recent call last):
  File "C:\Users\85251\PycharmProjects\HarTex discord.py\venv\lib\site-packages\discord\ext\commands\bot.py", line 596, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\85251\PycharmProjects\HarTex discord.py\cmds\levelling_system.py", line 12, in <module>
    from PIL import Image, ImageDraw, ImageFont
  File "C:\Users\85251\PycharmProjects\HarTex discord.py\venv\lib\site-packages\PIL\Image.py", line 69, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\85251\PycharmProjects\HarTex discord.py\venv\lib\site-packages\PIL\__init__.py)
```

**Comment by HTG-YT** [comment] 2020-02-29 08:26
So with the traceback I wonder if it is a problem of the PIL package.

**Comment by radarhere** [comment] 2020-02-29 08:32
#4149 may be of interest to you

**Comment by HTG-YT** [comment] 2020-02-29 08:43
That doesn't seem to work in the built-in terminal of PyCharm

**Comment by HTG-YT** [comment] 2020-02-29 08:43
Did that `miniconda3` mean I have to install external stuff to my computer?

**Comment by shiba24** [comment] 2020-04-06 08:04
I am getting the same error. I'm using virtual env - how is it resolved without miniconda?

**Comment by radarhere** [comment] 2020-04-21 10:41
I don't want to suggest that you have to use miniconda, I'm just attempting to provide another situation in the hope that it will help and lead you towards a solution. https://stackoverflow.com/questions/55419368/in-pycharm-importerror-dll-load-failed-the-specified-module-could-not-be-found, for example, is a person who has a similar problem to this, with Anaconda, and resolves it by adding the interpreter to PyCharm. So maybe the interpreter settings could be a solution here?

**Comment by HTG-YT** [comment] 2020-05-12 02:17
Well after I updated to newer version so pip, the problem is resolved.

**Closed** 2020-05-12 03:42 UTC
Labels: Windows

**Comment by Linkontoask** [comment] 2020-06-29 01:48
@HTG-YT I would like to know in which environment the problem was solved. I also tried to use the built code in the project.
+ Python: 3.7.3
+ Pillow: 5.2.0 (7.1.2 have tried)

**Comment by padfoot-y2m** [comment] 2020-08-28 13:07
I am using pycharm and I installed pillow from the settings,the version in 7.2.0. I am facing the same problem and after i type import PIL
print(PIL) i get this: <module 'PIL' from 'C:\\Users\\Prottoy Mobin\\PycharmProjects\\python_1\\venv\\lib\\site-packages\\PIL\\__init__.py'>
I am new in programming,please help me solve this issue.

**Comment by radarhere** [comment] 2020-08-28 22:19
The solution for @HTG-YT was to upgrade pip, so you might try
```python
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade Pillow
```

**Comment by etasnadi** [comment] 2020-12-02 18:49
Same issue here: `ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)` when using `scikit-image` (Pillow 7.0). Upgraded to 8.0.1 and it works.

**Comment by richtong** [comment] 2021-02-04 22:22
I'm getting this error on a Mac after running

```
brew install python@3.8
pip install Pillow
```

Then 

```
from PIL import images
```

This fails with the line

```
ImportError: cannot import name '_imaging' from 'PIL' (/usr/local/lib/python@3.8/PIL/__init__.py
```

The Pillow version is 8.2

I also tried this with conda and with:

```
conda activate test-driver
conda install Pillow
```

But when running this I get Pi

```
import PIL
PIL.__version__
from PIL import Images
```

I get nearly the same error

```
>>> PIL.__version__
'8.1.0'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Images' from 'PIL' (/usr/local/Caskroom/miniconda/base/envs/test-driver/lib/python3.8/site-packages/PIL/__init__.py)
```

So did something change with Pillow v8.1.0?

**Comment by radarhere** [comment] 2021-02-04 22:26
> from PIL import images
> from PIL import Images

For one thing, these are incorrect. It is `from PIL import Image`

**Comment by richtong** [comment] 2021-02-05 22:34
Yes that was problem, I just realized. I'm an idiot!!!

Sent via Superhuman ( https://sprh.mn/?vip=rich@tongfamily.com )

**Comment by ivanstepanovftw** [comment] 2021-09-04 18:39
PyPy3 enjoyer is here.
Environment: Windows 10 x64 under VMWare Player. Installation was:
```shell
choco install make pypy3 
pypy3 -m ensurepip
pypy3 -m pip install pillow
```

```shell
Python 3.7.10 (51efa818fd9b, Apr 04 2021, 12:09:32)
[PyPy 7.3.4 with MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>> import PIL
>>>> print(PIL)
<module 'PIL' from 'C:\\Users\\Ivan Stepanov\\AppData\\Roaming\\PyPy\\PyPy37\\site-packages\\PIL\\__init__.py'>
>>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ivan Stepanov\AppData\Roaming\PyPy\PyPy37\site-packages\PIL\Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging'
```

**Comment by radarhere** [comment] 2021-09-04 23:55
Did you want to try
- uninstalling Pillow
- check that you can't import it at all, to confirm that you don't have more than one copy installed
- and then
```
pypy3 -m pip install --upgrade pip
pypy3 -m pip install --upgrade Pillow
```

**Comment by rabiyulfahimhasim786** [comment] 2022-01-19 07:32
I am also facing an same issue but i sloved it using these below references -

Installations of PIL on wondows 10
[https://www.geeksforgeeks.org/how-to-install-pil-on-windows/](https://www.geeksforgeeks.org/how-to-install-pil-on-windows/)

Tutorials of pillow
[https://pillow.readthedocs.io/en/stable/handbook/tutorial.html](https://pillow.readthedocs.io/en/stable/handbook/tutorial.html
)

`pip install pillow`

Requirement already satisfied: pillow in c:\users\admin\anaconda3\lib\site-packages (8.4.0)
Note: you may need to restart the kernel to use updated packages.

`pip install PIL`

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL

```
import PIL

print(PIL)

PIL.__version__
```

<module 'PIL' from 'C:\\Users\\Admin\\anaconda3\\lib\\site-packages\\PIL\\__init__.py'>

'8.4.0'

`conda install -c anaconda Pillow`

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

`PIL.__version__`

`from PIL import Image `

`#make sure i should be caps in Image`

`Im = Image.open('53220.jpg')`

`type(Im)`

`Im`

`#It will showing an image`

`Im.show()`

`Im.size`

`#It will shows the size of an image`

**Comment by kernc** [comment] 2022-09-15 07:22
Mere `pip --upgrade` no longer reinstalls.

`pip install --force-reinstall pillow` fixed it for me.

**Comment by jason-s** [comment] 2023-02-03 19:52
> pip install --force-reinstall pillow fixed it for me.

That worked here too. Somehow conda's version isn't working (I had pillow 9.4.0, same error)

**Comment by vincent-bruel** [comment] 2023-03-28 10:55
+1 
pip install --force-reinstall pillow
worked also for my config:
ubuntu 22.04LTS
python 3.11.2
pip 23.0.1
