### ISSUE TITLE
cannot import name '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by RichardAntalik** [python-pillow/Pillow#3342] opened 2018-09-08 22:32 UTC
### What did you do?
import pillow Image module from within Blender

### What did you expect to happen?
module to be imported

### What actually happened?
Module did not import
```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\john\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\john\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\__init__.py)
```
### What versions of Pillow and Python are you using?

python 3.7.0
pillow 5.2.0

When I run python console, I can use pillow without problems.
When I run (same) python console from within blender pillow will not load.
I tried this with numpy, and result is the same

From what I know, blender, python and pillow should be compiled using the "same" compiler. Normally with blender you build python and numpy and I can use them.
I am using MSVC 2017 runtime v140.

Is there a way to make this work without building pillow?

**Comment by OHRjo** [comment] 2018-09-09 04:01
Hi guys, 

I have the same problem here. I did "pip install wordcloud", wordcloud, pillow and numpy were installed together as a package. 
Current installed: 
wordcloud 1.5.0
pillow 5.2.0
numpy 1.14.2

I am getting an error:

**ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: 5.2.0
Pillow version: 5.0.0**

Is it the PIL problem or the wordcloud problem?

**Comment by radarhere** [comment] 2018-09-09 04:27
@OHRjo you're receiving a different error message, so that's a different problem. The error is telling you that the compiled C code comes from one version of Pillow (5.2.0), while the Python code comes from another (5.0.0). I would recommend uninstalling and reinstalling Pillow.

**Comment by hugovk** [comment] 2018-09-09 05:28
@OHRjo If you're using Conda, it's a duplicate of https://github.com/python-pillow/Pillow/issues/2945 (which also affected Wordcloud users on Windows). See https://github.com/python-pillow/Pillow/issues/2945#issuecomment-356905216 for a workaround, or see https://github.com/conda-forge/pillow-feedstock/issues/45 for a proposed Conda fix you can test.

**Comment by RichardAntalik** [comment] 2018-09-09 09:55
@radarhere
> When you say 'I tried this with numpy, and result is the same', you mean that unrelated to Pillow, numpy will also not import for you within Blender, giving you a different error, yes?

Yes different error, not loading.


>You say 'Normally with blender you build python and numpy and I can use them' - so what is the difference between this time and 'normally'?

In blender I can select which python I want to use.
With built python, I can load built numpy, but not pillow. I tried import from command line, eliminating blender influence, still same issue...

I switched python to another one(installed with installer) I confirmed, that this is another python.
I could not load pillow or numpy.

maybe it's worth noting, that I was not able to install pillow using pip with built python
https://pastebin.com/iGqeiQpN
But as I said, I can use the other python...

**Comment by RichardAntalik** [comment] 2018-09-16 14:07
> What is the error you receive when you 'tried this with numpy'?
```
>>> import numpy
Traceback (most recent call last):
  File "C:\Users\john\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray' from 'numpy.core' (C:\Users\john\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\john\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\john\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\john\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\john\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\john\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray' from 'numpy.core' (C:\Users\john\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\__init__.py)
```

> Could you run the following from the Python console where Pillow is working?
> 
> >>> from PIL import _imaging
> >>> _imaging


```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> from PIL import _imaging
>>> _imaging
<module 'PIL._imaging' from 'C:\\Users\\john\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PIL\\_imaging.cp37-win32.pyd'>
>>> 
```

**Comment by radarhere** [comment] 2018-09-29 02:26
Hmm. I was hoping that the `_imaging` path would be different to the first path that you posted here, but that was not the case.

https://blenderartists.org/t/blender-2-78-python-3-5-2-and-pil-pillow/689470 is a thread that has ideas on how to get Blender working with Pillow. Part of that thread suggests going inside your Blender install, using the Python version there to install pip, and then using that pip to install Pillow. I like this plan. Could you let me know what you think of it?

**Comment by RichardAntalik** [comment] 2018-09-29 11:36
I've read that thread, PIP installation fails on blender bundled python. I think, that some dev said, that in future release pip may be shipped with blender/supported. I can try then.

I can confirm, that system python and blender are linked against same runtime lib.

Also there is tool dependency walker mentioned - when I open both instances of pil imaging module I got same result:
![dep](https://user-images.githubusercontent.com/8494974/46245331-ee992e00-c3a0-11e8-93bf-6c50d17f3eff.png)

maybe I have to set up path to these files?

**Comment by radarhere** [comment] 2019-04-28 23:47
@RichardAntalik did you ever resolve this situation?

**Comment by RichardAntalik** [comment] 2019-04-29 06:11
Actually, tried it this time, and I was able to import Image module.

I did 
`...\2.80\python\bin>python.exe -m pip install --upgrade pip setuptools wheel`
and
`...\2.80\python\bin>python.exe -m pip install pillow --user`
got pillow 6.0.0

You can close this

**Comment by radarhere** [comment] 2019-04-29 06:11
Thanks

**Closed** 2019-04-29 06:11 UTC
Labels: Install, Windows
