### ISSUE TITLE
Truevision TGA open error ("struct.error: unpack requires a bytes object of length 4")

### ISSUE THREAD

**Issue by filonik** [python-pillow/Pillow#1550] opened 2015-11-22 17:10 UTC
Attempting to open a TGA image (any image will do, e.g. one of those [1]) in Pillow 3.0.0 results in the following error:

	[ERROR] PIL.ImageFile: %s
	Traceback (most recent call last):
	  File "c:\Python34\lib\site-packages\PIL\ImageFile.py", line 100, in __init__
		self._open()
	  File "c:\Python34\lib\site-packages\PIL\CurImagePlugin.py", line 71, in _open
		self._bitmap(i32(m[12:]) + offset)
	  File "c:\Python34\lib\site-packages\PIL\_binary.py", line 49, in i32le
		return unpack("<I", c[o:o+4])[0]
	struct.error: unpack requires a bytes object of length 4

[1] http://www.quake3world.com/forum/viewtopic.php?t=9242

**Comment by radarhere** [comment] 2015-11-23 08:41
Hi. Maybe I'm just missing something, but I can't find links to TGA files on that page. Would you be able to post a direct link?

Also, just to point out, it can't be all TGA images generating this problem as the Pillow's tests still pass.

**Comment by filonik** [comment] 2015-11-23 10:28
Sorry, I was referring to those in the ZIP files. Here's a direct link:

http://www.zfight.com/misc/files/textures/envmap_grimmnight.rar

(Unfortunately, GitHub does not allow TGA attachments.)

**Comment by radarhere** [comment] 2015-11-24 09:03
I am unable to replicate the error with the linked file - no errors are generated when I open the TGAs.

**Comment by filonik** [comment] 2015-11-24 09:31
Strange, it is definitely giving an error for me, not sure why.

	c:\Python34\Scripts\pip3.4.exe install Pillow
	Downloading/unpacking Pillow
	Installing collected packages: Pillow
	Successfully installed Pillow
	Cleaning up...

	c:\Python34\python.exe
	Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (Intel)] on win32
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import PIL.Image
	>>> PIL.Image.open("envmap_grimmnight/grimmnight_bk.tga")
	%s
	Traceback (most recent call last):
	  File "c:\Python34\lib\site-packages\PIL\ImageFile.py", line 100, in __init__
		self._open()
	  File "c:\Python34\lib\site-packages\PIL\CurImagePlugin.py", line 71, in _open
		self._bitmap(i32(m[12:]) + offset)
	  File "c:\Python34\lib\site-packages\PIL\_binary.py", line 49, in i32le
		return unpack("<I", c[o:o+4])[0]
	struct.error: unpack requires a bytes object of length 4
	<PIL.TgaImagePlugin.TgaImageFile image mode=RGB size=1024x1024 at 0x2B89230>

**Comment by filonik** [comment] 2015-11-24 09:39
Strangely, the error is only logged to the console, but the returned TgaImageFile appears to be valid. Perhaps this is intended?

**Comment by ATXRanchHand** [comment] 2015-11-25 18:18
I am getting the same issue, but no returned image file just a crash every time i try to open a tga ( including the ones in the zip file)

**Comment by hugovk** [comment] 2015-11-25 18:51
Cannot reproduce crash on OS X with Python 2.7. This script:
```python
from PIL import Image, PILLOW_VERSION
import sys

print("Python version:", sys.version)
print("PILLOW_VERSION:", PILLOW_VERSION)

files = [
    "grimmnight_bk.tga",
    "grimmnight_ft.tga",
    "grimmnight_rt.tga",
    "grimmnight_dn.tga",
    "grimmnight_lf.tga",
    "grimmnight_up.tga"]

for f in files:
    print(f)
    im = Image.open(f)
    im.load()
    print(im)
```

Produces:
```
('Python version:', '2.7.10 (default, Sep 23 2015, 04:34:21) \n[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]')
('PILLOW_VERSION:', '3.0.0')
grimmnight_bk.tga
No handlers could be found for logger "PIL.ImageFile"
<PIL.TgaImagePlugin.TgaImageFile image mode=RGB size=1024x1024 at 0x10E225C50>
grimmnight_ft.tga
<PIL.TgaImagePlugin.TgaImageFile image mode=RGB size=1024x1024 at 0x10E225DD0>
grimmnight_rt.tga
<PIL.TgaImagePlugin.TgaImageFile image mode=RGB size=1024x1024 at 0x10E225C50>
grimmnight_dn.tga
<PIL.TgaImagePlugin.TgaImageFile image mode=RGB size=1024x1024 at 0x10E225DD0>
grimmnight_lf.tga
<PIL.TgaImagePlugin.TgaImageFile image mode=RGB size=1024x1024 at 0x10E225C50>
grimmnight_up.tga
<PIL.TgaImagePlugin.TgaImageFile image mode=RGB size=1024x1024 at 0x10E225DD0>
```

Does it only happen with Python 3.4?

**Comment by hugovk** [comment] 2015-11-25 19:05
On Travis CI (Linux) got similar working results with Pythons 2.6, 2.7 and PyPy.

But did get printed errors (but no crash) with Pythons 3.2, 3.3, 3.4, 3.5and PyPy3.

https://travis-ci.org/hugovk/test/builds/93219641

So it's a Python 3 issue.

**Comment by filonik** [comment] 2015-11-26 03:30
Thank you for testing on different Python versions, good to know it is not only me!

**Comment by radarhere** [comment] 2015-11-26 09:01
I've looked into this further - the unpack error is being generated in Python 2 as well, it's merely that the 'No handlers could be found for logger "PIL.ImageFile"' message is covering it.

I've created a PR to catch the struct.unpack error. However, I suspect this is only proper handling of the error thrown, and an error will still be thrown in loading the TGA file.

**Comment by wiredfool** [comment] 2015-11-26 09:10
Is this a regression from 2.9?  Are these valid TGA files that we should be supporting?

**Comment by hugovk** [comment] 2015-11-26 09:18
Yes, this is a regression from Pillow 2.9.0; with 2.9.0:

* Don't get 'No handlers could be found for logger "PIL.ImageFile"' with Python 2.
* Don't get struct.error with Python 3.

https://travis-ci.org/hugovk/test/builds/93320132

**Comment by filonik** [comment] 2015-11-26 13:42
The error has appeared with any TGA file that I have tried, not just the ones from this site.

**Comment by ATXRanchHand** [comment] 2015-11-30 15:11
I have the same issue with 2.7

**Comment by radarhere** [comment] 2015-12-10 00:22
In Pillow 2.9, the struct.error is still generated, it's just silently handled in a higher `try` block - https://github.com/python-pillow/Pillow/blob/2.9.x/PIL/ImageFile.py#L96

Now, the struct.error is thrown - https://github.com/python-pillow/Pillow/blob/master/PIL/ImageFile.py#L99

Since PR #1556 has been merged, this is caught and thrown as a TypeError - 'No cursors were found'

**Comment by radarhere** [comment] 2015-12-14 22:26
PR #1590 has now been merged. That should resolve the 'No handlers could be found for logger "PIL.ImageFile"' message.

So if anyone would care to test again with master, they should now find this issue should to be resolved.

**Closed** 2016-06-13 12:39 UTC
