### ISSUE TITLE
Division by zero error when using ImageOps.exif_transpose since Pillow 11.0

### ISSUE THREAD

**Issue by fabienarnaud** [python-pillow/Pillow#8478] opened 2024-10-17 09:36 UTC
Hi,

Some jpg images are returning a "division by zero" error since the Pillow version 11.0 was released when using the ImageOps.exif_transpose() function.

Below is for example 1 of these images with its exif information, using Pillow version 10.4:

![image](https://github.com/user-attachments/assets/81b42335-c823-4f2a-81aa-4258ca468892)

The same image and code, now with Pillow 11.0.0:

![image](https://github.com/user-attachments/assets/386a63c1-eac4-4193-852c-e5a9fd2ec1ca)

Some more error details:
![image](https://github.com/user-attachments/assets/e1537156-1910-4e25-ba89-1c985c42efbb)

**Comment by radarhere** [comment] 2024-10-17 10:02
Hi. If you would like to attach an image, then we could test it and know exactly what the problem is - but otherwise, this sounds like a duplicate of #8471.

#8474 has already been merged to resolve this in main.

**Comment by fabienarnaud** [comment] 2024-10-17 10:31
Thank you for your outstanding reactivity!
Sure, here is the EXIF data in text:
{296: 2, 282: 72.0, 256: 4096, 257: 3072, 270: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 271: 'samsung\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 272: 'SM-A022F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 274: 6, 531: 2, 283: 72.0, 544: 0, 545: 0, 546: 0, 547: 0, 548: 0, 549: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 34853: 952, 34665: 450, 305: 'A022FXXS3BWH1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 306: '2024:10:15 14:35:26'}

And here is the image leading to the division by zero:

![3uvf5cealhismxw0f6l178uuyc1q](https://github.com/user-attachments/assets/218d8053-f674-4c13-af3b-485d67e57d6b)

**Comment by radarhere** [comment] 2024-10-17 10:55
Thanks. Yes, this has been fixed in main already.

If you would like to patch your code so that it works for the moment, you could do the following -

```python
from PIL import Image, ImageOps, TiffImagePlugin

# Patch
def _limit_rational(val, max_val):
    inv = abs(val) > 1
    n_d = TiffImagePlugin.IFDRational(1 / val if inv else val).limit_rational(max_val)
    return n_d[::-1] if inv else n_d
TiffImagePlugin._limit_rational = _limit_rational

with Image.open('in.jpg') as im:
    ImageOps.exif_transpose(im)
```

**Comment by fabienarnaud** [comment] 2024-10-17 11:05
Happy to hear that! And thank you for the patch!

**Closed** 2024-10-17 11:43 UTC
Labels: Duplicate, Exif

**Comment by radarhere** [comment] 2025-01-02 08:38
Pillow 11.1.0 has now been released with the fix for this.

**Comment by fabienarnaud** [comment] 2025-01-02 09:48
Brilliant! Thank you so much for your support!
