### ISSUE TITLE
JPEG file fails to load with message "OSError: broken data stream when reading image file"

### ISSUE THREAD

**Issue by agateau** [python-pillow/Pillow#3185] opened 2018-06-14 20:24 UTC
### What did you do?

Tried to load attached panoramic JPEG file, which has been produced a long time ago using Hugin.

### What did you expect to happen?

Image should have loaded.

### What actually happened?

Loading fails with this output:
```
Traceback (most recent call last):
  File "fail.py", line 4, in <module>
    img.load()
  File "/home/perso/.local/share/virtualenvs/b5dc93ce1404c1f/lib/python3.6/site-packages/PIL/ImageFile.py", line 250, in load
    raise_ioerror(err_code)
  File "/home/perso/.local/share/virtualenvs/b5dc93ce1404c1f/lib/python3.6/site-packages/PIL/ImageFile.py", line 59, in raise_ioerror
    raise IOError(message + " when reading image file")
OSError: broken data stream when reading image file
```

### What versions of Pillow and Python are you using?

- Pillow: 5.1.0 and master (968c2cf)
- Python: 3.6.5

```python
from PIL import Image

img = Image.open('fail.jpg')
img.load()
```

Image failing to load: ![fail](https://user-images.githubusercontent.com/3575/41436241-5268f7a4-7021-11e8-8dc6-1b362d9b50cd.jpg)

**Comment by pkumar2-sps** [comment] 2018-06-25 13:31
Any update??

**Comment by radarhere** [comment] 2018-06-26 09:43
Hi. That is the error that typically describes truncated images. If you enable `LOAD_TRUNCATED_IMAGES`, the image can load.

```
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
Image.open('fail.jpg').load()
```

See a longer discussion of another instance of this problem, see #1510

**Comment by aclark4life** [comment] 2018-06-30 23:36
@agateau Please reopen if this is not a duplicate of #1510

**Closed by aclark4life** 2018-06-30 23:36 UTC
Labels: Documentation, JPEG

**Comment by danpla** [comment] 2018-07-01 09:56
I believe it's actually an issue with suspended loading in libjpeg-turbo (see [this](https://sourceforge.net/p/libjpeg-turbo/mailman/libjpeg-turbo-users/?viewmonth=201304) thread). On my Linux machine, neither Firefox nor Eye of GNOME can open the example image (giving "Suspension not allowed here" error), and the example by @radarhere only loads first rows of the image.

**Comment by EnriqueSolarte** [comment] 2022-10-26 13:13
I solved this issue by 
```py
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
Image.open('image.jpg').load()
```
Found here https://github.com/python-pillow/Pillow/issues/1510
