### ISSUE TITLE
Drawing shapes causes artifacts in output image

### ISSUE THREAD

**Issue by driscollis** [python-pillow/Pillow#5387] opened 2021-04-07 01:07 UTC
### What did you do?

I drew a shape using Pillow.

### What did you expect to happen?

I expected the original image to look correct but with a drawing overlaid on top of it

### What actually happened?

The output (in JPG) looks very pixelated and full of artifacts. This is especially true when creating a new image and then drawing on it. However, you can also see it when drawing on a pre-existing photo too.

### What are your OS, Python and Pillow versions?

* OS: Mac Mojave
* Python: 3.9
* Pillow: 8.0.0

```python
# draw_jointed_line.py

from PIL import Image, ImageDraw

def line(output_path):
    image = Image.new("RGB", (400, 400), "red")
    points = [(100, 100), (150, 200), (200, 50), (400, 400)]
    draw = ImageDraw.Draw(image)
    draw.line(points, width=15, fill="green", joint="curve")
    image.save(output_path)

if __name__ == "__main__":
    line("jointed_lines.jpg")
```

This example uses a pre-existing image:

```python
# draw_line.py

import random
from PIL import Image, ImageDraw


def line(image_path, output_path):
    image = Image.open(image_path)
    draw = ImageDraw.Draw(image)
    colors = ["red", "green", "blue", "yellow",
              "purple", "orange"]

    for i in range(0, 100, 20):
        draw.line((i, 0) + image.size, width=5, 
                  fill=random.choice(colors))

    image.save(output_path)

if __name__ == "__main__":
    line("madison_county_bridge_2.jpg", "lines.jpg")
```
![madison_county_bridge_2](https://user-images.githubusercontent.com/2895418/113795939-a3033000-9713-11eb-99f6-d3782a6e3a3d.jpg)

**Comment by radarhere** [comment] 2021-04-07 01:49
I find saving as PNG instead makes a difference.

Is that a solution for you? Or do you specifically want to save a JPG?

**Comment by radarhere** [comment] 2021-04-10 04:11
@driscollis I think this is essentially a duplicate of #5388, in that you're dissatisfied with the quality of JPEG saving.

Do you agree?

**Comment by driscollis** [comment] 2021-04-12 14:46
Probably. I wasn't sure if drawing text was different than drawing shapes. If the code artifacts are coming due to the way it is saved rather than the drawing mechanism, then I would agree that the root cause is the same.

**Comment by radarhere** [comment] 2021-04-12 22:05
Well, here's JPG vs PNG
![lines](https://user-images.githubusercontent.com/3112309/114468472-e76c5f80-9c2e-11eb-9eba-be3dbcd6d19f.jpg)
![lines](https://user-images.githubusercontent.com/3112309/114468464-e20f1500-9c2e-11eb-89cc-6cafe6cc3c7d.png)

**Closed** 2021-04-12 22:21 UTC
Labels: JPEG
