### ISSUE TITLE
Can't convert images with height / width < 64 to jpeg2000

### ISSUE THREAD

**Issue by bagipriyank** [python-pillow/Pillow#3161] opened 2018-06-08 00:52 UTC
### What did you do?
I am trying to convert a jpeg image of size 63x47 to jpeg2000

### What did you expect to happen?
Expected a jp2 image as output. However this issue doesn't happen if both the height and width of the image >= 64

### What actually happened?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/Image.py", line 1698, in save
    save_handler(self, fp, filename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/Jpeg2KImagePlugin.py", line 264, in _save
    ImageFile._save(im, fp, [('jpeg2k', (0, 0)+im.size, 0, kind)])
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/ImageFile.py", line 500, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file
```

### What versions of Pillow and Python are you using?
```pycon
>>> PIL.PILLOW_VERSION
'3.4.2'
>>> PIL.VERSION
'1.1.7'
```

```console
pbagrecha-mpb15:~$ python --version
Python 2.7.13
```

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```pycon
Python 2.7.13 (default, Apr  4 2017, 08:47:57)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.open('image.jpeg').save('image.jp2', 'JPEG2000', quality_mode='dB', quality_layers=[41])
```

Attaching the image I am trying to convert.
![image](https://user-images.githubusercontent.com/3229967/41133384-68e4bfd2-6a7b-11e8-9d6a-170f7188a588.jpeg)

**Comment by hugovk** [comment] 2018-06-08 08:46
Reproducible with Pillow 5.1.0 on Python 3.6.5 and Python 2.7.15 on macOS High Sierra.

**Comment by bagipriyank** [comment] 2018-09-04 21:12
any update on this?

**Comment by Iamanorange** [comment] 2018-11-14 10:01
Reproducible with Pillow 5.3.0 on Python 3.5.2 on Ubuntu 16.04.

**Comment by radarhere** [comment] 2019-07-16 10:27
I can't replicate this. I would guess that it's been fixed in OpenJPEG, but to check, @hugovk since you were able to reproduce this previously, could you give it another try?

**Comment by hugovk** [comment] 2019-07-16 10:34
Cannot reproduce with macOS Mojave 10.14.5, latest Pillow 6.1.0 and openjpeg stable 2.3.1:

```python
⌂115% 1z [hugo:/tmp/Downloads] % p
Python 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.open('image.jpeg').save('image.jp2', 'JPEG2000', quality_mode='dB', quality_layers=[41])
>>>
⌂82% 1z [hugo:/tmp/Downloads] 8s % p2
Python 2.7.16 (default, Mar  4 2019, 09:02:22)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.open('image.jpeg').save('image.jp2', 'JPEG2000', quality_mode='dB', quality_layers=[41])
```

The output `image.jp2` looks like the input `image.jpeg` in both cases.

**Comment by radarhere** [comment] 2019-07-16 10:52
Thanks

**Comment by radarhere** [comment] 2019-07-16 10:54
If anyone else is still experiencing this and would like it looked into further, feel free to comment and this can be re-opened.

**Comment by cattybaby723** [comment] 2021-05-14 03:06
Reproducible with Pillow 8.2.0 on Python 3.7.5 on MacOS Catalina 10.15.7

**Comment by radarhere** [comment] 2021-05-14 03:08
Using the image from the original post? Or another one?

**Comment by cattybaby723** [comment] 2021-05-31 02:15
I used my own image and here is my test code.

image_path = "small.jpg" # image size is 18 x 28
save_file_path = "test.jp2"
image = Image.open(image_path)
image.save(save_file_path, 'JPEG2000')

**Comment by cattybaby723** [comment] 2021-05-31 02:17
I used my own image and here is my test code.

image_path = "small.jpg" # image size is 18 x 28
save_file_path = "test.jp2"
image = Image.open(image_path)
image.save(save_file_path, 'JPEG2000')

Attaching the image I am testing.
![small](https://user-images.githubusercontent.com/6972498/120130648-44c96980-c1f9-11eb-8d3c-24b4699129ef.jpg)

**Comment by radarhere** [comment] 2021-06-13 13:01
I've found that OpenJPEG is trying to tell us that "Number of resolutions is too high in comparison to the size of tiles".

I find that setting `num_resolutions` to a value between 1 and 5 works.

```python
from PIL import Image
image_path = "small.jpeg" # image size is 18 x 28
save_file_path = "test.jp2"
image = Image.open(image_path)
image.save(save_file_path, 'JPEG2000', num_resolutions=5)
```

**Comment by radarhere** [comment] 2021-06-13 14:30
I've created PR #5540 to fix the default behaviour of Pillow.

**Closed** 2021-06-20 08:58 UTC
Labels: JPEG
