### ISSUE TITLE
P to PA conversion loses color

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#6496] opened 2022-08-12 20:06 UTC
### What did you do?

using https://github.com/python-pillow/Pillow/blob/main/Tests/images/hopper.jpg

```python
h = Image.open('hopper.jpg')
h.convert('P').show()
h.convert('PA').show()
h.convert('P').convert('PA').show()
h.convert('PA').convert('P').show()
```

### What did you expect to happen?

I expected all of the images to look essentially the same.

### What actually happened?

The image converted to P then to PA has no color.

### What are your OS, Python, and Pillow versions?

* OS: Windows 10
* Python: 3.9.6
* Pillow: 9.2.0

**Comment by Yay295** [comment] 2022-08-12 20:20
I think the issue is here:

https://github.com/python-pillow/Pillow/blob/7f39a21910f76b2f4e8d9c66fd91e6a3a72a28d9/src/libImaging/Convert.c#L1029-L1040

This function was previously changed two times:
1. https://github.com/python-pillow/Pillow/commit/4f3b44960f103bc201a742332dbf9a77de1eaa87#diff-504185fb56f577513c6b401b51e9d36abfabf172655309861f5f4f34892abf2f
2. https://github.com/python-pillow/Pillow/pull/6337/files#diff-504185fb56f577513c6b401b51e9d36abfabf172655309861f5f4f34892abf2f

I think the correct function would be:
```c
static void
p2pa(UINT8 *out, const UINT8 *in, int xsize, ImagingPalette palette) {
    int x;
    int rgb = strcmp(palette->mode, "RGB");
    for (x = 0; x < xsize; x++, in++) {
        const UINT8 *rgba = &palette->palette[in[0]*4];
        *out++ = in[0];
        *out++ = in[1]; // <- change 0 to 1
        *out++ = in[2]; // <- change 0 to 2
        *out++ = rgb == 0 ? 255 : rgba[3];
    }
}
```

**Comment by radarhere** [comment] 2022-08-13 07:53
The problem isn't in the pixels themselves. The PA mode is similar to the P mode - each pixel is just points to an index in the palette - except that PA also has an alpha channel. The problem is that the palette isn't correctly transferred.

```python
from PIL import Image
h = Image.open('hopper.jpg')

im_p = h.convert('P')
print(im_p.getpalette()[:40])  # [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 102, 0, 0, 153]

im_pa = h.convert('P').convert('PA')
print(im_pa.getpalette()[:40])  # [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 12, 13]
```

I've created PR #6497 to resolve this, by copying the palette into the new image.

**Comment by Yay295** [comment] 2022-08-13 08:40
Oh yeah, that makes sense. Shouldn't PA only need two bytes for each pixel though? It looks like LA and La also use more space than they need.

https://github.com/python-pillow/Pillow/blob/95cff6e959bb3c37848158ed2145d49d49806a31/src/libImaging/Storage.c#L77-L99

**Comment by radarhere** [comment] 2022-08-13 08:58
I can't think of any reason why that should be, I'll only say that PA and LA have been stored in 4 bytes since PIL.

If you'd like to make that change, you could create a PR. Or if you'd like to just request it, you could create a new issue.

**Comment by radarhere** [comment] 2022-08-14 04:14
The request was created as #6503

**Closed** 2022-08-31 14:09 UTC
Labels: Palette, Conversion
