### ISSUE TITLE
.draft on certain jpegs create incorrect color line at border

### ISSUE THREAD

**Issue by kkopachev** [python-pillow/Pillow#3419] opened 2018-10-19 17:20 UTC
### What did you do?
Found this issue posted on chromium bug tracker https://bugs.chromium.org/p/chromium/issues/detail?id=890745 and related [issue reported to libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo/issues/297) and obviously reproduced in Pillow. Both links have good explanation of what's going on and original image.

```python
from PIL import Image
im = Image.open('1.jpg')
im.draft('RGB', (75, 54))
# <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=150x108 at 0x7F46264B73D0>
im.save('2.jpg')
```
Scaled image with the line:
![2](https://user-images.githubusercontent.com/2279051/47233489-c9885180-d387-11e8-82ef-4a29f34bbe57.jpg)

I tried with libjpeg-turbo and libjpeg62, they both show same issue. 
I know that the problem is coming from how libjpeg handles scaling, and it's a feature, so I just want to have your attention and you might want to workaround issue as chromium team did, basically disabling libjpeg scaling for images with dimensions not multiple of MCU size.
Or do you think that users of Pillow should do that themselves? 

@homm

**Comment by homm** [comment] 2018-10-20 08:34
I suppose this the issue of libjpeg and should be fixed once in the codec. Before this happened, we can fix it on the our side.

> disabling libjpeg scaling for images with dimensions not multiple of MCU size.

This sounds reasonable since the `draft` doesn't provide any guarantee about performed actions. If a user needs to force DCT downscaling, she has the necessary low-level tools (decoderconfig).

Or we can do nothing because the image obviously handcrafted to expose the issue.

> andrescj@chromium.org
I suspect (but have no hard data) that instead of using garbage data, most encoders will repeat the last row of the image.

**Comment by radarhere** [comment] 2019-01-05 05:39
I have created PR #3545 as a possible solution to this, suggesting that any potential artifacts be cropped out of the image.

**Comment by radarhere** [comment] 2019-01-11 20:59
Okay, next idea - PR #3570, suggesting switching to `resize()` instead. Feel free to disagree with this idea, I'm just trying to move this issue along in some way that doesn't involve disabling existing functionality.

**Comment by kkopachev** [comment] 2019-01-11 23:04
@radarhere I think doing `resize` at that point does not help with original issue. `draft` already instructed decoder to read scaled image. Calling `resize` will make it load scaled image first, then resize down to requested size.
One way of fixing the issue is that not setting `scale` parameter on `decoderconfig` when size of image is  not whole number of MCU size. There is no need to call `resize` in that case, since `draft` does not guarantee anything.

That's only viable solution I see here. Not sure it's worth it, though. Unclear if affected image was crafted in a special way and there is low chances that such images would appear in the wild.

**Comment by hugovk** [comment] 2019-01-12 12:12
In the interest of avoiding regressions, shall we close this until someone runs into it in real life?

**Closed** 2019-05-02 05:02 UTC
Labels: JPEG
