### ISSUE TITLE
Filesize concerns

### ISSUE THREAD

**Issue by jvanasco** [python-pillow/Pillow#617] opened 2014-04-12 03:09 UTC
I've noticed that the images created by PIL are quite large.  

gifs seem to be over 4x larger than they could be.  
pngs are around 130% larger

i tested this just off of pillow created files vs the same ones imported/exported through a graphics app.  ie, i used lossless compression on the second time.   

as a quick example, i drew some text on a canvas.  a (256 color) gif from pillow was around 12k; the same gif was opened & exported to 2k using an app.  pillow generated it as 3 color gif at 3k (larger filesize than the much better looking 256 color), while it was a few hundred bytes via an app.

there are a handful of advanced image 'compressing' apps out there too, which do lossless optimizations.  i didn't run the images through any of them.

i'm wondering if anyone here knows any techniques or ways to address this.  i thought this might have something to do with the old gif patents, but they're long expired and pngs seem to be affected.

**Comment by hugovk** [comment] 2017-04-07 05:50
From https://github.com/python-pillow/Pillow/issues/2480 (closed as duplicate of this):

---

### What did you do?

Reverse a gif get it much bigger size on disk

### What did you expect to happen?

Still the original size or only a bit more

### What versions of Pillow and Python are you using?

latest Pillow and 3.6 Python

```python
from PIL import Image, ImageSequence
from PIL import ImagePalette
with Image.open('sd.gif') as im:
    if im.is_animated:
        frames = [f.copy() for f in ImageSequence.Iterator(im)]
        frames.reverse()
        frames[0].save('out.gif', save_all=True, append_images = frames[1:])  
```

**Comment by jvanasco** [comment] 2017-04-12 00:32
I'm not familiar with the exact inner workings, but #2480 is probably not the same as this (or an issue at all).

I should probably address some of the earlier comments in here too.

This ticket shouldn't have to do with quantization (which is lossy) but is meant to address bloat issues when doing a lossless encoding as gif.  Perhaps Pillow is running the gif through the quantizer when it doesn't have to, and could just ignore it if the number of colors is small enough?

In terms of #2480, animated gifs are built off of deltas -- not individual frames.  The bloat could also be created by:

* the original gif uses diffs, the Pillow created gif uses full frames
* reversing the image drastically changes the filesize of a few frames. 
* other things  (It's the end of the day!)

**Comment by wiredfool** [comment] 2017-04-12 10:43
Actually, it's simpler than that. Pillow doesn't do compression on GIFs. It only implements the uncompressed frame format. So anything that's going to do GIF compression is going to beat it. There was code for that, but it was in the closed source PILplus extension. 

Pillow does diffs of frames, though there's some subtle details of the disposal methods when writing that would mess with that.  There is a new quantizer that's been merged since this issue came in, but that's also probably not the main issue anymore.

**Comment by TheRockettek** [comment] 2019-06-29 11:34
Meanwhile my pillow just made a 800kb file into a 1.2Gb file somehow

**Comment by wiredfool** [comment] 2019-06-29 11:40
If you’d like to contribute a gif compressor under the PIL license, go for it.

**Comment by radarhere** [comment] 2021-02-27 11:50
#5278 adds LZW encoding to GIFs, reducing filesize by 30%.

**Comment by radarhere** [comment] 2021-08-01 13:39
Does anyone in this issue have a specific image that demonstrates this problem?

**Comment by jvanasco** [comment] 2021-08-01 14:35
I can try to recreate my older test images this week.

**Comment by xmo-odoo** [comment] 2022-07-19 12:21
I've got an animated gif which increases 10x in size when read, then re-stored as-is (with `save_all=True`):
![](https://user-images.githubusercontent.com/9977887/179728314-8255e120-dedd-4457-93a7-c4d025ca984f.gif)
I've also found [this SO entry](179728314-8255e120-dedd-4457-93a7-c4d025ca984f.gif) where a user went from a 2MB GIF to a 7.5MB GIF *after resizing* (incidentally it's a bit frustrating that resizing a gif will leave only the first frame but not signal the issue, maybe it should at least warn if the gif has multiple frames?)

**Comment by xmo-odoo** [comment] 2022-07-19 12:26
Complement: I was on a version of Pillow preceding #5291, updating to 9.2.0 does improve things significantly (the image still increases after saving but only to 400k).

**Comment by radarhere** [comment] 2023-11-25 03:04
> I've also found [this SO entry](https://stackoverflow.com/questions/41718892/pillow-resizing-a-gif) where a user went from a 2MB GIF to a 7.5MB GIF _after resizing_

There isn't a complete example in the StackOverflow post of the resizing, but for the initial example where the user is just resaving the image, testing it with main now it is only output as 2.1mb.

> incidentally it's a bit frustrating that resizing a gif will leave only the first frame but not signal the issue, maybe it should at least warn if the gif has multiple frames?

This is because `resize()` returns a copy of the image, and copying an image only includes the first frame. My feeling is that a warning would be an annoyance to any users who were used to this behaviour.

**Comment by radarhere** [comment] 2023-12-24 06:26
I'm hoping that between #5291 in Pillow 8.2.0 and #7568 in the upcoming Pillow 10.2.0 (reducing https://github.com/python-pillow/Pillow/issues/617#issuecomment-1188984138 from 408kb to 345kb), the GIF filesize concerns in this issue are now resolved.

**Comment by radarhere** [comment] 2024-12-31 11:40
> There's also a outstanding issue to add pngquant support

I presume this referred to #554, which has long since been resolved if you're interested in using [`quantize()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.quantize) to reduce file size.

> pngs are around 130% larger

> i have a workaround, where i save files to a named tempfile , then run pngcrush / gifsicle / jpegtran on it... outputting into another named tempfile.
> 
> It works well on Mac/Linux. The 3 apps are available on Linux and ImageOptim.app ( http://imageoptim.com/ ) has a resources folder that has those 3 ( plus a few more ) compiled; I just add that to my path.

If I open and save our ['hopper.png'](https://github.com/python-pillow/Pillow/blob/main/Tests/images/hopper.png) test image, then ImageOptim only reduces the size by 3%, which seems minor.

Closing. If someone still has a concern, please open a new issue with a specific image example to discuss.

**Closed by radarhere** 2024-12-31 11:40 UTC
Labels: Enhancement
