### ISSUE TITLE
Travis CI: test_high_characters sometimes fails

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#2758] opened 2017-09-23 21:57 UTC
I've seen it fail on some Docker build jobs. After rebuilding, it was fine.

Here's an example from DOCKER="debian-stretch-x86" from today at https://travis-ci.org/python-pillow/Pillow/jobs/279047420, which passed after rebuilding:
```
======================================================================
FAIL: TestFontPcf.test_high_characters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Pillow/Tests/test_font_pcf.py", line 59, in test_high_characters
    self._test_high_characters(message)
  File "/Pillow/Tests/test_font_pcf.py", line 55, in _test_high_characters
    self.assert_image_equal(image, compare)
  File "/Pillow/Tests/helper.py", line 85, in assert_image_equal
    msg or "got size %r, expected %r" % (a.size, b.size))
AssertionError: got size (783, 22), expected (765, 22)
-------------------- >> begin captured logging << --------------------
PIL.PngImagePlugin: DEBUG: STREAM 'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM 'IDAT' 41 2644
PIL.PngImagePlugin: DEBUG: STREAM 'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM 'IDAT' 41 1400
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
Ran 1068 tests in 16.060s
FAILED (SKIP=25, failures=1)
```

---

Here's another from August (https://github.com/python-pillow/Pillow/pull/2634#issuecomment-322232953):

> I'm not sure what's up with the Travis errors, as they're non-deterministic. This fails on debian-stretch in one commit or ubuntu-trusty-x86 in another, but the changes should not affect them.
```
======================================================================
FAIL: TestFontPcf.test_high_characters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Pillow/Tests/test_font_pcf.py", line 59, in test_high_characters
    self._test_high_characters(message)
  File "/Pillow/Tests/test_font_pcf.py", line 55, in _test_high_characters
    self.assert_image_equal(image, compare)
  File "/Pillow/Tests/helper.py", line 85, in assert_image_equal
    msg or "got size %r, expected %r" % (a.size, b.size))
AssertionError: got size (770, 22), expected (765, 22)
```
> (and when rerun, the ubuntu version passed, and the debian one still failed)

**Comment by wiredfool** [comment] 2017-09-24 20:54
I can't get them to do the same thing on my docker build machine. Leads one to believe that it's uninitialized memory or something similar.

**Comment by hugovk** [comment] 2017-09-28 07:38
Another fail on https://travis-ci.org/python-pillow/Pillow/jobs/280732802 passed when restarted. Here are full logs. Nothing much different in the setup.

```
======================================================================
FAIL: TestFontPcf.test_high_characters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Pillow/Tests/test_font_pcf.py", line 59, in test_high_characters
    self._test_high_characters(message)
  File "/Pillow/Tests/test_font_pcf.py", line 55, in _test_high_characters
    self.assert_image_equal(image, compare)
  File "/Pillow/Tests/helper.py", line 87, in assert_image_equal
    self.fail(msg or "got different content")
AssertionError: got different content
-------------------- >> begin captured logging << --------------------
PIL.PngImagePlugin: DEBUG: STREAM 'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM 'IDAT' 41 2644
PIL.PngImagePlugin: DEBUG: STREAM 'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM 'IDAT' 41 1400
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
Ran 1068 tests in 19.080s
FAILED (SKIP=26, failures=1)
```

[ubuntu-trusty-x86-fail.log](https://github.com/python-pillow/Pillow/files/1339884/ubuntu-trusty-x86-fail.log)
[ubuntu-trusty-x86-pass.log](https://github.com/python-pillow/Pillow/files/1339885/ubuntu-trusty-x86-pass.log)

**Comment by wiredfool** [comment] 2017-09-28 11:15
It's not deterministic, which sort of narrows down the possible roots of the problem. I've also never seen it happen on my docker build system, which makes me really suspicious. 

(aside -- I thought that part of the point with docker was reproducibility -- If you run the same docker image, you should get the same results. Clearly it's not quite there)

**Comment by hugovk** [comment] 2017-09-28 11:49
Same numbers on debian-stretch-x86 from https://travis-ci.org/python-pillow/Pillow:
```
======================================================================
FAIL: TestFontPcf.test_high_characters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Pillow/Tests/test_font_pcf.py", line 59, in test_high_characters
    self._test_high_characters(message)
  File "/Pillow/Tests/test_font_pcf.py", line 55, in _test_high_characters
    self.assert_image_equal(image, compare)
  File "/Pillow/Tests/helper.py", line 85, in assert_image_equal
    msg or "got size %r, expected %r" % (a.size, b.size))
AssertionError: got size (770, 22), expected (765, 22)
-------------------- >> begin captured logging << --------------------
PIL.PngImagePlugin: DEBUG: STREAM 'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM 'IDAT' 41 2644
PIL.PngImagePlugin: DEBUG: STREAM 'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM 'IDAT' 41 1400
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
Ran 1068 tests in 14.349s
FAILED (SKIP=25, failures=1)
```
[debian-stretch-x86-fail.log](https://github.com/python-pillow/Pillow/files/1340705/debian-stretch-x86-fail.log)
[debian-stretch-x86-pass.log](https://github.com/python-pillow/Pillow/files/1340706/debian-stretch-x86-pass.log)

**Comment by wiredfool** [comment] 2017-10-02 13:47
2 of the runs to make linux wheels died on the 4.3.0 version bump, got a size of (769,22).

**Comment by radarhere** [comment] 2017-11-03 11:33
I'm finding now that the 'MB_PYTHON_VERSION=2.7 PLAT=i686' build on Pillow Wheels is failing continuously because of this issue - might be helpful in resolving this?

**Comment by wiredfool** [comment] 2017-11-03 13:16
I'm pretty sure that the patch in #2825 is the fix.

**Closed** 2017-11-05 15:01 UTC
Labels: Bug, Build

**Comment by radarhere** [comment] 2017-11-07 12:07
Yes, it fixes the problem. Thanks
